using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace runnerDotNet
{
    public class dalTable_RSPDDB_at_172_16_0_80_dbo_rspdHeader : tDALTable
    {
        public XVar ID;
        public XVar referenceID;
        public XVar applicationNo;
        public XVar companyNameA;
        public XVar userCreate;
        public XVar userUpdate;
        public XVar dateCreated;
        public XVar dateUpdated;
        public XVar companyNameB;
        public XVar siteNameA;
        public XVar siteNameB;
        public XVar siteIDA;
        public XVar siteIDB;
        public XVar coordinateA;
        public XVar coordinateB;
        public XVar elevationA;
        public XVar elevationB;
        public XVar makeTypeModelA;
        public XVar gainA;
        public XVar diameterA;
        public XVar beamwidthA;
        public XVar polarizationA;
        public XVar azimuthA;
        public XVar elevAngleA;
        public XVar heightAGLA;
        public XVar feederLengthA;
        public XVar makeTypeModelB;
        public XVar gainB;
        public XVar diameterB;
        public XVar beamwidthB;
        public XVar polarizationB;
        public XVar azimuthB;
        public XVar elevAngleB;
        public XVar heightAGLB;
        public XVar feederLengthB;
        public XVar longtitudeA;
        public XVar longtitudeB;
        public XVar latitudeA;
        public XVar latitudeB;
        public XVar callSignA;
        public XVar callSignB;
        public XVar applicationType;
        public XVar unit_a;
        public XVar street_a;
        public XVar barangay_a;
        public XVar city_a;
        public XVar province_a;
        public XVar zipcode_a;
        public XVar unit_b;
        public XVar street_b;
        public XVar barangay_b;
        public XVar city_b;
        public XVar province_b;
        public XVar zipcode_b;
        public XVar map;
        public XVar stage;
        public XVar stageStatus;
        public XVar externalReferenceNo;
        public XVar classStationService;
        public XVar modeOfOperation;
        public XVar Remarks;
        public XVar dateOfApprovedBrief;
        public XVar natureOfService;
        public XVar recommendations;
        public XVar applicationCategory;
        public XVar address;
        public XVar rt;
        public XVar fx;
        public XVar fb;
        public XVar ml;
        public XVar p;
        public XVar bc;
        public XVar fc;
        public XVar fa;
        public XVar ma;
        public XVar tc;
        public XVar other_ClassSS;
        public XVar naturoOfRequest;
        public XVar serviceArea;
        public XVar caseNo;
        public XVar frequencyRange;
        public XVar directivity;
        public XVar encoder;
        public XVar evaluator;
        public XVar position;
        public XVar longDegA;
        public XVar longMinA;
        public XVar longSecA;
        public XVar longDegB;
        public XVar longMinB;
        public XVar longSecB;
        public XVar latDegA;
        public XVar latMinA;
        public XVar latSecA;
        public XVar latDegB;
        public XVar latMinB;
        public XVar latSecB;
        public XVar cardinalDirectionsLatA;
        public XVar cardinalDirectionsLongB;
        public XVar cardinalDirectionLongA;
        public XVar cardinalDirectionLatB;
        public XVar regionA;
        public XVar regionB;
        public static void Init()
        {
            XVar dalTablerspdHeader = XVar.Array();
            dalTablerspdHeader["ID"] = new XVar("type", 3, "varname", "ID", "name", "ID", "autoInc", "1");
            dalTablerspdHeader["referenceID"] = new XVar("type", 200, "varname", "referenceID", "name", "referenceID", "autoInc", "0");
            dalTablerspdHeader["applicationNo"] = new XVar("type", 130, "varname", "applicationNo", "name", "applicationNo", "autoInc", "0");
            dalTablerspdHeader["companyNameA"] = new XVar("type", 200, "varname", "companyNameA", "name", "companyNameA", "autoInc", "0");
            dalTablerspdHeader["userCreate"] = new XVar("type", 202, "varname", "userCreate", "name", "userCreate", "autoInc", "0");
            dalTablerspdHeader["userUpdate"] = new XVar("type", 202, "varname", "userUpdate", "name", "userUpdate", "autoInc", "0");
            dalTablerspdHeader["dateCreated"] = new XVar("type", 135, "varname", "dateCreated", "name", "dateCreated", "autoInc", "0");
            dalTablerspdHeader["dateUpdated"] = new XVar("type", 135, "varname", "dateUpdated", "name", "dateUpdated", "autoInc", "0");
            dalTablerspdHeader["companyNameB"] = new XVar("type", 200, "varname", "companyNameB", "name", "companyNameB", "autoInc", "0");
            dalTablerspdHeader["siteNameA"] = new XVar("type", 200, "varname", "siteNameA", "name", "siteNameA", "autoInc", "0");
            dalTablerspdHeader["siteNameB"] = new XVar("type", 200, "varname", "siteNameB", "name", "siteNameB", "autoInc", "0");
            dalTablerspdHeader["siteIDA"] = new XVar("type", 200, "varname", "siteIDA", "name", "siteIDA", "autoInc", "0");
            dalTablerspdHeader["siteIDB"] = new XVar("type", 200, "varname", "siteIDB", "name", "siteIDB", "autoInc", "0");
            dalTablerspdHeader["coordinateA"] = new XVar("type", 200, "varname", "coordinateA", "name", "coordinateA", "autoInc", "0");
            dalTablerspdHeader["coordinateB"] = new XVar("type", 200, "varname", "coordinateB", "name", "coordinateB", "autoInc", "0");
            dalTablerspdHeader["elevationA"] = new XVar("type", 200, "varname", "elevationA", "name", "elevationA", "autoInc", "0");
            dalTablerspdHeader["elevationB"] = new XVar("type", 200, "varname", "elevationB", "name", "elevationB", "autoInc", "0");
            dalTablerspdHeader["makeTypeModelA"] = new XVar("type", 200, "varname", "makeTypeModelA", "name", "makeTypeModelA", "autoInc", "0");
            dalTablerspdHeader["gainA"] = new XVar("type", 200, "varname", "gainA", "name", "gainA", "autoInc", "0");
            dalTablerspdHeader["diameterA"] = new XVar("type", 200, "varname", "diameterA", "name", "diameterA", "autoInc", "0");
            dalTablerspdHeader["beamwidthA"] = new XVar("type", 200, "varname", "beamwidthA", "name", "beamwidthA", "autoInc", "0");
            dalTablerspdHeader["polarizationA"] = new XVar("type", 200, "varname", "polarizationA", "name", "polarizationA", "autoInc", "0");
            dalTablerspdHeader["azimuthA"] = new XVar("type", 200, "varname", "azimuthA", "name", "azimuthA", "autoInc", "0");
            dalTablerspdHeader["elevAngleA"] = new XVar("type", 200, "varname", "elevAngleA", "name", "elevAngleA", "autoInc", "0");
            dalTablerspdHeader["heightAGLA"] = new XVar("type", 200, "varname", "heightAGLA", "name", "heightAGLA", "autoInc", "0");
            dalTablerspdHeader["feederLengthA"] = new XVar("type", 200, "varname", "feederLengthA", "name", "feederLengthA", "autoInc", "0");
            dalTablerspdHeader["makeTypeModelB"] = new XVar("type", 200, "varname", "makeTypeModelB", "name", "makeTypeModelB", "autoInc", "0");
            dalTablerspdHeader["gainB"] = new XVar("type", 200, "varname", "gainB", "name", "gainB", "autoInc", "0");
            dalTablerspdHeader["diameterB"] = new XVar("type", 200, "varname", "diameterB", "name", "diameterB", "autoInc", "0");
            dalTablerspdHeader["beamwidthB"] = new XVar("type", 200, "varname", "beamwidthB", "name", "beamwidthB", "autoInc", "0");
            dalTablerspdHeader["polarizationB"] = new XVar("type", 200, "varname", "polarizationB", "name", "polarizationB", "autoInc", "0");
            dalTablerspdHeader["azimuthB"] = new XVar("type", 200, "varname", "azimuthB", "name", "azimuthB", "autoInc", "0");
            dalTablerspdHeader["elevAngleB"] = new XVar("type", 200, "varname", "elevAngleB", "name", "elevAngleB", "autoInc", "0");
            dalTablerspdHeader["heightAGLB"] = new XVar("type", 200, "varname", "heightAGLB", "name", "heightAGLB", "autoInc", "0");
            dalTablerspdHeader["feederLengthB"] = new XVar("type", 200, "varname", "feederLengthB", "name", "feederLengthB", "autoInc", "0");
            dalTablerspdHeader["longtitudeA"] = new XVar("type", 200, "varname", "longtitudeA", "name", "longtitudeA", "autoInc", "0");
            dalTablerspdHeader["longtitudeB"] = new XVar("type", 200, "varname", "longtitudeB", "name", "longtitudeB", "autoInc", "0");
            dalTablerspdHeader["latitudeA"] = new XVar("type", 200, "varname", "latitudeA", "name", "latitudeA", "autoInc", "0");
            dalTablerspdHeader["latitudeB"] = new XVar("type", 200, "varname", "latitudeB", "name", "latitudeB", "autoInc", "0");
            dalTablerspdHeader["callSignA"] = new XVar("type", 200, "varname", "callSignA", "name", "callSignA", "autoInc", "0");
            dalTablerspdHeader["callSignB"] = new XVar("type", 200, "varname", "callSignB", "name", "callSignB", "autoInc", "0");
            dalTablerspdHeader["applicationType"] = new XVar("type", 200, "varname", "applicationType", "name", "applicationType", "autoInc", "0");
            dalTablerspdHeader["unit_a"] = new XVar("type", 200, "varname", "unit_a", "name", "unit_a", "autoInc", "0");
            dalTablerspdHeader["street_a"] = new XVar("type", 200, "varname", "street_a", "name", "street_a", "autoInc", "0");
            dalTablerspdHeader["barangay_a"] = new XVar("type", 200, "varname", "barangay_a", "name", "barangay_a", "autoInc", "0");
            dalTablerspdHeader["city_a"] = new XVar("type", 200, "varname", "city_a", "name", "city_a", "autoInc", "0");
            dalTablerspdHeader["province_a"] = new XVar("type", 200, "varname", "province_a", "name", "province_a", "autoInc", "0");
            dalTablerspdHeader["zipcode_a"] = new XVar("type", 200, "varname", "zipcode_a", "name", "zipcode_a", "autoInc", "0");
            dalTablerspdHeader["unit_b"] = new XVar("type", 200, "varname", "unit_b", "name", "unit_b", "autoInc", "0");
            dalTablerspdHeader["street_b"] = new XVar("type", 200, "varname", "street_b", "name", "street_b", "autoInc", "0");
            dalTablerspdHeader["barangay_b"] = new XVar("type", 200, "varname", "barangay_b", "name", "barangay_b", "autoInc", "0");
            dalTablerspdHeader["city_b"] = new XVar("type", 200, "varname", "city_b", "name", "city_b", "autoInc", "0");
            dalTablerspdHeader["province_b"] = new XVar("type", 200, "varname", "province_b", "name", "province_b", "autoInc", "0");
            dalTablerspdHeader["zipcode_b"] = new XVar("type", 200, "varname", "zipcode_b", "name", "zipcode_b", "autoInc", "0");
            dalTablerspdHeader["map"] = new XVar("type", 200, "varname", "map", "name", "map", "autoInc", "0");
            dalTablerspdHeader["stage"] = new XVar("type", 3, "varname", "stage", "name", "stage", "autoInc", "0");
            dalTablerspdHeader["stageStatus"] = new XVar("type", 200, "varname", "stageStatus", "name", "stageStatus", "autoInc", "0");
            dalTablerspdHeader["externalReferenceNo"] = new XVar("type", 200, "varname", "externalReferenceNo", "name", "externalReferenceNo", "autoInc", "0");
            dalTablerspdHeader["classStationService"] = new XVar("type", 200, "varname", "classStationService", "name", "classStationService", "autoInc", "0");
            dalTablerspdHeader["modeOfOperation"] = new XVar("type", 200, "varname", "modeOfOperation", "name", "modeOfOperation", "autoInc", "0");
            dalTablerspdHeader["Remarks"] = new XVar("type", 201, "varname", "Remarks", "name", "Remarks", "autoInc", "0");
            dalTablerspdHeader["dateOfApprovedBrief"] = new XVar("type", 200, "varname", "dateOfApprovedBrief", "name", "dateOfApprovedBrief", "autoInc", "0");
            dalTablerspdHeader["natureOfService"] = new XVar("type", 200, "varname", "natureOfService", "name", "natureOfService", "autoInc", "0");
            dalTablerspdHeader["recommendations"] = new XVar("type", 200, "varname", "recommendations", "name", "recommendations", "autoInc", "0");
            dalTablerspdHeader["applicationCategory"] = new XVar("type", 200, "varname", "applicationCategory", "name", "applicationCategory", "autoInc", "0");
            dalTablerspdHeader["address"] = new XVar("type", 201, "varname", "address", "name", "address", "autoInc", "0");
            dalTablerspdHeader["rt"] = new XVar("type", 3, "varname", "rt", "name", "rt", "autoInc", "0");
            dalTablerspdHeader["fx"] = new XVar("type", 3, "varname", "fx", "name", "fx", "autoInc", "0");
            dalTablerspdHeader["fb"] = new XVar("type", 3, "varname", "fb", "name", "fb", "autoInc", "0");
            dalTablerspdHeader["ml"] = new XVar("type", 3, "varname", "ml", "name", "ml", "autoInc", "0");
            dalTablerspdHeader["p"] = new XVar("type", 3, "varname", "p", "name", "p", "autoInc", "0");
            dalTablerspdHeader["bc"] = new XVar("type", 3, "varname", "bc", "name", "bc", "autoInc", "0");
            dalTablerspdHeader["fc"] = new XVar("type", 3, "varname", "fc", "name", "fc", "autoInc", "0");
            dalTablerspdHeader["fa"] = new XVar("type", 3, "varname", "fa", "name", "fa", "autoInc", "0");
            dalTablerspdHeader["ma"] = new XVar("type", 3, "varname", "ma", "name", "ma", "autoInc", "0");
            dalTablerspdHeader["tc"] = new XVar("type", 3, "varname", "tc", "name", "tc", "autoInc", "0");
            dalTablerspdHeader["other_ClassSS"] = new XVar("type", 200, "varname", "other_ClassSS", "name", "other_ClassSS", "autoInc", "0");
            dalTablerspdHeader["naturoOfRequest"] = new XVar("type", 200, "varname", "naturoOfRequest", "name", "naturoOfRequest", "autoInc", "0");
            dalTablerspdHeader["serviceArea"] = new XVar("type", 200, "varname", "serviceArea", "name", "serviceArea", "autoInc", "0");
            dalTablerspdHeader["caseNo"] = new XVar("type", 200, "varname", "caseNo", "name", "caseNo", "autoInc", "0");
            dalTablerspdHeader["frequencyRange"] = new XVar("type", 200, "varname", "frequencyRange", "name", "frequencyRange", "autoInc", "0");
            dalTablerspdHeader["directivity"] = new XVar("type", 200, "varname", "directivity", "name", "directivity", "autoInc", "0");
            dalTablerspdHeader["encoder"] = new XVar("type", 3, "varname", "encoder", "name", "encoder", "autoInc", "0");
            dalTablerspdHeader["evaluator"] = new XVar("type", 200, "varname", "evaluator", "name", "evaluator", "autoInc", "0");
            dalTablerspdHeader["position"] = new XVar("type", 200, "varname", "position", "name", "position", "autoInc", "0");
            dalTablerspdHeader["longDegA"] = new XVar("type", 14, "varname", "longDegA", "name", "longDegA", "autoInc", "0");
            dalTablerspdHeader["longMinA"] = new XVar("type", 14, "varname", "longMinA", "name", "longMinA", "autoInc", "0");
            dalTablerspdHeader["longSecA"] = new XVar("type", 14, "varname", "longSecA", "name", "longSecA", "autoInc", "0");
            dalTablerspdHeader["longDegB"] = new XVar("type", 14, "varname", "longDegB", "name", "longDegB", "autoInc", "0");
            dalTablerspdHeader["longMinB"] = new XVar("type", 14, "varname", "longMinB", "name", "longMinB", "autoInc", "0");
            dalTablerspdHeader["longSecB"] = new XVar("type", 14, "varname", "longSecB", "name", "longSecB", "autoInc", "0");
            dalTablerspdHeader["latDegA"] = new XVar("type", 14, "varname", "latDegA", "name", "latDegA", "autoInc", "0");
            dalTablerspdHeader["latMinA"] = new XVar("type", 14, "varname", "latMinA", "name", "latMinA", "autoInc", "0");
            dalTablerspdHeader["latSecA"] = new XVar("type", 14, "varname", "latSecA", "name", "latSecA", "autoInc", "0");
            dalTablerspdHeader["latDegB"] = new XVar("type", 14, "varname", "latDegB", "name", "latDegB", "autoInc", "0");
            dalTablerspdHeader["latMinB"] = new XVar("type", 14, "varname", "latMinB", "name", "latMinB", "autoInc", "0");
            dalTablerspdHeader["latSecB"] = new XVar("type", 14, "varname", "latSecB", "name", "latSecB", "autoInc", "0");
            dalTablerspdHeader["cardinalDirectionsLatA"] = new XVar("type", 200, "varname", "cardinalDirectionsLatA", "name", "cardinalDirectionsLatA", "autoInc", "0");
            dalTablerspdHeader["cardinalDirectionsLongB"] = new XVar("type", 200, "varname", "cardinalDirectionsLongB", "name", "cardinalDirectionsLongB", "autoInc", "0");
            dalTablerspdHeader["cardinalDirectionLongA"] = new XVar("type", 200, "varname", "cardinalDirectionLongA", "name", "cardinalDirectionLongA", "autoInc", "0");
            dalTablerspdHeader["cardinalDirectionLatB"] = new XVar("type", 200, "varname", "cardinalDirectionLatB", "name", "cardinalDirectionLatB", "autoInc", "0");
            dalTablerspdHeader["regionA"] = new XVar("type", 200, "varname", "regionA", "name", "regionA", "autoInc", "0");
            dalTablerspdHeader["regionB"] = new XVar("type", 200, "varname", "regionB", "name", "regionB", "autoInc", "0");
	        dalTablerspdHeader.InitAndSetArrayItem(true, "ID", "key");
            GlobalVars.dal_info["RSPDDB_at_172_16_0_80_dbo_rspdHeader"] = dalTablerspdHeader;
        }

        public  dalTable_RSPDDB_at_172_16_0_80_dbo_rspdHeader()
        {
            			this.m_TableName = "dbo.rspdHeader";
            this.m_infoKey = "RSPDDB_at_172_16_0_80_dbo_rspdHeader";
        }
    }
}