
		// <global>
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options____global____menu
			{
				static public XVar options()
				{
					return new XVar( "welcome", new XVar( "welcomePageSkip", false,
"welcomeItems", new XVar( "logo", new XVar( "menutItem", false ),
"menu", new XVar( "menutItem", false ),
"loginform_login", new XVar( "menutItem", false ),
"username_button", new XVar( "menutItem", false ),
"welcome_item", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.radioEquipment",
"page", "list" ),
"welcome_item1", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "Dashboard",
"page", "dashboard" ),
"welcome_item3", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.baranggay",
"page", "list" ),
"welcome_item2", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.city",
"page", "list" ),
"welcome_item4", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.province",
"page", "list" ),
"welcome_item5", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "FAS Report",
"page", "report" ),
"welcome_item7", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.stage",
"page", "list" ),
"welcome_item8", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.stageStatus",
"page", "list" ),
"welcome_item9", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.spectrum_beta_audit",
"page", "list" ),
"welcome_item14", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.spectrum_beta_settings",
"page", "list" ),
"welcome_item15", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.spectrum_betaugmembers",
"page", "list" ),
"welcome_item16", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.spectrum_betaugrights",
"page", "list" ),
"welcome_item17", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.transactionSetup",
"page", "list" ),
"welcome_item18", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "{04AFFBE6-86C0-47b0-ADD3-BA7FA19CA6FC}",
"page", null ),
"welcome_item10", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.rspd_application_received",
"page", "list" ),
"welcome_item11", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.applicationsRecieved",
"page", "list" ),
"welcome_item6", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.branch",
"page", "list" ),
"welcome_item12", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "users",
"page", "list" ),
"welcome_item13", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.classStation",
"page", "list" ),
"welcome_item19", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "applicationEndorsed",
"page", "list" ),
"welcome_item20", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "applicationUnderAssessment",
"page", "list" ),
"welcome_item21", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "applicationUnderTechnicalEvaluation",
"page", "list" ),
"welcome_item22", new XVar( "menutItem", true,
"group", false,
"linkType", 0,
"items", null,
"table", "dbo.region",
"page", "list" ) ) ),
"fields", new XVar( "gridFields", XVar.Array(),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar(  ) ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"supertop", new XVar( 0, "logo",
1, "menu",
2, "loginform_login",
3, "username_button" ),
"grid", new XVar( 0, "welcome_item",
1, "welcome_item1",
2, "welcome_item3",
3, "welcome_item2",
4, "welcome_item4",
5, "welcome_item5",
6, "welcome_item7",
7, "welcome_item8",
8, "welcome_item9",
9, "welcome_item14",
10, "welcome_item15",
11, "welcome_item16",
12, "welcome_item17",
13, "welcome_item18",
14, "welcome_item10",
15, "welcome_item11",
16, "welcome_item6",
17, "welcome_item12",
18, "welcome_item13",
19, "welcome_item19",
20, "welcome_item20",
21, "welcome_item21",
22, "welcome_item22" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array() ),
"itemForms", new XVar( "logo", "supertop",
"menu", "supertop",
"loginform_login", "supertop",
"username_button", "supertop",
"welcome_item", "grid",
"welcome_item1", "grid",
"welcome_item3", "grid",
"welcome_item2", "grid",
"welcome_item4", "grid",
"welcome_item5", "grid",
"welcome_item7", "grid",
"welcome_item8", "grid",
"welcome_item9", "grid",
"welcome_item14", "grid",
"welcome_item15", "grid",
"welcome_item16", "grid",
"welcome_item17", "grid",
"welcome_item18", "grid",
"welcome_item10", "grid",
"welcome_item11", "grid",
"welcome_item6", "grid",
"welcome_item12", "grid",
"welcome_item13", "grid",
"welcome_item19", "grid",
"welcome_item20", "grid",
"welcome_item21", "grid",
"welcome_item22", "grid" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar( "menu", 3,
"username_button", 3,
"loginform_login", 3 ) ),
"itemsByType", new XVar( "logo", new XVar( 0, "logo" ),
"menu", new XVar( 0, "menu" ),
"welcome_item", new XVar( 0, "welcome_item",
1, "welcome_item1",
2, "welcome_item2",
3, "welcome_item3",
4, "welcome_item4",
5, "welcome_item5",
6, "welcome_item6",
7, "welcome_item7",
8, "welcome_item8",
9, "welcome_item9",
10, "welcome_item10",
11, "welcome_item11",
12, "welcome_item12",
13, "welcome_item13",
14, "welcome_item14",
15, "welcome_item15",
16, "welcome_item16",
17, "welcome_item17",
18, "welcome_item18",
19, "welcome_item19",
20, "welcome_item20",
21, "welcome_item21",
22, "welcome_item22" ),
"username_button", new XVar( 0, "username_button" ),
"adminarea_link", new XVar( 0, "adminarea_link" ),
"loginform_login", new XVar( 0, "loginform_login" ),
"userinfo_link", new XVar( 0, "userinfo_link" ),
"logout_link", new XVar( 0, "logout_link" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 0 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", new XVar( 0, new XVar( "id", "main",
"horizontal", true ) ),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "menu",
"type", "menu",
"layoutId", "topbar",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "empty-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"supertop", new XVar( "modelId", "menu-topbar-menu",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "logo",
1, "menu" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "loginform_login",
1, "username_button" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "welcome",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "welcome_item",
1, "welcome_item1",
2, "welcome_item3",
3, "welcome_item2",
4, "welcome_item4",
5, "welcome_item5",
6, "welcome_item7",
7, "welcome_item8",
8, "welcome_item9",
9, "welcome_item14",
10, "welcome_item15",
11, "welcome_item16",
12, "welcome_item17",
13, "welcome_item18",
14, "welcome_item10",
15, "welcome_item11",
16, "welcome_item6",
17, "welcome_item12",
18, "welcome_item13",
19, "welcome_item19",
20, "welcome_item20",
21, "welcome_item21",
22, "welcome_item22" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "logo", new XVar( "type", "logo" ),
"menu", new XVar( "type", "menu" ),
"welcome_item", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.radioEquipment",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.radioEquipment",
"type", 6 ),
"linkIcon", new XVar( "glyph", "briefcase" ),
"linkComments", new XVar( "text", "Radio Equipment description",
"type", 0 ),
"background", "#DAA520",
"linkType", 0 ),
"welcome_item1", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "Dashboard",
"linkPage", "dashboard",
"linkText", new XVar( "table", "Dashboard",
"type", 6 ),
"linkIcon", new XVar( "glyph", "headphones" ),
"linkComments", new XVar( "text", "Dashboard description",
"type", 0 ),
"background", "#D2AF80",
"linkType", 0 ),
"welcome_item2", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.city",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.city",
"type", 6 ),
"linkIcon", new XVar( "glyph", "leaf" ),
"linkComments", new XVar( "text", "City description",
"type", 0 ),
"background", "#00C2C5",
"linkType", 0 ),
"welcome_item3", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.baranggay",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.baranggay",
"type", 6 ),
"linkIcon", new XVar( "glyph", "shopping-cart" ),
"linkComments", new XVar( "text", "Baranggay description",
"type", 0 ),
"background", "#4682B4",
"linkType", 0 ),
"welcome_item4", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.province",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.province",
"type", 6 ),
"linkIcon", new XVar( "glyph", "leaf" ),
"linkComments", new XVar( "text", "Province description",
"type", 0 ),
"background", "#BC8F8F",
"linkType", 0 ),
"username_button", new XVar( "type", "username_button",
"items", new XVar( 0, "userinfo_link",
1, "logout_link",
2, "adminarea_link" ) ),
"adminarea_link", new XVar( "type", "adminarea_link" ),
"loginform_login", new XVar( "type", "loginform_login",
"popup", false ),
"userinfo_link", new XVar( "type", "userinfo_link" ),
"logout_link", new XVar( "type", "logout_link" ),
"welcome_item5", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "FAS Report",
"linkPage", "report",
"linkText", new XVar( "table", "FAS Report",
"type", 6 ),
"linkIcon", new XVar( "glyph", "earphone" ),
"background", "#008B8B",
"linkType", 0 ),
"welcome_item6", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.branch",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.branch",
"type", 6 ),
"background", "#DAA520",
"linkType", 0 ),
"welcome_item7", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.stage",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.stage",
"type", 6 ),
"background", "#CFAE83",
"linkType", 0 ),
"welcome_item8", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.stageStatus",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.stageStatus",
"type", 6 ),
"background", "#00C2C5",
"linkType", 0 ),
"welcome_item9", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.spectrum_beta_audit",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.spectrum_beta_audit",
"type", 6 ),
"background", "#5F9EA0",
"linkType", 0 ),
"welcome_item10", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.rspd_application_received",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.rspd_application_received",
"type", 6 ),
"background", "#CFAE83",
"linkType", 0 ),
"welcome_item11", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.applicationsRecieved",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.applicationsRecieved",
"type", 6 ),
"background", "#6B8E23",
"linkType", 0 ),
"welcome_item12", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "users",
"linkPage", "list",
"linkText", new XVar( "table", "users",
"type", 6 ),
"background", "#D2691E",
"linkType", 0 ),
"welcome_item13", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.classStation",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.classStation",
"type", 6 ),
"background", "#EDCA00",
"linkType", 0 ),
"welcome_item14", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.spectrum_beta_settings",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.spectrum_beta_settings",
"type", 6 ),
"background", "#1E90FF",
"linkType", 0 ),
"welcome_item15", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.spectrum_betaugmembers",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.spectrum_betaugmembers",
"type", 6 ),
"background", "#4169E1",
"linkType", 0 ),
"welcome_item16", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.spectrum_betaugrights",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.spectrum_betaugrights",
"type", 6 ),
"background", "#8FBC8B",
"linkType", 0 ),
"welcome_item17", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.transactionSetup",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.transactionSetup",
"type", 6 ),
"background", "#DB7093",
"linkType", 0 ),
"welcome_item18", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "{04AFFBE6-86C0-47b0-ADD3-BA7FA19CA6FC}",
"linkPage", null,
"linkText", null,
"linkType", 0 ),
"welcome_item19", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "applicationEndorsed",
"linkPage", "list",
"linkText", new XVar( "table", "applicationEndorsed",
"type", 6 ),
"background", "#2F4F4F",
"linkType", 0 ),
"welcome_item20", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "applicationUnderAssessment",
"linkPage", "list",
"linkText", new XVar( "table", "applicationUnderAssessment",
"type", 6 ),
"background", "#DB7093",
"linkType", 0 ),
"welcome_item21", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "applicationUnderTechnicalEvaluation",
"linkPage", "list",
"linkText", new XVar( "table", "applicationUnderTechnicalEvaluation",
"type", 6 ),
"background", "#6B8E23",
"linkType", 0 ),
"welcome_item22", new XVar( "type", "welcome_item",
"linkUrl", "",
"linkTable", "dbo.region",
"linkPage", "list",
"linkText", new XVar( "table", "dbo.region",
"type", 6 ),
"background", "#CD853F",
"linkType", 0 ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"welcomePageStay", true,
"listTotals", 1 );
				}
			}
		}