
		// <global>
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options____global____userinfo
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "username",
1, "fullname",
2, "email" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "username", new XVar( 0, "integrated_edit_field" ),
"fullname", new XVar( 0, "integrated_edit_field1" ),
"email", new XVar( 0, "integrated_edit_field2" ) ) ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"below-grid", XVar.Array(),
"supertop", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb",
3, "loginform_login",
4, "username_button" ),
"left", new XVar( 0, "logo",
1, "expand_button",
2, "menu" ),
"top", XVar.Array(),
"grid", new XVar( 0, "user_fields_title",
1, "fields_message",
2, "user_fields_reset",
3, "user_fields_save",
4, "integrated_edit_field",
5, "integrated_edit_field1",
6, "integrated_edit_field2" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array(),
"below-grid", XVar.Array(),
"top", XVar.Array() ),
"itemForms", new XVar( "expand_menu_button", "supertop",
"collapse_button", "supertop",
"breadcrumb", "supertop",
"loginform_login", "supertop",
"username_button", "supertop",
"logo", "left",
"expand_button", "left",
"menu", "left",
"user_fields_title", "grid",
"fields_message", "grid",
"user_fields_reset", "grid",
"user_fields_save", "grid",
"integrated_edit_field", "grid",
"integrated_edit_field1", "grid",
"integrated_edit_field2", "grid" ),
"itemLocations", new XVar( "user_fields_title", new XVar( "location", "grid",
"cellId", "fields_message" ),
"fields_message", new XVar( "location", "grid",
"cellId", "fields_message" ),
"user_fields_reset", new XVar( "location", "grid",
"cellId", "buttons" ),
"user_fields_save", new XVar( "location", "grid",
"cellId", "buttons" ),
"integrated_edit_field", new XVar( "location", "grid",
"cellId", "fields" ),
"integrated_edit_field1", new XVar( "location", "grid",
"cellId", "fields" ),
"integrated_edit_field2", new XVar( "location", "grid",
"cellId", "fields" ) ),
"itemVisiblity", new XVar( "breadcrumb", 5,
"expand_menu_button", 2,
"expand_button", 5 ) ),
"itemsByType", new XVar( "fields_message", new XVar( 0, "fields_message" ),
"user_fields_reset", new XVar( 0, "user_fields_reset" ),
"user_fields_save", new XVar( 0, "user_fields_save" ),
"user_fields_title", new XVar( 0, "user_fields_title" ),
"breadcrumb", new XVar( 0, "breadcrumb" ),
"logo", new XVar( 0, "logo" ),
"menu", new XVar( 0, "menu" ),
"expand_menu_button", new XVar( 0, "expand_menu_button" ),
"collapse_button", new XVar( 0, "collapse_button" ),
"integrated_edit_field", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2" ),
"username_button", new XVar( 0, "username_button" ),
"adminarea_link", new XVar( 0, "adminarea_link" ),
"loginform_login", new XVar( 0, "loginform_login" ),
"userinfo_link", new XVar( 0, "userinfo_link" ),
"logout_link", new XVar( 0, "logout_link" ),
"expand_button", new XVar( 0, "expand_button" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "fields_message", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "user_fields_title",
1, "fields_message" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"fields", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"buttons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "user_fields_reset",
1, "user_fields_save" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 3 ) ) ),
"page", new XVar( "verticalBar", true,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", new XVar( 0, new XVar( "id", "main",
"horizontal", false ) ),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "userinfo",
"type", "userinfo",
"layoutId", "leftbar",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "empty-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "empty-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"supertop", new XVar( "modelId", "leftbar-top-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "loginform_login",
1, "username_button" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"left", new XVar( "modelId", "leftbar-menu",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c0" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c0", new XVar( "model", "c0",
"items", new XVar( 0, "logo",
1, "expand_button" ) ),
"c1", new XVar( "model", "c1",
"items", new XVar( 0, "menu" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "empty-above-grid",
"grid", XVar.Array(),
"cells", new XVar(  ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "userinfo-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "fields_message" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "fields" ) ),
"section", "" ),
2, new XVar( "cells", new XVar( 0, new XVar( "cell", "buttons" ) ),
"section", "" ) ),
"cells", new XVar( "fields_message", new XVar( "model", "fields_message",
"items", new XVar( 0, "user_fields_title",
1, "fields_message" ) ),
"buttons", new XVar( "model", "buttons",
"items", new XVar( 0, "user_fields_reset",
1, "user_fields_save" ) ),
"fields", new XVar( "model", "fields",
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field1",
2, "integrated_edit_field2" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ) ),
"items", new XVar( "fields_message", new XVar( "type", "fields_message" ),
"user_fields_reset", new XVar( "type", "user_fields_reset" ),
"user_fields_save", new XVar( "type", "user_fields_save" ),
"user_fields_title", new XVar( "type", "user_fields_title",
"font-size", "24px" ),
"breadcrumb", new XVar( "type", "breadcrumb" ),
"logo", new XVar( "type", "logo" ),
"menu", new XVar( "type", "menu" ),
"expand_menu_button", new XVar( "type", "expand_menu_button" ),
"collapse_button", new XVar( "type", "collapse_button" ),
"integrated_edit_field", new XVar( "field", "username",
"type", "integrated_edit_field",
"orientation", 0 ),
"username_button", new XVar( "type", "username_button",
"items", new XVar( 0, "userinfo_link",
1, "logout_link",
2, "adminarea_link" ) ),
"adminarea_link", new XVar( "type", "adminarea_link" ),
"loginform_login", new XVar( "type", "loginform_login",
"popup", false ),
"userinfo_link", new XVar( "type", "userinfo_link" ),
"logout_link", new XVar( "type", "logout_link" ),
"integrated_edit_field1", new XVar( "field", "fullname",
"type", "integrated_edit_field",
"orientation", 0 ),
"integrated_edit_field2", new XVar( "field", "email",
"type", "integrated_edit_field",
"orientation", 0 ),
"expand_button", new XVar( "type", "expand_button" ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}