
		// applicationEndorsed
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_applicationendorsed_export
			{
				static public XVar options()
				{
					return new XVar( "totals", new XVar( "ID", new XVar( "totalsType", "" ),
"referenceID", new XVar( "totalsType", "" ),
"applicationNo", new XVar( "totalsType", "" ),
"companyNameA", new XVar( "totalsType", "" ),
"userCreate", new XVar( "totalsType", "" ),
"userUpdate", new XVar( "totalsType", "" ),
"dateCreated", new XVar( "totalsType", "" ),
"dateUpdated", new XVar( "totalsType", "" ),
"companyNameB", new XVar( "totalsType", "" ),
"siteNameA", new XVar( "totalsType", "" ),
"siteNameB", new XVar( "totalsType", "" ),
"siteIDA", new XVar( "totalsType", "" ),
"siteIDB", new XVar( "totalsType", "" ),
"coordinateA", new XVar( "totalsType", "" ),
"coordinateB", new XVar( "totalsType", "" ),
"elevationA", new XVar( "totalsType", "" ),
"elevationB", new XVar( "totalsType", "" ),
"makeTypeModelA", new XVar( "totalsType", "" ),
"gainA", new XVar( "totalsType", "" ),
"diameterA", new XVar( "totalsType", "" ),
"beamwidthA", new XVar( "totalsType", "" ),
"polarizationA", new XVar( "totalsType", "" ),
"azimuthA", new XVar( "totalsType", "" ),
"elevAngleA", new XVar( "totalsType", "" ),
"heightAGLA", new XVar( "totalsType", "" ),
"feederLengthA", new XVar( "totalsType", "" ),
"makeTypeModelB", new XVar( "totalsType", "" ),
"gainB", new XVar( "totalsType", "" ),
"diameterB", new XVar( "totalsType", "" ),
"beamwidthB", new XVar( "totalsType", "" ),
"polarizationB", new XVar( "totalsType", "" ),
"azimuthB", new XVar( "totalsType", "" ),
"elevAngleB", new XVar( "totalsType", "" ),
"heightAGLB", new XVar( "totalsType", "" ),
"feederLengthB", new XVar( "totalsType", "" ),
"longtitudeA", new XVar( "totalsType", "" ),
"longtitudeB", new XVar( "totalsType", "" ),
"latitudeA", new XVar( "totalsType", "" ),
"latitudeB", new XVar( "totalsType", "" ),
"callSignA", new XVar( "totalsType", "" ),
"callSignB", new XVar( "totalsType", "" ),
"applicationType", new XVar( "totalsType", "" ),
"unit_a", new XVar( "totalsType", "" ),
"street_a", new XVar( "totalsType", "" ),
"barangay_a", new XVar( "totalsType", "" ),
"city_a", new XVar( "totalsType", "" ),
"province_a", new XVar( "totalsType", "" ),
"zipcode_a", new XVar( "totalsType", "" ),
"unit_b", new XVar( "totalsType", "" ),
"street_b", new XVar( "totalsType", "" ),
"barangay_b", new XVar( "totalsType", "" ),
"city_b", new XVar( "totalsType", "" ),
"province_b", new XVar( "totalsType", "" ),
"zipcode_b", new XVar( "totalsType", "" ),
"map", new XVar( "totalsType", "" ),
"stage", new XVar( "totalsType", "" ),
"stageStatus", new XVar( "totalsType", "" ),
"externalReferenceNo", new XVar( "totalsType", "" ),
"classStationService", new XVar( "totalsType", "" ),
"modeOfOperation", new XVar( "totalsType", "" ),
"Remarks", new XVar( "totalsType", "" ),
"dateOfApprovedBrief", new XVar( "totalsType", "" ),
"natureOfService", new XVar( "totalsType", "" ),
"recommendations", new XVar( "totalsType", "" ),
"applicationCategory", new XVar( "totalsType", "" ),
"address", new XVar( "totalsType", "" ),
"rt", new XVar( "totalsType", "" ),
"fx", new XVar( "totalsType", "" ),
"fb", new XVar( "totalsType", "" ),
"ml", new XVar( "totalsType", "" ),
"p", new XVar( "totalsType", "" ),
"bc", new XVar( "totalsType", "" ),
"fc", new XVar( "totalsType", "" ),
"fa", new XVar( "totalsType", "" ),
"ma", new XVar( "totalsType", "" ),
"tc", new XVar( "totalsType", "" ),
"other_ClassSS", new XVar( "totalsType", "" ),
"naturoOfRequest", new XVar( "totalsType", "" ),
"serviceArea", new XVar( "totalsType", "" ),
"caseNo", new XVar( "totalsType", "" ),
"frequencyRange", new XVar( "totalsType", "" ),
"directivity", new XVar( "totalsType", "" ),
"encoder", new XVar( "totalsType", "" ),
"evaluator", new XVar( "totalsType", "" ),
"position", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "companyNameA",
1, "siteIDA",
2, "siteNameA",
3, "siteNameB",
4, "siteIDB",
5, "elevationA",
6, "elevationB",
7, "makeTypeModelA",
8, "gainA",
9, "diameterA",
10, "beamwidthA",
11, "polarizationA",
12, "azimuthA",
13, "elevAngleA",
14, "heightAGLA",
15, "feederLengthA",
16, "makeTypeModelB",
17, "gainB",
18, "diameterB",
19, "beamwidthB",
20, "polarizationB",
21, "azimuthB",
22, "elevAngleB",
23, "heightAGLB",
24, "feederLengthB",
25, "longtitudeA",
26, "longtitudeB",
27, "latitudeA",
28, "latitudeB",
29, "callSignA",
30, "callSignB",
31, "applicationType",
32, "unit_a",
33, "street_a",
34, "barangay_a",
35, "city_a",
36, "province_a",
37, "zipcode_a",
38, "unit_b",
39, "street_b",
40, "barangay_b",
41, "city_b",
42, "province_b",
43, "zipcode_b",
44, "stage",
45, "stageStatus",
46, "externalReferenceNo",
47, "classStationService",
48, "modeOfOperation",
49, "Remarks",
50, "dateOfApprovedBrief",
51, "natureOfService",
52, "recommendations",
53, "applicationCategory",
54, "address",
55, "rt",
56, "fx",
57, "fb",
58, "ml",
59, "p",
60, "bc",
61, "fc",
62, "fa",
63, "ma",
64, "tc",
65, "other_ClassSS",
66, "naturoOfRequest",
67, "serviceArea",
68, "caseNo",
69, "frequencyRange",
70, "directivity",
71, "encoder",
72, "evaluator",
73, "position" ),
"exportFields", new XVar( 0, "companyNameA",
1, "siteNameA",
2, "siteNameB",
3, "elevationA",
4, "elevationB",
5, "makeTypeModelA",
6, "gainA",
7, "diameterA",
8, "beamwidthA",
9, "polarizationA",
10, "azimuthA",
11, "elevAngleA",
12, "heightAGLA",
13, "feederLengthA",
14, "makeTypeModelB",
15, "gainB",
16, "diameterB",
17, "beamwidthB",
18, "polarizationB",
19, "azimuthB",
20, "elevAngleB",
21, "heightAGLB",
22, "feederLengthB",
23, "longtitudeA",
24, "longtitudeB",
25, "latitudeA",
26, "latitudeB",
27, "callSignA",
28, "callSignB",
29, "applicationType",
30, "unit_a",
31, "street_a",
32, "barangay_a",
33, "city_a",
34, "province_a",
35, "zipcode_a",
36, "unit_b",
37, "street_b",
38, "barangay_b",
39, "city_b",
40, "province_b",
41, "zipcode_b",
42, "siteIDA",
43, "siteIDB",
44, "stage",
45, "stageStatus",
46, "externalReferenceNo",
47, "classStationService",
48, "modeOfOperation",
49, "Remarks",
50, "dateOfApprovedBrief",
51, "recommendations",
52, "applicationCategory",
53, "address",
54, "natureOfService",
55, "rt",
56, "fx",
57, "fb",
58, "ml",
59, "p",
60, "bc",
61, "fc",
62, "fa",
63, "ma",
64, "tc",
65, "other_ClassSS",
66, "naturoOfRequest",
67, "serviceArea",
68, "caseNo",
69, "frequencyRange",
70, "directivity",
71, "encoder",
72, "evaluator",
73, "position" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "companyNameA", new XVar( 0, "export_field" ),
"siteIDA", new XVar( 0, "export_field1" ),
"siteNameA", new XVar( 0, "export_field2" ),
"siteNameB", new XVar( 0, "export_field3" ),
"siteIDB", new XVar( 0, "export_field4" ),
"elevationA", new XVar( 0, "export_field5" ),
"elevationB", new XVar( 0, "export_field6" ),
"makeTypeModelA", new XVar( 0, "export_field7" ),
"gainA", new XVar( 0, "export_field8" ),
"diameterA", new XVar( 0, "export_field9" ),
"beamwidthA", new XVar( 0, "export_field10" ),
"polarizationA", new XVar( 0, "export_field11" ),
"azimuthA", new XVar( 0, "export_field12" ),
"elevAngleA", new XVar( 0, "export_field13" ),
"heightAGLA", new XVar( 0, "export_field14" ),
"feederLengthA", new XVar( 0, "export_field15" ),
"makeTypeModelB", new XVar( 0, "export_field16" ),
"gainB", new XVar( 0, "export_field17" ),
"diameterB", new XVar( 0, "export_field18" ),
"beamwidthB", new XVar( 0, "export_field19" ),
"polarizationB", new XVar( 0, "export_field20" ),
"azimuthB", new XVar( 0, "export_field21" ),
"elevAngleB", new XVar( 0, "export_field22" ),
"heightAGLB", new XVar( 0, "export_field23" ),
"feederLengthB", new XVar( 0, "export_field24" ),
"longtitudeA", new XVar( 0, "export_field25" ),
"longtitudeB", new XVar( 0, "export_field26" ),
"latitudeA", new XVar( 0, "export_field27" ),
"latitudeB", new XVar( 0, "export_field28" ),
"callSignA", new XVar( 0, "export_field29" ),
"callSignB", new XVar( 0, "export_field30" ),
"applicationType", new XVar( 0, "export_field31" ),
"unit_a", new XVar( 0, "export_field32" ),
"street_a", new XVar( 0, "export_field33" ),
"barangay_a", new XVar( 0, "export_field34" ),
"city_a", new XVar( 0, "export_field35" ),
"province_a", new XVar( 0, "export_field36" ),
"zipcode_a", new XVar( 0, "export_field37" ),
"unit_b", new XVar( 0, "export_field38" ),
"street_b", new XVar( 0, "export_field39" ),
"barangay_b", new XVar( 0, "export_field40" ),
"city_b", new XVar( 0, "export_field41" ),
"province_b", new XVar( 0, "export_field42" ),
"zipcode_b", new XVar( 0, "export_field43" ),
"stage", new XVar( 0, "export_field44" ),
"stageStatus", new XVar( 0, "export_field45" ),
"externalReferenceNo", new XVar( 0, "export_field46" ),
"classStationService", new XVar( 0, "export_field47" ),
"modeOfOperation", new XVar( 0, "export_field48" ),
"Remarks", new XVar( 0, "export_field49" ),
"dateOfApprovedBrief", new XVar( 0, "export_field50" ),
"natureOfService", new XVar( 0, "export_field51" ),
"recommendations", new XVar( 0, "export_field52" ),
"applicationCategory", new XVar( 0, "export_field53" ),
"address", new XVar( 0, "export_field54" ),
"rt", new XVar( 0, "export_field55" ),
"fx", new XVar( 0, "export_field56" ),
"fb", new XVar( 0, "export_field57" ),
"ml", new XVar( 0, "export_field58" ),
"p", new XVar( 0, "export_field59" ),
"bc", new XVar( 0, "export_field60" ),
"fc", new XVar( 0, "export_field61" ),
"fa", new XVar( 0, "export_field62" ),
"ma", new XVar( 0, "export_field63" ),
"tc", new XVar( 0, "export_field64" ),
"other_ClassSS", new XVar( 0, "export_field65" ),
"naturoOfRequest", new XVar( 0, "export_field66" ),
"serviceArea", new XVar( 0, "export_field67" ),
"caseNo", new XVar( 0, "export_field68" ),
"frequencyRange", new XVar( 0, "export_field69" ),
"directivity", new XVar( 0, "export_field70" ),
"encoder", new XVar( 0, "export_field71" ),
"evaluator", new XVar( 0, "export_field72" ),
"position", new XVar( 0, "export_field73" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "export_header" ),
"grid", new XVar( 0, "export_field",
1, "export_field2",
2, "export_field3",
3, "export_field5",
4, "export_field6",
5, "export_field7",
6, "export_field8",
7, "export_field9",
8, "export_field10",
9, "export_field11",
10, "export_field12",
11, "export_field13",
12, "export_field14",
13, "export_field15",
14, "export_field16",
15, "export_field17",
16, "export_field18",
17, "export_field19",
18, "export_field20",
19, "export_field21",
20, "export_field22",
21, "export_field23",
22, "export_field24",
23, "export_field25",
24, "export_field26",
25, "export_field27",
26, "export_field28",
27, "export_field29",
28, "export_field30",
29, "export_field31",
30, "export_field32",
31, "export_field33",
32, "export_field34",
33, "export_field35",
34, "export_field36",
35, "export_field37",
36, "export_field38",
37, "export_field39",
38, "export_field40",
39, "export_field41",
40, "export_field42",
41, "export_field43",
42, "export_field1",
43, "export_field4",
44, "export_field44",
45, "export_field45",
46, "export_field46",
47, "export_field47",
48, "export_field48",
49, "export_field49",
50, "export_field50",
51, "export_field52",
52, "export_field53",
53, "export_field54",
54, "export_field51",
55, "export_field55",
56, "export_field56",
57, "export_field57",
58, "export_field58",
59, "export_field59",
60, "export_field60",
61, "export_field61",
62, "export_field62",
63, "export_field63",
64, "export_field64",
65, "export_field65",
66, "export_field66",
67, "export_field67",
68, "export_field68",
69, "export_field69",
70, "export_field70",
71, "export_field71",
72, "export_field72",
73, "export_field73" ),
"footer", new XVar( 0, "export_export",
1, "export_cancel" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "export_header", "top",
"export_field", "grid",
"export_field2", "grid",
"export_field3", "grid",
"export_field5", "grid",
"export_field6", "grid",
"export_field7", "grid",
"export_field8", "grid",
"export_field9", "grid",
"export_field10", "grid",
"export_field11", "grid",
"export_field12", "grid",
"export_field13", "grid",
"export_field14", "grid",
"export_field15", "grid",
"export_field16", "grid",
"export_field17", "grid",
"export_field18", "grid",
"export_field19", "grid",
"export_field20", "grid",
"export_field21", "grid",
"export_field22", "grid",
"export_field23", "grid",
"export_field24", "grid",
"export_field25", "grid",
"export_field26", "grid",
"export_field27", "grid",
"export_field28", "grid",
"export_field29", "grid",
"export_field30", "grid",
"export_field31", "grid",
"export_field32", "grid",
"export_field33", "grid",
"export_field34", "grid",
"export_field35", "grid",
"export_field36", "grid",
"export_field37", "grid",
"export_field38", "grid",
"export_field39", "grid",
"export_field40", "grid",
"export_field41", "grid",
"export_field42", "grid",
"export_field43", "grid",
"export_field1", "grid",
"export_field4", "grid",
"export_field44", "grid",
"export_field45", "grid",
"export_field46", "grid",
"export_field47", "grid",
"export_field48", "grid",
"export_field49", "grid",
"export_field50", "grid",
"export_field52", "grid",
"export_field53", "grid",
"export_field54", "grid",
"export_field51", "grid",
"export_field55", "grid",
"export_field56", "grid",
"export_field57", "grid",
"export_field58", "grid",
"export_field59", "grid",
"export_field60", "grid",
"export_field61", "grid",
"export_field62", "grid",
"export_field63", "grid",
"export_field64", "grid",
"export_field65", "grid",
"export_field66", "grid",
"export_field67", "grid",
"export_field68", "grid",
"export_field69", "grid",
"export_field70", "grid",
"export_field71", "grid",
"export_field72", "grid",
"export_field73", "grid",
"export_export", "footer",
"export_cancel", "footer" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "export_header", new XVar( 0, "export_header" ),
"export_export", new XVar( 0, "export_export" ),
"export_cancel", new XVar( 0, "export_cancel" ),
"export_field", new XVar( 0, "export_field",
1, "export_field1",
2, "export_field2",
3, "export_field3",
4, "export_field4",
5, "export_field5",
6, "export_field6",
7, "export_field7",
8, "export_field8",
9, "export_field9",
10, "export_field10",
11, "export_field11",
12, "export_field12",
13, "export_field13",
14, "export_field14",
15, "export_field15",
16, "export_field16",
17, "export_field17",
18, "export_field18",
19, "export_field19",
20, "export_field20",
21, "export_field21",
22, "export_field22",
23, "export_field23",
24, "export_field24",
25, "export_field25",
26, "export_field26",
27, "export_field27",
28, "export_field28",
29, "export_field29",
30, "export_field30",
31, "export_field31",
32, "export_field32",
33, "export_field33",
34, "export_field34",
35, "export_field35",
36, "export_field36",
37, "export_field37",
38, "export_field38",
39, "export_field39",
40, "export_field40",
41, "export_field41",
42, "export_field42",
43, "export_field43",
44, "export_field44",
45, "export_field45",
46, "export_field46",
47, "export_field47",
48, "export_field48",
49, "export_field49",
50, "export_field50",
51, "export_field51",
52, "export_field52",
53, "export_field53",
54, "export_field54",
55, "export_field55",
56, "export_field56",
57, "export_field57",
58, "export_field58",
59, "export_field59",
60, "export_field60",
61, "export_field61",
62, "export_field62",
63, "export_field63",
64, "export_field64",
65, "export_field65",
66, "export_field66",
67, "export_field67",
68, "export_field68",
69, "export_field69",
70, "export_field70",
71, "export_field71",
72, "export_field72",
73, "export_field73" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"export", new XVar( "format", 2,
"selectFields", false,
"delimiter", ",",
"selectDelimiter", false,
"exportFileTypes", new XVar( "excel", true,
"word", true,
"csv", true,
"xml", false ) ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "export",
"type", "export",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "export-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "export-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_field",
1, "export_field2",
2, "export_field3",
3, "export_field5",
4, "export_field6",
5, "export_field7",
6, "export_field8",
7, "export_field9",
8, "export_field10",
9, "export_field11",
10, "export_field12",
11, "export_field13",
12, "export_field14",
13, "export_field15",
14, "export_field16",
15, "export_field17",
16, "export_field18",
17, "export_field19",
18, "export_field20",
19, "export_field21",
20, "export_field22",
21, "export_field23",
22, "export_field24",
23, "export_field25",
24, "export_field26",
25, "export_field27",
26, "export_field28",
27, "export_field29",
28, "export_field30",
29, "export_field31",
30, "export_field32",
31, "export_field33",
32, "export_field34",
33, "export_field35",
34, "export_field36",
35, "export_field37",
36, "export_field38",
37, "export_field39",
38, "export_field40",
39, "export_field41",
40, "export_field42",
41, "export_field43",
42, "export_field1",
43, "export_field4",
44, "export_field44",
45, "export_field45",
46, "export_field46",
47, "export_field47",
48, "export_field48",
49, "export_field49",
50, "export_field50",
51, "export_field52",
52, "export_field53",
53, "export_field54",
54, "export_field51",
55, "export_field55",
56, "export_field56",
57, "export_field57",
58, "export_field58",
59, "export_field59",
60, "export_field60",
61, "export_field61",
62, "export_field62",
63, "export_field63",
64, "export_field64",
65, "export_field65",
66, "export_field66",
67, "export_field67",
68, "export_field68",
69, "export_field69",
70, "export_field70",
71, "export_field71",
72, "export_field72",
73, "export_field73" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"footer", new XVar( "modelId", "export-footer",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "export_export",
1, "export_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "export_header", new XVar( "type", "export_header" ),
"export_export", new XVar( "type", "export_export" ),
"export_cancel", new XVar( "type", "export_cancel" ),
"export_field", new XVar( "field", "companyNameA",
"type", "export_field" ),
"export_field1", new XVar( "field", "siteIDA",
"type", "export_field" ),
"export_field2", new XVar( "field", "siteNameA",
"type", "export_field" ),
"export_field3", new XVar( "field", "siteNameB",
"type", "export_field" ),
"export_field4", new XVar( "field", "siteIDB",
"type", "export_field" ),
"export_field5", new XVar( "field", "elevationA",
"type", "export_field" ),
"export_field6", new XVar( "field", "elevationB",
"type", "export_field" ),
"export_field7", new XVar( "field", "makeTypeModelA",
"type", "export_field" ),
"export_field8", new XVar( "field", "gainA",
"type", "export_field" ),
"export_field9", new XVar( "field", "diameterA",
"type", "export_field" ),
"export_field10", new XVar( "field", "beamwidthA",
"type", "export_field" ),
"export_field11", new XVar( "field", "polarizationA",
"type", "export_field" ),
"export_field12", new XVar( "field", "azimuthA",
"type", "export_field" ),
"export_field13", new XVar( "field", "elevAngleA",
"type", "export_field" ),
"export_field14", new XVar( "field", "heightAGLA",
"type", "export_field" ),
"export_field15", new XVar( "field", "feederLengthA",
"type", "export_field" ),
"export_field16", new XVar( "field", "makeTypeModelB",
"type", "export_field" ),
"export_field17", new XVar( "field", "gainB",
"type", "export_field" ),
"export_field18", new XVar( "field", "diameterB",
"type", "export_field" ),
"export_field19", new XVar( "field", "beamwidthB",
"type", "export_field" ),
"export_field20", new XVar( "field", "polarizationB",
"type", "export_field" ),
"export_field21", new XVar( "field", "azimuthB",
"type", "export_field" ),
"export_field22", new XVar( "field", "elevAngleB",
"type", "export_field" ),
"export_field23", new XVar( "field", "heightAGLB",
"type", "export_field" ),
"export_field24", new XVar( "field", "feederLengthB",
"type", "export_field" ),
"export_field25", new XVar( "field", "longtitudeA",
"type", "export_field" ),
"export_field26", new XVar( "field", "longtitudeB",
"type", "export_field" ),
"export_field27", new XVar( "field", "latitudeA",
"type", "export_field" ),
"export_field28", new XVar( "field", "latitudeB",
"type", "export_field" ),
"export_field29", new XVar( "field", "callSignA",
"type", "export_field" ),
"export_field30", new XVar( "field", "callSignB",
"type", "export_field" ),
"export_field31", new XVar( "field", "applicationType",
"type", "export_field" ),
"export_field32", new XVar( "field", "unit_a",
"type", "export_field" ),
"export_field33", new XVar( "field", "street_a",
"type", "export_field" ),
"export_field34", new XVar( "field", "barangay_a",
"type", "export_field" ),
"export_field35", new XVar( "field", "city_a",
"type", "export_field" ),
"export_field36", new XVar( "field", "province_a",
"type", "export_field" ),
"export_field37", new XVar( "field", "zipcode_a",
"type", "export_field" ),
"export_field38", new XVar( "field", "unit_b",
"type", "export_field" ),
"export_field39", new XVar( "field", "street_b",
"type", "export_field" ),
"export_field40", new XVar( "field", "barangay_b",
"type", "export_field" ),
"export_field41", new XVar( "field", "city_b",
"type", "export_field" ),
"export_field42", new XVar( "field", "province_b",
"type", "export_field" ),
"export_field43", new XVar( "field", "zipcode_b",
"type", "export_field" ),
"export_field44", new XVar( "field", "stage",
"type", "export_field" ),
"export_field45", new XVar( "field", "stageStatus",
"type", "export_field" ),
"export_field46", new XVar( "field", "externalReferenceNo",
"type", "export_field" ),
"export_field47", new XVar( "field", "classStationService",
"type", "export_field" ),
"export_field48", new XVar( "field", "modeOfOperation",
"type", "export_field" ),
"export_field49", new XVar( "field", "Remarks",
"type", "export_field" ),
"export_field50", new XVar( "field", "dateOfApprovedBrief",
"type", "export_field" ),
"export_field51", new XVar( "field", "natureOfService",
"type", "export_field" ),
"export_field52", new XVar( "field", "recommendations",
"type", "export_field" ),
"export_field53", new XVar( "field", "applicationCategory",
"type", "export_field" ),
"export_field54", new XVar( "field", "address",
"type", "export_field" ),
"export_field55", new XVar( "field", "rt",
"type", "export_field" ),
"export_field56", new XVar( "field", "fx",
"type", "export_field" ),
"export_field57", new XVar( "field", "fb",
"type", "export_field" ),
"export_field58", new XVar( "field", "ml",
"type", "export_field" ),
"export_field59", new XVar( "field", "p",
"type", "export_field" ),
"export_field60", new XVar( "field", "bc",
"type", "export_field" ),
"export_field61", new XVar( "field", "fc",
"type", "export_field" ),
"export_field62", new XVar( "field", "fa",
"type", "export_field" ),
"export_field63", new XVar( "field", "ma",
"type", "export_field" ),
"export_field64", new XVar( "field", "tc",
"type", "export_field" ),
"export_field65", new XVar( "field", "other_ClassSS",
"type", "export_field" ),
"export_field66", new XVar( "field", "naturoOfRequest",
"type", "export_field" ),
"export_field67", new XVar( "field", "serviceArea",
"type", "export_field" ),
"export_field68", new XVar( "field", "caseNo",
"type", "export_field" ),
"export_field69", new XVar( "field", "frequencyRange",
"type", "export_field" ),
"export_field70", new XVar( "field", "directivity",
"type", "export_field" ),
"export_field71", new XVar( "field", "encoder",
"type", "export_field" ),
"export_field72", new XVar( "field", "evaluator",
"type", "export_field" ),
"export_field73", new XVar( "field", "position",
"type", "export_field" ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1,
"exportFormat", 2,
"exportDelimiter", ",",
"exportSelectDelimiter", false,
"exportSelectFields", false );
				}
			}
		}