
		// applicationUnderTechnicalEvaluation
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_applicationundertechnicalevaluation_view
			{
				static public XVar options()
				{
					return new XVar( "pdf", new XVar( "pdfView", true,
"orientation", "portrait",
"scale", 100 ),
"fields", new XVar( "gridFields", new XVar( 0, "rt",
1, "ml",
2, "fc",
3, "naturoOfRequest",
4, "position",
5, "dateOfApprovedBrief",
6, "recommendations",
7, "Remarks",
8, "directivity",
9, "serviceArea",
10, "evaluator",
11, "tc",
12, "fx",
13, "p",
14, "siteNameA",
15, "province_a",
16, "encoder",
17, "frequencyRange",
18, "caseNo",
19, "callSignB",
20, "callSignA",
21, "elevationB",
22, "latitudeB",
23, "longtitudeB",
24, "elevationA",
25, "latitudeA",
26, "longtitudeA",
27, "natureOfService",
28, "beamwidthA",
29, "modeOfOperation",
30, "externalReferenceNo",
31, "polarizationB",
32, "siteIDA",
33, "city_a",
34, "companyNameA",
35, "applicationCategory",
36, "gainB",
37, "applicationType",
38, "makeTypeModelB",
39, "zipcode_a",
40, "barangay_a",
41, "street_a",
42, "unit_a",
43, "siteNameB",
44, "referenceID",
45, "azimuthB",
46, "beamwidthB",
47, "diameterB",
48, "other_ClassSS",
49, "polarizationA",
50, "diameterA",
51, "siteIDB",
52, "province_b",
53, "city_b",
54, "zipcode_b",
55, "azimuthA",
56, "barangay_b",
57, "street_b",
58, "elevAngleA",
59, "makeTypeModelA",
60, "unit_b",
61, "heightAGLA",
62, "gainA",
63, "feederLengthA",
64, "ma",
65, "bc",
66, "fb",
67, "fa",
68, "feederLengthB",
69, "heightAGLB",
70, "elevAngleB" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "rt", new XVar( 0, "integrated_edit_field45" ),
"ml", new XVar( 0, "integrated_edit_field54" ),
"fc", new XVar( 0, "integrated_edit_field57" ),
"naturoOfRequest", new XVar( 0, "integrated_edit_field63" ),
"position", new XVar( 0, "integrated_edit_field70" ),
"dateOfApprovedBrief", new XVar( 0, "integrated_edit_field48" ),
"recommendations", new XVar( 0, "integrated_edit_field50" ),
"Remarks", new XVar( 0, "integrated_edit_field47" ),
"directivity", new XVar( 0, "integrated_edit_field67" ),
"serviceArea", new XVar( 0, "integrated_edit_field64" ),
"evaluator", new XVar( 0, "integrated_edit_field69" ),
"tc", new XVar( 0, "integrated_edit_field60" ),
"fx", new XVar( 0, "integrated_edit_field52" ),
"p", new XVar( 0, "integrated_edit_field55" ),
"siteNameA", new XVar( 0, "integrated_edit_field2" ),
"province_a", new XVar( 0, "integrated_edit_field36" ),
"encoder", new XVar( 0, "integrated_edit_field68" ),
"frequencyRange", new XVar( 0, "integrated_edit_field66" ),
"caseNo", new XVar( 0, "integrated_edit_field65" ),
"callSignB", new XVar( 0, "integrated_edit_field4" ),
"callSignA", new XVar( 0, "integrated_edit_field1" ),
"elevationB", new XVar( 0, "integrated_edit_field6" ),
"latitudeB", new XVar( 0, "integrated_edit_field28" ),
"longtitudeB", new XVar( 0, "integrated_edit_field26" ),
"elevationA", new XVar( 0, "integrated_edit_field5" ),
"latitudeA", new XVar( 0, "integrated_edit_field27" ),
"longtitudeA", new XVar( 0, "integrated_edit_field25" ),
"natureOfService", new XVar( 0, "integrated_edit_field49" ),
"beamwidthA", new XVar( 0, "integrated_edit_field10" ),
"modeOfOperation", new XVar( 0, "integrated_edit_field46" ),
"externalReferenceNo", new XVar( 0, "integrated_edit_field44" ),
"polarizationB", new XVar( 0, "integrated_edit_field20" ),
"siteIDA", new XVar( 0, "integrated_edit_field30" ),
"city_a", new XVar( 0, "integrated_edit_field35" ),
"companyNameA", new XVar( 0, "integrated_edit_field" ),
"applicationCategory", new XVar( 0, "integrated_edit_field51" ),
"gainB", new XVar( 0, "integrated_edit_field17" ),
"applicationType", new XVar( 0, "integrated_edit_field29" ),
"makeTypeModelB", new XVar( 0, "integrated_edit_field16" ),
"zipcode_a", new XVar( 0, "integrated_edit_field37" ),
"barangay_a", new XVar( 0, "integrated_edit_field34" ),
"street_a", new XVar( 0, "integrated_edit_field33" ),
"unit_a", new XVar( 0, "integrated_edit_field32" ),
"siteNameB", new XVar( 0, "integrated_edit_field3" ),
"referenceID", new XVar( 0, "integrated_edit_field62" ),
"azimuthB", new XVar( 0, "integrated_edit_field21" ),
"beamwidthB", new XVar( 0, "integrated_edit_field19" ),
"diameterB", new XVar( 0, "integrated_edit_field18" ),
"other_ClassSS", new XVar( 0, "integrated_edit_field61" ),
"polarizationA", new XVar( 0, "integrated_edit_field11" ),
"diameterA", new XVar( 0, "integrated_edit_field9" ),
"siteIDB", new XVar( 0, "integrated_edit_field31" ),
"province_b", new XVar( 0, "integrated_edit_field42" ),
"city_b", new XVar( 0, "integrated_edit_field41" ),
"zipcode_b", new XVar( 0, "integrated_edit_field43" ),
"azimuthA", new XVar( 0, "integrated_edit_field12" ),
"barangay_b", new XVar( 0, "integrated_edit_field40" ),
"street_b", new XVar( 0, "integrated_edit_field39" ),
"elevAngleA", new XVar( 0, "integrated_edit_field13" ),
"makeTypeModelA", new XVar( 0, "integrated_edit_field7" ),
"unit_b", new XVar( 0, "integrated_edit_field38" ),
"heightAGLA", new XVar( 0, "integrated_edit_field14" ),
"gainA", new XVar( 0, "integrated_edit_field8" ),
"feederLengthA", new XVar( 0, "integrated_edit_field15" ),
"ma", new XVar( 0, "integrated_edit_field59" ),
"bc", new XVar( 0, "integrated_edit_field56" ),
"fb", new XVar( 0, "integrated_edit_field53" ),
"fa", new XVar( 0, "integrated_edit_field58" ),
"feederLengthB", new XVar( 0, "integrated_edit_field24" ),
"heightAGLB", new XVar( 0, "integrated_edit_field23" ),
"elevAngleB", new XVar( 0, "integrated_edit_field22" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"below-grid", new XVar( 0, "view_back_list",
1, "view_close",
2, "hamburger" ),
"top", new XVar( 0, "view_header" ),
"grid", new XVar( 0, "integrated_edit_field45",
1, "integrated_edit_field54",
2, "integrated_edit_field57",
3, "section5",
4, "integrated_edit_field67",
5, "integrated_edit_field64",
6, "integrated_edit_field69",
7, "integrated_edit_field60",
8, "integrated_edit_field52",
9, "integrated_edit_field55",
10, "section2",
11, "section4",
12, "integrated_edit_field58",
13, "integrated_edit_field53",
14, "integrated_edit_field56",
15, "integrated_edit_field59",
16, "integrated_edit_field61",
17, "integrated_edit_field62",
18, "integrated_edit_field29",
19, "integrated_edit_field51",
20, "integrated_edit_field",
21, "integrated_edit_field44",
22, "integrated_edit_field46",
23, "integrated_edit_field49",
24, "text",
25, "section3",
26, "integrated_edit_field65",
27, "integrated_edit_field66",
28, "integrated_edit_field68",
29, "integrated_edit_field70" ),
"section3", new XVar( 0, "integrated_edit_field25",
1, "integrated_edit_field27",
2, "integrated_edit_field5",
3, "integrated_edit_field26",
4, "integrated_edit_field28",
5, "integrated_edit_field6",
6, "details_preview4",
7, "integrated_edit_field1",
8, "integrated_edit_field4" ),
"section2", new XVar( 0, "integrated_edit_field2",
1, "integrated_edit_field30",
2, "integrated_edit_field36",
3, "integrated_edit_field35",
4, "integrated_edit_field37",
5, "integrated_edit_field34",
6, "integrated_edit_field33",
7, "integrated_edit_field32",
8, "integrated_edit_field3",
9, "integrated_edit_field31",
10, "integrated_edit_field42",
11, "integrated_edit_field41",
12, "integrated_edit_field43",
13, "integrated_edit_field40",
14, "integrated_edit_field39",
15, "integrated_edit_field38" ),
"section4", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field8",
2, "integrated_edit_field9",
3, "integrated_edit_field10",
4, "integrated_edit_field11",
5, "integrated_edit_field12",
6, "integrated_edit_field13",
7, "integrated_edit_field14",
8, "integrated_edit_field15",
9, "integrated_edit_field16",
10, "integrated_edit_field17",
11, "integrated_edit_field18",
12, "integrated_edit_field19",
13, "integrated_edit_field20",
14, "integrated_edit_field21",
15, "integrated_edit_field22",
16, "integrated_edit_field23",
17, "integrated_edit_field24" ),
"section5", new XVar( 0, "integrated_edit_field63",
1, "integrated_edit_field48",
2, "integrated_edit_field50",
3, "integrated_edit_field47" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array() ),
"itemForms", new XVar( "view_back_list", "below-grid",
"view_close", "below-grid",
"hamburger", "below-grid",
"view_header", "top",
"integrated_edit_field45", "grid",
"integrated_edit_field54", "grid",
"integrated_edit_field57", "grid",
"section5", "grid",
"integrated_edit_field67", "grid",
"integrated_edit_field64", "grid",
"integrated_edit_field69", "grid",
"integrated_edit_field60", "grid",
"integrated_edit_field52", "grid",
"integrated_edit_field55", "grid",
"section2", "grid",
"section4", "grid",
"integrated_edit_field58", "grid",
"integrated_edit_field53", "grid",
"integrated_edit_field56", "grid",
"integrated_edit_field59", "grid",
"integrated_edit_field61", "grid",
"integrated_edit_field62", "grid",
"integrated_edit_field29", "grid",
"integrated_edit_field51", "grid",
"integrated_edit_field", "grid",
"integrated_edit_field44", "grid",
"integrated_edit_field46", "grid",
"integrated_edit_field49", "grid",
"text", "grid",
"section3", "grid",
"integrated_edit_field65", "grid",
"integrated_edit_field66", "grid",
"integrated_edit_field68", "grid",
"integrated_edit_field70", "grid",
"integrated_edit_field25", "section3",
"integrated_edit_field27", "section3",
"integrated_edit_field5", "section3",
"integrated_edit_field26", "section3",
"integrated_edit_field28", "section3",
"integrated_edit_field6", "section3",
"details_preview4", "section3",
"integrated_edit_field1", "section3",
"integrated_edit_field4", "section3",
"integrated_edit_field2", "section2",
"integrated_edit_field30", "section2",
"integrated_edit_field36", "section2",
"integrated_edit_field35", "section2",
"integrated_edit_field37", "section2",
"integrated_edit_field34", "section2",
"integrated_edit_field33", "section2",
"integrated_edit_field32", "section2",
"integrated_edit_field3", "section2",
"integrated_edit_field31", "section2",
"integrated_edit_field42", "section2",
"integrated_edit_field41", "section2",
"integrated_edit_field43", "section2",
"integrated_edit_field40", "section2",
"integrated_edit_field39", "section2",
"integrated_edit_field38", "section2",
"integrated_edit_field7", "section4",
"integrated_edit_field8", "section4",
"integrated_edit_field9", "section4",
"integrated_edit_field10", "section4",
"integrated_edit_field11", "section4",
"integrated_edit_field12", "section4",
"integrated_edit_field13", "section4",
"integrated_edit_field14", "section4",
"integrated_edit_field15", "section4",
"integrated_edit_field16", "section4",
"integrated_edit_field17", "section4",
"integrated_edit_field18", "section4",
"integrated_edit_field19", "section4",
"integrated_edit_field20", "section4",
"integrated_edit_field21", "section4",
"integrated_edit_field22", "section4",
"integrated_edit_field23", "section4",
"integrated_edit_field24", "section4",
"integrated_edit_field63", "section5",
"integrated_edit_field48", "section5",
"integrated_edit_field50", "section5",
"integrated_edit_field47", "section5" ),
"itemLocations", new XVar( "integrated_edit_field45", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field54", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field57", new XVar( "location", "grid",
"cellId", "c3" ),
"section5", new XVar( "location", "grid",
"cellId", "c" ),
"integrated_edit_field67", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field64", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field69", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field60", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field52", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field55", new XVar( "location", "grid",
"cellId", "c12" ),
"section2", new XVar( "location", "grid",
"cellId", "c10" ),
"section4", new XVar( "location", "grid",
"cellId", "c28" ),
"integrated_edit_field58", new XVar( "location", "grid",
"cellId", "c4" ),
"integrated_edit_field53", new XVar( "location", "grid",
"cellId", "c4" ),
"integrated_edit_field56", new XVar( "location", "grid",
"cellId", "c4" ),
"integrated_edit_field59", new XVar( "location", "grid",
"cellId", "c7" ),
"integrated_edit_field61", new XVar( "location", "grid",
"cellId", "c7" ),
"integrated_edit_field62", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field29", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field51", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field44", new XVar( "location", "grid",
"cellId", "c18" ),
"integrated_edit_field46", new XVar( "location", "grid",
"cellId", "c18" ),
"integrated_edit_field49", new XVar( "location", "grid",
"cellId", "c18" ),
"text", new XVar( "location", "grid",
"cellId", "c8" ),
"section3", new XVar( "location", "grid",
"cellId", "c19" ),
"integrated_edit_field65", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field66", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field68", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field70", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field25", new XVar( "location", "section3",
"cellId", "c1" ),
"integrated_edit_field27", new XVar( "location", "section3",
"cellId", "c1" ),
"integrated_edit_field5", new XVar( "location", "section3",
"cellId", "c1" ),
"integrated_edit_field26", new XVar( "location", "section3",
"cellId", "c" ),
"integrated_edit_field28", new XVar( "location", "section3",
"cellId", "c" ),
"integrated_edit_field6", new XVar( "location", "section3",
"cellId", "c" ),
"details_preview4", new XVar( "location", "section3",
"cellId", "c3" ),
"integrated_edit_field1", new XVar( "location", "section3",
"cellId", "c4" ),
"integrated_edit_field4", new XVar( "location", "section3",
"cellId", "c5" ),
"integrated_edit_field2", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field30", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field36", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field35", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field37", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field34", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field33", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field32", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field3", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field31", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field42", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field41", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field43", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field40", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field39", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field38", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field7", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field8", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field9", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field10", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field11", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field12", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field13", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field14", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field15", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field16", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field17", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field18", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field19", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field20", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field21", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field22", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field23", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field24", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field63", new XVar( "location", "section5",
"cellId", "c1" ),
"integrated_edit_field48", new XVar( "location", "section5",
"cellId", "c1" ),
"integrated_edit_field50", new XVar( "location", "section5",
"cellId", "c1" ),
"integrated_edit_field47", new XVar( "location", "section5",
"cellId", "c" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "view_header", new XVar( 0, "view_header" ),
"view_back_list", new XVar( 0, "view_back_list" ),
"view_close", new XVar( 0, "view_close" ),
"hamburger", new XVar( 0, "hamburger" ),
"integrated_edit_field", new XVar( 0, "integrated_edit_field45",
1, "integrated_edit_field54",
2, "integrated_edit_field57",
3, "integrated_edit_field63",
4, "integrated_edit_field70",
5, "integrated_edit_field48",
6, "integrated_edit_field50",
7, "integrated_edit_field47",
8, "integrated_edit_field67",
9, "integrated_edit_field64",
10, "integrated_edit_field69",
11, "integrated_edit_field60",
12, "integrated_edit_field52",
13, "integrated_edit_field55",
14, "integrated_edit_field2",
15, "integrated_edit_field36",
16, "integrated_edit_field68",
17, "integrated_edit_field66",
18, "integrated_edit_field65",
19, "integrated_edit_field4",
20, "integrated_edit_field1",
21, "integrated_edit_field6",
22, "integrated_edit_field28",
23, "integrated_edit_field26",
24, "integrated_edit_field5",
25, "integrated_edit_field27",
26, "integrated_edit_field25",
27, "integrated_edit_field49",
28, "integrated_edit_field10",
29, "integrated_edit_field46",
30, "integrated_edit_field44",
31, "integrated_edit_field20",
32, "integrated_edit_field30",
33, "integrated_edit_field35",
34, "integrated_edit_field",
35, "integrated_edit_field51",
36, "integrated_edit_field17",
37, "integrated_edit_field29",
38, "integrated_edit_field16",
39, "integrated_edit_field37",
40, "integrated_edit_field34",
41, "integrated_edit_field33",
42, "integrated_edit_field32",
43, "integrated_edit_field3",
44, "integrated_edit_field62",
45, "integrated_edit_field21",
46, "integrated_edit_field19",
47, "integrated_edit_field18",
48, "integrated_edit_field61",
49, "integrated_edit_field11",
50, "integrated_edit_field9",
51, "integrated_edit_field31",
52, "integrated_edit_field42",
53, "integrated_edit_field41",
54, "integrated_edit_field43",
55, "integrated_edit_field12",
56, "integrated_edit_field40",
57, "integrated_edit_field39",
58, "integrated_edit_field13",
59, "integrated_edit_field7",
60, "integrated_edit_field38",
61, "integrated_edit_field14",
62, "integrated_edit_field8",
63, "integrated_edit_field15",
64, "integrated_edit_field59",
65, "integrated_edit_field56",
66, "integrated_edit_field53",
67, "integrated_edit_field58",
68, "integrated_edit_field24",
69, "integrated_edit_field23",
70, "integrated_edit_field22" ),
"section", new XVar( 0, "section5",
1, "section2",
2, "section3",
3, "section4" ),
"details_preview", new XVar( 0, "details_preview4" ),
"text", new XVar( 0, "text" ),
"view_pdf", new XVar( 0, "view_pdf" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c17", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field62",
1, "integrated_edit_field29",
2, "integrated_edit_field51",
3, "integrated_edit_field" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c18", new XVar( "cols", new XVar( 0, 3,
1, 4,
2, 5 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field44",
1, "integrated_edit_field46",
2, "integrated_edit_field49" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c8", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", new XVar( 0, "text" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c11", new XVar( "cols", new XVar( 0, 3,
1, 4,
2, 5 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field45",
1, "integrated_edit_field54",
2, "integrated_edit_field57" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c12", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field60",
1, "integrated_edit_field52",
2, "integrated_edit_field55" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c4", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field58",
1, "integrated_edit_field53",
2, "integrated_edit_field56" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c7", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field59",
1, "integrated_edit_field61" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c33", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c2", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c10", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4,
5, 5 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", new XVar( 0, "section2" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c19", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4,
5, 5 ),
"rows", new XVar( 0, 4 ),
"tags", XVar.Array(),
"items", new XVar( 0, "section3" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c28", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4,
5, 5 ),
"rows", new XVar( 0, 5 ),
"tags", XVar.Array(),
"items", new XVar( 0, "section4" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4,
5, 5 ),
"rows", new XVar( 0, 6 ),
"tags", XVar.Array(),
"items", new XVar( 0, "section5" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c5", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2 ),
"rows", new XVar( 0, 7 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field65",
1, "integrated_edit_field66",
2, "integrated_edit_field68",
3, "integrated_edit_field70" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c6", new XVar( "cols", new XVar( 0, 3,
1, 4,
2, 5 ),
"rows", new XVar( 0, 7 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field67",
1, "integrated_edit_field64",
2, "integrated_edit_field69" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 6,
"height", 8 ),
"section3", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field25",
1, "integrated_edit_field27",
2, "integrated_edit_field5" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field26",
1, "integrated_edit_field28",
2, "integrated_edit_field6" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c3", new XVar( "cols", new XVar( 0, 0,
1, 1 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", new XVar( 0, "details_preview4" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c4", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field1" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c5", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field4" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 2,
"height", 3 ),
"section2", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field2",
1, "integrated_edit_field30",
2, "integrated_edit_field36",
3, "integrated_edit_field35",
4, "integrated_edit_field37",
5, "integrated_edit_field34",
6, "integrated_edit_field33",
7, "integrated_edit_field32" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field3",
1, "integrated_edit_field31",
2, "integrated_edit_field42",
3, "integrated_edit_field41",
4, "integrated_edit_field43",
5, "integrated_edit_field40",
6, "integrated_edit_field39",
7, "integrated_edit_field38" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 2,
"height", 1 ),
"section4", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field8",
2, "integrated_edit_field9",
3, "integrated_edit_field10",
4, "integrated_edit_field11",
5, "integrated_edit_field12",
6, "integrated_edit_field13",
7, "integrated_edit_field14",
8, "integrated_edit_field15" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field16",
1, "integrated_edit_field17",
2, "integrated_edit_field18",
3, "integrated_edit_field19",
4, "integrated_edit_field20",
5, "integrated_edit_field21",
6, "integrated_edit_field22",
7, "integrated_edit_field23",
8, "integrated_edit_field24" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 2,
"height", 1 ),
"section5", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field63",
1, "integrated_edit_field48",
2, "integrated_edit_field50" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field47" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 2,
"height", 1 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "view",
"breadcrumb", false,
"nextPrev", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "view",
"type", "view",
"layoutId", "nomenu",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "view-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1",
"colspan", 2 ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "view-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_back_list",
1, "view_close" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "hamburger" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "view-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c17",
"colspan", 3 ),
1, new XVar( "cell", "c18",
"colspan", 3 ) ) ),
1, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c8",
"colspan", 3 ),
1, new XVar( "cell", "c11",
"colspan", 3 ) ) ),
2, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3",
"rowspan", 1 ),
1, new XVar( "cell", "c12" ),
2, new XVar( "cell", "c4",
"colspan", 1 ),
3, new XVar( "cell", "c7",
"rowspan", 1 ),
4, new XVar( "cell", "c33",
"rowspan", 1 ),
5, new XVar( "cell", "c2",
"colspan", 1 ) ),
"section", "" ),
3, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c10",
"colspan", 6 ) ) ),
4, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c19",
"colspan", 6,
"rowspan", 1 ) ) ),
5, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c28",
"colspan", 6 ) ) ),
6, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c",
"colspan", 6,
"rowspan", 1 ) ) ),
7, new XVar( "cells", new XVar( 0, new XVar( "cell", "c5",
"colspan", 3 ),
1, new XVar( "cell", "c6",
"colspan", 3 ) ),
"section", "" ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field45",
1, "integrated_edit_field54",
2, "integrated_edit_field57" ),
"align", "left" ),
"c", new XVar( "model", "c3",
"items", new XVar( 0, "section5" ) ),
"c6", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field67",
1, "integrated_edit_field64",
2, "integrated_edit_field69" ) ),
"c12", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field60",
1, "integrated_edit_field52",
2, "integrated_edit_field55" ),
"align", "left" ),
"c10", new XVar( "model", "c3",
"items", new XVar( 0, "section2" ),
"width", "33%" ),
"c28", new XVar( "model", "c3",
"items", new XVar( 0, "section4" ) ),
"c33", new XVar( "model", "c3",
"items", XVar.Array() ),
"c4", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field58",
1, "integrated_edit_field53",
2, "integrated_edit_field56" ),
"align", "left" ),
"c7", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field59",
1, "integrated_edit_field61" ),
"align", "left" ),
"c2", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "33%" ),
"c17", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field62",
1, "integrated_edit_field29",
2, "integrated_edit_field51",
3, "integrated_edit_field" ) ),
"c18", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field44",
1, "integrated_edit_field46",
2, "integrated_edit_field49" ) ),
"c8", new XVar( "model", "c3",
"items", new XVar( 0, "text" ),
"align", "left" ),
"c11", new XVar( "model", "c3",
"items", XVar.Array(),
"align", "left" ),
"c19", new XVar( "model", "c3",
"items", new XVar( 0, "section3" ) ),
"c5", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field65",
1, "integrated_edit_field66",
2, "integrated_edit_field68",
3, "integrated_edit_field70" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", true,
"separateLabels", false ),
"section3", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c" ) ),
"section", "" ),
1, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c3",
"colspan", 2 ) ) ),
2, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c4" ),
1, new XVar( "cell", "c5" ) ) ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field25",
1, "integrated_edit_field27",
2, "integrated_edit_field5" ) ),
"c", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field26",
1, "integrated_edit_field28",
2, "integrated_edit_field6" ) ),
"c3", new XVar( "model", "c1",
"items", new XVar( 0, "details_preview4" ) ),
"c4", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field1" ) ),
"c5", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field4" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section2", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field2",
1, "integrated_edit_field30",
2, "integrated_edit_field36",
3, "integrated_edit_field35",
4, "integrated_edit_field37",
5, "integrated_edit_field34",
6, "integrated_edit_field33",
7, "integrated_edit_field32" ) ),
"c", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field3",
1, "integrated_edit_field31",
2, "integrated_edit_field42",
3, "integrated_edit_field41",
4, "integrated_edit_field43",
5, "integrated_edit_field40",
6, "integrated_edit_field39",
7, "integrated_edit_field38" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section4", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field8",
2, "integrated_edit_field9",
3, "integrated_edit_field10",
4, "integrated_edit_field11",
5, "integrated_edit_field12",
6, "integrated_edit_field13",
7, "integrated_edit_field14",
8, "integrated_edit_field15" ) ),
"c", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field16",
1, "integrated_edit_field17",
2, "integrated_edit_field18",
3, "integrated_edit_field19",
4, "integrated_edit_field20",
5, "integrated_edit_field21",
6, "integrated_edit_field22",
7, "integrated_edit_field23",
8, "integrated_edit_field24" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section5", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field63",
1, "integrated_edit_field48",
2, "integrated_edit_field50" ) ),
"c", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field47" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ) ),
"items", new XVar( "view_header", new XVar( "type", "view_header" ),
"view_back_list", new XVar( "type", "view_back_list" ),
"view_close", new XVar( "type", "view_close" ),
"hamburger", new XVar( "type", "hamburger",
"items", new XVar( 0, "view_pdf" ) ),
"integrated_edit_field45", new XVar( "field", "rt",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "rt",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field54", new XVar( "field", "ml",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "ml",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field57", new XVar( "field", "fc",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "fc",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"section5", new XVar( "type", "section",
"title", new XVar( "type", 0,
"text", "<h2><b><u>OTHERS</u></b></h2>" ),
"location", "section5",
"bsStyle", "default",
"panelType", 3,
"headerBg", "#0033c4",
"headerColor", "#fff",
"bodyBg", "",
"bodyColor", "",
"panelBorder", null,
"borderColor", "" ),
"integrated_edit_field63", new XVar( "field", "naturoOfRequest",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field70", new XVar( "field", "position",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field48", new XVar( "field", "dateOfApprovedBrief",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field50", new XVar( "field", "recommendations",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field47", new XVar( "field", "Remarks",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field67", new XVar( "field", "directivity",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field64", new XVar( "field", "serviceArea",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field69", new XVar( "field", "evaluator",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field60", new XVar( "field", "tc",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "tc",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field52", new XVar( "field", "fx",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "fx",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field55", new XVar( "field", "p",
"type", "integrated_edit_field",
"orientation", 1 ),
"section2", new XVar( "type", "section",
"title", new XVar( "type", 0,
"text", "<h2><b><u>STATION LOCATIONS</u></b></h2>" ),
"location", "section2",
"bsStyle", "default",
"panelType", 3,
"headerBg", "#0033c4",
"headerColor", "#FFF",
"bodyBg", "",
"bodyColor", "",
"panelBorder", null,
"borderColor", "" ),
"integrated_edit_field2", new XVar( "field", "siteNameA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "siteNameA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field36", new XVar( "field", "province_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "province_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field68", new XVar( "field", "encoder",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field66", new XVar( "field", "frequencyRange",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field65", new XVar( "field", "caseNo",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field4", new XVar( "field", "callSignB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field1", new XVar( "field", "callSignA",
"type", "integrated_edit_field",
"orientation", 1 ),
"details_preview4", new XVar( "type", "details_preview",
"table", "dbo.radioEquipment",
"items", XVar.Array(),
"popup", false,
"pageId", "list",
"bold", true ),
"integrated_edit_field6", new XVar( "field", "elevationB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field28", new XVar( "field", "latitudeB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field26", new XVar( "field", "longtitudeB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field5", new XVar( "field", "elevationA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "elevationA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field27", new XVar( "field", "latitudeA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "latitudeA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field25", new XVar( "field", "longtitudeA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "longtitudeA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"section3", new XVar( "type", "section",
"title", new XVar( "type", 0,
"text", "<h2><b><u>COORDINATES</u></b></h2>" ),
"location", "section3",
"bsStyle", "default",
"panelType", 3,
"headerBg", "#0033c4",
"headerColor", "#FFF",
"bodyBg", "",
"bodyColor", "",
"panelBorder", null,
"borderColor", "" ),
"text", new XVar( "type", "text",
"label", new XVar( "text", "<h2><u>Class of Station or Service</u></h2>",
"type", 0 ),
"editedByRte", true ),
"integrated_edit_field49", new XVar( "field", "natureOfService",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field10", new XVar( "field", "beamwidthA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "beamwidthA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field46", new XVar( "field", "modeOfOperation",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field44", new XVar( "field", "externalReferenceNo",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field20", new XVar( "field", "polarizationB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field30", new XVar( "field", "siteIDA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "siteIDA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field35", new XVar( "field", "city_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "city_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field", new XVar( "field", "companyNameA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field51", new XVar( "field", "applicationCategory",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field17", new XVar( "field", "gainB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field29", new XVar( "field", "applicationType",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field16", new XVar( "field", "makeTypeModelB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field37", new XVar( "field", "zipcode_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "zipcode_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field34", new XVar( "field", "barangay_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "barangay_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field33", new XVar( "field", "street_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "street_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"view_pdf", new XVar( "type", "view_pdf",
"targetPages", XVar.Array(),
"splitModes", XVar.Array(),
"scopes", XVar.Array() ),
"integrated_edit_field32", new XVar( "field", "unit_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "unit_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field3", new XVar( "field", "siteNameB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field62", new XVar( "field", "referenceID",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field21", new XVar( "field", "azimuthB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field19", new XVar( "field", "beamwidthB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field18", new XVar( "field", "diameterB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field61", new XVar( "field", "other_ClassSS",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "other_ClassSS",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field11", new XVar( "field", "polarizationA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "polarizationA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field9", new XVar( "field", "diameterA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "diameterA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field31", new XVar( "field", "siteIDB",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "siteIDB",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field42", new XVar( "field", "province_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field41", new XVar( "field", "city_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field43", new XVar( "field", "zipcode_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field12", new XVar( "field", "azimuthA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "azimuthA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field40", new XVar( "field", "barangay_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field39", new XVar( "field", "street_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field13", new XVar( "field", "elevAngleA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "elevAngleA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field7", new XVar( "field", "makeTypeModelA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "makeTypeModelA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field38", new XVar( "field", "unit_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field14", new XVar( "field", "heightAGLA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "heightAGLA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field8", new XVar( "field", "gainA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "gainA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"section4", new XVar( "type", "section",
"title", new XVar( "type", 0,
"text", "<h2><b><u>ANTENNA SYSTEM</u></b></h2>" ),
"location", "section4",
"bsStyle", "default",
"panelType", 3,
"headerBg", "#0033c4",
"headerColor", "#FFF",
"bodyBg", "",
"bodyColor", "",
"panelBorder", null,
"borderColor", "" ),
"integrated_edit_field15", new XVar( "field", "feederLengthA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "feederLengthA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field59", new XVar( "field", "ma",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "ma",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field56", new XVar( "field", "bc",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "bc",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field53", new XVar( "field", "fb",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "fb",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field58", new XVar( "field", "fa",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "fa",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field24", new XVar( "field", "feederLengthB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field23", new XVar( "field", "heightAGLB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field22", new XVar( "field", "elevAngleB",
"type", "integrated_edit_field",
"orientation", 1 ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}