
		// dbo.applicationsRecieved
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_applicationsrecieved_add
			{
				static public XVar options()
				{
					return new XVar( "captcha", new XVar( "captcha", false ),
"fields", new XVar( "gridFields", new XVar( 0, "companyNameA",
1, "siteNameA",
2, "callSignA",
3, "elevationA",
4, "siteNameB",
5, "callSignB",
6, "elevationB",
7, "makeTypeModelA",
8, "gainA",
9, "diameterA",
10, "beamwidthA",
11, "polarizationA",
12, "azimuthA",
13, "elevAngleA",
14, "heightAGLA",
15, "feederLengthA",
16, "makeTypeModelB",
17, "gainB",
18, "diameterB",
19, "beamwidthB",
20, "polarizationB",
21, "azimuthB",
22, "elevAngleB",
23, "heightAGLB",
24, "feederLengthB",
25, "longtitudeA",
26, "longtitudeB",
27, "latitudeA",
28, "latitudeB",
29, "applicationType",
30, "siteIDA",
31, "siteIDB",
32, "unit_a",
33, "street_a",
34, "barangay_a",
35, "city_a",
36, "province_a",
37, "zipcode_a",
38, "unit_b",
39, "street_b",
40, "barangay_b",
41, "city_b",
42, "province_b",
43, "zipcode_b",
44, "externalReferenceNo",
45, "classStationService",
46, "modeOfOperation",
47, "Remarks",
48, "dateOfApprovedBrief",
49, "natureOfService",
50, "recommendations",
51, "applicationCategory",
52, "rt",
53, "fx",
54, "fb",
55, "ml",
56, "p",
57, "bc",
58, "fc",
59, "fa",
60, "ma",
61, "tc",
62, "other_ClassSS",
63, "naturoOfRequest",
64, "serviceArea",
65, "caseNo",
66, "frequencyRange",
67, "directivity",
68, "encoder",
69, "evaluator",
70, "position" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "companyNameA", new XVar( 0, "integrated_edit_field" ),
"siteNameA", new XVar( 0, "integrated_edit_field2" ),
"callSignA", new XVar( 0, "integrated_edit_field1" ),
"elevationA", new XVar( 0, "integrated_edit_field5" ),
"siteNameB", new XVar( 0, "integrated_edit_field3" ),
"callSignB", new XVar( 0, "integrated_edit_field4" ),
"elevationB", new XVar( 0, "integrated_edit_field6" ),
"makeTypeModelA", new XVar( 0, "integrated_edit_field7" ),
"gainA", new XVar( 0, "integrated_edit_field8" ),
"diameterA", new XVar( 0, "integrated_edit_field9" ),
"beamwidthA", new XVar( 0, "integrated_edit_field10" ),
"polarizationA", new XVar( 0, "integrated_edit_field11" ),
"azimuthA", new XVar( 0, "integrated_edit_field12" ),
"elevAngleA", new XVar( 0, "integrated_edit_field13" ),
"heightAGLA", new XVar( 0, "integrated_edit_field14" ),
"feederLengthA", new XVar( 0, "integrated_edit_field15" ),
"makeTypeModelB", new XVar( 0, "integrated_edit_field16" ),
"gainB", new XVar( 0, "integrated_edit_field17" ),
"diameterB", new XVar( 0, "integrated_edit_field18" ),
"beamwidthB", new XVar( 0, "integrated_edit_field19" ),
"polarizationB", new XVar( 0, "integrated_edit_field20" ),
"azimuthB", new XVar( 0, "integrated_edit_field21" ),
"elevAngleB", new XVar( 0, "integrated_edit_field22" ),
"heightAGLB", new XVar( 0, "integrated_edit_field23" ),
"feederLengthB", new XVar( 0, "integrated_edit_field24" ),
"longtitudeA", new XVar( 0, "integrated_edit_field25" ),
"longtitudeB", new XVar( 0, "integrated_edit_field26" ),
"latitudeA", new XVar( 0, "integrated_edit_field27" ),
"latitudeB", new XVar( 0, "integrated_edit_field28" ),
"applicationType", new XVar( 0, "integrated_edit_field29" ),
"siteIDA", new XVar( 0, "integrated_edit_field30" ),
"siteIDB", new XVar( 0, "integrated_edit_field31" ),
"unit_a", new XVar( 0, "integrated_edit_field32" ),
"street_a", new XVar( 0, "integrated_edit_field33" ),
"barangay_a", new XVar( 0, "integrated_edit_field34" ),
"city_a", new XVar( 0, "integrated_edit_field35" ),
"province_a", new XVar( 0, "integrated_edit_field36" ),
"zipcode_a", new XVar( 0, "integrated_edit_field37" ),
"unit_b", new XVar( 0, "integrated_edit_field38" ),
"street_b", new XVar( 0, "integrated_edit_field39" ),
"barangay_b", new XVar( 0, "integrated_edit_field40" ),
"city_b", new XVar( 0, "integrated_edit_field41" ),
"province_b", new XVar( 0, "integrated_edit_field42" ),
"zipcode_b", new XVar( 0, "integrated_edit_field43" ),
"externalReferenceNo", new XVar( 0, "integrated_edit_field44" ),
"classStationService", new XVar( 0, "integrated_edit_field45" ),
"modeOfOperation", new XVar( 0, "integrated_edit_field46" ),
"Remarks", new XVar( 0, "integrated_edit_field47" ),
"dateOfApprovedBrief", new XVar( 0, "integrated_edit_field48" ),
"natureOfService", new XVar( 0, "integrated_edit_field49" ),
"recommendations", new XVar( 0, "integrated_edit_field50" ),
"applicationCategory", new XVar( 0, "integrated_edit_field51" ),
"rt", new XVar( 0, "integrated_edit_field52" ),
"fx", new XVar( 0, "integrated_edit_field53" ),
"fb", new XVar( 0, "integrated_edit_field54" ),
"ml", new XVar( 0, "integrated_edit_field55" ),
"p", new XVar( 0, "integrated_edit_field56" ),
"bc", new XVar( 0, "integrated_edit_field57" ),
"fc", new XVar( 0, "integrated_edit_field58" ),
"fa", new XVar( 0, "integrated_edit_field59" ),
"ma", new XVar( 0, "integrated_edit_field60" ),
"tc", new XVar( 0, "integrated_edit_field61" ),
"other_ClassSS", new XVar( 0, "integrated_edit_field62" ),
"naturoOfRequest", new XVar( 0, "integrated_edit_field63" ),
"serviceArea", new XVar( 0, "integrated_edit_field64" ),
"caseNo", new XVar( 0, "integrated_edit_field65" ),
"frequencyRange", new XVar( 0, "integrated_edit_field66" ),
"directivity", new XVar( 0, "integrated_edit_field67" ),
"encoder", new XVar( 0, "integrated_edit_field68" ),
"evaluator", new XVar( 0, "integrated_edit_field69" ),
"position", new XVar( 0, "integrated_edit_field70" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "add_message" ),
"below-grid", new XVar( 0, "add_save",
1, "add_reset",
2, "add_back_list",
3, "add_cancel" ),
"supertop", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "loginform_login",
3, "username_button" ),
"left", new XVar( 0, "logo",
1, "expand_button",
2, "menu" ),
"top", new XVar( 0, "add_header" ),
"grid", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field44",
2, "integrated_edit_field45",
3, "integrated_edit_field48",
4, "integrated_edit_field53",
5, "integrated_edit_field56",
6, "integrated_edit_field59",
7, "integrated_edit_field62",
8, "integrated_edit_field65",
9, "integrated_edit_field68",
10, "integrated_edit_field1",
11, "integrated_edit_field7",
12, "integrated_edit_field8",
13, "integrated_edit_field9",
14, "integrated_edit_field10",
15, "integrated_edit_field11",
16, "integrated_edit_field12",
17, "integrated_edit_field13",
18, "integrated_edit_field14",
19, "integrated_edit_field15",
20, "integrated_edit_field3",
21, "integrated_edit_field31",
22, "section1",
23, "integrated_edit_field52",
24, "integrated_edit_field55",
25, "integrated_edit_field58",
26, "integrated_edit_field61",
27, "integrated_edit_field64",
28, "integrated_edit_field67",
29, "integrated_edit_field70",
30, "integrated_edit_field49",
31, "integrated_edit_field54",
32, "integrated_edit_field57",
33, "integrated_edit_field60",
34, "integrated_edit_field63",
35, "integrated_edit_field66",
36, "integrated_edit_field69",
37, "details_preview4",
38, "integrated_edit_field2",
39, "integrated_edit_field30",
40, "section",
41, "integrated_edit_field29",
42, "integrated_edit_field51",
43, "integrated_edit_field46",
44, "integrated_edit_field50",
45, "integrated_edit_field47",
46, "text",
47, "integrated_edit_field16",
48, "integrated_edit_field17",
49, "integrated_edit_field18",
50, "integrated_edit_field19",
51, "integrated_edit_field20",
52, "integrated_edit_field21",
53, "integrated_edit_field22",
54, "integrated_edit_field23",
55, "integrated_edit_field24",
56, "integrated_edit_field4",
57, "text2",
58, "text1",
59, "integrated_edit_field25",
60, "integrated_edit_field27",
61, "integrated_edit_field5",
62, "integrated_edit_field26",
63, "integrated_edit_field28",
64, "integrated_edit_field6" ),
"section", new XVar( 0, "integrated_edit_field36",
1, "integrated_edit_field35",
2, "integrated_edit_field37",
3, "integrated_edit_field34",
4, "integrated_edit_field33",
5, "integrated_edit_field32" ),
"section1", new XVar( 0, "integrated_edit_field42",
1, "integrated_edit_field41",
2, "integrated_edit_field43",
3, "integrated_edit_field40",
4, "integrated_edit_field39",
5, "integrated_edit_field38" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "message_block" ) ),
"itemForms", new XVar( "add_message", "above-grid",
"add_save", "below-grid",
"add_reset", "below-grid",
"add_back_list", "below-grid",
"add_cancel", "below-grid",
"expand_menu_button", "supertop",
"collapse_button", "supertop",
"loginform_login", "supertop",
"username_button", "supertop",
"logo", "left",
"expand_button", "left",
"menu", "left",
"add_header", "top",
"integrated_edit_field", "grid",
"integrated_edit_field44", "grid",
"integrated_edit_field45", "grid",
"integrated_edit_field48", "grid",
"integrated_edit_field53", "grid",
"integrated_edit_field56", "grid",
"integrated_edit_field59", "grid",
"integrated_edit_field62", "grid",
"integrated_edit_field65", "grid",
"integrated_edit_field68", "grid",
"integrated_edit_field1", "grid",
"integrated_edit_field7", "grid",
"integrated_edit_field8", "grid",
"integrated_edit_field9", "grid",
"integrated_edit_field10", "grid",
"integrated_edit_field11", "grid",
"integrated_edit_field12", "grid",
"integrated_edit_field13", "grid",
"integrated_edit_field14", "grid",
"integrated_edit_field15", "grid",
"integrated_edit_field3", "grid",
"integrated_edit_field31", "grid",
"section1", "grid",
"integrated_edit_field52", "grid",
"integrated_edit_field55", "grid",
"integrated_edit_field58", "grid",
"integrated_edit_field61", "grid",
"integrated_edit_field64", "grid",
"integrated_edit_field67", "grid",
"integrated_edit_field70", "grid",
"integrated_edit_field49", "grid",
"integrated_edit_field54", "grid",
"integrated_edit_field57", "grid",
"integrated_edit_field60", "grid",
"integrated_edit_field63", "grid",
"integrated_edit_field66", "grid",
"integrated_edit_field69", "grid",
"details_preview4", "grid",
"integrated_edit_field2", "grid",
"integrated_edit_field30", "grid",
"section", "grid",
"integrated_edit_field29", "grid",
"integrated_edit_field51", "grid",
"integrated_edit_field46", "grid",
"integrated_edit_field50", "grid",
"integrated_edit_field47", "grid",
"text", "grid",
"integrated_edit_field16", "grid",
"integrated_edit_field17", "grid",
"integrated_edit_field18", "grid",
"integrated_edit_field19", "grid",
"integrated_edit_field20", "grid",
"integrated_edit_field21", "grid",
"integrated_edit_field22", "grid",
"integrated_edit_field23", "grid",
"integrated_edit_field24", "grid",
"integrated_edit_field4", "grid",
"text2", "grid",
"text1", "grid",
"integrated_edit_field25", "grid",
"integrated_edit_field27", "grid",
"integrated_edit_field5", "grid",
"integrated_edit_field26", "grid",
"integrated_edit_field28", "grid",
"integrated_edit_field6", "grid",
"integrated_edit_field36", "section",
"integrated_edit_field35", "section",
"integrated_edit_field37", "section",
"integrated_edit_field34", "section",
"integrated_edit_field33", "section",
"integrated_edit_field32", "section",
"integrated_edit_field42", "section1",
"integrated_edit_field41", "section1",
"integrated_edit_field43", "section1",
"integrated_edit_field40", "section1",
"integrated_edit_field39", "section1",
"integrated_edit_field38", "section1" ),
"itemLocations", new XVar( "integrated_edit_field", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field44", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field45", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field48", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field53", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field56", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field59", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field62", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field65", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field68", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field1", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field7", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field8", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field9", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field10", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field11", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field12", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field13", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field14", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field15", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field3", new XVar( "location", "grid",
"cellId", "c15" ),
"integrated_edit_field31", new XVar( "location", "grid",
"cellId", "c15" ),
"section1", new XVar( "location", "grid",
"cellId", "c15" ),
"integrated_edit_field52", new XVar( "location", "grid",
"cellId", "c16" ),
"integrated_edit_field55", new XVar( "location", "grid",
"cellId", "c16" ),
"integrated_edit_field58", new XVar( "location", "grid",
"cellId", "c16" ),
"integrated_edit_field61", new XVar( "location", "grid",
"cellId", "c16" ),
"integrated_edit_field64", new XVar( "location", "grid",
"cellId", "c16" ),
"integrated_edit_field67", new XVar( "location", "grid",
"cellId", "c16" ),
"integrated_edit_field70", new XVar( "location", "grid",
"cellId", "c16" ),
"integrated_edit_field49", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field54", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field57", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field60", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field63", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field66", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field69", new XVar( "location", "grid",
"cellId", "c17" ),
"details_preview4", new XVar( "location", "grid",
"cellId", "c21" ),
"integrated_edit_field2", new XVar( "location", "grid",
"cellId", "c20" ),
"integrated_edit_field30", new XVar( "location", "grid",
"cellId", "c20" ),
"section", new XVar( "location", "grid",
"cellId", "c20" ),
"integrated_edit_field29", new XVar( "location", "grid",
"cellId", "c8" ),
"integrated_edit_field51", new XVar( "location", "grid",
"cellId", "c8" ),
"integrated_edit_field46", new XVar( "location", "grid",
"cellId", "c10" ),
"integrated_edit_field50", new XVar( "location", "grid",
"cellId", "c10" ),
"integrated_edit_field47", new XVar( "location", "grid",
"cellId", "c10" ),
"text", new XVar( "location", "grid",
"cellId", "c22" ),
"integrated_edit_field16", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field17", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field18", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field19", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field20", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field21", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field22", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field23", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field24", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field4", new XVar( "location", "grid",
"cellId", "c24" ),
"text2", new XVar( "location", "grid",
"cellId", "c25" ),
"text1", new XVar( "location", "grid",
"cellId", "c29" ),
"integrated_edit_field25", new XVar( "location", "grid",
"cellId", "c30" ),
"integrated_edit_field27", new XVar( "location", "grid",
"cellId", "c30" ),
"integrated_edit_field5", new XVar( "location", "grid",
"cellId", "c30" ),
"integrated_edit_field26", new XVar( "location", "grid",
"cellId", "c32" ),
"integrated_edit_field28", new XVar( "location", "grid",
"cellId", "c32" ),
"integrated_edit_field6", new XVar( "location", "grid",
"cellId", "c32" ),
"integrated_edit_field36", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field35", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field37", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field34", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field33", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field32", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field42", new XVar( "location", "section1",
"cellId", "c1" ),
"integrated_edit_field41", new XVar( "location", "section1",
"cellId", "c1" ),
"integrated_edit_field43", new XVar( "location", "section1",
"cellId", "c1" ),
"integrated_edit_field40", new XVar( "location", "section1",
"cellId", "c1" ),
"integrated_edit_field39", new XVar( "location", "section1",
"cellId", "c1" ),
"integrated_edit_field38", new XVar( "location", "section1",
"cellId", "c1" ) ),
"itemVisiblity", new XVar( "expand_menu_button", 2,
"expand_button", 5 ) ),
"itemsByType", new XVar( "add_header", new XVar( 0, "add_header" ),
"add_message", new XVar( 0, "add_message" ),
"add_save", new XVar( 0, "add_save" ),
"add_reset", new XVar( 0, "add_reset" ),
"add_back_list", new XVar( 0, "add_back_list" ),
"add_cancel", new XVar( 0, "add_cancel" ),
"integrated_edit_field", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field2",
2, "integrated_edit_field1",
3, "integrated_edit_field5",
4, "integrated_edit_field3",
5, "integrated_edit_field4",
6, "integrated_edit_field6",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field13",
14, "integrated_edit_field14",
15, "integrated_edit_field15",
16, "integrated_edit_field16",
17, "integrated_edit_field17",
18, "integrated_edit_field18",
19, "integrated_edit_field19",
20, "integrated_edit_field20",
21, "integrated_edit_field21",
22, "integrated_edit_field22",
23, "integrated_edit_field23",
24, "integrated_edit_field24",
25, "integrated_edit_field25",
26, "integrated_edit_field26",
27, "integrated_edit_field27",
28, "integrated_edit_field28",
29, "integrated_edit_field29",
30, "integrated_edit_field30",
31, "integrated_edit_field31",
32, "integrated_edit_field32",
33, "integrated_edit_field33",
34, "integrated_edit_field34",
35, "integrated_edit_field35",
36, "integrated_edit_field36",
37, "integrated_edit_field37",
38, "integrated_edit_field38",
39, "integrated_edit_field39",
40, "integrated_edit_field40",
41, "integrated_edit_field41",
42, "integrated_edit_field42",
43, "integrated_edit_field43",
44, "integrated_edit_field44",
45, "integrated_edit_field45",
46, "integrated_edit_field46",
47, "integrated_edit_field47",
48, "integrated_edit_field48",
49, "integrated_edit_field49",
50, "integrated_edit_field50",
51, "integrated_edit_field51",
52, "integrated_edit_field52",
53, "integrated_edit_field53",
54, "integrated_edit_field54",
55, "integrated_edit_field55",
56, "integrated_edit_field56",
57, "integrated_edit_field57",
58, "integrated_edit_field58",
59, "integrated_edit_field59",
60, "integrated_edit_field60",
61, "integrated_edit_field61",
62, "integrated_edit_field62",
63, "integrated_edit_field63",
64, "integrated_edit_field64",
65, "integrated_edit_field65",
66, "integrated_edit_field66",
67, "integrated_edit_field67",
68, "integrated_edit_field68",
69, "integrated_edit_field69",
70, "integrated_edit_field70" ),
"logo", new XVar( 0, "logo" ),
"menu", new XVar( 0, "menu" ),
"expand_menu_button", new XVar( 0, "expand_menu_button" ),
"collapse_button", new XVar( 0, "collapse_button" ),
"details_preview", new XVar( 0, "details_preview4" ),
"text", new XVar( 0, "text",
1, "text1",
2, "text2" ),
"section", new XVar( 0, "section",
1, "section1" ),
"username_button", new XVar( 0, "username_button" ),
"adminarea_link", new XVar( 0, "adminarea_link" ),
"loginform_login", new XVar( 0, "loginform_login" ),
"userinfo_link", new XVar( 0, "userinfo_link" ),
"logout_link", new XVar( 0, "logout_link" ),
"expand_button", new XVar( 0, "expand_button" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c8", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field29",
1, "integrated_edit_field51" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c10", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0,
1, 1,
2, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field46",
1, "integrated_edit_field50",
2, "integrated_edit_field47" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c11", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c14", new XVar( "cols", new XVar( 0, 3,
1, 4 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field44",
2, "integrated_edit_field45",
3, "integrated_edit_field48" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c9", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1,
1, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 3,
1, 4 ),
"rows", new XVar( 0, 1,
1, 2,
2, 3,
3, 4,
4, 5 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c22", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "text" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c20", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field2",
1, "integrated_edit_field30",
2, "section" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c15", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field3",
1, "integrated_edit_field31",
2, "section1" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c18", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 3,
1, 4,
2, 5 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c29", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 4 ),
"tags", XVar.Array(),
"items", new XVar( 0, "text1" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c31", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 4 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c30", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 5 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field25",
1, "integrated_edit_field27",
2, "integrated_edit_field5" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c32", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 5 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field26",
1, "integrated_edit_field28",
2, "integrated_edit_field6" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c21", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4 ),
"rows", new XVar( 0, 6 ),
"tags", XVar.Array(),
"items", new XVar( 0, "details_preview4" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c25", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 7 ),
"tags", XVar.Array(),
"items", new XVar( 0, "text2" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c26", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 7 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c27", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 7 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c28", new XVar( "cols", new XVar( 0, 3,
1, 4 ),
"rows", new XVar( 0, 7 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c12", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 8 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field8",
2, "integrated_edit_field9",
3, "integrated_edit_field10",
4, "integrated_edit_field11",
5, "integrated_edit_field12",
6, "integrated_edit_field13",
7, "integrated_edit_field14",
8, "integrated_edit_field15" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c23", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 8 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field16",
1, "integrated_edit_field17",
2, "integrated_edit_field18",
3, "integrated_edit_field19",
4, "integrated_edit_field20",
5, "integrated_edit_field21",
6, "integrated_edit_field22",
7, "integrated_edit_field23",
8, "integrated_edit_field24" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c19", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 8 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c13", new XVar( "cols", new XVar( 0, 3,
1, 4 ),
"rows", new XVar( 0, 8 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c6", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 9 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field1" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c24", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 9 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field4" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c17", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 9 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field49",
1, "integrated_edit_field54",
2, "integrated_edit_field57",
3, "integrated_edit_field60",
4, "integrated_edit_field63",
5, "integrated_edit_field66",
6, "integrated_edit_field69" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c16", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 9 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field52",
1, "integrated_edit_field55",
2, "integrated_edit_field58",
3, "integrated_edit_field61",
4, "integrated_edit_field64",
5, "integrated_edit_field67",
6, "integrated_edit_field70" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c5", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 9 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field53",
1, "integrated_edit_field56",
2, "integrated_edit_field59",
3, "integrated_edit_field62",
4, "integrated_edit_field65",
5, "integrated_edit_field68" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 5,
"height", 10 ),
"section", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field36",
1, "integrated_edit_field35",
2, "integrated_edit_field37",
3, "integrated_edit_field34",
4, "integrated_edit_field33",
5, "integrated_edit_field32" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ),
"section1", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field42",
1, "integrated_edit_field41",
2, "integrated_edit_field43",
3, "integrated_edit_field40",
4, "integrated_edit_field39",
5, "integrated_edit_field38" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ) ) ),
"loginForm", new XVar( "loginForm", 0 ),
"page", new XVar( "verticalBar", true,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", new XVar( 0, new XVar( "id", "main",
"horizontal", false ) ),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "add",
"breadcrumb", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "add",
"type", "add",
"layoutId", "leftbar",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "add-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "add_message" ) ),
"c2", new XVar( "model", "c2",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "add-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "add_save",
1, "add_reset",
2, "add_back_list",
3, "add_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"supertop", new XVar( "modelId", "leftbar-top-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "expand_menu_button",
1, "collapse_button" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "loginform_login",
1, "username_button" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"left", new XVar( "modelId", "leftbar-menu",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c0" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c0", new XVar( "model", "c0",
"items", new XVar( 0, "logo",
1, "expand_button" ) ),
"c1", new XVar( "model", "c1",
"items", new XVar( 0, "menu" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "add-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "add_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c8" ),
1, new XVar( "cell", "c10",
"rowspan", 3 ),
2, new XVar( "cell", "c11" ),
3, new XVar( "cell", "c14",
"colspan", 2 ) ) ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ),
1, new XVar( "cell", "c9",
"rowspan", 2 ),
2, new XVar( "cell", "c",
"rowspan", 5,
"colspan", 2 ) ),
"section", "" ),
2, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c22" ) ) ),
3, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c20",
"rowspan", 1 ),
1, new XVar( "cell", "c15",
"rowspan", 1 ),
2, new XVar( "cell", "c18",
"rowspan", 3 ) ) ),
4, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c29" ),
1, new XVar( "cell", "c31" ) ) ),
5, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c30" ),
1, new XVar( "cell", "c32" ) ) ),
6, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c21",
"colspan", 5 ) ) ),
7, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c25" ),
1, new XVar( "cell", "c26" ),
2, new XVar( "cell", "c27" ),
3, new XVar( "cell", "c28",
"colspan", 2 ) ) ),
8, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c12" ),
1, new XVar( "cell", "c23" ),
2, new XVar( "cell", "c19" ),
3, new XVar( "cell", "c13",
"colspan", 2 ) ) ),
9, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c6" ),
1, new XVar( "cell", "c24" ),
2, new XVar( "cell", "c17" ),
3, new XVar( "cell", "c16",
"colspan", 1 ),
4, new XVar( "cell", "c5" ) ) ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field44",
2, "integrated_edit_field45",
3, "integrated_edit_field48" ),
"width", "33%",
"align", "left" ),
"c", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "33%" ),
"c5", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field53",
1, "integrated_edit_field56",
2, "integrated_edit_field59",
3, "integrated_edit_field62",
4, "integrated_edit_field65",
5, "integrated_edit_field68" ) ),
"c6", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field1" ) ),
"c9", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "20%" ),
"c12", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field8",
2, "integrated_edit_field9",
3, "integrated_edit_field10",
4, "integrated_edit_field11",
5, "integrated_edit_field12",
6, "integrated_edit_field13",
7, "integrated_edit_field14",
8, "integrated_edit_field15" ),
"width", "33%" ),
"c13", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "33%" ),
"c14", new XVar( "model", "c3",
"items", XVar.Array() ),
"c15", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field3",
1, "integrated_edit_field31",
2, "section1" ),
"width", "33%",
"align", "left" ),
"c16", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field52",
1, "integrated_edit_field55",
2, "integrated_edit_field58",
3, "integrated_edit_field61",
4, "integrated_edit_field64",
5, "integrated_edit_field67",
6, "integrated_edit_field70" ) ),
"c17", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field49",
1, "integrated_edit_field54",
2, "integrated_edit_field57",
3, "integrated_edit_field60",
4, "integrated_edit_field63",
5, "integrated_edit_field66",
6, "integrated_edit_field69" ) ),
"c18", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "33%" ),
"c19", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "33%" ),
"c21", new XVar( "model", "c3",
"items", new XVar( 0, "details_preview4" ) ),
"c20", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field2",
1, "integrated_edit_field30",
2, "section" ),
"width", "33%",
"align", "left" ),
"c8", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field29",
1, "integrated_edit_field51" ) ),
"c10", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field46",
1, "integrated_edit_field50",
2, "integrated_edit_field47" ) ),
"c11", new XVar( "model", "c3",
"items", XVar.Array() ),
"c22", new XVar( "model", "c3",
"items", new XVar( 0, "text" ),
"width", "33%",
"align", "left" ),
"c23", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field16",
1, "integrated_edit_field17",
2, "integrated_edit_field18",
3, "integrated_edit_field19",
4, "integrated_edit_field20",
5, "integrated_edit_field21",
6, "integrated_edit_field22",
7, "integrated_edit_field23",
8, "integrated_edit_field24" ),
"width", "33%" ),
"c24", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field4" ) ),
"c25", new XVar( "model", "c3",
"items", new XVar( 0, "text2" ) ),
"c26", new XVar( "model", "c3",
"items", XVar.Array() ),
"c27", new XVar( "model", "c3",
"items", XVar.Array() ),
"c28", new XVar( "model", "c3",
"items", XVar.Array() ),
"c29", new XVar( "model", "c3",
"items", new XVar( 0, "text1" ),
"width", "33%",
"align", "left" ),
"c30", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field25",
1, "integrated_edit_field27",
2, "integrated_edit_field5" ),
"width", "33%",
"align", "left" ),
"c31", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "33%",
"align", "left" ),
"c32", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field26",
1, "integrated_edit_field28",
2, "integrated_edit_field6" ),
"width", "33%",
"align", "left" ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", true,
"separateLabels", false ),
"section", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field36",
1, "integrated_edit_field35",
2, "integrated_edit_field37",
3, "integrated_edit_field34",
4, "integrated_edit_field33",
5, "integrated_edit_field32" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section1", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field42",
1, "integrated_edit_field41",
2, "integrated_edit_field43",
3, "integrated_edit_field40",
4, "integrated_edit_field39",
5, "integrated_edit_field38" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ) ),
"items", new XVar( "add_header", new XVar( "type", "add_header",
"title", new XVar( "page", "add",
"table", "dbo.rspdHeader",
"type", 7 ) ),
"add_message", new XVar( "type", "add_message" ),
"add_save", new XVar( "type", "add_save" ),
"add_reset", new XVar( "type", "add_reset" ),
"add_back_list", new XVar( "type", "add_back_list" ),
"add_cancel", new XVar( "type", "add_cancel" ),
"integrated_edit_field", new XVar( "field", "companyNameA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field2", new XVar( "field", "siteNameA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "siteNameA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field1", new XVar( "field", "callSignA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field5", new XVar( "field", "elevationA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "elevationA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field3", new XVar( "field", "siteNameB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field4", new XVar( "field", "callSignB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field6", new XVar( "field", "elevationB",
"type", "integrated_edit_field",
"orientation", 1 ),
"logo", new XVar( "type", "logo" ),
"menu", new XVar( "type", "menu" ),
"expand_menu_button", new XVar( "type", "expand_menu_button" ),
"collapse_button", new XVar( "type", "collapse_button" ),
"details_preview4", new XVar( "type", "details_preview",
"table", "dbo.radioEquipment",
"items", XVar.Array(),
"popup", false,
"pageId", "list" ),
"integrated_edit_field7", new XVar( "field", "makeTypeModelA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "makeTypeModelA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field8", new XVar( "field", "gainA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "gainA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field9", new XVar( "field", "diameterA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "diameterA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field10", new XVar( "field", "beamwidthA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "beamwidthA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field11", new XVar( "field", "polarizationA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "polarizationA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field12", new XVar( "field", "azimuthA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "azimuthA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field13", new XVar( "field", "elevAngleA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "elevAngleA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field14", new XVar( "field", "heightAGLA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "heightAGLA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field15", new XVar( "field", "feederLengthA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "feederLengthA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field16", new XVar( "field", "makeTypeModelB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field17", new XVar( "field", "gainB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field18", new XVar( "field", "diameterB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field19", new XVar( "field", "beamwidthB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field20", new XVar( "field", "polarizationB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field21", new XVar( "field", "azimuthB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field22", new XVar( "field", "elevAngleB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field23", new XVar( "field", "heightAGLB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field24", new XVar( "field", "feederLengthB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field25", new XVar( "field", "longtitudeA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "longtitudeA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field26", new XVar( "field", "longtitudeB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field27", new XVar( "field", "latitudeA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "latitudeA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field28", new XVar( "field", "latitudeB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field29", new XVar( "field", "applicationType",
"type", "integrated_edit_field",
"orientation", 1 ),
"text", new XVar( "type", "text",
"label", new XVar( "text", "<h2><u>STATION LOCATIONS</u></h2>",
"type", 0 ),
"editedByRte", true ),
"text1", new XVar( "type", "text",
"label", new XVar( "type", 0,
"text", "<h2><u>COORDINATES</u></h2>" ),
"editedByRte", true ),
"text2", new XVar( "type", "text",
"label", new XVar( "text", "<h2><u>ANTENNA SYSTEM</u></h2>",
"type", 0 ),
"editedByRte", true ),
"integrated_edit_field30", new XVar( "field", "siteIDA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "siteIDA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field31", new XVar( "field", "siteIDB",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "siteIDB",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"section", new XVar( "type", "section",
"title", new XVar( "type", 0,
"text", "Location Details" ),
"location", "section",
"bsStyle", "default",
"panelType", 3 ),
"integrated_edit_field32", new XVar( "field", "unit_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "unit_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field33", new XVar( "field", "street_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "street_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field34", new XVar( "field", "barangay_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "barangay_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field35", new XVar( "field", "city_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "city_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field36", new XVar( "field", "province_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "province_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field37", new XVar( "field", "zipcode_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "zipcode_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field38", new XVar( "field", "unit_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field39", new XVar( "field", "street_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field40", new XVar( "field", "barangay_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field41", new XVar( "field", "city_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field42", new XVar( "field", "province_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field43", new XVar( "field", "zipcode_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"section1", new XVar( "type", "section",
"title", new XVar( "type", 0,
"text", "Location Details" ),
"location", "section1",
"bsStyle", "default",
"panelType", 3 ),
"username_button", new XVar( "type", "username_button",
"items", new XVar( 0, "userinfo_link",
1, "logout_link",
2, "adminarea_link" ) ),
"adminarea_link", new XVar( "type", "adminarea_link" ),
"loginform_login", new XVar( "type", "loginform_login",
"popup", false ),
"userinfo_link", new XVar( "type", "userinfo_link" ),
"logout_link", new XVar( "type", "logout_link" ),
"integrated_edit_field44", new XVar( "field", "externalReferenceNo",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field45", new XVar( "field", "classStationService",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field46", new XVar( "field", "modeOfOperation",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field47", new XVar( "field", "Remarks",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field48", new XVar( "field", "dateOfApprovedBrief",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field49", new XVar( "field", "natureOfService",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field50", new XVar( "field", "recommendations",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field51", new XVar( "field", "applicationCategory",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field52", new XVar( "field", "rt",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field53", new XVar( "field", "fx",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field54", new XVar( "field", "fb",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field55", new XVar( "field", "ml",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field56", new XVar( "field", "p",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field57", new XVar( "field", "bc",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field58", new XVar( "field", "fc",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field59", new XVar( "field", "fa",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field60", new XVar( "field", "ma",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field61", new XVar( "field", "tc",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field62", new XVar( "field", "other_ClassSS",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field63", new XVar( "field", "naturoOfRequest",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field64", new XVar( "field", "serviceArea",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field65", new XVar( "field", "caseNo",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field66", new XVar( "field", "frequencyRange",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field67", new XVar( "field", "directivity",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field68", new XVar( "field", "encoder",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field69", new XVar( "field", "evaluator",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field70", new XVar( "field", "position",
"type", "integrated_edit_field",
"orientation", 1 ),
"expand_button", new XVar( "type", "expand_button" ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"pageCSS", "",
"listTotals", 1 );
				}
			}
		}