
		// dbo.rspdHeader
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_dbo_rspdheader_search
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "ID",
1, "referenceID",
2, "applicationNo",
3, "companyNameA",
4, "userCreate",
5, "userUpdate",
6, "dateCreated",
7, "dateUpdated",
8, "companyNameB",
9, "siteNameA",
10, "siteNameB",
11, "coordinateA",
12, "coordinateB",
13, "elevationA",
14, "elevationB",
15, "makeTypeModelA",
16, "gainA",
17, "diameterA",
18, "beamwidthA",
19, "polarizationA",
20, "azimuthA",
21, "elevAngleA",
22, "heightAGLA",
23, "feederLengthA",
24, "makeTypeModelB",
25, "gainB",
26, "diameterB",
27, "beamwidthB",
28, "polarizationB",
29, "azimuthB",
30, "elevAngleB",
31, "heightAGLB",
32, "feederLengthB",
33, "longtitudeA",
34, "longtitudeB",
35, "latitudeA",
36, "latitudeB",
37, "callSignA",
38, "callSignB",
39, "applicationType",
40, "unit_a",
41, "street_a",
42, "barangay_a",
43, "city_a",
44, "province_a",
45, "zipcode_a",
46, "unit_b",
47, "street_b",
48, "barangay_b",
49, "city_b",
50, "province_b",
51, "zipcode_b",
52, "map",
53, "stage",
54, "stageStatus",
55, "externalReferenceNo",
56, "classStationService",
57, "modeOfOperation",
58, "Remarks",
59, "dateOfApprovedBrief",
60, "natureOfService",
61, "recommendations",
62, "applicationCategory",
63, "address",
64, "rt",
65, "fx",
66, "fb",
67, "ml",
68, "p",
69, "bc",
70, "fc",
71, "fa",
72, "ma",
73, "tc",
74, "other_ClassSS",
75, "naturoOfRequest",
76, "serviceArea",
77, "caseNo",
78, "frequencyRange",
79, "directivity",
80, "encoder",
81, "evaluator",
82, "position",
83, "longDegA",
84, "longMinA",
85, "longSecA",
86, "longDegB",
87, "longMinB",
88, "longSecB",
89, "latDegA",
90, "latMinA",
91, "latSecA",
92, "latDegB",
93, "latMinB",
94, "latSecB",
95, "cardinalDirectionsLatA",
96, "cardinalDirectionsLongB",
97, "cardinalDirectionLongA",
98, "cardinalDirectionLatB",
99, "regionA",
100, "regionB" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "ID", new XVar( 0, "integrated_search_field" ),
"referenceID", new XVar( 0, "integrated_search_field1" ),
"applicationNo", new XVar( 0, "integrated_search_field2" ),
"companyNameA", new XVar( 0, "integrated_search_field3" ),
"userCreate", new XVar( 0, "integrated_search_field4" ),
"userUpdate", new XVar( 0, "integrated_search_field5" ),
"dateCreated", new XVar( 0, "integrated_search_field6" ),
"dateUpdated", new XVar( 0, "integrated_search_field7" ),
"companyNameB", new XVar( 0, "integrated_search_field8" ),
"siteNameA", new XVar( 0, "integrated_search_field9" ),
"siteNameB", new XVar( 0, "integrated_search_field10" ),
"coordinateA", new XVar( 0, "integrated_search_field11" ),
"coordinateB", new XVar( 0, "integrated_search_field12" ),
"elevationA", new XVar( 0, "integrated_search_field13" ),
"elevationB", new XVar( 0, "integrated_search_field14" ),
"makeTypeModelA", new XVar( 0, "integrated_search_field15" ),
"gainA", new XVar( 0, "integrated_search_field16" ),
"diameterA", new XVar( 0, "integrated_search_field17" ),
"beamwidthA", new XVar( 0, "integrated_search_field18" ),
"polarizationA", new XVar( 0, "integrated_search_field19" ),
"azimuthA", new XVar( 0, "integrated_search_field20" ),
"elevAngleA", new XVar( 0, "integrated_search_field21" ),
"heightAGLA", new XVar( 0, "integrated_search_field22" ),
"feederLengthA", new XVar( 0, "integrated_search_field23" ),
"makeTypeModelB", new XVar( 0, "integrated_search_field24" ),
"gainB", new XVar( 0, "integrated_search_field25" ),
"diameterB", new XVar( 0, "integrated_search_field26" ),
"beamwidthB", new XVar( 0, "integrated_search_field27" ),
"polarizationB", new XVar( 0, "integrated_search_field28" ),
"azimuthB", new XVar( 0, "integrated_search_field29" ),
"elevAngleB", new XVar( 0, "integrated_search_field30" ),
"heightAGLB", new XVar( 0, "integrated_search_field31" ),
"feederLengthB", new XVar( 0, "integrated_search_field32" ),
"longtitudeA", new XVar( 0, "integrated_search_field33" ),
"longtitudeB", new XVar( 0, "integrated_search_field34" ),
"latitudeA", new XVar( 0, "integrated_search_field35" ),
"latitudeB", new XVar( 0, "integrated_search_field36" ),
"callSignA", new XVar( 0, "integrated_search_field37" ),
"callSignB", new XVar( 0, "integrated_search_field38" ),
"applicationType", new XVar( 0, "integrated_search_field39" ),
"unit_a", new XVar( 0, "integrated_search_field40" ),
"street_a", new XVar( 0, "integrated_search_field41" ),
"barangay_a", new XVar( 0, "integrated_search_field42" ),
"city_a", new XVar( 0, "integrated_search_field43" ),
"province_a", new XVar( 0, "integrated_search_field44" ),
"zipcode_a", new XVar( 0, "integrated_search_field45" ),
"unit_b", new XVar( 0, "integrated_search_field46" ),
"street_b", new XVar( 0, "integrated_search_field47" ),
"barangay_b", new XVar( 0, "integrated_search_field48" ),
"city_b", new XVar( 0, "integrated_search_field49" ),
"province_b", new XVar( 0, "integrated_search_field50" ),
"zipcode_b", new XVar( 0, "integrated_search_field51" ),
"map", new XVar( 0, "integrated_search_field52" ),
"stage", new XVar( 0, "integrated_search_field53" ),
"stageStatus", new XVar( 0, "integrated_search_field54" ),
"externalReferenceNo", new XVar( 0, "integrated_search_field55" ),
"classStationService", new XVar( 0, "integrated_search_field56" ),
"modeOfOperation", new XVar( 0, "integrated_search_field57" ),
"Remarks", new XVar( 0, "integrated_search_field58" ),
"dateOfApprovedBrief", new XVar( 0, "integrated_search_field59" ),
"natureOfService", new XVar( 0, "integrated_search_field60" ),
"recommendations", new XVar( 0, "integrated_search_field61" ),
"applicationCategory", new XVar( 0, "integrated_search_field62" ),
"address", new XVar( 0, "integrated_search_field63" ),
"rt", new XVar( 0, "integrated_search_field64" ),
"fx", new XVar( 0, "integrated_search_field65" ),
"fb", new XVar( 0, "integrated_search_field66" ),
"ml", new XVar( 0, "integrated_search_field67" ),
"p", new XVar( 0, "integrated_search_field68" ),
"bc", new XVar( 0, "integrated_search_field69" ),
"fc", new XVar( 0, "integrated_search_field70" ),
"fa", new XVar( 0, "integrated_search_field71" ),
"ma", new XVar( 0, "integrated_search_field72" ),
"tc", new XVar( 0, "integrated_search_field73" ),
"other_ClassSS", new XVar( 0, "integrated_search_field74" ),
"naturoOfRequest", new XVar( 0, "integrated_search_field75" ),
"serviceArea", new XVar( 0, "integrated_search_field76" ),
"caseNo", new XVar( 0, "integrated_search_field77" ),
"frequencyRange", new XVar( 0, "integrated_search_field78" ),
"directivity", new XVar( 0, "integrated_search_field79" ),
"encoder", new XVar( 0, "integrated_search_field80" ),
"evaluator", new XVar( 0, "integrated_search_field81" ),
"position", new XVar( 0, "integrated_search_field82" ),
"longDegA", new XVar( 0, "integrated_search_field83" ),
"longMinA", new XVar( 0, "integrated_search_field84" ),
"longSecA", new XVar( 0, "integrated_search_field85" ),
"longDegB", new XVar( 0, "integrated_search_field86" ),
"longMinB", new XVar( 0, "integrated_search_field87" ),
"longSecB", new XVar( 0, "integrated_search_field88" ),
"latDegA", new XVar( 0, "integrated_search_field89" ),
"latMinA", new XVar( 0, "integrated_search_field90" ),
"latSecA", new XVar( 0, "integrated_search_field91" ),
"latDegB", new XVar( 0, "integrated_search_field92" ),
"latMinB", new XVar( 0, "integrated_search_field93" ),
"latSecB", new XVar( 0, "integrated_search_field94" ),
"cardinalDirectionsLatA", new XVar( 0, "integrated_search_field95" ),
"cardinalDirectionsLongB", new XVar( 0, "integrated_search_field96" ),
"cardinalDirectionLongA", new XVar( 0, "integrated_search_field97" ),
"cardinalDirectionLatB", new XVar( 0, "integrated_search_field98" ),
"regionA", new XVar( 0, "integrated_search_field99" ),
"regionB", new XVar( 0, "integrated_search_field100" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"below-grid", new XVar( 0, "search_search",
1, "search_reset",
2, "search_back_list",
3, "search_cancel" ),
"top", new XVar( 0, "search_header" ),
"grid", new XVar( 0, "integrated_search_field",
1, "integrated_search_field1",
2, "integrated_search_field2",
3, "integrated_search_field4",
4, "integrated_search_field5",
5, "integrated_search_field6",
6, "integrated_search_field7",
7, "integrated_search_field3",
8, "integrated_search_field8",
9, "integrated_search_field9",
10, "integrated_search_field10",
11, "integrated_search_field11",
12, "integrated_search_field12",
13, "integrated_search_field13",
14, "integrated_search_field14",
15, "integrated_search_field15",
16, "integrated_search_field16",
17, "integrated_search_field17",
18, "integrated_search_field18",
19, "integrated_search_field19",
20, "integrated_search_field20",
21, "integrated_search_field21",
22, "integrated_search_field22",
23, "integrated_search_field23",
24, "integrated_search_field24",
25, "integrated_search_field25",
26, "integrated_search_field26",
27, "integrated_search_field27",
28, "integrated_search_field28",
29, "integrated_search_field29",
30, "integrated_search_field30",
31, "integrated_search_field31",
32, "integrated_search_field32",
33, "integrated_search_field33",
34, "integrated_search_field34",
35, "integrated_search_field35",
36, "integrated_search_field36",
37, "integrated_search_field37",
38, "integrated_search_field38",
39, "integrated_search_field39",
40, "integrated_search_field40",
41, "integrated_search_field41",
42, "integrated_search_field42",
43, "integrated_search_field43",
44, "integrated_search_field44",
45, "integrated_search_field45",
46, "integrated_search_field46",
47, "integrated_search_field47",
48, "integrated_search_field48",
49, "integrated_search_field49",
50, "integrated_search_field50",
51, "integrated_search_field51",
52, "integrated_search_field52",
53, "integrated_search_field53",
54, "integrated_search_field54",
55, "integrated_search_field55",
56, "integrated_search_field56",
57, "integrated_search_field57",
58, "integrated_search_field58",
59, "integrated_search_field59",
60, "integrated_search_field61",
61, "integrated_search_field62",
62, "integrated_search_field63",
63, "integrated_search_field60",
64, "integrated_search_field64",
65, "integrated_search_field65",
66, "integrated_search_field66",
67, "integrated_search_field67",
68, "integrated_search_field68",
69, "integrated_search_field69",
70, "integrated_search_field70",
71, "integrated_search_field71",
72, "integrated_search_field72",
73, "integrated_search_field73",
74, "integrated_search_field74",
75, "integrated_search_field75",
76, "integrated_search_field76",
77, "integrated_search_field77",
78, "integrated_search_field78",
79, "integrated_search_field79",
80, "integrated_search_field80",
81, "integrated_search_field81",
82, "integrated_search_field82",
83, "integrated_search_field83",
84, "integrated_search_field84",
85, "integrated_search_field85",
86, "integrated_search_field86",
87, "integrated_search_field87",
88, "integrated_search_field88",
89, "integrated_search_field89",
90, "integrated_search_field90",
91, "integrated_search_field91",
92, "integrated_search_field92",
93, "integrated_search_field93",
94, "integrated_search_field94",
95, "integrated_search_field95",
96, "integrated_search_field96",
97, "integrated_search_field97",
98, "integrated_search_field98",
99, "integrated_search_field99",
100, "integrated_search_field100" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array() ),
"itemForms", new XVar( "search_search", "below-grid",
"search_reset", "below-grid",
"search_back_list", "below-grid",
"search_cancel", "below-grid",
"search_header", "top",
"integrated_search_field", "grid",
"integrated_search_field1", "grid",
"integrated_search_field2", "grid",
"integrated_search_field4", "grid",
"integrated_search_field5", "grid",
"integrated_search_field6", "grid",
"integrated_search_field7", "grid",
"integrated_search_field3", "grid",
"integrated_search_field8", "grid",
"integrated_search_field9", "grid",
"integrated_search_field10", "grid",
"integrated_search_field11", "grid",
"integrated_search_field12", "grid",
"integrated_search_field13", "grid",
"integrated_search_field14", "grid",
"integrated_search_field15", "grid",
"integrated_search_field16", "grid",
"integrated_search_field17", "grid",
"integrated_search_field18", "grid",
"integrated_search_field19", "grid",
"integrated_search_field20", "grid",
"integrated_search_field21", "grid",
"integrated_search_field22", "grid",
"integrated_search_field23", "grid",
"integrated_search_field24", "grid",
"integrated_search_field25", "grid",
"integrated_search_field26", "grid",
"integrated_search_field27", "grid",
"integrated_search_field28", "grid",
"integrated_search_field29", "grid",
"integrated_search_field30", "grid",
"integrated_search_field31", "grid",
"integrated_search_field32", "grid",
"integrated_search_field33", "grid",
"integrated_search_field34", "grid",
"integrated_search_field35", "grid",
"integrated_search_field36", "grid",
"integrated_search_field37", "grid",
"integrated_search_field38", "grid",
"integrated_search_field39", "grid",
"integrated_search_field40", "grid",
"integrated_search_field41", "grid",
"integrated_search_field42", "grid",
"integrated_search_field43", "grid",
"integrated_search_field44", "grid",
"integrated_search_field45", "grid",
"integrated_search_field46", "grid",
"integrated_search_field47", "grid",
"integrated_search_field48", "grid",
"integrated_search_field49", "grid",
"integrated_search_field50", "grid",
"integrated_search_field51", "grid",
"integrated_search_field52", "grid",
"integrated_search_field53", "grid",
"integrated_search_field54", "grid",
"integrated_search_field55", "grid",
"integrated_search_field56", "grid",
"integrated_search_field57", "grid",
"integrated_search_field58", "grid",
"integrated_search_field59", "grid",
"integrated_search_field61", "grid",
"integrated_search_field62", "grid",
"integrated_search_field63", "grid",
"integrated_search_field60", "grid",
"integrated_search_field64", "grid",
"integrated_search_field65", "grid",
"integrated_search_field66", "grid",
"integrated_search_field67", "grid",
"integrated_search_field68", "grid",
"integrated_search_field69", "grid",
"integrated_search_field70", "grid",
"integrated_search_field71", "grid",
"integrated_search_field72", "grid",
"integrated_search_field73", "grid",
"integrated_search_field74", "grid",
"integrated_search_field75", "grid",
"integrated_search_field76", "grid",
"integrated_search_field77", "grid",
"integrated_search_field78", "grid",
"integrated_search_field79", "grid",
"integrated_search_field80", "grid",
"integrated_search_field81", "grid",
"integrated_search_field82", "grid",
"integrated_search_field83", "grid",
"integrated_search_field84", "grid",
"integrated_search_field85", "grid",
"integrated_search_field86", "grid",
"integrated_search_field87", "grid",
"integrated_search_field88", "grid",
"integrated_search_field89", "grid",
"integrated_search_field90", "grid",
"integrated_search_field91", "grid",
"integrated_search_field92", "grid",
"integrated_search_field93", "grid",
"integrated_search_field94", "grid",
"integrated_search_field95", "grid",
"integrated_search_field96", "grid",
"integrated_search_field97", "grid",
"integrated_search_field98", "grid",
"integrated_search_field99", "grid",
"integrated_search_field100", "grid" ),
"itemLocations", new XVar( "integrated_search_field", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field1", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field2", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field4", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field5", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field6", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field7", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field3", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field8", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field9", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field10", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field11", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field12", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field13", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field14", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field15", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field16", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field17", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field18", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field19", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field20", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field21", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field22", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field23", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field24", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field25", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field26", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field27", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field28", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field29", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field30", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field31", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field32", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field33", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field34", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field35", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field36", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field37", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field38", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field39", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field40", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field41", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field42", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field43", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field44", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field45", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field46", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field47", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field48", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field49", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field50", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field51", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field52", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field53", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field54", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field55", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field56", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field57", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field58", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field59", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field61", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field62", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field63", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field60", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field64", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field65", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field66", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field67", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field68", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field69", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field70", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field71", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field72", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field73", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field74", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field75", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field76", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field77", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field78", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field79", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field80", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field81", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field82", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field83", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field84", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field85", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field86", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field87", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field88", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field89", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field90", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field91", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field92", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field93", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field94", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field95", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field96", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field97", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field98", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field99", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field100", new XVar( "location", "grid",
"cellId", "c3" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "search_header", new XVar( 0, "search_header" ),
"search_reset", new XVar( 0, "search_reset" ),
"search_back_list", new XVar( 0, "search_back_list" ),
"search_search", new XVar( 0, "search_search" ),
"search_cancel", new XVar( 0, "search_cancel" ),
"integrated_search_field", new XVar( 0, "integrated_search_field",
1, "integrated_search_field1",
2, "integrated_search_field2",
3, "integrated_search_field3",
4, "integrated_search_field4",
5, "integrated_search_field5",
6, "integrated_search_field6",
7, "integrated_search_field7",
8, "integrated_search_field8",
9, "integrated_search_field9",
10, "integrated_search_field10",
11, "integrated_search_field11",
12, "integrated_search_field12",
13, "integrated_search_field13",
14, "integrated_search_field14",
15, "integrated_search_field15",
16, "integrated_search_field16",
17, "integrated_search_field17",
18, "integrated_search_field18",
19, "integrated_search_field19",
20, "integrated_search_field20",
21, "integrated_search_field21",
22, "integrated_search_field22",
23, "integrated_search_field23",
24, "integrated_search_field24",
25, "integrated_search_field25",
26, "integrated_search_field26",
27, "integrated_search_field27",
28, "integrated_search_field28",
29, "integrated_search_field29",
30, "integrated_search_field30",
31, "integrated_search_field31",
32, "integrated_search_field32",
33, "integrated_search_field33",
34, "integrated_search_field34",
35, "integrated_search_field35",
36, "integrated_search_field36",
37, "integrated_search_field37",
38, "integrated_search_field38",
39, "integrated_search_field39",
40, "integrated_search_field40",
41, "integrated_search_field41",
42, "integrated_search_field42",
43, "integrated_search_field43",
44, "integrated_search_field44",
45, "integrated_search_field45",
46, "integrated_search_field46",
47, "integrated_search_field47",
48, "integrated_search_field48",
49, "integrated_search_field49",
50, "integrated_search_field50",
51, "integrated_search_field51",
52, "integrated_search_field52",
53, "integrated_search_field53",
54, "integrated_search_field54",
55, "integrated_search_field55",
56, "integrated_search_field56",
57, "integrated_search_field57",
58, "integrated_search_field58",
59, "integrated_search_field59",
60, "integrated_search_field60",
61, "integrated_search_field61",
62, "integrated_search_field62",
63, "integrated_search_field63",
64, "integrated_search_field64",
65, "integrated_search_field65",
66, "integrated_search_field66",
67, "integrated_search_field67",
68, "integrated_search_field68",
69, "integrated_search_field69",
70, "integrated_search_field70",
71, "integrated_search_field71",
72, "integrated_search_field72",
73, "integrated_search_field73",
74, "integrated_search_field74",
75, "integrated_search_field75",
76, "integrated_search_field76",
77, "integrated_search_field77",
78, "integrated_search_field78",
79, "integrated_search_field79",
80, "integrated_search_field80",
81, "integrated_search_field81",
82, "integrated_search_field82",
83, "integrated_search_field83",
84, "integrated_search_field84",
85, "integrated_search_field85",
86, "integrated_search_field86",
87, "integrated_search_field87",
88, "integrated_search_field88",
89, "integrated_search_field89",
90, "integrated_search_field90",
91, "integrated_search_field91",
92, "integrated_search_field92",
93, "integrated_search_field93",
94, "integrated_search_field94",
95, "integrated_search_field95",
96, "integrated_search_field96",
97, "integrated_search_field97",
98, "integrated_search_field98",
99, "integrated_search_field99",
100, "integrated_search_field100" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_search_field",
1, "integrated_search_field1",
2, "integrated_search_field2",
3, "integrated_search_field4",
4, "integrated_search_field5",
5, "integrated_search_field6",
6, "integrated_search_field7",
7, "integrated_search_field3",
8, "integrated_search_field8",
9, "integrated_search_field9",
10, "integrated_search_field10",
11, "integrated_search_field11",
12, "integrated_search_field12",
13, "integrated_search_field13",
14, "integrated_search_field14",
15, "integrated_search_field15",
16, "integrated_search_field16",
17, "integrated_search_field17",
18, "integrated_search_field18",
19, "integrated_search_field19",
20, "integrated_search_field20",
21, "integrated_search_field21",
22, "integrated_search_field22",
23, "integrated_search_field23",
24, "integrated_search_field24",
25, "integrated_search_field25",
26, "integrated_search_field26",
27, "integrated_search_field27",
28, "integrated_search_field28",
29, "integrated_search_field29",
30, "integrated_search_field30",
31, "integrated_search_field31",
32, "integrated_search_field32",
33, "integrated_search_field33",
34, "integrated_search_field34",
35, "integrated_search_field35",
36, "integrated_search_field36",
37, "integrated_search_field37",
38, "integrated_search_field38",
39, "integrated_search_field39",
40, "integrated_search_field40",
41, "integrated_search_field41",
42, "integrated_search_field42",
43, "integrated_search_field43",
44, "integrated_search_field44",
45, "integrated_search_field45",
46, "integrated_search_field46",
47, "integrated_search_field47",
48, "integrated_search_field48",
49, "integrated_search_field49",
50, "integrated_search_field50",
51, "integrated_search_field51",
52, "integrated_search_field52",
53, "integrated_search_field53",
54, "integrated_search_field54",
55, "integrated_search_field55",
56, "integrated_search_field56",
57, "integrated_search_field57",
58, "integrated_search_field58",
59, "integrated_search_field59",
60, "integrated_search_field61",
61, "integrated_search_field62",
62, "integrated_search_field63",
63, "integrated_search_field60",
64, "integrated_search_field64",
65, "integrated_search_field65",
66, "integrated_search_field66",
67, "integrated_search_field67",
68, "integrated_search_field68",
69, "integrated_search_field69",
70, "integrated_search_field70",
71, "integrated_search_field71",
72, "integrated_search_field72",
73, "integrated_search_field73",
74, "integrated_search_field74",
75, "integrated_search_field75",
76, "integrated_search_field76",
77, "integrated_search_field77",
78, "integrated_search_field78",
79, "integrated_search_field79",
80, "integrated_search_field80",
81, "integrated_search_field81",
82, "integrated_search_field82",
83, "integrated_search_field83",
84, "integrated_search_field84",
85, "integrated_search_field85",
86, "integrated_search_field86",
87, "integrated_search_field87",
88, "integrated_search_field88",
89, "integrated_search_field89",
90, "integrated_search_field90",
91, "integrated_search_field91",
92, "integrated_search_field92",
93, "integrated_search_field93",
94, "integrated_search_field94",
95, "integrated_search_field95",
96, "integrated_search_field96",
97, "integrated_search_field97",
98, "integrated_search_field98",
99, "integrated_search_field99",
100, "integrated_search_field100" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "search",
"breadcrumb", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "search",
"type", "search",
"layoutId", "nomenu",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "search-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1",
"colspan", 2 ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "search-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "search_search",
1, "search_reset",
2, "search_back_list",
3, "search_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "search-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "search_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-search",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ) ),
"section", "" ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_search_field",
1, "integrated_search_field1",
2, "integrated_search_field2",
3, "integrated_search_field4",
4, "integrated_search_field5",
5, "integrated_search_field6",
6, "integrated_search_field7",
7, "integrated_search_field3",
8, "integrated_search_field8",
9, "integrated_search_field9",
10, "integrated_search_field10",
11, "integrated_search_field11",
12, "integrated_search_field12",
13, "integrated_search_field13",
14, "integrated_search_field14",
15, "integrated_search_field15",
16, "integrated_search_field16",
17, "integrated_search_field17",
18, "integrated_search_field18",
19, "integrated_search_field19",
20, "integrated_search_field20",
21, "integrated_search_field21",
22, "integrated_search_field22",
23, "integrated_search_field23",
24, "integrated_search_field24",
25, "integrated_search_field25",
26, "integrated_search_field26",
27, "integrated_search_field27",
28, "integrated_search_field28",
29, "integrated_search_field29",
30, "integrated_search_field30",
31, "integrated_search_field31",
32, "integrated_search_field32",
33, "integrated_search_field33",
34, "integrated_search_field34",
35, "integrated_search_field35",
36, "integrated_search_field36",
37, "integrated_search_field37",
38, "integrated_search_field38",
39, "integrated_search_field39",
40, "integrated_search_field40",
41, "integrated_search_field41",
42, "integrated_search_field42",
43, "integrated_search_field43",
44, "integrated_search_field44",
45, "integrated_search_field45",
46, "integrated_search_field46",
47, "integrated_search_field47",
48, "integrated_search_field48",
49, "integrated_search_field49",
50, "integrated_search_field50",
51, "integrated_search_field51",
52, "integrated_search_field52",
53, "integrated_search_field53",
54, "integrated_search_field54",
55, "integrated_search_field55",
56, "integrated_search_field56",
57, "integrated_search_field57",
58, "integrated_search_field58",
59, "integrated_search_field59",
60, "integrated_search_field61",
61, "integrated_search_field62",
62, "integrated_search_field63",
63, "integrated_search_field60",
64, "integrated_search_field64",
65, "integrated_search_field65",
66, "integrated_search_field66",
67, "integrated_search_field67",
68, "integrated_search_field68",
69, "integrated_search_field69",
70, "integrated_search_field70",
71, "integrated_search_field71",
72, "integrated_search_field72",
73, "integrated_search_field73",
74, "integrated_search_field74",
75, "integrated_search_field75",
76, "integrated_search_field76",
77, "integrated_search_field77",
78, "integrated_search_field78",
79, "integrated_search_field79",
80, "integrated_search_field80",
81, "integrated_search_field81",
82, "integrated_search_field82",
83, "integrated_search_field83",
84, "integrated_search_field84",
85, "integrated_search_field85",
86, "integrated_search_field86",
87, "integrated_search_field87",
88, "integrated_search_field88",
89, "integrated_search_field89",
90, "integrated_search_field90",
91, "integrated_search_field91",
92, "integrated_search_field92",
93, "integrated_search_field93",
94, "integrated_search_field94",
95, "integrated_search_field95",
96, "integrated_search_field96",
97, "integrated_search_field97",
98, "integrated_search_field98",
99, "integrated_search_field99",
100, "integrated_search_field100" ) ) ),
"deferredItems", XVar.Array(),
"separateLabels", false ) ),
"items", new XVar( "search_header", new XVar( "type", "search_header" ),
"search_reset", new XVar( "type", "search_reset" ),
"search_back_list", new XVar( "type", "search_back_list" ),
"search_search", new XVar( "type", "search_search" ),
"search_cancel", new XVar( "type", "search_cancel" ),
"integrated_search_field", new XVar( "field", "ID",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field1", new XVar( "field", "referenceID",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field2", new XVar( "field", "applicationNo",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field3", new XVar( "field", "companyNameA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field4", new XVar( "field", "userCreate",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field5", new XVar( "field", "userUpdate",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field6", new XVar( "field", "dateCreated",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field7", new XVar( "field", "dateUpdated",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field8", new XVar( "field", "companyNameB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field9", new XVar( "field", "siteNameA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field10", new XVar( "field", "siteNameB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field11", new XVar( "field", "coordinateA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field12", new XVar( "field", "coordinateB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field13", new XVar( "field", "elevationA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field14", new XVar( "field", "elevationB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field15", new XVar( "field", "makeTypeModelA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field16", new XVar( "field", "gainA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field17", new XVar( "field", "diameterA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field18", new XVar( "field", "beamwidthA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field19", new XVar( "field", "polarizationA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field20", new XVar( "field", "azimuthA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field21", new XVar( "field", "elevAngleA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field22", new XVar( "field", "heightAGLA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field23", new XVar( "field", "feederLengthA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field24", new XVar( "field", "makeTypeModelB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field25", new XVar( "field", "gainB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field26", new XVar( "field", "diameterB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field27", new XVar( "field", "beamwidthB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field28", new XVar( "field", "polarizationB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field29", new XVar( "field", "azimuthB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field30", new XVar( "field", "elevAngleB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field31", new XVar( "field", "heightAGLB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field32", new XVar( "field", "feederLengthB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field33", new XVar( "field", "longtitudeA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field34", new XVar( "field", "longtitudeB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field35", new XVar( "field", "latitudeA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field36", new XVar( "field", "latitudeB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field37", new XVar( "field", "callSignA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field38", new XVar( "field", "callSignB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field39", new XVar( "field", "applicationType",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field40", new XVar( "field", "unit_a",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field41", new XVar( "field", "street_a",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field42", new XVar( "field", "barangay_a",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field43", new XVar( "field", "city_a",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field44", new XVar( "field", "province_a",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field45", new XVar( "field", "zipcode_a",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field46", new XVar( "field", "unit_b",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field47", new XVar( "field", "street_b",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field48", new XVar( "field", "barangay_b",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field49", new XVar( "field", "city_b",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field50", new XVar( "field", "province_b",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field51", new XVar( "field", "zipcode_b",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field52", new XVar( "field", "map",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field53", new XVar( "field", "stage",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field54", new XVar( "field", "stageStatus",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field55", new XVar( "field", "externalReferenceNo",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field56", new XVar( "field", "classStationService",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field57", new XVar( "field", "modeOfOperation",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field58", new XVar( "field", "Remarks",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field59", new XVar( "field", "dateOfApprovedBrief",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field60", new XVar( "field", "natureOfService",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field61", new XVar( "field", "recommendations",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field62", new XVar( "field", "applicationCategory",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field63", new XVar( "field", "address",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field64", new XVar( "field", "rt",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field65", new XVar( "field", "fx",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field66", new XVar( "field", "fb",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field67", new XVar( "field", "ml",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field68", new XVar( "field", "p",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field69", new XVar( "field", "bc",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field70", new XVar( "field", "fc",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field71", new XVar( "field", "fa",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field72", new XVar( "field", "ma",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field73", new XVar( "field", "tc",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field74", new XVar( "field", "other_ClassSS",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field75", new XVar( "field", "naturoOfRequest",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field76", new XVar( "field", "serviceArea",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field77", new XVar( "field", "caseNo",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field78", new XVar( "field", "frequencyRange",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field79", new XVar( "field", "directivity",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field80", new XVar( "field", "encoder",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field81", new XVar( "field", "evaluator",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field82", new XVar( "field", "position",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field83", new XVar( "field", "longDegA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field84", new XVar( "field", "longMinA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field85", new XVar( "field", "longSecA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field86", new XVar( "field", "longDegB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field87", new XVar( "field", "longMinB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field88", new XVar( "field", "longSecB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field89", new XVar( "field", "latDegA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field90", new XVar( "field", "latMinA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field91", new XVar( "field", "latSecA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field92", new XVar( "field", "latDegB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field93", new XVar( "field", "latMinB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field94", new XVar( "field", "latSecB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field95", new XVar( "field", "cardinalDirectionsLatA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field96", new XVar( "field", "cardinalDirectionsLongB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field97", new XVar( "field", "cardinalDirectionLongA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field98", new XVar( "field", "cardinalDirectionLatB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field99", new XVar( "field", "regionA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field100", new XVar( "field", "regionB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}