
		// dbo.rspdHeader
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_dbo_rspdheader_edit
			{
				static public XVar options()
				{
					return new XVar( "details", new XVar( "dbo.radioEquipment", new XVar( "displayPreview", 1,
"previewPageId", "list" ) ),
"captcha", new XVar( "captcha", false ),
"fields", new XVar( "gridFields", new XVar( 0, "position",
1, "frequencyRange",
2, "elevationB",
3, "rt",
4, "caseNo",
5, "callSignB",
6, "callSignA",
7, "latitudeB",
8, "longtitudeB",
9, "elevationA",
10, "latitudeA",
11, "longtitudeA",
12, "azimuthB",
13, "ml",
14, "fc",
15, "dateOfApprovedBrief",
16, "recommendations",
17, "Remarks",
18, "directivity",
19, "serviceArea",
20, "evaluator",
21, "tc",
22, "fx",
23, "p",
24, "naturoOfRequest",
25, "siteNameA",
26, "gainB",
27, "siteIDA",
28, "province_a",
29, "makeTypeModelA",
30, "natureOfService",
31, "modeOfOperation",
32, "city_a",
33, "zipcode_a",
34, "beamwidthA",
35, "barangay_a",
36, "polarizationA",
37, "externalReferenceNo",
38, "companyNameA",
39, "applicationCategory",
40, "applicationType",
41, "referenceID",
42, "street_a",
43, "gainA",
44, "diameterA",
45, "unit_a",
46, "makeTypeModelB",
47, "diameterB",
48, "other_ClassSS",
49, "ma",
50, "bc",
51, "fb",
52, "feederLengthA",
53, "fa",
54, "feederLengthB",
55, "heightAGLA",
56, "zipcode_b",
57, "heightAGLB",
58, "elevAngleA",
59, "polarizationB",
60, "elevAngleB",
61, "azimuthA",
62, "beamwidthB",
63, "siteNameB",
64, "siteIDB",
65, "province_b",
66, "city_b",
67, "barangay_b",
68, "street_b",
69, "unit_b",
70, "longDegA",
71, "longMinA",
72, "longSecA",
73, "longDegB",
74, "longMinB",
75, "longSecB",
76, "coordinateA",
77, "coordinateB",
78, "latDegA",
79, "latMinA",
80, "latSecA",
81, "latDegB",
82, "latMinB",
83, "latSecB",
84, "cardinalDirectionsLatA",
85, "cardinalDirectionsLongB",
86, "cardinalDirectionLongA",
87, "cardinalDirectionLatB",
88, "regionA",
89, "regionB" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"updateOnEditFields", XVar.Array(),
"fieldItems", new XVar( "position", new XVar( 0, "integrated_edit_field70" ),
"frequencyRange", new XVar( 0, "integrated_edit_field66" ),
"elevationB", new XVar( 0, "integrated_edit_field6" ),
"rt", new XVar( 0, "integrated_edit_field45" ),
"caseNo", new XVar( 0, "integrated_edit_field65" ),
"callSignB", new XVar( 0, "integrated_edit_field4" ),
"callSignA", new XVar( 0, "integrated_edit_field1" ),
"latitudeB", new XVar( 0, "integrated_edit_field28" ),
"longtitudeB", new XVar( 0, "integrated_edit_field26" ),
"elevationA", new XVar( 0, "integrated_edit_field5" ),
"latitudeA", new XVar( 0, "integrated_edit_field27" ),
"longtitudeA", new XVar( 0, "integrated_edit_field25" ),
"azimuthB", new XVar( 0, "integrated_edit_field21" ),
"ml", new XVar( 0, "integrated_edit_field54" ),
"fc", new XVar( 0, "integrated_edit_field57" ),
"dateOfApprovedBrief", new XVar( 0, "integrated_edit_field48" ),
"recommendations", new XVar( 0, "integrated_edit_field50" ),
"Remarks", new XVar( 0, "integrated_edit_field47" ),
"directivity", new XVar( 0, "integrated_edit_field67" ),
"serviceArea", new XVar( 0, "integrated_edit_field64" ),
"evaluator", new XVar( 0, "integrated_edit_field69" ),
"tc", new XVar( 0, "integrated_edit_field60" ),
"fx", new XVar( 0, "integrated_edit_field52" ),
"p", new XVar( 0, "integrated_edit_field55" ),
"naturoOfRequest", new XVar( 0, "integrated_edit_field63" ),
"siteNameA", new XVar( 0, "integrated_edit_field2" ),
"gainB", new XVar( 0, "integrated_edit_field17" ),
"siteIDA", new XVar( 0, "integrated_edit_field30" ),
"province_a", new XVar( 0, "integrated_edit_field36" ),
"makeTypeModelA", new XVar( 0, "integrated_edit_field7" ),
"natureOfService", new XVar( 0, "integrated_edit_field49" ),
"modeOfOperation", new XVar( 0, "integrated_edit_field46" ),
"city_a", new XVar( 0, "integrated_edit_field35" ),
"zipcode_a", new XVar( 0, "integrated_edit_field37" ),
"beamwidthA", new XVar( 0, "integrated_edit_field10" ),
"barangay_a", new XVar( 0, "integrated_edit_field34" ),
"polarizationA", new XVar( 0, "integrated_edit_field11" ),
"externalReferenceNo", new XVar( 0, "integrated_edit_field44" ),
"companyNameA", new XVar( 0, "integrated_edit_field" ),
"applicationCategory", new XVar( 0, "integrated_edit_field51" ),
"applicationType", new XVar( 0, "integrated_edit_field29" ),
"referenceID", new XVar( 0, "integrated_edit_field62" ),
"street_a", new XVar( 0, "integrated_edit_field33" ),
"gainA", new XVar( 0, "integrated_edit_field8" ),
"diameterA", new XVar( 0, "integrated_edit_field9" ),
"unit_a", new XVar( 0, "integrated_edit_field32" ),
"makeTypeModelB", new XVar( 0, "integrated_edit_field16" ),
"diameterB", new XVar( 0, "integrated_edit_field18" ),
"other_ClassSS", new XVar( 0, "integrated_edit_field61" ),
"ma", new XVar( 0, "integrated_edit_field59" ),
"bc", new XVar( 0, "integrated_edit_field56" ),
"fb", new XVar( 0, "integrated_edit_field53" ),
"feederLengthA", new XVar( 0, "integrated_edit_field15" ),
"fa", new XVar( 0, "integrated_edit_field58" ),
"feederLengthB", new XVar( 0, "integrated_edit_field24" ),
"heightAGLA", new XVar( 0, "integrated_edit_field14" ),
"zipcode_b", new XVar( 0, "integrated_edit_field43" ),
"heightAGLB", new XVar( 0, "integrated_edit_field23" ),
"elevAngleA", new XVar( 0, "integrated_edit_field13" ),
"polarizationB", new XVar( 0, "integrated_edit_field20" ),
"elevAngleB", new XVar( 0, "integrated_edit_field22" ),
"azimuthA", new XVar( 0, "integrated_edit_field12" ),
"beamwidthB", new XVar( 0, "integrated_edit_field19" ),
"siteNameB", new XVar( 0, "integrated_edit_field3" ),
"siteIDB", new XVar( 0, "integrated_edit_field31" ),
"province_b", new XVar( 0, "integrated_edit_field42" ),
"city_b", new XVar( 0, "integrated_edit_field41" ),
"barangay_b", new XVar( 0, "integrated_edit_field40" ),
"street_b", new XVar( 0, "integrated_edit_field39" ),
"unit_b", new XVar( 0, "integrated_edit_field38" ),
"longDegA", new XVar( 0, "integrated_edit_field71" ),
"longMinA", new XVar( 0, "integrated_edit_field72" ),
"longSecA", new XVar( 0, "integrated_edit_field73" ),
"longDegB", new XVar( 0, "integrated_edit_field74" ),
"longMinB", new XVar( 0, "integrated_edit_field75" ),
"longSecB", new XVar( 0, "integrated_edit_field76" ),
"coordinateA", new XVar( 0, "integrated_edit_field77" ),
"coordinateB", new XVar( 0, "integrated_edit_field78" ),
"latDegA", new XVar( 0, "integrated_edit_field79" ),
"latMinA", new XVar( 0, "integrated_edit_field80" ),
"latSecA", new XVar( 0, "integrated_edit_field81" ),
"latDegB", new XVar( 0, "integrated_edit_field82" ),
"latMinB", new XVar( 0, "integrated_edit_field83" ),
"latSecB", new XVar( 0, "integrated_edit_field84" ),
"cardinalDirectionsLatA", new XVar( 0, "integrated_edit_field85" ),
"cardinalDirectionsLongB", new XVar( 0, "integrated_edit_field86" ),
"cardinalDirectionLongA", new XVar( 0, "integrated_edit_field87" ),
"cardinalDirectionLatB", new XVar( 0, "integrated_edit_field88" ),
"regionA", new XVar( 0, "integrated_edit_field89" ),
"regionB", new XVar( 0, "integrated_edit_field90" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", true,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "edit_message" ),
"below-grid", new XVar( 0, "edit_save",
1, "edit_back_list",
2, "edit_close",
3, "hamburger" ),
"top", new XVar( 0, "edit_header" ),
"grid", new XVar( 0, "integrated_edit_field45",
1, "integrated_edit_field54",
2, "integrated_edit_field57",
3, "section5",
4, "integrated_edit_field67",
5, "integrated_edit_field64",
6, "integrated_edit_field69",
7, "integrated_edit_field71",
8, "integrated_edit_field73",
9, "integrated_edit_field75",
10, "integrated_edit_field77",
11, "integrated_edit_field79",
12, "integrated_edit_field81",
13, "integrated_edit_field83",
14, "integrated_edit_field85",
15, "integrated_edit_field87",
16, "integrated_edit_field89",
17, "integrated_edit_field60",
18, "integrated_edit_field52",
19, "integrated_edit_field55",
20, "section2",
21, "section4",
22, "integrated_edit_field58",
23, "integrated_edit_field53",
24, "integrated_edit_field56",
25, "integrated_edit_field59",
26, "integrated_edit_field61",
27, "integrated_edit_field62",
28, "integrated_edit_field29",
29, "integrated_edit_field51",
30, "integrated_edit_field",
31, "integrated_edit_field44",
32, "integrated_edit_field46",
33, "integrated_edit_field49",
34, "text",
35, "section3",
36, "integrated_edit_field65",
37, "integrated_edit_field66",
38, "integrated_edit_field70",
39, "integrated_edit_field72",
40, "integrated_edit_field74",
41, "integrated_edit_field78",
42, "integrated_edit_field76",
43, "integrated_edit_field80",
44, "integrated_edit_field82",
45, "integrated_edit_field84",
46, "integrated_edit_field86",
47, "integrated_edit_field88",
48, "integrated_edit_field90" ),
"section3", new XVar( 0, "integrated_edit_field25",
1, "integrated_edit_field27",
2, "integrated_edit_field5",
3, "integrated_edit_field26",
4, "integrated_edit_field28",
5, "integrated_edit_field6",
6, "details_preview4",
7, "integrated_edit_field1",
8, "integrated_edit_field4" ),
"section2", new XVar( 0, "integrated_edit_field2",
1, "integrated_edit_field30",
2, "integrated_edit_field36",
3, "integrated_edit_field35",
4, "integrated_edit_field37",
5, "integrated_edit_field34",
6, "integrated_edit_field33",
7, "integrated_edit_field32",
8, "integrated_edit_field3",
9, "integrated_edit_field31",
10, "integrated_edit_field42",
11, "integrated_edit_field41",
12, "integrated_edit_field43",
13, "integrated_edit_field40",
14, "integrated_edit_field39",
15, "integrated_edit_field38" ),
"section4", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field8",
2, "integrated_edit_field9",
3, "integrated_edit_field10",
4, "integrated_edit_field11",
5, "integrated_edit_field12",
6, "integrated_edit_field13",
7, "integrated_edit_field14",
8, "integrated_edit_field15",
9, "integrated_edit_field16",
10, "integrated_edit_field17",
11, "integrated_edit_field18",
12, "integrated_edit_field19",
13, "integrated_edit_field20",
14, "integrated_edit_field21",
15, "integrated_edit_field22",
16, "integrated_edit_field23",
17, "integrated_edit_field24" ),
"section5", new XVar( 0, "integrated_edit_field63",
1, "integrated_edit_field48",
2, "integrated_edit_field50",
3, "integrated_edit_field47" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "message_block" ) ),
"itemForms", new XVar( "edit_message", "above-grid",
"edit_save", "below-grid",
"edit_back_list", "below-grid",
"edit_close", "below-grid",
"hamburger", "below-grid",
"edit_header", "top",
"integrated_edit_field45", "grid",
"integrated_edit_field54", "grid",
"integrated_edit_field57", "grid",
"section5", "grid",
"integrated_edit_field67", "grid",
"integrated_edit_field64", "grid",
"integrated_edit_field69", "grid",
"integrated_edit_field71", "grid",
"integrated_edit_field73", "grid",
"integrated_edit_field75", "grid",
"integrated_edit_field77", "grid",
"integrated_edit_field79", "grid",
"integrated_edit_field81", "grid",
"integrated_edit_field83", "grid",
"integrated_edit_field85", "grid",
"integrated_edit_field87", "grid",
"integrated_edit_field89", "grid",
"integrated_edit_field60", "grid",
"integrated_edit_field52", "grid",
"integrated_edit_field55", "grid",
"section2", "grid",
"section4", "grid",
"integrated_edit_field58", "grid",
"integrated_edit_field53", "grid",
"integrated_edit_field56", "grid",
"integrated_edit_field59", "grid",
"integrated_edit_field61", "grid",
"integrated_edit_field62", "grid",
"integrated_edit_field29", "grid",
"integrated_edit_field51", "grid",
"integrated_edit_field", "grid",
"integrated_edit_field44", "grid",
"integrated_edit_field46", "grid",
"integrated_edit_field49", "grid",
"text", "grid",
"section3", "grid",
"integrated_edit_field65", "grid",
"integrated_edit_field66", "grid",
"integrated_edit_field70", "grid",
"integrated_edit_field72", "grid",
"integrated_edit_field74", "grid",
"integrated_edit_field78", "grid",
"integrated_edit_field76", "grid",
"integrated_edit_field80", "grid",
"integrated_edit_field82", "grid",
"integrated_edit_field84", "grid",
"integrated_edit_field86", "grid",
"integrated_edit_field88", "grid",
"integrated_edit_field90", "grid",
"integrated_edit_field25", "section3",
"integrated_edit_field27", "section3",
"integrated_edit_field5", "section3",
"integrated_edit_field26", "section3",
"integrated_edit_field28", "section3",
"integrated_edit_field6", "section3",
"details_preview4", "section3",
"integrated_edit_field1", "section3",
"integrated_edit_field4", "section3",
"integrated_edit_field2", "section2",
"integrated_edit_field30", "section2",
"integrated_edit_field36", "section2",
"integrated_edit_field35", "section2",
"integrated_edit_field37", "section2",
"integrated_edit_field34", "section2",
"integrated_edit_field33", "section2",
"integrated_edit_field32", "section2",
"integrated_edit_field3", "section2",
"integrated_edit_field31", "section2",
"integrated_edit_field42", "section2",
"integrated_edit_field41", "section2",
"integrated_edit_field43", "section2",
"integrated_edit_field40", "section2",
"integrated_edit_field39", "section2",
"integrated_edit_field38", "section2",
"integrated_edit_field7", "section4",
"integrated_edit_field8", "section4",
"integrated_edit_field9", "section4",
"integrated_edit_field10", "section4",
"integrated_edit_field11", "section4",
"integrated_edit_field12", "section4",
"integrated_edit_field13", "section4",
"integrated_edit_field14", "section4",
"integrated_edit_field15", "section4",
"integrated_edit_field16", "section4",
"integrated_edit_field17", "section4",
"integrated_edit_field18", "section4",
"integrated_edit_field19", "section4",
"integrated_edit_field20", "section4",
"integrated_edit_field21", "section4",
"integrated_edit_field22", "section4",
"integrated_edit_field23", "section4",
"integrated_edit_field24", "section4",
"integrated_edit_field63", "section5",
"integrated_edit_field48", "section5",
"integrated_edit_field50", "section5",
"integrated_edit_field47", "section5" ),
"itemLocations", new XVar( "integrated_edit_field45", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field54", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field57", new XVar( "location", "grid",
"cellId", "c3" ),
"section5", new XVar( "location", "grid",
"cellId", "c" ),
"integrated_edit_field67", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field64", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field69", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field71", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field73", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field75", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field77", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field79", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field81", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field83", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field85", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field87", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field89", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field60", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field52", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field55", new XVar( "location", "grid",
"cellId", "c12" ),
"section2", new XVar( "location", "grid",
"cellId", "c10" ),
"section4", new XVar( "location", "grid",
"cellId", "c28" ),
"integrated_edit_field58", new XVar( "location", "grid",
"cellId", "c4" ),
"integrated_edit_field53", new XVar( "location", "grid",
"cellId", "c4" ),
"integrated_edit_field56", new XVar( "location", "grid",
"cellId", "c4" ),
"integrated_edit_field59", new XVar( "location", "grid",
"cellId", "c7" ),
"integrated_edit_field61", new XVar( "location", "grid",
"cellId", "c7" ),
"integrated_edit_field62", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field29", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field51", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field44", new XVar( "location", "grid",
"cellId", "c18" ),
"integrated_edit_field46", new XVar( "location", "grid",
"cellId", "c18" ),
"integrated_edit_field49", new XVar( "location", "grid",
"cellId", "c18" ),
"text", new XVar( "location", "grid",
"cellId", "c8" ),
"section3", new XVar( "location", "grid",
"cellId", "c19" ),
"integrated_edit_field65", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field66", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field70", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field72", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field74", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field78", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field76", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field80", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field82", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field84", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field86", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field88", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field90", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field25", new XVar( "location", "section3",
"cellId", "c1" ),
"integrated_edit_field27", new XVar( "location", "section3",
"cellId", "c1" ),
"integrated_edit_field5", new XVar( "location", "section3",
"cellId", "c1" ),
"integrated_edit_field26", new XVar( "location", "section3",
"cellId", "c" ),
"integrated_edit_field28", new XVar( "location", "section3",
"cellId", "c" ),
"integrated_edit_field6", new XVar( "location", "section3",
"cellId", "c" ),
"details_preview4", new XVar( "location", "section3",
"cellId", "c3" ),
"integrated_edit_field1", new XVar( "location", "section3",
"cellId", "c4" ),
"integrated_edit_field4", new XVar( "location", "section3",
"cellId", "c5" ),
"integrated_edit_field2", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field30", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field36", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field35", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field37", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field34", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field33", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field32", new XVar( "location", "section2",
"cellId", "c1" ),
"integrated_edit_field3", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field31", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field42", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field41", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field43", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field40", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field39", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field38", new XVar( "location", "section2",
"cellId", "c" ),
"integrated_edit_field7", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field8", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field9", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field10", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field11", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field12", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field13", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field14", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field15", new XVar( "location", "section4",
"cellId", "c1" ),
"integrated_edit_field16", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field17", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field18", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field19", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field20", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field21", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field22", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field23", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field24", new XVar( "location", "section4",
"cellId", "c" ),
"integrated_edit_field63", new XVar( "location", "section5",
"cellId", "c1" ),
"integrated_edit_field48", new XVar( "location", "section5",
"cellId", "c1" ),
"integrated_edit_field50", new XVar( "location", "section5",
"cellId", "c1" ),
"integrated_edit_field47", new XVar( "location", "section5",
"cellId", "c" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "edit_header", new XVar( 0, "edit_header" ),
"hamburger", new XVar( 0, "hamburger" ),
"edit_reset", new XVar( 0, "edit_reset" ),
"edit_message", new XVar( 0, "edit_message" ),
"edit_save", new XVar( 0, "edit_save" ),
"edit_back_list", new XVar( 0, "edit_back_list" ),
"edit_close", new XVar( 0, "edit_close" ),
"edit_view", new XVar( 0, "edit_view" ),
"integrated_edit_field", new XVar( 0, "integrated_edit_field70",
1, "integrated_edit_field66",
2, "integrated_edit_field6",
3, "integrated_edit_field45",
4, "integrated_edit_field65",
5, "integrated_edit_field4",
6, "integrated_edit_field1",
7, "integrated_edit_field28",
8, "integrated_edit_field26",
9, "integrated_edit_field5",
10, "integrated_edit_field27",
11, "integrated_edit_field25",
12, "integrated_edit_field21",
13, "integrated_edit_field54",
14, "integrated_edit_field57",
15, "integrated_edit_field48",
16, "integrated_edit_field50",
17, "integrated_edit_field47",
18, "integrated_edit_field67",
19, "integrated_edit_field64",
20, "integrated_edit_field69",
21, "integrated_edit_field60",
22, "integrated_edit_field52",
23, "integrated_edit_field55",
24, "integrated_edit_field63",
25, "integrated_edit_field2",
26, "integrated_edit_field17",
27, "integrated_edit_field30",
28, "integrated_edit_field36",
29, "integrated_edit_field7",
30, "integrated_edit_field49",
31, "integrated_edit_field46",
32, "integrated_edit_field35",
33, "integrated_edit_field37",
34, "integrated_edit_field10",
35, "integrated_edit_field34",
36, "integrated_edit_field11",
37, "integrated_edit_field44",
38, "integrated_edit_field",
39, "integrated_edit_field51",
40, "integrated_edit_field29",
41, "integrated_edit_field62",
42, "integrated_edit_field33",
43, "integrated_edit_field8",
44, "integrated_edit_field9",
45, "integrated_edit_field32",
46, "integrated_edit_field16",
47, "integrated_edit_field18",
48, "integrated_edit_field61",
49, "integrated_edit_field59",
50, "integrated_edit_field56",
51, "integrated_edit_field53",
52, "integrated_edit_field15",
53, "integrated_edit_field58",
54, "integrated_edit_field24",
55, "integrated_edit_field14",
56, "integrated_edit_field43",
57, "integrated_edit_field23",
58, "integrated_edit_field13",
59, "integrated_edit_field20",
60, "integrated_edit_field22",
61, "integrated_edit_field12",
62, "integrated_edit_field19",
63, "integrated_edit_field3",
64, "integrated_edit_field31",
65, "integrated_edit_field42",
66, "integrated_edit_field41",
67, "integrated_edit_field40",
68, "integrated_edit_field39",
69, "integrated_edit_field38",
70, "integrated_edit_field71",
71, "integrated_edit_field72",
72, "integrated_edit_field73",
73, "integrated_edit_field74",
74, "integrated_edit_field75",
75, "integrated_edit_field76",
76, "integrated_edit_field77",
77, "integrated_edit_field78",
78, "integrated_edit_field79",
79, "integrated_edit_field80",
80, "integrated_edit_field81",
81, "integrated_edit_field82",
82, "integrated_edit_field83",
83, "integrated_edit_field84",
84, "integrated_edit_field85",
85, "integrated_edit_field86",
86, "integrated_edit_field87",
87, "integrated_edit_field88",
88, "integrated_edit_field89",
89, "integrated_edit_field90" ),
"details_preview", new XVar( 0, "details_preview4" ),
"section", new XVar( 0, "section3",
1, "section5",
2, "section2",
3, "section4" ),
"text", new XVar( 0, "text" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c17", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field62",
1, "integrated_edit_field29",
2, "integrated_edit_field51",
3, "integrated_edit_field" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c18", new XVar( "cols", new XVar( 0, 3,
1, 4,
2, 5 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field44",
1, "integrated_edit_field46",
2, "integrated_edit_field49" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c8", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", new XVar( 0, "text" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c11", new XVar( "cols", new XVar( 0, 3,
1, 4,
2, 5 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field45",
1, "integrated_edit_field54",
2, "integrated_edit_field57" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c12", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field60",
1, "integrated_edit_field52",
2, "integrated_edit_field55" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c4", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field58",
1, "integrated_edit_field53",
2, "integrated_edit_field56" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c7", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field59",
1, "integrated_edit_field61" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c33", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c2", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c10", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4,
5, 5 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", new XVar( 0, "section2" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c19", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4,
5, 5 ),
"rows", new XVar( 0, 4 ),
"tags", XVar.Array(),
"items", new XVar( 0, "section3" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c28", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4,
5, 5 ),
"rows", new XVar( 0, 5 ),
"tags", XVar.Array(),
"items", new XVar( 0, "section4" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4,
5, 5 ),
"rows", new XVar( 0, 6 ),
"tags", XVar.Array(),
"items", new XVar( 0, "section5" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c5", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2 ),
"rows", new XVar( 0, 7 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field65",
1, "integrated_edit_field66",
2, "integrated_edit_field70",
3, "integrated_edit_field72",
4, "integrated_edit_field74",
5, "integrated_edit_field78",
6, "integrated_edit_field76",
7, "integrated_edit_field80",
8, "integrated_edit_field82",
9, "integrated_edit_field84",
10, "integrated_edit_field86",
11, "integrated_edit_field88",
12, "integrated_edit_field90" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c6", new XVar( "cols", new XVar( 0, 3,
1, 4,
2, 5 ),
"rows", new XVar( 0, 7 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field67",
1, "integrated_edit_field64",
2, "integrated_edit_field69",
3, "integrated_edit_field71",
4, "integrated_edit_field73",
5, "integrated_edit_field75",
6, "integrated_edit_field77",
7, "integrated_edit_field79",
8, "integrated_edit_field81",
9, "integrated_edit_field83",
10, "integrated_edit_field85",
11, "integrated_edit_field87",
12, "integrated_edit_field89" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 6,
"height", 8 ),
"section3", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field25",
1, "integrated_edit_field27",
2, "integrated_edit_field5" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field26",
1, "integrated_edit_field28",
2, "integrated_edit_field6" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c3", new XVar( "cols", new XVar( 0, 0,
1, 1 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", new XVar( 0, "details_preview4" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c4", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field1" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c5", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field4" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 2,
"height", 3 ),
"section2", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field2",
1, "integrated_edit_field30",
2, "integrated_edit_field36",
3, "integrated_edit_field35",
4, "integrated_edit_field37",
5, "integrated_edit_field34",
6, "integrated_edit_field33",
7, "integrated_edit_field32" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field3",
1, "integrated_edit_field31",
2, "integrated_edit_field42",
3, "integrated_edit_field41",
4, "integrated_edit_field43",
5, "integrated_edit_field40",
6, "integrated_edit_field39",
7, "integrated_edit_field38" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 2,
"height", 1 ),
"section4", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field8",
2, "integrated_edit_field9",
3, "integrated_edit_field10",
4, "integrated_edit_field11",
5, "integrated_edit_field12",
6, "integrated_edit_field13",
7, "integrated_edit_field14",
8, "integrated_edit_field15" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field16",
1, "integrated_edit_field17",
2, "integrated_edit_field18",
3, "integrated_edit_field19",
4, "integrated_edit_field20",
5, "integrated_edit_field21",
6, "integrated_edit_field22",
7, "integrated_edit_field23",
8, "integrated_edit_field24" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 2,
"height", 1 ),
"section5", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field63",
1, "integrated_edit_field48",
2, "integrated_edit_field50" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field47" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 2,
"height", 1 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "edit",
"breadcrumb", false,
"nextPrev", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"edit", new XVar( "updateSelected", false ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "edit",
"type", "edit",
"layoutId", "nomenu",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "edit-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "edit_message" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "edit-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "edit_save",
1, "edit_back_list",
2, "edit_close" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "hamburger" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "edit-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "edit_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c17",
"colspan", 3 ),
1, new XVar( "cell", "c18",
"colspan", 3 ) ) ),
1, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c8",
"colspan", 3 ),
1, new XVar( "cell", "c11",
"colspan", 3 ) ) ),
2, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3",
"rowspan", 1 ),
1, new XVar( "cell", "c12" ),
2, new XVar( "cell", "c4",
"colspan", 1 ),
3, new XVar( "cell", "c7",
"rowspan", 1 ),
4, new XVar( "cell", "c33",
"rowspan", 1 ),
5, new XVar( "cell", "c2",
"colspan", 1 ) ),
"section", "" ),
3, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c10",
"colspan", 6 ) ) ),
4, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c19",
"colspan", 6,
"rowspan", 1 ) ) ),
5, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c28",
"colspan", 6 ) ) ),
6, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c",
"colspan", 6,
"rowspan", 1 ) ) ),
7, new XVar( "cells", new XVar( 0, new XVar( "cell", "c5",
"colspan", 3 ),
1, new XVar( "cell", "c6",
"colspan", 3 ) ),
"section", "" ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field45",
1, "integrated_edit_field54",
2, "integrated_edit_field57" ),
"align", "left" ),
"c", new XVar( "model", "c3",
"items", new XVar( 0, "section5" ) ),
"c6", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field67",
1, "integrated_edit_field64",
2, "integrated_edit_field69",
3, "integrated_edit_field71",
4, "integrated_edit_field73",
5, "integrated_edit_field75",
6, "integrated_edit_field77",
7, "integrated_edit_field79",
8, "integrated_edit_field81",
9, "integrated_edit_field83",
10, "integrated_edit_field85",
11, "integrated_edit_field87",
12, "integrated_edit_field89" ) ),
"c12", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field60",
1, "integrated_edit_field52",
2, "integrated_edit_field55" ),
"align", "left" ),
"c10", new XVar( "model", "c3",
"items", new XVar( 0, "section2" ),
"width", "33%" ),
"c28", new XVar( "model", "c3",
"items", new XVar( 0, "section4" ) ),
"c33", new XVar( "model", "c3",
"items", XVar.Array() ),
"c4", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field58",
1, "integrated_edit_field53",
2, "integrated_edit_field56" ),
"align", "left" ),
"c7", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field59",
1, "integrated_edit_field61" ),
"align", "left" ),
"c2", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "33%" ),
"c17", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field62",
1, "integrated_edit_field29",
2, "integrated_edit_field51",
3, "integrated_edit_field" ) ),
"c18", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field44",
1, "integrated_edit_field46",
2, "integrated_edit_field49" ) ),
"c8", new XVar( "model", "c3",
"items", new XVar( 0, "text" ),
"align", "left" ),
"c11", new XVar( "model", "c3",
"items", XVar.Array(),
"align", "left" ),
"c19", new XVar( "model", "c3",
"items", new XVar( 0, "section3" ) ),
"c5", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field65",
1, "integrated_edit_field66",
2, "integrated_edit_field70",
3, "integrated_edit_field72",
4, "integrated_edit_field74",
5, "integrated_edit_field78",
6, "integrated_edit_field76",
7, "integrated_edit_field80",
8, "integrated_edit_field82",
9, "integrated_edit_field84",
10, "integrated_edit_field86",
11, "integrated_edit_field88",
12, "integrated_edit_field90" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", true,
"separateLabels", false ),
"section3", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c" ) ),
"section", "" ),
1, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c3",
"colspan", 2 ) ) ),
2, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c4" ),
1, new XVar( "cell", "c5" ) ) ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field25",
1, "integrated_edit_field27",
2, "integrated_edit_field5" ) ),
"c", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field26",
1, "integrated_edit_field28",
2, "integrated_edit_field6" ) ),
"c3", new XVar( "model", "c1",
"items", new XVar( 0, "details_preview4" ) ),
"c4", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field1" ) ),
"c5", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field4" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section2", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field2",
1, "integrated_edit_field30",
2, "integrated_edit_field36",
3, "integrated_edit_field35",
4, "integrated_edit_field37",
5, "integrated_edit_field34",
6, "integrated_edit_field33",
7, "integrated_edit_field32" ) ),
"c", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field3",
1, "integrated_edit_field31",
2, "integrated_edit_field42",
3, "integrated_edit_field41",
4, "integrated_edit_field43",
5, "integrated_edit_field40",
6, "integrated_edit_field39",
7, "integrated_edit_field38" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section4", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field8",
2, "integrated_edit_field9",
3, "integrated_edit_field10",
4, "integrated_edit_field11",
5, "integrated_edit_field12",
6, "integrated_edit_field13",
7, "integrated_edit_field14",
8, "integrated_edit_field15" ) ),
"c", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field16",
1, "integrated_edit_field17",
2, "integrated_edit_field18",
3, "integrated_edit_field19",
4, "integrated_edit_field20",
5, "integrated_edit_field21",
6, "integrated_edit_field22",
7, "integrated_edit_field23",
8, "integrated_edit_field24" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section5", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field63",
1, "integrated_edit_field48",
2, "integrated_edit_field50" ) ),
"c", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field47" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ) ),
"items", new XVar( "edit_header", new XVar( "type", "edit_header" ),
"hamburger", new XVar( "type", "hamburger",
"items", new XVar( 0, "edit_reset",
1, "edit_view" ) ),
"edit_reset", new XVar( "type", "edit_reset" ),
"edit_message", new XVar( "type", "edit_message" ),
"edit_save", new XVar( "type", "edit_save" ),
"edit_back_list", new XVar( "type", "edit_back_list" ),
"edit_close", new XVar( "type", "edit_close" ),
"edit_view", new XVar( "type", "edit_view" ),
"integrated_edit_field70", new XVar( "field", "position",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field66", new XVar( "field", "frequencyRange",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field6", new XVar( "field", "elevationB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field45", new XVar( "field", "rt",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "rt",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field65", new XVar( "field", "caseNo",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field4", new XVar( "field", "callSignB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field1", new XVar( "field", "callSignA",
"type", "integrated_edit_field",
"orientation", 1 ),
"details_preview4", new XVar( "type", "details_preview",
"table", "dbo.radioEquipment",
"items", XVar.Array(),
"popup", false,
"pageId", "list",
"bold", true ),
"integrated_edit_field28", new XVar( "field", "latitudeB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field26", new XVar( "field", "longtitudeB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field5", new XVar( "field", "elevationA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "elevationA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field27", new XVar( "field", "latitudeA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "latitudeA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field25", new XVar( "field", "longtitudeA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "longtitudeA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"section3", new XVar( "type", "section",
"title", new XVar( "type", 0,
"text", "<h2><b><u>COORDINATES</u></b></h2>" ),
"location", "section3",
"bsStyle", "default",
"panelType", 3,
"headerBg", "#0033c4",
"headerColor", "#FFF",
"bodyBg", "",
"bodyColor", "",
"panelBorder", null,
"borderColor", "" ),
"integrated_edit_field21", new XVar( "field", "azimuthB",
"type", "integrated_edit_field",
"orientation", 1 ),
"text", new XVar( "type", "text",
"label", new XVar( "text", "<h2><u>Class of Station or Service</u></h2>",
"type", 0 ),
"editedByRte", true ),
"integrated_edit_field54", new XVar( "field", "ml",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "ml",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field57", new XVar( "field", "fc",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "fc",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"section5", new XVar( "type", "section",
"title", new XVar( "type", 0,
"text", "<h2><b><u>OTHERS</u></b></h2>" ),
"location", "section5",
"bsStyle", "default",
"panelType", 3,
"headerBg", "#0033c4",
"headerColor", "#fff",
"bodyBg", "",
"bodyColor", "",
"panelBorder", null,
"borderColor", "" ),
"integrated_edit_field48", new XVar( "field", "dateOfApprovedBrief",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field50", new XVar( "field", "recommendations",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field47", new XVar( "field", "Remarks",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field67", new XVar( "field", "directivity",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field64", new XVar( "field", "serviceArea",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field69", new XVar( "field", "evaluator",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field60", new XVar( "field", "tc",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "tc",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field52", new XVar( "field", "fx",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "fx",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field55", new XVar( "field", "p",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field63", new XVar( "field", "naturoOfRequest",
"type", "integrated_edit_field",
"orientation", 1 ),
"section2", new XVar( "type", "section",
"title", new XVar( "type", 0,
"text", "<h2><b><u>STATION LOCATIONS</u></b></h2>" ),
"location", "section2",
"bsStyle", "default",
"panelType", 3,
"headerBg", "#0033c4",
"headerColor", "#FFF",
"bodyBg", "",
"bodyColor", "",
"panelBorder", null,
"borderColor", "" ),
"integrated_edit_field2", new XVar( "field", "siteNameA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "siteNameA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field17", new XVar( "field", "gainB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field30", new XVar( "field", "siteIDA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "siteIDA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field36", new XVar( "field", "province_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "province_a",
"table", "dbo.rspdHeader",
"type", 3 ),
"updateOnEdit", false ),
"integrated_edit_field7", new XVar( "field", "makeTypeModelA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "makeTypeModelA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field49", new XVar( "field", "natureOfService",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field46", new XVar( "field", "modeOfOperation",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field35", new XVar( "field", "city_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "city_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field37", new XVar( "field", "zipcode_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "zipcode_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field10", new XVar( "field", "beamwidthA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "beamwidthA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field34", new XVar( "field", "barangay_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "barangay_a",
"table", "dbo.rspdHeader",
"type", 3 ),
"updateOnEdit", false ),
"integrated_edit_field11", new XVar( "field", "polarizationA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "polarizationA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field44", new XVar( "field", "externalReferenceNo",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field", new XVar( "field", "companyNameA",
"type", "integrated_edit_field",
"orientation", 1,
"updateOnEdit", false ),
"integrated_edit_field51", new XVar( "field", "applicationCategory",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field29", new XVar( "field", "applicationType",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "applicationType",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field62", new XVar( "field", "referenceID",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field33", new XVar( "field", "street_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "street_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"section4", new XVar( "type", "section",
"title", new XVar( "type", 0,
"text", "<h2><b><u>ANTENNA SYSTEM</u></b></h2>" ),
"location", "section4",
"bsStyle", "default",
"panelType", 3,
"headerBg", "#0033c4",
"headerColor", "#FFF",
"bodyBg", "",
"bodyColor", "",
"panelBorder", null,
"borderColor", "" ),
"integrated_edit_field8", new XVar( "field", "gainA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "gainA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field9", new XVar( "field", "diameterA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "diameterA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field32", new XVar( "field", "unit_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "unit_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field16", new XVar( "field", "makeTypeModelB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field18", new XVar( "field", "diameterB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field61", new XVar( "field", "other_ClassSS",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "other_ClassSS",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field59", new XVar( "field", "ma",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "ma",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field56", new XVar( "field", "bc",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "bc",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field53", new XVar( "field", "fb",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "fb",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field15", new XVar( "field", "feederLengthA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "feederLengthA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field58", new XVar( "field", "fa",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "fa",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field24", new XVar( "field", "feederLengthB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field14", new XVar( "field", "heightAGLA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "heightAGLA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field43", new XVar( "field", "zipcode_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field23", new XVar( "field", "heightAGLB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field13", new XVar( "field", "elevAngleA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "elevAngleA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field20", new XVar( "field", "polarizationB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field22", new XVar( "field", "elevAngleB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field12", new XVar( "field", "azimuthA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "azimuthA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field19", new XVar( "field", "beamwidthB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field3", new XVar( "field", "siteNameB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field31", new XVar( "field", "siteIDB",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "siteIDB",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field42", new XVar( "field", "province_b",
"type", "integrated_edit_field",
"orientation", 1,
"updateOnEdit", false ),
"integrated_edit_field41", new XVar( "field", "city_b",
"type", "integrated_edit_field",
"orientation", 1,
"updateOnEdit", false ),
"integrated_edit_field40", new XVar( "field", "barangay_b",
"type", "integrated_edit_field",
"orientation", 1,
"updateOnEdit", false ),
"integrated_edit_field39", new XVar( "field", "street_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field38", new XVar( "field", "unit_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field71", new XVar( "field", "longDegA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field72", new XVar( "field", "longMinA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field73", new XVar( "field", "longSecA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field74", new XVar( "field", "longDegB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field75", new XVar( "field", "longMinB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field76", new XVar( "field", "longSecB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field77", new XVar( "field", "coordinateA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field78", new XVar( "field", "coordinateB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field79", new XVar( "field", "latDegA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field80", new XVar( "field", "latMinA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field81", new XVar( "field", "latSecA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field82", new XVar( "field", "latDegB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field83", new XVar( "field", "latMinB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field84", new XVar( "field", "latSecB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field85", new XVar( "field", "cardinalDirectionsLatA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field86", new XVar( "field", "cardinalDirectionsLongB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field87", new XVar( "field", "cardinalDirectionLongA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field88", new XVar( "field", "cardinalDirectionLatB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field89", new XVar( "field", "regionA",
"type", "integrated_edit_field",
"orientation", 1,
"updateOnEdit", false ),
"integrated_edit_field90", new XVar( "field", "regionB",
"type", "integrated_edit_field",
"orientation", 1,
"updateOnEdit", false ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}