
		// dbo.delivery_Unit
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_delivery_unit_export
			{
				static public XVar options()
				{
					return new XVar( "totals", new XVar( "id", new XVar( "totalsType", "" ),
"first_name", new XVar( "totalsType", "" ),
"last_name", new XVar( "totalsType", "" ),
"email", new XVar( "totalsType", "" ),
"userName", new XVar( "totalsType", "" ),
"password", new XVar( "totalsType", "" ),
"address", new XVar( "totalsType", "" ),
"dateCreated", new XVar( "totalsType", "" ),
"createdBy", new XVar( "totalsType", "" ),
"Name", new XVar( "totalsType", "" ),
"office", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "id",
1, "email",
2, "userName",
3, "password",
4, "address",
5, "dateCreated",
6, "createdBy",
7, "Name",
8, "office" ),
"exportFields", new XVar( 0, "id",
1, "email",
2, "userName",
3, "password",
4, "address",
5, "dateCreated",
6, "createdBy",
7, "Name",
8, "office" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "id", new XVar( 0, "export_field" ),
"email", new XVar( 0, "export_field3" ),
"userName", new XVar( 0, "export_field4" ),
"password", new XVar( 0, "export_field5" ),
"address", new XVar( 0, "export_field6" ),
"dateCreated", new XVar( 0, "export_field7" ),
"createdBy", new XVar( 0, "export_field8" ),
"Name", new XVar( 0, "export_field9" ),
"office", new XVar( 0, "export_field10" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "export_header" ),
"grid", new XVar( 0, "export_field",
1, "export_field3",
2, "export_field4",
3, "export_field5",
4, "export_field6",
5, "export_field7",
6, "export_field8",
7, "export_field9",
8, "export_field10" ),
"footer", new XVar( 0, "export_export",
1, "export_cancel" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "export_header", "top",
"export_field", "grid",
"export_field3", "grid",
"export_field4", "grid",
"export_field5", "grid",
"export_field6", "grid",
"export_field7", "grid",
"export_field8", "grid",
"export_field9", "grid",
"export_field10", "grid",
"export_export", "footer",
"export_cancel", "footer" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "export_header", new XVar( 0, "export_header" ),
"export_export", new XVar( 0, "export_export" ),
"export_cancel", new XVar( 0, "export_cancel" ),
"export_field", new XVar( 0, "export_field",
1, "export_field3",
2, "export_field4",
3, "export_field5",
4, "export_field6",
5, "export_field7",
6, "export_field8",
7, "export_field9",
8, "export_field10" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"export", new XVar( "format", 2,
"selectFields", false,
"delimiter", ",",
"selectDelimiter", false,
"exportFileTypes", new XVar( "excel", true,
"word", true,
"csv", true,
"xml", false ) ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "export",
"type", "export",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "export-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "export-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "export_field",
1, "export_field3",
2, "export_field4",
3, "export_field5",
4, "export_field6",
5, "export_field7",
6, "export_field8",
7, "export_field9",
8, "export_field10" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"footer", new XVar( "modelId", "export-footer",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "export_export",
1, "export_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "export_header", new XVar( "type", "export_header" ),
"export_export", new XVar( "type", "export_export" ),
"export_cancel", new XVar( "type", "export_cancel" ),
"export_field", new XVar( "field", "id",
"type", "export_field" ),
"export_field3", new XVar( "field", "email",
"type", "export_field" ),
"export_field4", new XVar( "field", "userName",
"type", "export_field" ),
"export_field5", new XVar( "field", "password",
"type", "export_field" ),
"export_field6", new XVar( "field", "address",
"type", "export_field" ),
"export_field7", new XVar( "field", "dateCreated",
"type", "export_field" ),
"export_field8", new XVar( "field", "createdBy",
"type", "export_field" ),
"export_field9", new XVar( "field", "Name",
"type", "export_field" ),
"export_field10", new XVar( "field", "office",
"type", "export_field" ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1,
"exportFormat", 2,
"exportDelimiter", ",",
"exportSelectDelimiter", false,
"exportSelectFields", false );
				}
			}
		}