
		// FAS Report
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_fas_report_search
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "makeModelA",
1, "referenceID",
2, "applicationNo",
3, "companyNameA",
4, "userCreate",
5, "userUpdate",
6, "dateCreated",
7, "dateUpdated",
8, "companyNameB",
9, "siteNameA",
10, "siteNameB",
11, "siteIDA",
12, "siteIDB",
13, "coordinateA",
14, "coordinateB",
15, "elevationA",
16, "elevationB",
17, "makeTypeModelA",
18, "gainA",
19, "diameterA",
20, "beamwidthA",
21, "polarizationA",
22, "azimuthA",
23, "elevAngleA",
24, "heightAGLA",
25, "feederLengthA",
26, "makeTypeModelB",
27, "gainB",
28, "diameterB",
29, "beamwidthB",
30, "polarizationB",
31, "azimuthB",
32, "elevAngleB",
33, "heightAGLB",
34, "feederLengthB",
35, "longtitudeA",
36, "longtitudeB",
37, "latitudeA",
38, "latitudeB",
39, "callSignA",
40, "callSignB",
41, "applicationType",
42, "unit_a",
43, "street_a",
44, "barangay_a",
45, "city_a",
46, "province_a",
47, "zipcode_a",
48, "unit_b",
49, "street_b",
50, "barangay_b",
51, "city_b",
52, "province_b",
53, "zipcode_b",
54, "map",
55, "stage",
56, "stageStatus",
57, "capacityA",
58, "powerA",
59, "modA",
60, "BWEA",
61, "serialNoA",
62, "makeModelB",
63, "capacityB",
64, "powerB",
65, "modB",
66, "BWEB",
67, "serialNoB",
68, "rspdID",
69, "txA",
70, "txB",
71, "rxA",
72, "rxB" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "makeModelA", new XVar( 0, "integrated_search_field" ),
"referenceID", new XVar( 0, "integrated_search_field1" ),
"applicationNo", new XVar( 0, "integrated_search_field2" ),
"companyNameA", new XVar( 0, "integrated_search_field3" ),
"userCreate", new XVar( 0, "integrated_search_field4" ),
"userUpdate", new XVar( 0, "integrated_search_field5" ),
"dateCreated", new XVar( 0, "integrated_search_field6" ),
"dateUpdated", new XVar( 0, "integrated_search_field7" ),
"companyNameB", new XVar( 0, "integrated_search_field8" ),
"siteNameA", new XVar( 0, "integrated_search_field9" ),
"siteNameB", new XVar( 0, "integrated_search_field10" ),
"siteIDA", new XVar( 0, "integrated_search_field11" ),
"siteIDB", new XVar( 0, "integrated_search_field12" ),
"coordinateA", new XVar( 0, "integrated_search_field13" ),
"coordinateB", new XVar( 0, "integrated_search_field14" ),
"elevationA", new XVar( 0, "integrated_search_field15" ),
"elevationB", new XVar( 0, "integrated_search_field16" ),
"makeTypeModelA", new XVar( 0, "integrated_search_field17" ),
"gainA", new XVar( 0, "integrated_search_field18" ),
"diameterA", new XVar( 0, "integrated_search_field19" ),
"beamwidthA", new XVar( 0, "integrated_search_field20" ),
"polarizationA", new XVar( 0, "integrated_search_field21" ),
"azimuthA", new XVar( 0, "integrated_search_field22" ),
"elevAngleA", new XVar( 0, "integrated_search_field23" ),
"heightAGLA", new XVar( 0, "integrated_search_field24" ),
"feederLengthA", new XVar( 0, "integrated_search_field25" ),
"makeTypeModelB", new XVar( 0, "integrated_search_field26" ),
"gainB", new XVar( 0, "integrated_search_field27" ),
"diameterB", new XVar( 0, "integrated_search_field28" ),
"beamwidthB", new XVar( 0, "integrated_search_field29" ),
"polarizationB", new XVar( 0, "integrated_search_field30" ),
"azimuthB", new XVar( 0, "integrated_search_field31" ),
"elevAngleB", new XVar( 0, "integrated_search_field32" ),
"heightAGLB", new XVar( 0, "integrated_search_field33" ),
"feederLengthB", new XVar( 0, "integrated_search_field34" ),
"longtitudeA", new XVar( 0, "integrated_search_field35" ),
"longtitudeB", new XVar( 0, "integrated_search_field36" ),
"latitudeA", new XVar( 0, "integrated_search_field37" ),
"latitudeB", new XVar( 0, "integrated_search_field38" ),
"callSignA", new XVar( 0, "integrated_search_field39" ),
"callSignB", new XVar( 0, "integrated_search_field40" ),
"applicationType", new XVar( 0, "integrated_search_field41" ),
"unit_a", new XVar( 0, "integrated_search_field42" ),
"street_a", new XVar( 0, "integrated_search_field43" ),
"barangay_a", new XVar( 0, "integrated_search_field44" ),
"city_a", new XVar( 0, "integrated_search_field45" ),
"province_a", new XVar( 0, "integrated_search_field46" ),
"zipcode_a", new XVar( 0, "integrated_search_field47" ),
"unit_b", new XVar( 0, "integrated_search_field48" ),
"street_b", new XVar( 0, "integrated_search_field49" ),
"barangay_b", new XVar( 0, "integrated_search_field50" ),
"city_b", new XVar( 0, "integrated_search_field51" ),
"province_b", new XVar( 0, "integrated_search_field52" ),
"zipcode_b", new XVar( 0, "integrated_search_field53" ),
"map", new XVar( 0, "integrated_search_field54" ),
"stage", new XVar( 0, "integrated_search_field55" ),
"stageStatus", new XVar( 0, "integrated_search_field56" ),
"capacityA", new XVar( 0, "integrated_search_field57" ),
"powerA", new XVar( 0, "integrated_search_field58" ),
"modA", new XVar( 0, "integrated_search_field59" ),
"BWEA", new XVar( 0, "integrated_search_field60" ),
"serialNoA", new XVar( 0, "integrated_search_field61" ),
"makeModelB", new XVar( 0, "integrated_search_field62" ),
"capacityB", new XVar( 0, "integrated_search_field63" ),
"powerB", new XVar( 0, "integrated_search_field64" ),
"modB", new XVar( 0, "integrated_search_field65" ),
"BWEB", new XVar( 0, "integrated_search_field66" ),
"serialNoB", new XVar( 0, "integrated_search_field67" ),
"rspdID", new XVar( 0, "integrated_search_field68" ),
"txA", new XVar( 0, "integrated_search_field69" ),
"txB", new XVar( 0, "integrated_search_field70" ),
"rxA", new XVar( 0, "integrated_search_field71" ),
"rxB", new XVar( 0, "integrated_search_field72" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"below-grid", new XVar( 0, "search_search",
1, "search_reset",
2, "search_back_list",
3, "search_cancel" ),
"top", new XVar( 0, "search_header" ),
"grid", new XVar( 0, "integrated_search_field1",
1, "integrated_search_field2",
2, "integrated_search_field3",
3, "integrated_search_field4",
4, "integrated_search_field5",
5, "integrated_search_field6",
6, "integrated_search_field7",
7, "integrated_search_field8",
8, "integrated_search_field9",
9, "integrated_search_field10",
10, "integrated_search_field11",
11, "integrated_search_field12",
12, "integrated_search_field13",
13, "integrated_search_field14",
14, "integrated_search_field15",
15, "integrated_search_field16",
16, "integrated_search_field17",
17, "integrated_search_field18",
18, "integrated_search_field19",
19, "integrated_search_field20",
20, "integrated_search_field21",
21, "integrated_search_field22",
22, "integrated_search_field23",
23, "integrated_search_field24",
24, "integrated_search_field25",
25, "integrated_search_field26",
26, "integrated_search_field27",
27, "integrated_search_field28",
28, "integrated_search_field29",
29, "integrated_search_field30",
30, "integrated_search_field31",
31, "integrated_search_field32",
32, "integrated_search_field33",
33, "integrated_search_field34",
34, "integrated_search_field35",
35, "integrated_search_field36",
36, "integrated_search_field37",
37, "integrated_search_field38",
38, "integrated_search_field39",
39, "integrated_search_field40",
40, "integrated_search_field41",
41, "integrated_search_field42",
42, "integrated_search_field43",
43, "integrated_search_field44",
44, "integrated_search_field45",
45, "integrated_search_field46",
46, "integrated_search_field47",
47, "integrated_search_field48",
48, "integrated_search_field49",
49, "integrated_search_field50",
50, "integrated_search_field51",
51, "integrated_search_field52",
52, "integrated_search_field53",
53, "integrated_search_field54",
54, "integrated_search_field55",
55, "integrated_search_field56",
56, "integrated_search_field",
57, "integrated_search_field57",
58, "integrated_search_field58",
59, "integrated_search_field59",
60, "integrated_search_field60",
61, "integrated_search_field61",
62, "integrated_search_field62",
63, "integrated_search_field63",
64, "integrated_search_field64",
65, "integrated_search_field65",
66, "integrated_search_field66",
67, "integrated_search_field67",
68, "integrated_search_field68",
69, "integrated_search_field69",
70, "integrated_search_field70",
71, "integrated_search_field71",
72, "integrated_search_field72" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array() ),
"itemForms", new XVar( "search_search", "below-grid",
"search_reset", "below-grid",
"search_back_list", "below-grid",
"search_cancel", "below-grid",
"search_header", "top",
"integrated_search_field1", "grid",
"integrated_search_field2", "grid",
"integrated_search_field3", "grid",
"integrated_search_field4", "grid",
"integrated_search_field5", "grid",
"integrated_search_field6", "grid",
"integrated_search_field7", "grid",
"integrated_search_field8", "grid",
"integrated_search_field9", "grid",
"integrated_search_field10", "grid",
"integrated_search_field11", "grid",
"integrated_search_field12", "grid",
"integrated_search_field13", "grid",
"integrated_search_field14", "grid",
"integrated_search_field15", "grid",
"integrated_search_field16", "grid",
"integrated_search_field17", "grid",
"integrated_search_field18", "grid",
"integrated_search_field19", "grid",
"integrated_search_field20", "grid",
"integrated_search_field21", "grid",
"integrated_search_field22", "grid",
"integrated_search_field23", "grid",
"integrated_search_field24", "grid",
"integrated_search_field25", "grid",
"integrated_search_field26", "grid",
"integrated_search_field27", "grid",
"integrated_search_field28", "grid",
"integrated_search_field29", "grid",
"integrated_search_field30", "grid",
"integrated_search_field31", "grid",
"integrated_search_field32", "grid",
"integrated_search_field33", "grid",
"integrated_search_field34", "grid",
"integrated_search_field35", "grid",
"integrated_search_field36", "grid",
"integrated_search_field37", "grid",
"integrated_search_field38", "grid",
"integrated_search_field39", "grid",
"integrated_search_field40", "grid",
"integrated_search_field41", "grid",
"integrated_search_field42", "grid",
"integrated_search_field43", "grid",
"integrated_search_field44", "grid",
"integrated_search_field45", "grid",
"integrated_search_field46", "grid",
"integrated_search_field47", "grid",
"integrated_search_field48", "grid",
"integrated_search_field49", "grid",
"integrated_search_field50", "grid",
"integrated_search_field51", "grid",
"integrated_search_field52", "grid",
"integrated_search_field53", "grid",
"integrated_search_field54", "grid",
"integrated_search_field55", "grid",
"integrated_search_field56", "grid",
"integrated_search_field", "grid",
"integrated_search_field57", "grid",
"integrated_search_field58", "grid",
"integrated_search_field59", "grid",
"integrated_search_field60", "grid",
"integrated_search_field61", "grid",
"integrated_search_field62", "grid",
"integrated_search_field63", "grid",
"integrated_search_field64", "grid",
"integrated_search_field65", "grid",
"integrated_search_field66", "grid",
"integrated_search_field67", "grid",
"integrated_search_field68", "grid",
"integrated_search_field69", "grid",
"integrated_search_field70", "grid",
"integrated_search_field71", "grid",
"integrated_search_field72", "grid" ),
"itemLocations", new XVar( "integrated_search_field1", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field2", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field3", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field4", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field5", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field6", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field7", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field8", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field9", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field10", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field11", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field12", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field13", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field14", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field15", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field16", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field17", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field18", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field19", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field20", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field21", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field22", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field23", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field24", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field25", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field26", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field27", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field28", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field29", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field30", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field31", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field32", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field33", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field34", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field35", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field36", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field37", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field38", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field39", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field40", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field41", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field42", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field43", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field44", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field45", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field46", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field47", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field48", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field49", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field50", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field51", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field52", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field53", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field54", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field55", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field56", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field57", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field58", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field59", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field60", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field61", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field62", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field63", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field64", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field65", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field66", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field67", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field68", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field69", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field70", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field71", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_search_field72", new XVar( "location", "grid",
"cellId", "c3" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "search_header", new XVar( 0, "search_header" ),
"search_reset", new XVar( 0, "search_reset" ),
"search_back_list", new XVar( 0, "search_back_list" ),
"search_search", new XVar( 0, "search_search" ),
"search_cancel", new XVar( 0, "search_cancel" ),
"integrated_search_field", new XVar( 0, "integrated_search_field",
1, "integrated_search_field1",
2, "integrated_search_field2",
3, "integrated_search_field3",
4, "integrated_search_field4",
5, "integrated_search_field5",
6, "integrated_search_field6",
7, "integrated_search_field7",
8, "integrated_search_field8",
9, "integrated_search_field9",
10, "integrated_search_field10",
11, "integrated_search_field11",
12, "integrated_search_field12",
13, "integrated_search_field13",
14, "integrated_search_field14",
15, "integrated_search_field15",
16, "integrated_search_field16",
17, "integrated_search_field17",
18, "integrated_search_field18",
19, "integrated_search_field19",
20, "integrated_search_field20",
21, "integrated_search_field21",
22, "integrated_search_field22",
23, "integrated_search_field23",
24, "integrated_search_field24",
25, "integrated_search_field25",
26, "integrated_search_field26",
27, "integrated_search_field27",
28, "integrated_search_field28",
29, "integrated_search_field29",
30, "integrated_search_field30",
31, "integrated_search_field31",
32, "integrated_search_field32",
33, "integrated_search_field33",
34, "integrated_search_field34",
35, "integrated_search_field35",
36, "integrated_search_field36",
37, "integrated_search_field37",
38, "integrated_search_field38",
39, "integrated_search_field39",
40, "integrated_search_field40",
41, "integrated_search_field41",
42, "integrated_search_field42",
43, "integrated_search_field43",
44, "integrated_search_field44",
45, "integrated_search_field45",
46, "integrated_search_field46",
47, "integrated_search_field47",
48, "integrated_search_field48",
49, "integrated_search_field49",
50, "integrated_search_field50",
51, "integrated_search_field51",
52, "integrated_search_field52",
53, "integrated_search_field53",
54, "integrated_search_field54",
55, "integrated_search_field55",
56, "integrated_search_field56",
57, "integrated_search_field57",
58, "integrated_search_field58",
59, "integrated_search_field59",
60, "integrated_search_field60",
61, "integrated_search_field61",
62, "integrated_search_field62",
63, "integrated_search_field63",
64, "integrated_search_field64",
65, "integrated_search_field65",
66, "integrated_search_field66",
67, "integrated_search_field67",
68, "integrated_search_field68",
69, "integrated_search_field69",
70, "integrated_search_field70",
71, "integrated_search_field71",
72, "integrated_search_field72" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_search_field1",
1, "integrated_search_field2",
2, "integrated_search_field3",
3, "integrated_search_field4",
4, "integrated_search_field5",
5, "integrated_search_field6",
6, "integrated_search_field7",
7, "integrated_search_field8",
8, "integrated_search_field9",
9, "integrated_search_field10",
10, "integrated_search_field11",
11, "integrated_search_field12",
12, "integrated_search_field13",
13, "integrated_search_field14",
14, "integrated_search_field15",
15, "integrated_search_field16",
16, "integrated_search_field17",
17, "integrated_search_field18",
18, "integrated_search_field19",
19, "integrated_search_field20",
20, "integrated_search_field21",
21, "integrated_search_field22",
22, "integrated_search_field23",
23, "integrated_search_field24",
24, "integrated_search_field25",
25, "integrated_search_field26",
26, "integrated_search_field27",
27, "integrated_search_field28",
28, "integrated_search_field29",
29, "integrated_search_field30",
30, "integrated_search_field31",
31, "integrated_search_field32",
32, "integrated_search_field33",
33, "integrated_search_field34",
34, "integrated_search_field35",
35, "integrated_search_field36",
36, "integrated_search_field37",
37, "integrated_search_field38",
38, "integrated_search_field39",
39, "integrated_search_field40",
40, "integrated_search_field41",
41, "integrated_search_field42",
42, "integrated_search_field43",
43, "integrated_search_field44",
44, "integrated_search_field45",
45, "integrated_search_field46",
46, "integrated_search_field47",
47, "integrated_search_field48",
48, "integrated_search_field49",
49, "integrated_search_field50",
50, "integrated_search_field51",
51, "integrated_search_field52",
52, "integrated_search_field53",
53, "integrated_search_field54",
54, "integrated_search_field55",
55, "integrated_search_field56",
56, "integrated_search_field",
57, "integrated_search_field57",
58, "integrated_search_field58",
59, "integrated_search_field59",
60, "integrated_search_field60",
61, "integrated_search_field61",
62, "integrated_search_field62",
63, "integrated_search_field63",
64, "integrated_search_field64",
65, "integrated_search_field65",
66, "integrated_search_field66",
67, "integrated_search_field67",
68, "integrated_search_field68",
69, "integrated_search_field69",
70, "integrated_search_field70",
71, "integrated_search_field71",
72, "integrated_search_field72" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "search",
"breadcrumb", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "search",
"type", "search",
"layoutId", "nomenu",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "search-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1",
"colspan", 2 ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "search-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "search_search",
1, "search_reset",
2, "search_back_list",
3, "search_cancel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "search-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "search_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-search",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ) ),
"section", "" ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_search_field1",
1, "integrated_search_field2",
2, "integrated_search_field3",
3, "integrated_search_field4",
4, "integrated_search_field5",
5, "integrated_search_field6",
6, "integrated_search_field7",
7, "integrated_search_field8",
8, "integrated_search_field9",
9, "integrated_search_field10",
10, "integrated_search_field11",
11, "integrated_search_field12",
12, "integrated_search_field13",
13, "integrated_search_field14",
14, "integrated_search_field15",
15, "integrated_search_field16",
16, "integrated_search_field17",
17, "integrated_search_field18",
18, "integrated_search_field19",
19, "integrated_search_field20",
20, "integrated_search_field21",
21, "integrated_search_field22",
22, "integrated_search_field23",
23, "integrated_search_field24",
24, "integrated_search_field25",
25, "integrated_search_field26",
26, "integrated_search_field27",
27, "integrated_search_field28",
28, "integrated_search_field29",
29, "integrated_search_field30",
30, "integrated_search_field31",
31, "integrated_search_field32",
32, "integrated_search_field33",
33, "integrated_search_field34",
34, "integrated_search_field35",
35, "integrated_search_field36",
36, "integrated_search_field37",
37, "integrated_search_field38",
38, "integrated_search_field39",
39, "integrated_search_field40",
40, "integrated_search_field41",
41, "integrated_search_field42",
42, "integrated_search_field43",
43, "integrated_search_field44",
44, "integrated_search_field45",
45, "integrated_search_field46",
46, "integrated_search_field47",
47, "integrated_search_field48",
48, "integrated_search_field49",
49, "integrated_search_field50",
50, "integrated_search_field51",
51, "integrated_search_field52",
52, "integrated_search_field53",
53, "integrated_search_field54",
54, "integrated_search_field55",
55, "integrated_search_field56",
56, "integrated_search_field",
57, "integrated_search_field57",
58, "integrated_search_field58",
59, "integrated_search_field59",
60, "integrated_search_field60",
61, "integrated_search_field61",
62, "integrated_search_field62",
63, "integrated_search_field63",
64, "integrated_search_field64",
65, "integrated_search_field65",
66, "integrated_search_field66",
67, "integrated_search_field67",
68, "integrated_search_field68",
69, "integrated_search_field69",
70, "integrated_search_field70",
71, "integrated_search_field71",
72, "integrated_search_field72" ) ) ),
"deferredItems", XVar.Array(),
"separateLabels", false ) ),
"items", new XVar( "search_header", new XVar( "type", "search_header" ),
"search_reset", new XVar( "type", "search_reset" ),
"search_back_list", new XVar( "type", "search_back_list" ),
"search_search", new XVar( "type", "search_search" ),
"search_cancel", new XVar( "type", "search_cancel" ),
"integrated_search_field", new XVar( "field", "makeModelA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field1", new XVar( "field", "referenceID",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field2", new XVar( "field", "applicationNo",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field3", new XVar( "field", "companyNameA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field4", new XVar( "field", "userCreate",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field5", new XVar( "field", "userUpdate",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field6", new XVar( "field", "dateCreated",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field7", new XVar( "field", "dateUpdated",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field8", new XVar( "field", "companyNameB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field9", new XVar( "field", "siteNameA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field10", new XVar( "field", "siteNameB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field11", new XVar( "field", "siteIDA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field12", new XVar( "field", "siteIDB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field13", new XVar( "field", "coordinateA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field14", new XVar( "field", "coordinateB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field15", new XVar( "field", "elevationA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field16", new XVar( "field", "elevationB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field17", new XVar( "field", "makeTypeModelA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field18", new XVar( "field", "gainA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field19", new XVar( "field", "diameterA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field20", new XVar( "field", "beamwidthA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field21", new XVar( "field", "polarizationA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field22", new XVar( "field", "azimuthA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field23", new XVar( "field", "elevAngleA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field24", new XVar( "field", "heightAGLA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field25", new XVar( "field", "feederLengthA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field26", new XVar( "field", "makeTypeModelB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field27", new XVar( "field", "gainB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field28", new XVar( "field", "diameterB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field29", new XVar( "field", "beamwidthB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field30", new XVar( "field", "polarizationB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field31", new XVar( "field", "azimuthB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field32", new XVar( "field", "elevAngleB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field33", new XVar( "field", "heightAGLB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field34", new XVar( "field", "feederLengthB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field35", new XVar( "field", "longtitudeA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field36", new XVar( "field", "longtitudeB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field37", new XVar( "field", "latitudeA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field38", new XVar( "field", "latitudeB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field39", new XVar( "field", "callSignA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field40", new XVar( "field", "callSignB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field41", new XVar( "field", "applicationType",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field42", new XVar( "field", "unit_a",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field43", new XVar( "field", "street_a",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field44", new XVar( "field", "barangay_a",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field45", new XVar( "field", "city_a",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field46", new XVar( "field", "province_a",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field47", new XVar( "field", "zipcode_a",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field48", new XVar( "field", "unit_b",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field49", new XVar( "field", "street_b",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field50", new XVar( "field", "barangay_b",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field51", new XVar( "field", "city_b",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field52", new XVar( "field", "province_b",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field53", new XVar( "field", "zipcode_b",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field54", new XVar( "field", "map",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field55", new XVar( "field", "stage",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field56", new XVar( "field", "stageStatus",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field57", new XVar( "field", "capacityA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field58", new XVar( "field", "powerA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field59", new XVar( "field", "modA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field60", new XVar( "field", "BWEA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field61", new XVar( "field", "serialNoA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field62", new XVar( "field", "makeModelB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field63", new XVar( "field", "capacityB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field64", new XVar( "field", "powerB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field65", new XVar( "field", "modB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field66", new XVar( "field", "BWEB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field67", new XVar( "field", "serialNoB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field68", new XVar( "field", "rspdID",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field69", new XVar( "field", "txA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field70", new XVar( "field", "txB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field71", new XVar( "field", "rxA",
"type", "integrated_search_field",
"orientation", 0,
"required", false ),
"integrated_search_field72", new XVar( "field", "rxB",
"type", "integrated_search_field",
"orientation", 0,
"required", false ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}