
		// dbo.rspd_application_received
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_rspd_application_received_view
			{
				static public XVar options()
				{
					return new XVar( "pdf", new XVar( "pdfView", true,
"orientation", "portrait",
"scale", 100 ),
"fields", new XVar( "gridFields", new XVar( 0, "companyNameA",
1, "elevationB",
2, "externalReferenceNo",
3, "classStationService",
4, "dateOfApprovedBrief",
5, "callSignA",
6, "latitudeB",
7, "makeTypeModelA",
8, "gainA",
9, "diameterA",
10, "beamwidthA",
11, "polarizationA",
12, "azimuthA",
13, "province_b",
14, "elevAngleA",
15, "heightAGLA",
16, "feederLengthA",
17, "siteNameB",
18, "siteIDB",
19, "longtitudeB",
20, "elevationA",
21, "latitudeA",
22, "longtitudeA",
23, "callSignB",
24, "feederLengthB",
25, "heightAGLB",
26, "elevAngleB",
27, "azimuthB",
28, "polarizationB",
29, "beamwidthB",
30, "diameterB",
31, "gainB",
32, "makeTypeModelB",
33, "Remarks",
34, "modeOfOperation",
35, "natureOfService",
36, "barangay_b",
37, "applicationType",
38, "unit_a",
39, "siteNameA",
40, "street_a",
41, "unit_b",
42, "street_b",
43, "zipcode_b",
44, "city_b",
45, "barangay_a",
46, "zipcode_a",
47, "city_a",
48, "province_a",
49, "siteIDA",
50, "recommendations",
51, "applicationCategory",
52, "address",
53, "view_data" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "companyNameA", new XVar( 0, "integrated_edit_field" ),
"elevationB", new XVar( 0, "integrated_edit_field6" ),
"externalReferenceNo", new XVar( 0, "integrated_edit_field44" ),
"classStationService", new XVar( 0, "integrated_edit_field45" ),
"dateOfApprovedBrief", new XVar( 0, "integrated_edit_field48" ),
"callSignA", new XVar( 0, "integrated_edit_field1" ),
"latitudeB", new XVar( 0, "integrated_edit_field28" ),
"makeTypeModelA", new XVar( 0, "integrated_edit_field7" ),
"gainA", new XVar( 0, "integrated_edit_field8" ),
"diameterA", new XVar( 0, "integrated_edit_field9" ),
"beamwidthA", new XVar( 0, "integrated_edit_field10" ),
"polarizationA", new XVar( 0, "integrated_edit_field11" ),
"azimuthA", new XVar( 0, "integrated_edit_field12" ),
"province_b", new XVar( 0, "integrated_edit_field42" ),
"elevAngleA", new XVar( 0, "integrated_edit_field13" ),
"heightAGLA", new XVar( 0, "integrated_edit_field14" ),
"feederLengthA", new XVar( 0, "integrated_edit_field15" ),
"siteNameB", new XVar( 0, "integrated_edit_field3" ),
"siteIDB", new XVar( 0, "integrated_edit_field31" ),
"longtitudeB", new XVar( 0, "integrated_edit_field26" ),
"elevationA", new XVar( 0, "integrated_edit_field5" ),
"latitudeA", new XVar( 0, "integrated_edit_field27" ),
"longtitudeA", new XVar( 0, "integrated_edit_field25" ),
"callSignB", new XVar( 0, "integrated_edit_field4" ),
"feederLengthB", new XVar( 0, "integrated_edit_field24" ),
"heightAGLB", new XVar( 0, "integrated_edit_field23" ),
"elevAngleB", new XVar( 0, "integrated_edit_field22" ),
"azimuthB", new XVar( 0, "integrated_edit_field21" ),
"polarizationB", new XVar( 0, "integrated_edit_field20" ),
"beamwidthB", new XVar( 0, "integrated_edit_field19" ),
"diameterB", new XVar( 0, "integrated_edit_field18" ),
"gainB", new XVar( 0, "integrated_edit_field17" ),
"makeTypeModelB", new XVar( 0, "integrated_edit_field16" ),
"Remarks", new XVar( 0, "integrated_edit_field47" ),
"modeOfOperation", new XVar( 0, "integrated_edit_field46" ),
"natureOfService", new XVar( 0, "integrated_edit_field49" ),
"barangay_b", new XVar( 0, "integrated_edit_field40" ),
"applicationType", new XVar( 0, "integrated_edit_field29" ),
"unit_a", new XVar( 0, "integrated_edit_field32" ),
"siteNameA", new XVar( 0, "integrated_edit_field2" ),
"street_a", new XVar( 0, "integrated_edit_field33" ),
"unit_b", new XVar( 0, "integrated_edit_field38" ),
"street_b", new XVar( 0, "integrated_edit_field39" ),
"zipcode_b", new XVar( 0, "integrated_edit_field43" ),
"city_b", new XVar( 0, "integrated_edit_field41" ),
"barangay_a", new XVar( 0, "integrated_edit_field34" ),
"zipcode_a", new XVar( 0, "integrated_edit_field37" ),
"city_a", new XVar( 0, "integrated_edit_field35" ),
"province_a", new XVar( 0, "integrated_edit_field36" ),
"siteIDA", new XVar( 0, "integrated_edit_field30" ),
"recommendations", new XVar( 0, "integrated_edit_field50" ),
"applicationCategory", new XVar( 0, "integrated_edit_field51" ),
"address", new XVar( 0, "integrated_edit_field52" ),
"view_data", new XVar( 0, "integrated_edit_field53" ) ) ),
"pageLinks", new XVar( "edit", true,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", XVar.Array(),
"below-grid", new XVar( 0, "view_back_list",
1, "view_close",
2, "hamburger" ),
"top", new XVar( 0, "view_header" ),
"grid", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field44",
2, "integrated_edit_field45",
3, "integrated_edit_field48",
4, "integrated_edit_field52",
5, "integrated_edit_field1",
6, "integrated_edit_field7",
7, "integrated_edit_field8",
8, "integrated_edit_field9",
9, "integrated_edit_field10",
10, "integrated_edit_field11",
11, "integrated_edit_field12",
12, "integrated_edit_field13",
13, "integrated_edit_field14",
14, "integrated_edit_field15",
15, "integrated_edit_field3",
16, "integrated_edit_field31",
17, "section1",
18, "integrated_edit_field51",
19, "integrated_edit_field49",
20, "integrated_edit_field50",
21, "integrated_edit_field53",
22, "details_preview4",
23, "integrated_edit_field2",
24, "integrated_edit_field30",
25, "section",
26, "integrated_edit_field29",
27, "integrated_edit_field46",
28, "integrated_edit_field47",
29, "text",
30, "integrated_edit_field16",
31, "integrated_edit_field17",
32, "integrated_edit_field18",
33, "integrated_edit_field19",
34, "integrated_edit_field20",
35, "integrated_edit_field21",
36, "integrated_edit_field22",
37, "integrated_edit_field23",
38, "integrated_edit_field24",
39, "integrated_edit_field4",
40, "text2",
41, "text1",
42, "integrated_edit_field25",
43, "integrated_edit_field27",
44, "integrated_edit_field5",
45, "integrated_edit_field26",
46, "integrated_edit_field28",
47, "integrated_edit_field6" ),
"section1", new XVar( 0, "integrated_edit_field42",
1, "integrated_edit_field41",
2, "integrated_edit_field43",
3, "integrated_edit_field40",
4, "integrated_edit_field39",
5, "integrated_edit_field38" ),
"section", new XVar( 0, "integrated_edit_field36",
1, "integrated_edit_field35",
2, "integrated_edit_field37",
3, "integrated_edit_field34",
4, "integrated_edit_field33",
5, "integrated_edit_field32" ) ),
"formXtTags", new XVar( "above-grid", XVar.Array() ),
"itemForms", new XVar( "view_back_list", "below-grid",
"view_close", "below-grid",
"hamburger", "below-grid",
"view_header", "top",
"integrated_edit_field", "grid",
"integrated_edit_field44", "grid",
"integrated_edit_field45", "grid",
"integrated_edit_field48", "grid",
"integrated_edit_field52", "grid",
"integrated_edit_field1", "grid",
"integrated_edit_field7", "grid",
"integrated_edit_field8", "grid",
"integrated_edit_field9", "grid",
"integrated_edit_field10", "grid",
"integrated_edit_field11", "grid",
"integrated_edit_field12", "grid",
"integrated_edit_field13", "grid",
"integrated_edit_field14", "grid",
"integrated_edit_field15", "grid",
"integrated_edit_field3", "grid",
"integrated_edit_field31", "grid",
"section1", "grid",
"integrated_edit_field51", "grid",
"integrated_edit_field49", "grid",
"integrated_edit_field50", "grid",
"integrated_edit_field53", "grid",
"details_preview4", "grid",
"integrated_edit_field2", "grid",
"integrated_edit_field30", "grid",
"section", "grid",
"integrated_edit_field29", "grid",
"integrated_edit_field46", "grid",
"integrated_edit_field47", "grid",
"text", "grid",
"integrated_edit_field16", "grid",
"integrated_edit_field17", "grid",
"integrated_edit_field18", "grid",
"integrated_edit_field19", "grid",
"integrated_edit_field20", "grid",
"integrated_edit_field21", "grid",
"integrated_edit_field22", "grid",
"integrated_edit_field23", "grid",
"integrated_edit_field24", "grid",
"integrated_edit_field4", "grid",
"text2", "grid",
"text1", "grid",
"integrated_edit_field25", "grid",
"integrated_edit_field27", "grid",
"integrated_edit_field5", "grid",
"integrated_edit_field26", "grid",
"integrated_edit_field28", "grid",
"integrated_edit_field6", "grid",
"integrated_edit_field42", "section1",
"integrated_edit_field41", "section1",
"integrated_edit_field43", "section1",
"integrated_edit_field40", "section1",
"integrated_edit_field39", "section1",
"integrated_edit_field38", "section1",
"integrated_edit_field36", "section",
"integrated_edit_field35", "section",
"integrated_edit_field37", "section",
"integrated_edit_field34", "section",
"integrated_edit_field33", "section",
"integrated_edit_field32", "section" ),
"itemLocations", new XVar( "integrated_edit_field", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field44", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field45", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field48", new XVar( "location", "grid",
"cellId", "c3" ),
"integrated_edit_field52", new XVar( "location", "grid",
"cellId", "c5" ),
"integrated_edit_field1", new XVar( "location", "grid",
"cellId", "c6" ),
"integrated_edit_field7", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field8", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field9", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field10", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field11", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field12", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field13", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field14", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field15", new XVar( "location", "grid",
"cellId", "c12" ),
"integrated_edit_field3", new XVar( "location", "grid",
"cellId", "c15" ),
"integrated_edit_field31", new XVar( "location", "grid",
"cellId", "c15" ),
"section1", new XVar( "location", "grid",
"cellId", "c15" ),
"integrated_edit_field51", new XVar( "location", "grid",
"cellId", "c16" ),
"integrated_edit_field49", new XVar( "location", "grid",
"cellId", "c16" ),
"integrated_edit_field50", new XVar( "location", "grid",
"cellId", "c17" ),
"integrated_edit_field53", new XVar( "location", "grid",
"cellId", "c17" ),
"details_preview4", new XVar( "location", "grid",
"cellId", "c21" ),
"integrated_edit_field2", new XVar( "location", "grid",
"cellId", "c20" ),
"integrated_edit_field30", new XVar( "location", "grid",
"cellId", "c20" ),
"section", new XVar( "location", "grid",
"cellId", "c20" ),
"integrated_edit_field29", new XVar( "location", "grid",
"cellId", "c8" ),
"integrated_edit_field46", new XVar( "location", "grid",
"cellId", "c10" ),
"integrated_edit_field47", new XVar( "location", "grid",
"cellId", "c10" ),
"text", new XVar( "location", "grid",
"cellId", "c22" ),
"integrated_edit_field16", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field17", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field18", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field19", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field20", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field21", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field22", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field23", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field24", new XVar( "location", "grid",
"cellId", "c23" ),
"integrated_edit_field4", new XVar( "location", "grid",
"cellId", "c24" ),
"text2", new XVar( "location", "grid",
"cellId", "c25" ),
"text1", new XVar( "location", "grid",
"cellId", "c29" ),
"integrated_edit_field25", new XVar( "location", "grid",
"cellId", "c30" ),
"integrated_edit_field27", new XVar( "location", "grid",
"cellId", "c30" ),
"integrated_edit_field5", new XVar( "location", "grid",
"cellId", "c30" ),
"integrated_edit_field26", new XVar( "location", "grid",
"cellId", "c32" ),
"integrated_edit_field28", new XVar( "location", "grid",
"cellId", "c32" ),
"integrated_edit_field6", new XVar( "location", "grid",
"cellId", "c32" ),
"integrated_edit_field42", new XVar( "location", "section1",
"cellId", "c1" ),
"integrated_edit_field41", new XVar( "location", "section1",
"cellId", "c1" ),
"integrated_edit_field43", new XVar( "location", "section1",
"cellId", "c1" ),
"integrated_edit_field40", new XVar( "location", "section1",
"cellId", "c1" ),
"integrated_edit_field39", new XVar( "location", "section1",
"cellId", "c1" ),
"integrated_edit_field38", new XVar( "location", "section1",
"cellId", "c1" ),
"integrated_edit_field36", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field35", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field37", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field34", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field33", new XVar( "location", "section",
"cellId", "c1" ),
"integrated_edit_field32", new XVar( "location", "section",
"cellId", "c1" ) ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "view_header", new XVar( 0, "view_header" ),
"view_back_list", new XVar( 0, "view_back_list" ),
"view_close", new XVar( 0, "view_close" ),
"hamburger", new XVar( 0, "hamburger" ),
"view_edit", new XVar( 0, "view_edit" ),
"integrated_edit_field", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field6",
2, "integrated_edit_field44",
3, "integrated_edit_field45",
4, "integrated_edit_field48",
5, "integrated_edit_field1",
6, "integrated_edit_field28",
7, "integrated_edit_field7",
8, "integrated_edit_field8",
9, "integrated_edit_field9",
10, "integrated_edit_field10",
11, "integrated_edit_field11",
12, "integrated_edit_field12",
13, "integrated_edit_field42",
14, "integrated_edit_field13",
15, "integrated_edit_field14",
16, "integrated_edit_field15",
17, "integrated_edit_field3",
18, "integrated_edit_field31",
19, "integrated_edit_field26",
20, "integrated_edit_field5",
21, "integrated_edit_field27",
22, "integrated_edit_field25",
23, "integrated_edit_field4",
24, "integrated_edit_field24",
25, "integrated_edit_field23",
26, "integrated_edit_field22",
27, "integrated_edit_field21",
28, "integrated_edit_field20",
29, "integrated_edit_field19",
30, "integrated_edit_field18",
31, "integrated_edit_field17",
32, "integrated_edit_field16",
33, "integrated_edit_field47",
34, "integrated_edit_field46",
35, "integrated_edit_field49",
36, "integrated_edit_field40",
37, "integrated_edit_field29",
38, "integrated_edit_field32",
39, "integrated_edit_field2",
40, "integrated_edit_field33",
41, "integrated_edit_field38",
42, "integrated_edit_field39",
43, "integrated_edit_field43",
44, "integrated_edit_field41",
45, "integrated_edit_field34",
46, "integrated_edit_field37",
47, "integrated_edit_field35",
48, "integrated_edit_field36",
49, "integrated_edit_field30",
50, "integrated_edit_field50",
51, "integrated_edit_field51",
52, "integrated_edit_field52",
53, "integrated_edit_field53" ),
"text", new XVar( 0, "text1",
1, "text2",
2, "text" ),
"details_preview", new XVar( 0, "details_preview4" ),
"section", new XVar( 0, "section1",
1, "section" ),
"view_pdf", new XVar( 0, "view_pdf" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "c8", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field29" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c10", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0,
1, 1,
2, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field46",
1, "integrated_edit_field47" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c11", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c14", new XVar( "cols", new XVar( 0, 3,
1, 4 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c3", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field44",
2, "integrated_edit_field45",
3, "integrated_edit_field48" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c9", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1,
1, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c", new XVar( "cols", new XVar( 0, 3,
1, 4 ),
"rows", new XVar( 0, 1,
1, 2,
2, 3,
3, 4,
4, 5 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c22", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "text" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c20", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field2",
1, "integrated_edit_field30",
2, "section" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c15", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field3",
1, "integrated_edit_field31",
2, "section1" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c18", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 3,
1, 4,
2, 5 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c29", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 4 ),
"tags", XVar.Array(),
"items", new XVar( 0, "text1" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c31", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 4 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c30", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 5 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field25",
1, "integrated_edit_field27",
2, "integrated_edit_field5" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c32", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 5 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field26",
1, "integrated_edit_field28",
2, "integrated_edit_field6" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c21", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4 ),
"rows", new XVar( 0, 6 ),
"tags", XVar.Array(),
"items", new XVar( 0, "details_preview4" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c25", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 7 ),
"tags", XVar.Array(),
"items", new XVar( 0, "text2" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c26", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 7 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c27", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 7 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c28", new XVar( "cols", new XVar( 0, 3,
1, 4 ),
"rows", new XVar( 0, 7 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c12", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 8 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field8",
2, "integrated_edit_field9",
3, "integrated_edit_field10",
4, "integrated_edit_field11",
5, "integrated_edit_field12",
6, "integrated_edit_field13",
7, "integrated_edit_field14",
8, "integrated_edit_field15" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c23", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 8 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field16",
1, "integrated_edit_field17",
2, "integrated_edit_field18",
3, "integrated_edit_field19",
4, "integrated_edit_field20",
5, "integrated_edit_field21",
6, "integrated_edit_field22",
7, "integrated_edit_field23",
8, "integrated_edit_field24" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c19", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 8 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c13", new XVar( "cols", new XVar( 0, 3,
1, 4 ),
"rows", new XVar( 0, 8 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"c6", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 9 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field1" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c24", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 9 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field4" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c17", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 9 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field50",
1, "integrated_edit_field53" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c16", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 9 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field51",
1, "integrated_edit_field49" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"c5", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 9 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field52" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 5,
"height", 10 ),
"section1", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field42",
1, "integrated_edit_field41",
2, "integrated_edit_field43",
3, "integrated_edit_field40",
4, "integrated_edit_field39",
5, "integrated_edit_field38" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ),
"section", new XVar( "cells", new XVar( "c1", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", new XVar( 0, "integrated_edit_field36",
1, "integrated_edit_field35",
2, "integrated_edit_field37",
3, "integrated_edit_field34",
4, "integrated_edit_field33",
5, "integrated_edit_field32" ),
"fixedAtServer", true,
"fixedAtClient", false ) ),
"width", 1,
"height", 1 ) ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "view",
"breadcrumb", false,
"nextPrev", false ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "view",
"type", "view",
"layoutId", "nomenu",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "view-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1",
"colspan", 2 ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "view-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_back_list",
1, "view_close" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "hamburger" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "view-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "view_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c8" ),
1, new XVar( "cell", "c10",
"rowspan", 3 ),
2, new XVar( "cell", "c11" ),
3, new XVar( "cell", "c14",
"colspan", 2 ) ) ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c3" ),
1, new XVar( "cell", "c9",
"rowspan", 2 ),
2, new XVar( "cell", "c",
"rowspan", 5,
"colspan", 2 ) ),
"section", "" ),
2, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c22" ) ) ),
3, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c20",
"rowspan", 1 ),
1, new XVar( "cell", "c15",
"rowspan", 1 ),
2, new XVar( "cell", "c18",
"rowspan", 3 ) ) ),
4, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c29" ),
1, new XVar( "cell", "c31" ) ) ),
5, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c30" ),
1, new XVar( "cell", "c32" ) ) ),
6, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c21",
"colspan", 5 ) ) ),
7, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c25" ),
1, new XVar( "cell", "c26" ),
2, new XVar( "cell", "c27" ),
3, new XVar( "cell", "c28",
"colspan", 2 ) ) ),
8, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c12" ),
1, new XVar( "cell", "c23" ),
2, new XVar( "cell", "c19" ),
3, new XVar( "cell", "c13",
"colspan", 2 ) ) ),
9, new XVar( "section", "",
"cells", new XVar( 0, new XVar( "cell", "c6" ),
1, new XVar( "cell", "c24" ),
2, new XVar( "cell", "c17" ),
3, new XVar( "cell", "c16",
"colspan", 1 ),
4, new XVar( "cell", "c5" ) ) ) ),
"cells", new XVar( "c3", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field",
1, "integrated_edit_field44",
2, "integrated_edit_field45",
3, "integrated_edit_field48" ),
"width", "33%",
"align", "left" ),
"c", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "33%" ),
"c5", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field52" ) ),
"c6", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field1" ) ),
"c9", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "20%" ),
"c12", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field7",
1, "integrated_edit_field8",
2, "integrated_edit_field9",
3, "integrated_edit_field10",
4, "integrated_edit_field11",
5, "integrated_edit_field12",
6, "integrated_edit_field13",
7, "integrated_edit_field14",
8, "integrated_edit_field15" ),
"width", "33%" ),
"c13", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "33%" ),
"c14", new XVar( "model", "c3",
"items", XVar.Array() ),
"c15", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field3",
1, "integrated_edit_field31",
2, "section1" ),
"width", "33%",
"align", "left" ),
"c16", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field51",
1, "integrated_edit_field49" ) ),
"c17", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field50",
1, "integrated_edit_field53" ) ),
"c18", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "33%" ),
"c19", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "33%" ),
"c21", new XVar( "model", "c3",
"items", new XVar( 0, "details_preview4" ) ),
"c20", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field2",
1, "integrated_edit_field30",
2, "section" ),
"width", "33%",
"align", "left" ),
"c8", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field29" ) ),
"c10", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field46",
1, "integrated_edit_field47" ) ),
"c11", new XVar( "model", "c3",
"items", XVar.Array() ),
"c22", new XVar( "model", "c3",
"items", new XVar( 0, "text" ),
"width", "33%",
"align", "left" ),
"c23", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field16",
1, "integrated_edit_field17",
2, "integrated_edit_field18",
3, "integrated_edit_field19",
4, "integrated_edit_field20",
5, "integrated_edit_field21",
6, "integrated_edit_field22",
7, "integrated_edit_field23",
8, "integrated_edit_field24" ),
"width", "33%" ),
"c24", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field4" ) ),
"c25", new XVar( "model", "c3",
"items", new XVar( 0, "text2" ) ),
"c26", new XVar( "model", "c3",
"items", XVar.Array() ),
"c27", new XVar( "model", "c3",
"items", XVar.Array() ),
"c28", new XVar( "model", "c3",
"items", XVar.Array() ),
"c29", new XVar( "model", "c3",
"items", new XVar( 0, "text1" ),
"width", "33%",
"align", "left" ),
"c30", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field25",
1, "integrated_edit_field27",
2, "integrated_edit_field5" ),
"width", "33%",
"align", "left" ),
"c31", new XVar( "model", "c3",
"items", XVar.Array(),
"width", "33%",
"align", "left" ),
"c32", new XVar( "model", "c3",
"items", new XVar( 0, "integrated_edit_field26",
1, "integrated_edit_field28",
2, "integrated_edit_field6" ),
"width", "33%",
"align", "left" ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", true,
"separateLabels", false ),
"section1", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field42",
1, "integrated_edit_field41",
2, "integrated_edit_field43",
3, "integrated_edit_field40",
4, "integrated_edit_field39",
5, "integrated_edit_field38" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ),
"section", new XVar( "modelId", "simple-edit",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "integrated_edit_field36",
1, "integrated_edit_field35",
2, "integrated_edit_field37",
3, "integrated_edit_field34",
4, "integrated_edit_field33",
5, "integrated_edit_field32" ) ) ),
"deferredItems", XVar.Array(),
"columnCount", 1,
"inlineLabels", false,
"separateLabels", false ) ),
"items", new XVar( "view_header", new XVar( "type", "view_header" ),
"view_back_list", new XVar( "type", "view_back_list" ),
"view_close", new XVar( "type", "view_close" ),
"hamburger", new XVar( "type", "hamburger",
"items", new XVar( 0, "view_edit",
1, "view_pdf" ) ),
"view_edit", new XVar( "type", "view_edit" ),
"integrated_edit_field", new XVar( "field", "companyNameA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field6", new XVar( "field", "elevationB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field44", new XVar( "field", "externalReferenceNo",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field45", new XVar( "field", "classStationService",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field48", new XVar( "field", "dateOfApprovedBrief",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field1", new XVar( "field", "callSignA",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field28", new XVar( "field", "latitudeB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field7", new XVar( "field", "makeTypeModelA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "makeTypeModelA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field8", new XVar( "field", "gainA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "gainA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field9", new XVar( "field", "diameterA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "diameterA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field10", new XVar( "field", "beamwidthA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "beamwidthA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field11", new XVar( "field", "polarizationA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "polarizationA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field12", new XVar( "field", "azimuthA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "azimuthA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field42", new XVar( "field", "province_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field13", new XVar( "field", "elevAngleA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "elevAngleA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field14", new XVar( "field", "heightAGLA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "heightAGLA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field15", new XVar( "field", "feederLengthA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "feederLengthA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field3", new XVar( "field", "siteNameB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field31", new XVar( "field", "siteIDB",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "siteIDB",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field26", new XVar( "field", "longtitudeB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field5", new XVar( "field", "elevationA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "elevationA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field27", new XVar( "field", "latitudeA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "latitudeA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field25", new XVar( "field", "longtitudeA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "longtitudeA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"text1", new XVar( "type", "text",
"label", new XVar( "type", 0,
"text", "<h2><u>COORDINATES</u></h2>" ),
"editedByRte", true ),
"text2", new XVar( "type", "text",
"label", new XVar( "text", "<h2><u>ANTENNA SYSTEM</u></h2>",
"type", 0 ),
"editedByRte", true ),
"integrated_edit_field4", new XVar( "field", "callSignB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field24", new XVar( "field", "feederLengthB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field23", new XVar( "field", "heightAGLB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field22", new XVar( "field", "elevAngleB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field21", new XVar( "field", "azimuthB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field20", new XVar( "field", "polarizationB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field19", new XVar( "field", "beamwidthB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field18", new XVar( "field", "diameterB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field17", new XVar( "field", "gainB",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field16", new XVar( "field", "makeTypeModelB",
"type", "integrated_edit_field",
"orientation", 1 ),
"text", new XVar( "type", "text",
"label", new XVar( "text", "<h2><u>STATION LOCATIONS</u></h2>",
"type", 0 ),
"editedByRte", true ),
"integrated_edit_field47", new XVar( "field", "Remarks",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field46", new XVar( "field", "modeOfOperation",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field49", new XVar( "field", "natureOfService",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field40", new XVar( "field", "barangay_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field29", new XVar( "field", "applicationType",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field32", new XVar( "field", "unit_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "unit_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field2", new XVar( "field", "siteNameA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "siteNameA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field33", new XVar( "field", "street_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "street_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"details_preview4", new XVar( "type", "details_preview",
"table", "dbo.radioEquipment",
"items", XVar.Array(),
"popup", false,
"pageId", "list" ),
"integrated_edit_field38", new XVar( "field", "unit_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field39", new XVar( "field", "street_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"section1", new XVar( "type", "section",
"title", new XVar( "type", 0,
"text", "Location Details" ),
"location", "section1",
"bsStyle", "default",
"panelType", 3 ),
"view_pdf", new XVar( "type", "view_pdf",
"targetPages", XVar.Array(),
"splitModes", XVar.Array(),
"scopes", XVar.Array() ),
"integrated_edit_field43", new XVar( "field", "zipcode_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field41", new XVar( "field", "city_b",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field34", new XVar( "field", "barangay_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "barangay_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field37", new XVar( "field", "zipcode_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "zipcode_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field35", new XVar( "field", "city_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "city_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field36", new XVar( "field", "province_a",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "province_a",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"section", new XVar( "type", "section",
"title", new XVar( "type", 0,
"text", "Location Details" ),
"location", "section",
"bsStyle", "default",
"panelType", 3 ),
"integrated_edit_field30", new XVar( "field", "siteIDA",
"type", "integrated_edit_field",
"orientation", 1,
"label", new XVar( "field", "siteIDA",
"table", "dbo.rspdHeader",
"type", 3 ) ),
"integrated_edit_field50", new XVar( "field", "recommendations",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field51", new XVar( "field", "applicationCategory",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field52", new XVar( "field", "address",
"type", "integrated_edit_field",
"orientation", 1 ),
"integrated_edit_field53", new XVar( "field", "view_data",
"type", "integrated_edit_field",
"orientation", 1 ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}