
		// dbo.rspdLineA
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_rspdlinea_import
			{
				static public XVar options()
				{
					return new XVar( "fields", new XVar( "gridFields", new XVar( 0, "ID",
1, "HdrID",
2, "LOC_UNIT_STA_A",
3, "LOC_STREET_STA_A",
4, "LOC_BRGY_STA_A",
5, "CITY/MUNICIPALITY_STA_A",
6, "PROVINCE_STA_A",
7, "ZIPCODE_STA_A",
8, "eDegA",
9, "eMinA",
10, "eSecA",
11, "nDegA",
12, "nMinA",
13, "nSecA",
14, "elevationA",
15, "aMakeTypeModelA",
16, "gainA",
17, "diameterA",
18, "beamwidthA",
19, "polarizationA",
20, "azimuthA",
21, "elevAngleA",
22, "heightAGLA",
23, "feederLengthA",
24, "callSignA" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", XVar.Array(),
"fieldItems", new XVar( "ID", new XVar( 0, "import_field" ),
"HdrID", new XVar( 0, "import_field1" ),
"LOC_UNIT_STA_A", new XVar( 0, "import_field2" ),
"LOC_STREET_STA_A", new XVar( 0, "import_field3" ),
"LOC_BRGY_STA_A", new XVar( 0, "import_field4" ),
"CITY/MUNICIPALITY_STA_A", new XVar( 0, "import_field5" ),
"PROVINCE_STA_A", new XVar( 0, "import_field6" ),
"ZIPCODE_STA_A", new XVar( 0, "import_field7" ),
"eDegA", new XVar( 0, "import_field8" ),
"eMinA", new XVar( 0, "import_field9" ),
"eSecA", new XVar( 0, "import_field10" ),
"nDegA", new XVar( 0, "import_field11" ),
"nMinA", new XVar( 0, "import_field12" ),
"nSecA", new XVar( 0, "import_field13" ),
"elevationA", new XVar( 0, "import_field14" ),
"aMakeTypeModelA", new XVar( 0, "import_field15" ),
"gainA", new XVar( 0, "import_field16" ),
"diameterA", new XVar( 0, "import_field17" ),
"beamwidthA", new XVar( 0, "import_field18" ),
"polarizationA", new XVar( 0, "import_field19" ),
"azimuthA", new XVar( 0, "import_field20" ),
"elevAngleA", new XVar( 0, "import_field21" ),
"heightAGLA", new XVar( 0, "import_field22" ),
"feederLengthA", new XVar( 0, "import_field23" ),
"callSignA", new XVar( 0, "import_field24" ) ) ),
"pageLinks", new XVar( "edit", false,
"add", false,
"view", false,
"print", false ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "supertop", XVar.Array(),
"top", new XVar( 0, "import_header" ),
"grid", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15",
16, "import_field16",
17, "import_field17",
18, "import_field18",
19, "import_field19",
20, "import_field20",
21, "import_field21",
22, "import_field22",
23, "import_field23",
24, "import_field24" ) ),
"formXtTags", new XVar( "supertop", XVar.Array() ),
"itemForms", new XVar( "import_header", "top",
"import_field", "grid",
"import_field1", "grid",
"import_field2", "grid",
"import_field3", "grid",
"import_field4", "grid",
"import_field5", "grid",
"import_field6", "grid",
"import_field7", "grid",
"import_field8", "grid",
"import_field9", "grid",
"import_field10", "grid",
"import_field11", "grid",
"import_field12", "grid",
"import_field13", "grid",
"import_field14", "grid",
"import_field15", "grid",
"import_field16", "grid",
"import_field17", "grid",
"import_field18", "grid",
"import_field19", "grid",
"import_field20", "grid",
"import_field21", "grid",
"import_field22", "grid",
"import_field23", "grid",
"import_field24", "grid" ),
"itemLocations", new XVar(  ),
"itemVisiblity", new XVar(  ) ),
"itemsByType", new XVar( "import_header", new XVar( 0, "import_header" ),
"import_field", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15",
16, "import_field16",
17, "import_field17",
18, "import_field18",
19, "import_field19",
20, "import_field20",
21, "import_field21",
22, "import_field22",
23, "import_field23",
24, "import_field24" ) ),
"cellMaps", new XVar(  ) ),
"loginForm", new XVar( "loginForm", 3 ),
"page", new XVar( "verticalBar", false,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar(  ) ),
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", XVar.Array(),
"calcTotalsFor", 1 ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "import",
"type", "import",
"layoutId", "first",
"disabled", 0,
"default", 0,
"forms", new XVar( "supertop", new XVar( "modelId", "panel-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "import-header",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_header" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "import-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "import_field",
1, "import_field1",
2, "import_field2",
3, "import_field3",
4, "import_field4",
5, "import_field5",
6, "import_field6",
7, "import_field7",
8, "import_field8",
9, "import_field9",
10, "import_field10",
11, "import_field11",
12, "import_field12",
13, "import_field13",
14, "import_field14",
15, "import_field15",
16, "import_field16",
17, "import_field17",
18, "import_field18",
19, "import_field19",
20, "import_field20",
21, "import_field21",
22, "import_field22",
23, "import_field23",
24, "import_field24" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "import_header", new XVar( "type", "import_header" ),
"import_field", new XVar( "field", "ID",
"type", "import_field" ),
"import_field1", new XVar( "field", "HdrID",
"type", "import_field" ),
"import_field2", new XVar( "field", "LOC_UNIT_STA_A",
"type", "import_field" ),
"import_field3", new XVar( "field", "LOC_STREET_STA_A",
"type", "import_field" ),
"import_field4", new XVar( "field", "LOC_BRGY_STA_A",
"type", "import_field" ),
"import_field5", new XVar( "field", "CITY/MUNICIPALITY_STA_A",
"type", "import_field" ),
"import_field6", new XVar( "field", "PROVINCE_STA_A",
"type", "import_field" ),
"import_field7", new XVar( "field", "ZIPCODE_STA_A",
"type", "import_field" ),
"import_field8", new XVar( "field", "eDegA",
"type", "import_field" ),
"import_field9", new XVar( "field", "eMinA",
"type", "import_field" ),
"import_field10", new XVar( "field", "eSecA",
"type", "import_field" ),
"import_field11", new XVar( "field", "nDegA",
"type", "import_field" ),
"import_field12", new XVar( "field", "nMinA",
"type", "import_field" ),
"import_field13", new XVar( "field", "nSecA",
"type", "import_field" ),
"import_field14", new XVar( "field", "elevationA",
"type", "import_field" ),
"import_field15", new XVar( "field", "aMakeTypeModelA",
"type", "import_field" ),
"import_field16", new XVar( "field", "gainA",
"type", "import_field" ),
"import_field17", new XVar( "field", "diameterA",
"type", "import_field" ),
"import_field18", new XVar( "field", "beamwidthA",
"type", "import_field" ),
"import_field19", new XVar( "field", "polarizationA",
"type", "import_field" ),
"import_field20", new XVar( "field", "azimuthA",
"type", "import_field" ),
"import_field21", new XVar( "field", "elevAngleA",
"type", "import_field" ),
"import_field22", new XVar( "field", "heightAGLA",
"type", "import_field" ),
"import_field23", new XVar( "field", "feederLengthA",
"type", "import_field" ),
"import_field24", new XVar( "field", "callSignA",
"type", "import_field" ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}