
		// dbo.rspd_application_received
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_rspd_application_received_list
			{
				static public XVar options()
				{
					return new XVar( "list", new XVar( "inlineAdd", false,
"detailsAdd", false,
"inlineEdit", true,
"spreadsheetMode", false,
"reorderRows", false,
"addToBottom", false,
"delete", true,
"updateSelected", false,
"addInPopup", false,
"editInPopup", false,
"viewInPopup", false,
"clickSort", true,
"sortDropdown", false,
"showHideFields", true,
"reorderFields", false,
"fieldFilter", true ),
"listSearch", new XVar( "alwaysOnPanelFields", XVar.Array(),
"searchPanel", true,
"fixedSearchPanel", false,
"simpleSearchOptions", false,
"searchSaving", false ),
"totals", new XVar( "view_data", new XVar( "totalsType", "" ),
"ID", new XVar( "totalsType", "" ),
"referenceID", new XVar( "totalsType", "" ),
"applicationNo", new XVar( "totalsType", "" ),
"companyNameA", new XVar( "totalsType", "" ),
"userCreate", new XVar( "totalsType", "" ),
"userUpdate", new XVar( "totalsType", "" ),
"dateCreated", new XVar( "totalsType", "" ),
"dateUpdated", new XVar( "totalsType", "" ),
"companyNameB", new XVar( "totalsType", "" ),
"siteNameA", new XVar( "totalsType", "" ),
"siteNameB", new XVar( "totalsType", "" ),
"siteIDA", new XVar( "totalsType", "" ),
"siteIDB", new XVar( "totalsType", "" ),
"coordinateA", new XVar( "totalsType", "" ),
"coordinateB", new XVar( "totalsType", "" ),
"elevationA", new XVar( "totalsType", "" ),
"elevationB", new XVar( "totalsType", "" ),
"makeTypeModelA", new XVar( "totalsType", "" ),
"gainA", new XVar( "totalsType", "" ),
"diameterA", new XVar( "totalsType", "" ),
"beamwidthA", new XVar( "totalsType", "" ),
"polarizationA", new XVar( "totalsType", "" ),
"azimuthA", new XVar( "totalsType", "" ),
"elevAngleA", new XVar( "totalsType", "" ),
"heightAGLA", new XVar( "totalsType", "" ),
"feederLengthA", new XVar( "totalsType", "" ),
"makeTypeModelB", new XVar( "totalsType", "" ),
"gainB", new XVar( "totalsType", "" ),
"diameterB", new XVar( "totalsType", "" ),
"beamwidthB", new XVar( "totalsType", "" ),
"polarizationB", new XVar( "totalsType", "" ),
"azimuthB", new XVar( "totalsType", "" ),
"elevAngleB", new XVar( "totalsType", "" ),
"heightAGLB", new XVar( "totalsType", "" ),
"feederLengthB", new XVar( "totalsType", "" ),
"longtitudeA", new XVar( "totalsType", "" ),
"longtitudeB", new XVar( "totalsType", "" ),
"latitudeA", new XVar( "totalsType", "" ),
"latitudeB", new XVar( "totalsType", "" ),
"callSignA", new XVar( "totalsType", "" ),
"callSignB", new XVar( "totalsType", "" ),
"applicationType", new XVar( "totalsType", "" ),
"unit_a", new XVar( "totalsType", "" ),
"street_a", new XVar( "totalsType", "" ),
"barangay_a", new XVar( "totalsType", "" ),
"city_a", new XVar( "totalsType", "" ),
"province_a", new XVar( "totalsType", "" ),
"zipcode_a", new XVar( "totalsType", "" ),
"unit_b", new XVar( "totalsType", "" ),
"street_b", new XVar( "totalsType", "" ),
"barangay_b", new XVar( "totalsType", "" ),
"city_b", new XVar( "totalsType", "" ),
"province_b", new XVar( "totalsType", "" ),
"zipcode_b", new XVar( "totalsType", "" ),
"map", new XVar( "totalsType", "" ),
"stage", new XVar( "totalsType", "" ),
"stageStatus", new XVar( "totalsType", "" ),
"externalReferenceNo", new XVar( "totalsType", "" ),
"classStationService", new XVar( "totalsType", "" ),
"modeOfOperation", new XVar( "totalsType", "" ),
"Remarks", new XVar( "totalsType", "" ),
"dateOfApprovedBrief", new XVar( "totalsType", "" ),
"recommendations", new XVar( "totalsType", "" ),
"applicationCategory", new XVar( "totalsType", "" ),
"address", new XVar( "totalsType", "" ),
"natureOfService", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "referenceID",
1, "companyNameA",
2, "siteNameA",
3, "siteNameB",
4, "siteIDA",
5, "siteIDB",
6, "view_data",
7, "natureOfService" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", new XVar( 0, "companyNameA",
1, "natureOfService",
2, "view_data",
3, "address",
4, "applicationCategory",
5, "recommendations",
6, "dateOfApprovedBrief",
7, "Remarks",
8, "modeOfOperation",
9, "classStationService",
10, "externalReferenceNo",
11, "stageStatus",
12, "stage",
13, "siteIDB",
14, "siteIDA",
15, "zipcode_b",
16, "province_b",
17, "city_b",
18, "barangay_b",
19, "street_b",
20, "unit_b",
21, "zipcode_a",
22, "province_a",
23, "city_a",
24, "barangay_a",
25, "street_a",
26, "unit_a",
27, "applicationType",
28, "callSignB",
29, "callSignA",
30, "latitudeB",
31, "latitudeA",
32, "longtitudeB",
33, "longtitudeA",
34, "feederLengthB",
35, "heightAGLB",
36, "elevAngleB",
37, "azimuthB",
38, "polarizationB",
39, "beamwidthB",
40, "diameterB",
41, "gainB",
42, "makeTypeModelB",
43, "feederLengthA",
44, "heightAGLA",
45, "elevAngleA",
46, "azimuthA",
47, "polarizationA",
48, "beamwidthA",
49, "diameterA",
50, "gainA",
51, "makeTypeModelA",
52, "elevationB",
53, "elevationA",
54, "siteNameB",
55, "siteNameA" ),
"filterFields", XVar.Array(),
"inlineAddFields", XVar.Array(),
"inlineEditFields", new XVar( 0, "natureOfService" ),
"fieldItems", new XVar( "referenceID", new XVar( 0, "simple_grid_field55",
1, "simple_grid_field56" ),
"companyNameA", new XVar( 0, "simple_grid_field",
1, "simple_grid_field6" ),
"siteNameA", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field7" ),
"siteNameB", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field9" ),
"siteIDA", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field10" ),
"siteIDB", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field11" ),
"view_data", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field12" ),
"natureOfService", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field13" ) ),
"hideEmptyFields", XVar.Array(),
"fieldFilterFields", new XVar( 0, "companyNameA",
1, "siteNameA",
2, "siteNameB",
3, "siteIDA",
4, "siteIDB" ) ),
"pageLinks", new XVar( "edit", true,
"add", true,
"view", true,
"print", true ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "add",
1, "inline_save_all",
2, "inline_cancel_all",
3, "delete",
4, "details_found",
5, "page_size",
6, "print_panel",
7, "columns_control" ),
"below-grid", new XVar( 0, "pagination" ),
"left", new XVar( 0, "logo",
1, "expand_button",
2, "menu",
3, "search_panel" ),
"supertop", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb",
3, "simple_search",
4, "list_options",
5, "loginform_login",
6, "username_button" ),
"top", XVar.Array(),
"grid", new XVar( 0, "simple_grid_field56",
1, "simple_grid_field55",
2, "simple_grid_field6",
3, "simple_grid_field",
4, "simple_grid_field7",
5, "simple_grid_field2",
6, "simple_grid_field9",
7, "simple_grid_field3",
8, "simple_grid_field10",
9, "simple_grid_field1",
10, "simple_grid_field11",
11, "simple_grid_field8",
12, "simple_grid_field12",
13, "simple_grid_field4",
14, "simple_grid_field13",
15, "simple_grid_field5",
16, "details_preview4",
17, "grid_checkbox_head",
18, "grid_checkbox",
19, "grid_edit",
20, "grid_inline_edit",
21, "grid_inline_save",
22, "grid_inline_cancel",
23, "grid_view",
24, "grid_alldetails_link",
25, "grid_details_link4" ) ),
"formXtTags", new XVar( "below-grid", new XVar( 0, "pagination" ),
"top", XVar.Array() ),
"itemForms", new XVar( "add", "above-grid",
"inline_save_all", "above-grid",
"inline_cancel_all", "above-grid",
"delete", "above-grid",
"details_found", "above-grid",
"page_size", "above-grid",
"print_panel", "above-grid",
"columns_control", "above-grid",
"pagination", "below-grid",
"logo", "left",
"expand_button", "left",
"menu", "left",
"search_panel", "left",
"expand_menu_button", "supertop",
"collapse_button", "supertop",
"breadcrumb", "supertop",
"simple_search", "supertop",
"list_options", "supertop",
"loginform_login", "supertop",
"username_button", "supertop",
"simple_grid_field56", "grid",
"simple_grid_field55", "grid",
"simple_grid_field6", "grid",
"simple_grid_field", "grid",
"simple_grid_field7", "grid",
"simple_grid_field2", "grid",
"simple_grid_field9", "grid",
"simple_grid_field3", "grid",
"simple_grid_field10", "grid",
"simple_grid_field1", "grid",
"simple_grid_field11", "grid",
"simple_grid_field8", "grid",
"simple_grid_field12", "grid",
"simple_grid_field4", "grid",
"simple_grid_field13", "grid",
"simple_grid_field5", "grid",
"details_preview4", "grid",
"grid_checkbox_head", "grid",
"grid_checkbox", "grid",
"grid_edit", "grid",
"grid_inline_edit", "grid",
"grid_inline_save", "grid",
"grid_inline_cancel", "grid",
"grid_view", "grid",
"grid_alldetails_link", "grid",
"grid_details_link4", "grid" ),
"itemLocations", new XVar( "simple_grid_field56", new XVar( "location", "grid",
"cellId", "headcell_field" ),
"simple_grid_field55", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field1", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field8", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"simple_grid_field12", new XVar( "location", "grid",
"cellId", "headcell_field6" ),
"simple_grid_field4", new XVar( "location", "grid",
"cellId", "cell_field6" ),
"simple_grid_field13", new XVar( "location", "grid",
"cellId", "headcell_field7" ),
"simple_grid_field5", new XVar( "location", "grid",
"cellId", "cell_field7" ),
"details_preview4", new XVar( "location", "grid",
"cellId", "cell_dpreview" ),
"grid_checkbox_head", new XVar( "location", "grid",
"cellId", "headcell_checkbox" ),
"grid_checkbox", new XVar( "location", "grid",
"cellId", "cell_checkbox" ),
"grid_edit", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_inline_edit", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_inline_save", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_inline_cancel", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_view", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_alldetails_link", new XVar( "location", "grid",
"cellId", "cell_details" ),
"grid_details_link4", new XVar( "location", "grid",
"cellId", "cell_details" ) ),
"itemVisiblity", new XVar( "breadcrumb", 5,
"expand_menu_button", 2,
"print_panel", 5,
"expand_button", 5 ) ),
"itemsByType", new XVar( "page_size", new XVar( 0, "page_size" ),
"details_found", new XVar( 0, "details_found" ),
"breadcrumb", new XVar( 0, "breadcrumb" ),
"logo", new XVar( 0, "logo" ),
"menu", new XVar( 0, "menu" ),
"simple_search", new XVar( 0, "simple_search" ),
"pagination", new XVar( 0, "pagination" ),
"search_panel", new XVar( 0, "search_panel" ),
"list_options", new XVar( 0, "list_options" ),
"show_search_panel", new XVar( 0, "show_search_panel" ),
"hide_search_panel", new XVar( 0, "hide_search_panel" ),
"search_panel_field", new XVar( 0, "search_panel_field",
1, "search_panel_field1",
2, "search_panel_field55",
3, "search_panel_field2",
4, "search_panel_field3",
5, "search_panel_field4",
6, "search_panel_field5",
7, "search_panel_field6",
8, "search_panel_field7",
9, "search_panel_field8",
10, "search_panel_field9",
11, "search_panel_field10",
12, "search_panel_field11",
13, "search_panel_field12",
14, "search_panel_field13",
15, "search_panel_field14",
16, "search_panel_field15",
17, "search_panel_field16",
18, "search_panel_field17",
19, "search_panel_field18",
20, "search_panel_field19",
21, "search_panel_field20",
22, "search_panel_field21",
23, "search_panel_field22",
24, "search_panel_field23",
25, "search_panel_field24",
26, "search_panel_field25",
27, "search_panel_field26",
28, "search_panel_field27",
29, "search_panel_field28",
30, "search_panel_field29",
31, "search_panel_field30",
32, "search_panel_field31",
33, "search_panel_field32",
34, "search_panel_field33",
35, "search_panel_field34",
36, "search_panel_field35",
37, "search_panel_field36",
38, "search_panel_field37",
39, "search_panel_field38",
40, "search_panel_field39",
41, "search_panel_field40",
42, "search_panel_field41",
43, "search_panel_field42",
44, "search_panel_field43",
45, "search_panel_field44",
46, "search_panel_field45",
47, "search_panel_field46",
48, "search_panel_field47",
49, "search_panel_field48",
50, "search_panel_field49",
51, "search_panel_field50",
52, "search_panel_field51",
53, "search_panel_field52",
54, "search_panel_field53",
55, "search_panel_field54" ),
"expand_menu_button", new XVar( 0, "expand_menu_button" ),
"collapse_button", new XVar( 0, "collapse_button" ),
"add", new XVar( 0, "add" ),
"print_panel", new XVar( 0, "print_panel" ),
"print_scope", new XVar( 0, "print_scope" ),
"print_button", new XVar( 0, "print_button" ),
"print_records", new XVar( 0, "print_records" ),
"export", new XVar( 0, "export" ),
"-", new XVar( 0, "-",
1, "-1",
2, "-2",
3, "-3" ),
"export_selected", new XVar( 0, "export_selected" ),
"import", new XVar( 0, "import" ),
"delete", new XVar( 0, "delete" ),
"delete_selected", new XVar( 0, "delete_selected" ),
"advsearch_link", new XVar( 0, "advsearch_link" ),
"print_details", new XVar( 0, "print_details" ),
"username_button", new XVar( 0, "username_button" ),
"adminarea_link", new XVar( 0, "adminarea_link" ),
"loginform_login", new XVar( 0, "loginform_login" ),
"userinfo_link", new XVar( 0, "userinfo_link" ),
"logout_link", new XVar( 0, "logout_link" ),
"columns_control", new XVar( 0, "columns_control" ),
"edit_selected", new XVar( 0, "edit_selected" ),
"inline_save_all", new XVar( 0, "inline_save_all" ),
"inline_cancel_all", new XVar( 0, "inline_cancel_all" ),
"grid_field", new XVar( 0, "simple_grid_field55",
1, "simple_grid_field",
2, "simple_grid_field2",
3, "simple_grid_field3",
4, "simple_grid_field1",
5, "simple_grid_field8",
6, "simple_grid_field4",
7, "simple_grid_field5" ),
"grid_field_label", new XVar( 0, "simple_grid_field56",
1, "simple_grid_field6",
2, "simple_grid_field7",
3, "simple_grid_field9",
4, "simple_grid_field10",
5, "simple_grid_field11",
6, "simple_grid_field12",
7, "simple_grid_field13" ),
"details_preview", new XVar( 0, "details_preview4" ),
"grid_checkbox", new XVar( 0, "grid_checkbox" ),
"grid_checkbox_head", new XVar( 0, "grid_checkbox_head" ),
"grid_edit", new XVar( 0, "grid_edit" ),
"grid_view", new XVar( 0, "grid_view" ),
"grid_alldetails_link", new XVar( 0, "grid_alldetails_link" ),
"grid_inline_edit", new XVar( 0, "grid_inline_edit" ),
"grid_inline_save", new XVar( 0, "grid_inline_save" ),
"grid_inline_cancel", new XVar( 0, "grid_inline_cancel" ),
"grid_details_link", new XVar( 0, "grid_details_link4" ),
"expand_button", new XVar( 0, "expand_button" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox_head" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_details", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "referenceID_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field56" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "companyNameA_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "siteNameA_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "siteNameB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "siteIDA_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "siteIDB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field6", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "view_data_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field12" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field7", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "natureOfService_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field13" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "edit_column",
1, "inlineedit_column",
2, "inline_save",
3, "inline_cancel",
4, "view_column" ),
"items", new XVar( 0, "grid_edit",
1, "grid_inline_edit",
2, "grid_inline_save",
3, "grid_inline_cancel",
4, "grid_view" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_details", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", XVar.Array(),
"items", new XVar( 0, "grid_alldetails_link",
1, "grid_details_link4" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"cell_field", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "referenceID_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field55" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "companyNameA_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "siteNameA_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "siteNameB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "siteIDA_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "siteIDB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field6", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "view_data_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field7", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "natureOfService_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_dpreview", new XVar( "cols", new XVar( 0, 0,
1, 1,
2, 2,
3, 3,
4, 4,
5, 5,
6, 6,
7, 7,
8, 8,
9, 9,
10, 10 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", new XVar( 0, "details_preview4" ),
"fixedAtServer", true,
"fixedAtClient", false ),
"footcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_details", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field6", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field7", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 3 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 11,
"height", 4 ) ) ),
"loginForm", new XVar( "loginForm", 0 ),
"page", new XVar( "verticalBar", true,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar( "details_found", new XVar( "tag", "DISPLAYING",
"type", 2 ) ) ),
"gridType", 0,
"recsPerRow", 1,
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", new XVar( 0, new XVar( "id", "main",
"horizontal", false ) ),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "list",
"breadcrumb", true ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"dataGrid", new XVar( "groupFields", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "list",
"type", "list",
"layoutId", "leftbar",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "list-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "add",
1, "inline_save_all",
2, "inline_cancel_all",
3, "delete" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "details_found",
1, "page_size",
2, "print_panel",
3, "columns_control" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "list-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "pagination" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"left", new XVar( "modelId", "leftbar-menu",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c0" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c0", new XVar( "model", "c0",
"items", new XVar( 0, "logo",
1, "expand_button" ) ),
"c1", new XVar( "model", "c1",
"items", new XVar( 0, "menu",
1, "search_panel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"supertop", new XVar( "modelId", "leftbar-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "simple_search",
1, "list_options",
2, "loginform_login",
3, "username_button" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "list-sidebar-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c2", new XVar( "model", "c2",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_icons" ),
1, new XVar( "cell", "headcell_checkbox" ),
2, new XVar( "cell", "headcell_details" ),
3, new XVar( "cell", "headcell_field" ),
4, new XVar( "cell", "headcell_field1" ),
5, new XVar( "cell", "headcell_field2" ),
6, new XVar( "cell", "headcell_field3" ),
7, new XVar( "cell", "headcell_field4" ),
8, new XVar( "cell", "headcell_field5" ),
9, new XVar( "cell", "headcell_field6" ),
10, new XVar( "cell", "headcell_field7" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_icons" ),
1, new XVar( "cell", "cell_checkbox" ),
2, new XVar( "cell", "cell_details" ),
3, new XVar( "cell", "cell_field" ),
4, new XVar( "cell", "cell_field1" ),
5, new XVar( "cell", "cell_field2" ),
6, new XVar( "cell", "cell_field3" ),
7, new XVar( "cell", "cell_field4" ),
8, new XVar( "cell", "cell_field5" ),
9, new XVar( "cell", "cell_field6" ),
10, new XVar( "cell", "cell_field7" ) ) ),
2, new XVar( "cells", new XVar( 0, new XVar( "cell", "cell_dpreview",
"colspan", 11 ) ),
"section", "body" ),
3, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_icons" ),
1, new XVar( "cell", "footcell_checkbox" ),
2, new XVar( "cell", "footcell_details" ),
3, new XVar( "cell", "footcell_field" ),
4, new XVar( "cell", "footcell_field1" ),
5, new XVar( "cell", "footcell_field2" ),
6, new XVar( "cell", "footcell_field3" ),
7, new XVar( "cell", "footcell_field4" ),
8, new XVar( "cell", "footcell_field5" ),
9, new XVar( "cell", "footcell_field6" ),
10, new XVar( "cell", "footcell_field7" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field56" ),
"field", "referenceID",
"columnName", "field" ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field55" ),
"field", "referenceID",
"columnName", "field" ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "companyNameA",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "companyNameA",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "siteNameA",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "siteNameA",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "siteNameB",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "siteNameB",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "siteIDA",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "siteIDA",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "siteIDB",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "siteIDB",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field6", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field12" ),
"field", "view_data",
"columnName", "field" ),
"cell_field6", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "view_data",
"columnName", "field" ),
"footcell_field6", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field7", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field13" ),
"field", "natureOfService",
"columnName", "field" ),
"cell_field7", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "natureOfService",
"columnName", "field" ),
"footcell_field7", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"cell_dpreview", new XVar( "model", "cell_dpreview",
"items", new XVar( 0, "details_preview4" ) ),
"headcell_checkbox", new XVar( "model", "headcell_checkbox",
"items", new XVar( 0, "grid_checkbox_head" ) ),
"cell_checkbox", new XVar( "model", "cell_checkbox",
"items", new XVar( 0, "grid_checkbox" ) ),
"footcell_checkbox", new XVar( "model", "footcell_checkbox",
"items", XVar.Array() ),
"headcell_icons", new XVar( "model", "headcell_icons",
"items", XVar.Array() ),
"cell_icons", new XVar( "model", "cell_icons",
"items", new XVar( 0, "grid_edit",
1, "grid_inline_edit",
2, "grid_inline_save",
3, "grid_inline_cancel",
4, "grid_view" ) ),
"footcell_icons", new XVar( "model", "footcell_icons",
"items", XVar.Array() ),
"headcell_details", new XVar( "model", "headcell_details",
"items", XVar.Array() ),
"cell_details", new XVar( "model", "cell_details",
"items", new XVar( 0, "grid_alldetails_link",
1, "grid_details_link4" ) ),
"footcell_details", new XVar( "model", "footcell_details",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "page_size", new XVar( "type", "page_size" ),
"details_found", new XVar( "type", "details_found" ),
"breadcrumb", new XVar( "type", "breadcrumb" ),
"logo", new XVar( "type", "logo" ),
"menu", new XVar( "type", "menu" ),
"simple_search", new XVar( "type", "simple_search" ),
"pagination", new XVar( "type", "pagination" ),
"search_panel", new XVar( "type", "search_panel",
"items", new XVar( 0, "search_panel_field",
1, "search_panel_field51",
2, "search_panel_field55",
3, "search_panel_field54",
4, "search_panel_field53",
5, "search_panel_field52",
6, "search_panel_field50",
7, "search_panel_field49",
8, "search_panel_field48",
9, "search_panel_field47",
10, "search_panel_field46",
11, "search_panel_field45",
12, "search_panel_field44",
13, "search_panel_field4",
14, "search_panel_field1",
15, "search_panel_field43",
16, "search_panel_field42",
17, "search_panel_field41",
18, "search_panel_field40",
19, "search_panel_field39",
20, "search_panel_field38",
21, "search_panel_field37",
22, "search_panel_field36",
23, "search_panel_field35",
24, "search_panel_field34",
25, "search_panel_field33",
26, "search_panel_field32",
27, "search_panel_field31",
28, "search_panel_field30",
29, "search_panel_field29",
30, "search_panel_field28",
31, "search_panel_field27",
32, "search_panel_field26",
33, "search_panel_field25",
34, "search_panel_field24",
35, "search_panel_field23",
36, "search_panel_field22",
37, "search_panel_field21",
38, "search_panel_field20",
39, "search_panel_field19",
40, "search_panel_field18",
41, "search_panel_field17",
42, "search_panel_field16",
43, "search_panel_field15",
44, "search_panel_field14",
45, "search_panel_field13",
46, "search_panel_field12",
47, "search_panel_field11",
48, "search_panel_field10",
49, "search_panel_field9",
50, "search_panel_field8",
51, "search_panel_field7",
52, "search_panel_field6",
53, "search_panel_field5",
54, "search_panel_field3",
55, "search_panel_field2" ) ),
"list_options", new XVar( "type", "list_options",
"items", new XVar( 0, "edit_selected",
1, "export_selected",
2, "delete_selected",
3, "-3",
4, "advsearch_link",
5, "show_search_panel",
6, "hide_search_panel",
7, "-1",
8, "export",
9, "-2",
10, "import" ) ),
"show_search_panel", new XVar( "type", "show_search_panel" ),
"hide_search_panel", new XVar( "type", "hide_search_panel" ),
"search_panel_field", new XVar( "field", "companyNameA",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field1", new XVar( "field", "siteIDA",
"type", "search_panel_field",
"alwaysOnPanel", false,
"required", false ),
"expand_menu_button", new XVar( "type", "expand_menu_button" ),
"collapse_button", new XVar( "type", "collapse_button" ),
"add", new XVar( "type", "add",
"popup", false ),
"print_panel", new XVar( "type", "print_panel",
"items", new XVar( 0, "print_scope",
1, "print_details",
2, "print_records",
3, "print_button" ) ),
"print_scope", new XVar( "type", "print_scope" ),
"print_button", new XVar( "type", "print_button" ),
"print_records", new XVar( "type", "print_records" ),
"export", new XVar( "type", "export" ),
"-", new XVar( "type", "-" ),
"export_selected", new XVar( "type", "export_selected" ),
"-1", new XVar( "type", "-" ),
"import", new XVar( "type", "import" ),
"-2", new XVar( "type", "-" ),
"delete", new XVar( "type", "delete" ),
"delete_selected", new XVar( "type", "delete_selected" ),
"advsearch_link", new XVar( "type", "advsearch_link" ),
"-3", new XVar( "type", "-" ),
"search_panel_field55", new XVar( "field", "view_data",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"print_details", new XVar( "type", "print_details",
"tables", new XVar( "dbo.radioEquipment", true ) ),
"search_panel_field2", new XVar( "field", "siteNameA",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field3", new XVar( "field", "siteNameB",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field4", new XVar( "field", "siteIDB",
"type", "search_panel_field",
"alwaysOnPanel", false,
"required", false ),
"search_panel_field5", new XVar( "field", "elevationA",
"type", "search_panel_field",
"required", false ),
"search_panel_field6", new XVar( "field", "elevationB",
"type", "search_panel_field",
"required", false ),
"search_panel_field7", new XVar( "field", "makeTypeModelA",
"type", "search_panel_field",
"required", false ),
"search_panel_field8", new XVar( "field", "gainA",
"type", "search_panel_field",
"required", false ),
"search_panel_field9", new XVar( "field", "diameterA",
"type", "search_panel_field",
"required", false ),
"search_panel_field10", new XVar( "field", "beamwidthA",
"type", "search_panel_field",
"required", false ),
"search_panel_field11", new XVar( "field", "polarizationA",
"type", "search_panel_field",
"required", false ),
"search_panel_field12", new XVar( "field", "azimuthA",
"type", "search_panel_field",
"required", false ),
"search_panel_field13", new XVar( "field", "elevAngleA",
"type", "search_panel_field",
"required", false ),
"search_panel_field14", new XVar( "field", "heightAGLA",
"type", "search_panel_field",
"required", false ),
"search_panel_field15", new XVar( "field", "feederLengthA",
"type", "search_panel_field",
"required", false ),
"search_panel_field16", new XVar( "field", "makeTypeModelB",
"type", "search_panel_field",
"required", false ),
"search_panel_field17", new XVar( "field", "gainB",
"type", "search_panel_field",
"required", false ),
"search_panel_field18", new XVar( "field", "diameterB",
"type", "search_panel_field",
"required", false ),
"search_panel_field19", new XVar( "field", "beamwidthB",
"type", "search_panel_field",
"required", false ),
"search_panel_field20", new XVar( "field", "polarizationB",
"type", "search_panel_field",
"required", false ),
"search_panel_field21", new XVar( "field", "azimuthB",
"type", "search_panel_field",
"required", false ),
"search_panel_field22", new XVar( "field", "elevAngleB",
"type", "search_panel_field",
"required", false ),
"search_panel_field23", new XVar( "field", "heightAGLB",
"type", "search_panel_field",
"required", false ),
"search_panel_field24", new XVar( "field", "feederLengthB",
"type", "search_panel_field",
"required", false ),
"search_panel_field25", new XVar( "field", "longtitudeA",
"type", "search_panel_field",
"required", false ),
"search_panel_field26", new XVar( "field", "longtitudeB",
"type", "search_panel_field",
"required", false ),
"search_panel_field27", new XVar( "field", "latitudeA",
"type", "search_panel_field",
"required", false ),
"search_panel_field28", new XVar( "field", "latitudeB",
"type", "search_panel_field",
"required", false ),
"search_panel_field29", new XVar( "field", "callSignA",
"type", "search_panel_field",
"required", false ),
"search_panel_field30", new XVar( "field", "callSignB",
"type", "search_panel_field",
"required", false ),
"search_panel_field31", new XVar( "field", "applicationType",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field32", new XVar( "field", "unit_a",
"type", "search_panel_field",
"required", false ),
"search_panel_field33", new XVar( "field", "street_a",
"type", "search_panel_field",
"required", false ),
"search_panel_field34", new XVar( "field", "barangay_a",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field35", new XVar( "field", "city_a",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field36", new XVar( "field", "province_a",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field37", new XVar( "field", "zipcode_a",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field38", new XVar( "field", "unit_b",
"type", "search_panel_field",
"required", false ),
"search_panel_field39", new XVar( "field", "street_b",
"type", "search_panel_field",
"required", false ),
"search_panel_field40", new XVar( "field", "barangay_b",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field41", new XVar( "field", "city_b",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field42", new XVar( "field", "province_b",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field43", new XVar( "field", "zipcode_b",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"username_button", new XVar( "type", "username_button",
"items", new XVar( 0, "userinfo_link",
1, "logout_link",
2, "adminarea_link" ) ),
"adminarea_link", new XVar( "type", "adminarea_link" ),
"loginform_login", new XVar( "type", "loginform_login",
"popup", false ),
"userinfo_link", new XVar( "type", "userinfo_link" ),
"logout_link", new XVar( "type", "logout_link" ),
"columns_control", new XVar( "type", "columns_control",
"showHide", true,
"reorder", false ),
"search_panel_field44", new XVar( "field", "stage",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field45", new XVar( "field", "stageStatus",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"edit_selected", new XVar( "type", "edit_selected" ),
"inline_save_all", new XVar( "type", "inline_save_all" ),
"inline_cancel_all", new XVar( "type", "inline_cancel_all" ),
"search_panel_field46", new XVar( "field", "externalReferenceNo",
"type", "search_panel_field",
"required", false ),
"search_panel_field47", new XVar( "field", "classStationService",
"type", "search_panel_field",
"required", false ),
"search_panel_field48", new XVar( "field", "modeOfOperation",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field49", new XVar( "field", "Remarks",
"type", "search_panel_field",
"required", false ),
"search_panel_field50", new XVar( "field", "dateOfApprovedBrief",
"type", "search_panel_field",
"required", false ),
"search_panel_field51", new XVar( "field", "natureOfService",
"type", "search_panel_field",
"required", false ),
"search_panel_field52", new XVar( "field", "recommendations",
"type", "search_panel_field",
"required", false ),
"search_panel_field53", new XVar( "field", "applicationCategory",
"type", "search_panel_field",
"required", false,
"alwaysOnPanel", false ),
"search_panel_field54", new XVar( "field", "address",
"type", "search_panel_field",
"required", false ),
"simple_grid_field55", new XVar( "field", "referenceID",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field56", new XVar( "type", "grid_field_label",
"field", "referenceID" ),
"simple_grid_field", new XVar( "field", "companyNameA",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false,
"showFilter", true,
"clickSort", true ),
"simple_grid_field6", new XVar( "type", "grid_field_label",
"field", "companyNameA",
"clickSort", true,
"showFilter", true ),
"simple_grid_field2", new XVar( "field", "siteNameA",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false,
"showFilter", true,
"clickSort", true ),
"simple_grid_field7", new XVar( "type", "grid_field_label",
"field", "siteNameA",
"clickSort", true,
"showFilter", true ),
"simple_grid_field3", new XVar( "field", "siteNameB",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false,
"showFilter", true,
"clickSort", true ),
"simple_grid_field9", new XVar( "type", "grid_field_label",
"field", "siteNameB",
"clickSort", true,
"showFilter", true ),
"simple_grid_field1", new XVar( "field", "siteIDA",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false,
"showFilter", true,
"clickSort", true ),
"simple_grid_field10", new XVar( "type", "grid_field_label",
"field", "siteIDA",
"clickSort", true,
"showFilter", true ),
"simple_grid_field8", new XVar( "field", "siteIDB",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false,
"showFilter", true,
"clickSort", true ),
"simple_grid_field11", new XVar( "type", "grid_field_label",
"field", "siteIDB",
"clickSort", true,
"showFilter", true ),
"simple_grid_field4", new XVar( "field", "view_data",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field12", new XVar( "type", "grid_field_label",
"field", "view_data" ),
"simple_grid_field5", new XVar( "field", "natureOfService",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", true ),
"simple_grid_field13", new XVar( "type", "grid_field_label",
"field", "natureOfService" ),
"details_preview4", new XVar( "type", "details_preview",
"table", "dbo.radioEquipment",
"items", XVar.Array(),
"popup", false,
"hideEmptyPreview", false,
"proceedLink", true,
"pageId", "list" ),
"grid_checkbox", new XVar( "type", "grid_checkbox" ),
"grid_checkbox_head", new XVar( "type", "grid_checkbox_head" ),
"grid_edit", new XVar( "type", "grid_edit",
"popup", false ),
"grid_view", new XVar( "type", "grid_view",
"popup", false ),
"grid_alldetails_link", new XVar( "type", "grid_alldetails_link" ),
"grid_inline_edit", new XVar( "type", "grid_inline_edit" ),
"grid_inline_save", new XVar( "type", "grid_inline_save" ),
"grid_inline_cancel", new XVar( "type", "grid_inline_cancel" ),
"grid_details_link4", new XVar( "type", "grid_details_link",
"table", "dbo.radioEquipment",
"badge", true,
"showCount", false,
"hideIfNone", false ),
"expand_button", new XVar( "type", "expand_button" ) ),
"dbProps", new XVar(  ),
"spreadsheetGrid", false,
"version", 13,
"reorderRows", false,
"reorderRowsField", "",
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}