
		// dbo.rspdLineB
		using System;
		using System.IO;
		using System.Collections.Generic;
		using System.Linq;
		using System.Text;
		using System.Web;
		using System.Web.Mvc;
		using System.Reflection;
		using runnerDotNet;
		namespace runnerDotNet
		{
			public static partial class Options_rspdlineb_list
			{
				static public XVar options()
				{
					return new XVar( "list", new XVar( "inlineAdd", false,
"detailsAdd", true,
"inlineEdit", false,
"addToBottom", false,
"delete", true,
"updateSelected", false,
"clickSort", true,
"sortDropdown", false,
"showHideFields", false,
"reorderFields", false,
"fieldFilter", false ),
"master", new XVar( "dbo.rspdHeader", new XVar( "preview", true ) ),
"listSearch", new XVar( "alwaysOnPanelFields", XVar.Array(),
"searchPanel", true,
"fixedSearchPanel", false,
"simpleSearchOptions", false,
"searchSaving", false ),
"totals", new XVar( "ID", new XVar( "totalsType", "" ),
"HdrID", new XVar( "totalsType", "" ),
"LOC_UNIT_STA_B", new XVar( "totalsType", "" ),
"LOC_STREET_STA_B", new XVar( "totalsType", "" ),
"LOC_BRGY_STA_B", new XVar( "totalsType", "" ),
"CITY/MUNICIPALITY_STA_B", new XVar( "totalsType", "" ),
"PROVINCE_STA_B", new XVar( "totalsType", "" ),
"ZIPCODE_STA_B", new XVar( "totalsType", "" ),
"eDegB", new XVar( "totalsType", "" ),
"eMinB", new XVar( "totalsType", "" ),
"eSecB", new XVar( "totalsType", "" ),
"nDegB", new XVar( "totalsType", "" ),
"nMinB", new XVar( "totalsType", "" ),
"nSecB", new XVar( "totalsType", "" ),
"elevationB", new XVar( "totalsType", "" ),
"aMakeTypeModelB", new XVar( "totalsType", "" ),
"gainB", new XVar( "totalsType", "" ),
"diameterB", new XVar( "totalsType", "" ),
"beamwidthB", new XVar( "totalsType", "" ),
"polarizationB", new XVar( "totalsType", "" ),
"azimuthB", new XVar( "totalsType", "" ),
"elevAngleB", new XVar( "totalsType", "" ),
"heightAGLB", new XVar( "totalsType", "" ),
"feederLengthB", new XVar( "totalsType", "" ),
"callSignB", new XVar( "totalsType", "" ) ),
"fields", new XVar( "gridFields", new XVar( 0, "ID",
1, "HdrID",
2, "LOC_UNIT_STA_B",
3, "LOC_STREET_STA_B",
4, "LOC_BRGY_STA_B",
5, "CITY/MUNICIPALITY_STA_B",
6, "PROVINCE_STA_B",
7, "ZIPCODE_STA_B",
8, "eDegB",
9, "eMinB",
10, "eSecB",
11, "nDegB",
12, "nMinB",
13, "nSecB",
14, "elevationB",
15, "aMakeTypeModelB",
16, "gainB",
17, "diameterB",
18, "beamwidthB",
19, "polarizationB",
20, "azimuthB",
21, "elevAngleB",
22, "heightAGLB",
23, "feederLengthB",
24, "callSignB" ),
"searchRequiredFields", XVar.Array(),
"searchPanelFields", new XVar( 0, "CITY/MUNICIPALITY_STA_B",
1, "polarizationB",
2, "nSecB",
3, "nMinB",
4, "nDegB",
5, "heightAGLB",
6, "gainB",
7, "feederLengthB",
8, "elevationB",
9, "elevAngleB",
10, "eSecB",
11, "eMinB",
12, "eDegB",
13, "diameterB",
14, "callSignB",
15, "beamwidthB",
16, "azimuthB",
17, "aMakeTypeModelB",
18, "ZIPCODE_STA_B",
19, "PROVINCE_STA_B",
20, "LOC_UNIT_STA_B",
21, "LOC_STREET_STA_B",
22, "LOC_BRGY_STA_B",
23, "ID",
24, "HdrID" ),
"filterFields", XVar.Array(),
"inlineAddFields", new XVar( 0, "HdrID",
1, "LOC_UNIT_STA_B",
2, "LOC_STREET_STA_B",
3, "LOC_BRGY_STA_B",
4, "CITY/MUNICIPALITY_STA_B",
5, "PROVINCE_STA_B",
6, "ZIPCODE_STA_B",
7, "eDegB",
8, "eMinB",
9, "eSecB",
10, "nDegB",
11, "nMinB",
12, "nSecB",
13, "elevationB",
14, "aMakeTypeModelB",
15, "gainB",
16, "diameterB",
17, "beamwidthB",
18, "polarizationB",
19, "azimuthB",
20, "elevAngleB",
21, "heightAGLB",
22, "feederLengthB",
23, "callSignB" ),
"inlineEditFields", new XVar( 0, "HdrID",
1, "LOC_UNIT_STA_B",
2, "LOC_STREET_STA_B",
3, "LOC_BRGY_STA_B",
4, "CITY/MUNICIPALITY_STA_B",
5, "PROVINCE_STA_B",
6, "ZIPCODE_STA_B",
7, "eDegB",
8, "eMinB",
9, "eSecB",
10, "nDegB",
11, "nMinB",
12, "nSecB",
13, "elevationB",
14, "aMakeTypeModelB",
15, "gainB",
16, "diameterB",
17, "beamwidthB",
18, "polarizationB",
19, "azimuthB",
20, "elevAngleB",
21, "heightAGLB",
22, "feederLengthB",
23, "callSignB" ),
"fieldItems", new XVar( "ID", new XVar( 0, "simple_grid_field",
1, "simple_grid_field25" ),
"HdrID", new XVar( 0, "simple_grid_field1",
1, "simple_grid_field26" ),
"LOC_UNIT_STA_B", new XVar( 0, "simple_grid_field2",
1, "simple_grid_field27" ),
"LOC_STREET_STA_B", new XVar( 0, "simple_grid_field3",
1, "simple_grid_field28" ),
"LOC_BRGY_STA_B", new XVar( 0, "simple_grid_field4",
1, "simple_grid_field29" ),
"CITY/MUNICIPALITY_STA_B", new XVar( 0, "simple_grid_field5",
1, "simple_grid_field30" ),
"PROVINCE_STA_B", new XVar( 0, "simple_grid_field6",
1, "simple_grid_field31" ),
"ZIPCODE_STA_B", new XVar( 0, "simple_grid_field7",
1, "simple_grid_field32" ),
"eDegB", new XVar( 0, "simple_grid_field8",
1, "simple_grid_field33" ),
"eMinB", new XVar( 0, "simple_grid_field9",
1, "simple_grid_field34" ),
"eSecB", new XVar( 0, "simple_grid_field10",
1, "simple_grid_field35" ),
"nDegB", new XVar( 0, "simple_grid_field11",
1, "simple_grid_field36" ),
"nMinB", new XVar( 0, "simple_grid_field12",
1, "simple_grid_field37" ),
"nSecB", new XVar( 0, "simple_grid_field13",
1, "simple_grid_field38" ),
"elevationB", new XVar( 0, "simple_grid_field14",
1, "simple_grid_field39" ),
"aMakeTypeModelB", new XVar( 0, "simple_grid_field15",
1, "simple_grid_field40" ),
"gainB", new XVar( 0, "simple_grid_field16",
1, "simple_grid_field41" ),
"diameterB", new XVar( 0, "simple_grid_field17",
1, "simple_grid_field42" ),
"beamwidthB", new XVar( 0, "simple_grid_field18",
1, "simple_grid_field43" ),
"polarizationB", new XVar( 0, "simple_grid_field19",
1, "simple_grid_field44" ),
"azimuthB", new XVar( 0, "simple_grid_field20",
1, "simple_grid_field45" ),
"elevAngleB", new XVar( 0, "simple_grid_field21",
1, "simple_grid_field46" ),
"heightAGLB", new XVar( 0, "simple_grid_field22",
1, "simple_grid_field47" ),
"feederLengthB", new XVar( 0, "simple_grid_field23",
1, "simple_grid_field48" ),
"callSignB", new XVar( 0, "simple_grid_field24",
1, "simple_grid_field49" ) ),
"hideEmptyFields", XVar.Array(),
"fieldFilterFields", XVar.Array() ),
"pageLinks", new XVar( "edit", true,
"add", true,
"view", true,
"print", true ),
"layoutHelper", new XVar( "formItems", new XVar( "formItems", new XVar( "above-grid", new XVar( 0, "add",
1, "inline_add",
2, "delete",
3, "details_found",
4, "page_size",
5, "print_panel" ),
"below-grid", new XVar( 0, "pagination" ),
"left", new XVar( 0, "logo",
1, "expand_button",
2, "menu",
3, "search_panel" ),
"supertop", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb",
3, "simple_search",
4, "list_options",
5, "loginform_login",
6, "username_button" ),
"top", new XVar( 0, "master_info" ),
"grid", new XVar( 0, "simple_grid_field25",
1, "simple_grid_field",
2, "simple_grid_field26",
3, "simple_grid_field1",
4, "simple_grid_field27",
5, "simple_grid_field2",
6, "simple_grid_field28",
7, "simple_grid_field3",
8, "simple_grid_field29",
9, "simple_grid_field4",
10, "simple_grid_field30",
11, "simple_grid_field5",
12, "simple_grid_field31",
13, "simple_grid_field6",
14, "simple_grid_field32",
15, "simple_grid_field7",
16, "simple_grid_field33",
17, "simple_grid_field8",
18, "simple_grid_field34",
19, "simple_grid_field9",
20, "simple_grid_field35",
21, "simple_grid_field10",
22, "simple_grid_field36",
23, "simple_grid_field11",
24, "simple_grid_field37",
25, "simple_grid_field12",
26, "simple_grid_field38",
27, "simple_grid_field13",
28, "simple_grid_field39",
29, "simple_grid_field14",
30, "simple_grid_field40",
31, "simple_grid_field15",
32, "simple_grid_field41",
33, "simple_grid_field16",
34, "simple_grid_field42",
35, "simple_grid_field17",
36, "simple_grid_field43",
37, "simple_grid_field18",
38, "simple_grid_field44",
39, "simple_grid_field19",
40, "simple_grid_field45",
41, "simple_grid_field20",
42, "simple_grid_field46",
43, "simple_grid_field21",
44, "simple_grid_field47",
45, "simple_grid_field22",
46, "simple_grid_field48",
47, "simple_grid_field23",
48, "simple_grid_field49",
49, "simple_grid_field24",
50, "grid_checkbox_head",
51, "grid_checkbox",
52, "grid_edit",
53, "grid_inline_cancel",
54, "grid_view" ) ),
"formXtTags", new XVar( "above-grid", new XVar( 0, "add_link",
1, "inlineadd_link",
2, "deleteselected_link",
3, "details_found",
4, "recsPerPage",
5, "print_friendly" ),
"below-grid", new XVar( 0, "pagination" ),
"top", new XVar( 0, "mastertable_block" ) ),
"itemForms", new XVar( "add", "above-grid",
"inline_add", "above-grid",
"delete", "above-grid",
"details_found", "above-grid",
"page_size", "above-grid",
"print_panel", "above-grid",
"pagination", "below-grid",
"logo", "left",
"expand_button", "left",
"menu", "left",
"search_panel", "left",
"expand_menu_button", "supertop",
"collapse_button", "supertop",
"breadcrumb", "supertop",
"simple_search", "supertop",
"list_options", "supertop",
"loginform_login", "supertop",
"username_button", "supertop",
"master_info", "top",
"simple_grid_field25", "grid",
"simple_grid_field", "grid",
"simple_grid_field26", "grid",
"simple_grid_field1", "grid",
"simple_grid_field27", "grid",
"simple_grid_field2", "grid",
"simple_grid_field28", "grid",
"simple_grid_field3", "grid",
"simple_grid_field29", "grid",
"simple_grid_field4", "grid",
"simple_grid_field30", "grid",
"simple_grid_field5", "grid",
"simple_grid_field31", "grid",
"simple_grid_field6", "grid",
"simple_grid_field32", "grid",
"simple_grid_field7", "grid",
"simple_grid_field33", "grid",
"simple_grid_field8", "grid",
"simple_grid_field34", "grid",
"simple_grid_field9", "grid",
"simple_grid_field35", "grid",
"simple_grid_field10", "grid",
"simple_grid_field36", "grid",
"simple_grid_field11", "grid",
"simple_grid_field37", "grid",
"simple_grid_field12", "grid",
"simple_grid_field38", "grid",
"simple_grid_field13", "grid",
"simple_grid_field39", "grid",
"simple_grid_field14", "grid",
"simple_grid_field40", "grid",
"simple_grid_field15", "grid",
"simple_grid_field41", "grid",
"simple_grid_field16", "grid",
"simple_grid_field42", "grid",
"simple_grid_field17", "grid",
"simple_grid_field43", "grid",
"simple_grid_field18", "grid",
"simple_grid_field44", "grid",
"simple_grid_field19", "grid",
"simple_grid_field45", "grid",
"simple_grid_field20", "grid",
"simple_grid_field46", "grid",
"simple_grid_field21", "grid",
"simple_grid_field47", "grid",
"simple_grid_field22", "grid",
"simple_grid_field48", "grid",
"simple_grid_field23", "grid",
"simple_grid_field49", "grid",
"simple_grid_field24", "grid",
"grid_checkbox_head", "grid",
"grid_checkbox", "grid",
"grid_edit", "grid",
"grid_inline_cancel", "grid",
"grid_view", "grid" ),
"itemLocations", new XVar( "simple_grid_field25", new XVar( "location", "grid",
"cellId", "headcell_field" ),
"simple_grid_field", new XVar( "location", "grid",
"cellId", "cell_field" ),
"simple_grid_field26", new XVar( "location", "grid",
"cellId", "headcell_field1" ),
"simple_grid_field1", new XVar( "location", "grid",
"cellId", "cell_field1" ),
"simple_grid_field27", new XVar( "location", "grid",
"cellId", "headcell_field2" ),
"simple_grid_field2", new XVar( "location", "grid",
"cellId", "cell_field2" ),
"simple_grid_field28", new XVar( "location", "grid",
"cellId", "headcell_field3" ),
"simple_grid_field3", new XVar( "location", "grid",
"cellId", "cell_field3" ),
"simple_grid_field29", new XVar( "location", "grid",
"cellId", "headcell_field4" ),
"simple_grid_field4", new XVar( "location", "grid",
"cellId", "cell_field4" ),
"simple_grid_field30", new XVar( "location", "grid",
"cellId", "headcell_field5" ),
"simple_grid_field5", new XVar( "location", "grid",
"cellId", "cell_field5" ),
"simple_grid_field31", new XVar( "location", "grid",
"cellId", "headcell_field6" ),
"simple_grid_field6", new XVar( "location", "grid",
"cellId", "cell_field6" ),
"simple_grid_field32", new XVar( "location", "grid",
"cellId", "headcell_field7" ),
"simple_grid_field7", new XVar( "location", "grid",
"cellId", "cell_field7" ),
"simple_grid_field33", new XVar( "location", "grid",
"cellId", "headcell_field8" ),
"simple_grid_field8", new XVar( "location", "grid",
"cellId", "cell_field8" ),
"simple_grid_field34", new XVar( "location", "grid",
"cellId", "headcell_field9" ),
"simple_grid_field9", new XVar( "location", "grid",
"cellId", "cell_field9" ),
"simple_grid_field35", new XVar( "location", "grid",
"cellId", "headcell_field10" ),
"simple_grid_field10", new XVar( "location", "grid",
"cellId", "cell_field10" ),
"simple_grid_field36", new XVar( "location", "grid",
"cellId", "headcell_field11" ),
"simple_grid_field11", new XVar( "location", "grid",
"cellId", "cell_field11" ),
"simple_grid_field37", new XVar( "location", "grid",
"cellId", "headcell_field12" ),
"simple_grid_field12", new XVar( "location", "grid",
"cellId", "cell_field12" ),
"simple_grid_field38", new XVar( "location", "grid",
"cellId", "headcell_field13" ),
"simple_grid_field13", new XVar( "location", "grid",
"cellId", "cell_field13" ),
"simple_grid_field39", new XVar( "location", "grid",
"cellId", "headcell_field14" ),
"simple_grid_field14", new XVar( "location", "grid",
"cellId", "cell_field14" ),
"simple_grid_field40", new XVar( "location", "grid",
"cellId", "headcell_field15" ),
"simple_grid_field15", new XVar( "location", "grid",
"cellId", "cell_field15" ),
"simple_grid_field41", new XVar( "location", "grid",
"cellId", "headcell_field16" ),
"simple_grid_field16", new XVar( "location", "grid",
"cellId", "cell_field16" ),
"simple_grid_field42", new XVar( "location", "grid",
"cellId", "headcell_field17" ),
"simple_grid_field17", new XVar( "location", "grid",
"cellId", "cell_field17" ),
"simple_grid_field43", new XVar( "location", "grid",
"cellId", "headcell_field18" ),
"simple_grid_field18", new XVar( "location", "grid",
"cellId", "cell_field18" ),
"simple_grid_field44", new XVar( "location", "grid",
"cellId", "headcell_field19" ),
"simple_grid_field19", new XVar( "location", "grid",
"cellId", "cell_field19" ),
"simple_grid_field45", new XVar( "location", "grid",
"cellId", "headcell_field20" ),
"simple_grid_field20", new XVar( "location", "grid",
"cellId", "cell_field20" ),
"simple_grid_field46", new XVar( "location", "grid",
"cellId", "headcell_field21" ),
"simple_grid_field21", new XVar( "location", "grid",
"cellId", "cell_field21" ),
"simple_grid_field47", new XVar( "location", "grid",
"cellId", "headcell_field22" ),
"simple_grid_field22", new XVar( "location", "grid",
"cellId", "cell_field22" ),
"simple_grid_field48", new XVar( "location", "grid",
"cellId", "headcell_field23" ),
"simple_grid_field23", new XVar( "location", "grid",
"cellId", "cell_field23" ),
"simple_grid_field49", new XVar( "location", "grid",
"cellId", "headcell_field24" ),
"simple_grid_field24", new XVar( "location", "grid",
"cellId", "cell_field24" ),
"grid_checkbox_head", new XVar( "location", "grid",
"cellId", "headcell_checkbox" ),
"grid_checkbox", new XVar( "location", "grid",
"cellId", "cell_checkbox" ),
"grid_edit", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_inline_cancel", new XVar( "location", "grid",
"cellId", "cell_icons" ),
"grid_view", new XVar( "location", "grid",
"cellId", "cell_icons" ) ),
"itemVisiblity", new XVar( "breadcrumb", 5,
"expand_menu_button", 2,
"print_panel", 5,
"expand_button", 5 ) ),
"itemsByType", new XVar( "page_size", new XVar( 0, "page_size" ),
"details_found", new XVar( 0, "details_found" ),
"breadcrumb", new XVar( 0, "breadcrumb" ),
"logo", new XVar( 0, "logo" ),
"menu", new XVar( 0, "menu" ),
"simple_search", new XVar( 0, "simple_search" ),
"pagination", new XVar( 0, "pagination" ),
"search_panel", new XVar( 0, "search_panel" ),
"list_options", new XVar( 0, "list_options" ),
"show_search_panel", new XVar( 0, "show_search_panel" ),
"hide_search_panel", new XVar( 0, "hide_search_panel" ),
"search_panel_field", new XVar( 0, "search_panel_field",
1, "search_panel_field1",
2, "search_panel_field2",
3, "search_panel_field3",
4, "search_panel_field4",
5, "search_panel_field5",
6, "search_panel_field6",
7, "search_panel_field7",
8, "search_panel_field8",
9, "search_panel_field9",
10, "search_panel_field10",
11, "search_panel_field11",
12, "search_panel_field12",
13, "search_panel_field13",
14, "search_panel_field14",
15, "search_panel_field15",
16, "search_panel_field16",
17, "search_panel_field17",
18, "search_panel_field18",
19, "search_panel_field19",
20, "search_panel_field20",
21, "search_panel_field21",
22, "search_panel_field22",
23, "search_panel_field23",
24, "search_panel_field24" ),
"username_button", new XVar( 0, "username_button" ),
"loginform_login", new XVar( 0, "loginform_login" ),
"userinfo_link", new XVar( 0, "userinfo_link" ),
"logout_link", new XVar( 0, "logout_link" ),
"adminarea_link", new XVar( 0, "adminarea_link" ),
"expand_menu_button", new XVar( 0, "expand_menu_button" ),
"collapse_button", new XVar( 0, "collapse_button" ),
"add", new XVar( 0, "add" ),
"print_panel", new XVar( 0, "print_panel" ),
"print_scope", new XVar( 0, "print_scope" ),
"print_button", new XVar( 0, "print_button" ),
"print_records", new XVar( 0, "print_records" ),
"export", new XVar( 0, "export" ),
"-", new XVar( 0, "-",
1, "-1",
2, "-2",
3, "-3" ),
"export_selected", new XVar( 0, "export_selected" ),
"import", new XVar( 0, "import" ),
"delete", new XVar( 0, "delete" ),
"delete_selected", new XVar( 0, "delete_selected" ),
"advsearch_link", new XVar( 0, "advsearch_link" ),
"master_info", new XVar( 0, "master_info" ),
"grid_field", new XVar( 0, "simple_grid_field",
1, "simple_grid_field1",
2, "simple_grid_field2",
3, "simple_grid_field3",
4, "simple_grid_field4",
5, "simple_grid_field5",
6, "simple_grid_field6",
7, "simple_grid_field7",
8, "simple_grid_field8",
9, "simple_grid_field9",
10, "simple_grid_field10",
11, "simple_grid_field11",
12, "simple_grid_field12",
13, "simple_grid_field13",
14, "simple_grid_field14",
15, "simple_grid_field15",
16, "simple_grid_field16",
17, "simple_grid_field17",
18, "simple_grid_field18",
19, "simple_grid_field19",
20, "simple_grid_field20",
21, "simple_grid_field21",
22, "simple_grid_field22",
23, "simple_grid_field23",
24, "simple_grid_field24" ),
"grid_field_label", new XVar( 0, "simple_grid_field25",
1, "simple_grid_field26",
2, "simple_grid_field27",
3, "simple_grid_field28",
4, "simple_grid_field29",
5, "simple_grid_field30",
6, "simple_grid_field31",
7, "simple_grid_field32",
8, "simple_grid_field33",
9, "simple_grid_field34",
10, "simple_grid_field35",
11, "simple_grid_field36",
12, "simple_grid_field37",
13, "simple_grid_field38",
14, "simple_grid_field39",
15, "simple_grid_field40",
16, "simple_grid_field41",
17, "simple_grid_field42",
18, "simple_grid_field43",
19, "simple_grid_field44",
20, "simple_grid_field45",
21, "simple_grid_field46",
22, "simple_grid_field47",
23, "simple_grid_field48",
24, "simple_grid_field49" ),
"grid_checkbox", new XVar( 0, "grid_checkbox" ),
"grid_checkbox_head", new XVar( 0, "grid_checkbox_head" ),
"grid_edit", new XVar( 0, "grid_edit" ),
"grid_view", new XVar( 0, "grid_view" ),
"expand_button", new XVar( 0, "expand_button" ),
"inline_add", new XVar( 0, "inline_add" ),
"grid_inline_cancel", new XVar( 0, "grid_inline_cancel" ) ),
"cellMaps", new XVar( "grid", new XVar( "cells", new XVar( "headcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 0 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox_head" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "ID_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field25" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field1", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "HdrID_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field26" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field2", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "LOC_UNIT_STA_B_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field27" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field3", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "LOC_STREET_STA_B_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field28" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field4", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "LOC_BRGY_STA_B_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field29" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field5", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "CITY_MUNICIPALITY_STA_B_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field30" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field6", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "PROVINCE_STA_B_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field31" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field7", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "ZIPCODE_STA_B_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field32" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field8", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "eDegB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field33" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field9", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "eMinB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field34" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field10", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "eSecB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field35" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field11", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "nDegB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field36" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field12", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "nMinB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field37" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field13", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "nSecB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field38" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field14", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "elevationB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field39" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field15", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "aMakeTypeModelB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field40" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field16", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "gainB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field41" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field17", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "diameterB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field42" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field18", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "beamwidthB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field43" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field19", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "polarizationB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field44" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field20", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "azimuthB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field45" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field21", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "elevAngleB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field46" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field22", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "heightAGLB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field47" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field23", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "feederLengthB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field48" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"headcell_field24", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 0 ),
"tags", new XVar( 0, "callSignB_fieldheadercolumn" ),
"items", new XVar( 0, "simple_grid_field49" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "edit_column",
1, "inline_cancel",
2, "view_column" ),
"items", new XVar( 0, "grid_edit",
1, "grid_inline_cancel",
2, "grid_view" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "checkbox_column" ),
"items", new XVar( 0, "grid_checkbox" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "ID_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field1", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "HdrID_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field1" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field2", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "LOC_UNIT_STA_B_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field2" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field3", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "LOC_STREET_STA_B_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field3" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field4", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "LOC_BRGY_STA_B_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field4" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field5", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "CITY_MUNICIPALITY_STA_B_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field5" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field6", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "PROVINCE_STA_B_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field6" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field7", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "ZIPCODE_STA_B_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field7" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field8", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "eDegB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field8" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field9", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "eMinB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field9" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field10", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "eSecB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field10" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field11", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "nDegB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field11" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field12", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "nMinB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field12" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field13", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "nSecB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field13" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field14", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "elevationB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field14" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field15", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "aMakeTypeModelB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field15" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field16", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "gainB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field16" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field17", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "diameterB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field17" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field18", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "beamwidthB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field18" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field19", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "polarizationB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field19" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field20", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "azimuthB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field20" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field21", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "elevAngleB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field21" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field22", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "heightAGLB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field22" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field23", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "feederLengthB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field23" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"cell_field24", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 1 ),
"tags", new XVar( 0, "callSignB_fieldcolumn" ),
"items", new XVar( 0, "simple_grid_field24" ),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_icons", new XVar( "cols", new XVar( 0, 0 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_checkbox", new XVar( "cols", new XVar( 0, 1 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field", new XVar( "cols", new XVar( 0, 2 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field1", new XVar( "cols", new XVar( 0, 3 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field2", new XVar( "cols", new XVar( 0, 4 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field3", new XVar( "cols", new XVar( 0, 5 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field4", new XVar( "cols", new XVar( 0, 6 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field5", new XVar( "cols", new XVar( 0, 7 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field6", new XVar( "cols", new XVar( 0, 8 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field7", new XVar( "cols", new XVar( 0, 9 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field8", new XVar( "cols", new XVar( 0, 10 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field9", new XVar( "cols", new XVar( 0, 11 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field10", new XVar( "cols", new XVar( 0, 12 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field11", new XVar( "cols", new XVar( 0, 13 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field12", new XVar( "cols", new XVar( 0, 14 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field13", new XVar( "cols", new XVar( 0, 15 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field14", new XVar( "cols", new XVar( 0, 16 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field15", new XVar( "cols", new XVar( 0, 17 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field16", new XVar( "cols", new XVar( 0, 18 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field17", new XVar( "cols", new XVar( 0, 19 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field18", new XVar( "cols", new XVar( 0, 20 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field19", new XVar( "cols", new XVar( 0, 21 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field20", new XVar( "cols", new XVar( 0, 22 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field21", new XVar( "cols", new XVar( 0, 23 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field22", new XVar( "cols", new XVar( 0, 24 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field23", new XVar( "cols", new XVar( 0, 25 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ),
"footcell_field24", new XVar( "cols", new XVar( 0, 26 ),
"rows", new XVar( 0, 2 ),
"tags", XVar.Array(),
"items", XVar.Array(),
"fixedAtServer", false,
"fixedAtClient", false ) ),
"width", 27,
"height", 3 ) ) ),
"loginForm", new XVar( "loginForm", 0 ),
"page", new XVar( "verticalBar", true,
"labeledButtons", new XVar( "update_records", new XVar(  ),
"print_pages", new XVar(  ),
"register_activate_message", new XVar(  ),
"details_found", new XVar( "details_found", new XVar( "tag", "DISPLAYING",
"type", 2 ) ) ),
"gridType", 0,
"recsPerRow", 1,
"hasCustomButtons", false,
"customButtons", XVar.Array(),
"hasNotifications", false,
"menus", new XVar( 0, new XVar( "id", "main",
"horizontal", false ) ),
"calcTotalsFor", 1 ),
"misc", new XVar( "type", "list",
"breadcrumb", true ),
"events", new XVar( "maps", XVar.Array(),
"mapsData", new XVar(  ),
"buttons", XVar.Array() ),
"dataGrid", new XVar( "groupFields", XVar.Array() ) );
				}
				static public XVar page()
				{
					return new XVar( "id", "list",
"type", "list",
"layoutId", "leftbar",
"disabled", 0,
"default", 0,
"forms", new XVar( "above-grid", new XVar( "modelId", "list-above-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "add",
1, "inline_add",
2, "delete" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "details_found",
1, "page_size",
2, "print_panel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"below-grid", new XVar( "modelId", "list-below-grid",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "pagination" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"left", new XVar( "modelId", "leftbar-menu",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c0" ) ),
"section", "" ),
1, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ) ),
"section", "" ) ),
"cells", new XVar( "c0", new XVar( "model", "c0",
"items", new XVar( 0, "logo",
1, "expand_button" ) ),
"c1", new XVar( "model", "c1",
"items", new XVar( 0, "menu",
1, "search_panel" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"supertop", new XVar( "modelId", "leftbar-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c1" ),
1, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c1", new XVar( "model", "c1",
"items", new XVar( 0, "expand_menu_button",
1, "collapse_button",
2, "breadcrumb" ) ),
"c2", new XVar( "model", "c2",
"items", new XVar( 0, "simple_search",
1, "list_options",
2, "loginform_login",
3, "username_button" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"top", new XVar( "modelId", "list-sidebar-top",
"grid", new XVar( 0, new XVar( "cells", new XVar( 0, new XVar( "cell", "c2" ) ),
"section", "" ) ),
"cells", new XVar( "c2", new XVar( "model", "c2",
"items", new XVar( 0, "master_info" ) ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ),
"grid", new XVar( "modelId", "horizontal-grid",
"grid", new XVar( 0, new XVar( "section", "head",
"cells", new XVar( 0, new XVar( "cell", "headcell_icons" ),
1, new XVar( "cell", "headcell_checkbox" ),
2, new XVar( "cell", "headcell_field" ),
3, new XVar( "cell", "headcell_field1" ),
4, new XVar( "cell", "headcell_field2" ),
5, new XVar( "cell", "headcell_field3" ),
6, new XVar( "cell", "headcell_field4" ),
7, new XVar( "cell", "headcell_field5" ),
8, new XVar( "cell", "headcell_field6" ),
9, new XVar( "cell", "headcell_field7" ),
10, new XVar( "cell", "headcell_field8" ),
11, new XVar( "cell", "headcell_field9" ),
12, new XVar( "cell", "headcell_field10" ),
13, new XVar( "cell", "headcell_field11" ),
14, new XVar( "cell", "headcell_field12" ),
15, new XVar( "cell", "headcell_field13" ),
16, new XVar( "cell", "headcell_field14" ),
17, new XVar( "cell", "headcell_field15" ),
18, new XVar( "cell", "headcell_field16" ),
19, new XVar( "cell", "headcell_field17" ),
20, new XVar( "cell", "headcell_field18" ),
21, new XVar( "cell", "headcell_field19" ),
22, new XVar( "cell", "headcell_field20" ),
23, new XVar( "cell", "headcell_field21" ),
24, new XVar( "cell", "headcell_field22" ),
25, new XVar( "cell", "headcell_field23" ),
26, new XVar( "cell", "headcell_field24" ) ) ),
1, new XVar( "section", "body",
"cells", new XVar( 0, new XVar( "cell", "cell_icons" ),
1, new XVar( "cell", "cell_checkbox" ),
2, new XVar( "cell", "cell_field" ),
3, new XVar( "cell", "cell_field1" ),
4, new XVar( "cell", "cell_field2" ),
5, new XVar( "cell", "cell_field3" ),
6, new XVar( "cell", "cell_field4" ),
7, new XVar( "cell", "cell_field5" ),
8, new XVar( "cell", "cell_field6" ),
9, new XVar( "cell", "cell_field7" ),
10, new XVar( "cell", "cell_field8" ),
11, new XVar( "cell", "cell_field9" ),
12, new XVar( "cell", "cell_field10" ),
13, new XVar( "cell", "cell_field11" ),
14, new XVar( "cell", "cell_field12" ),
15, new XVar( "cell", "cell_field13" ),
16, new XVar( "cell", "cell_field14" ),
17, new XVar( "cell", "cell_field15" ),
18, new XVar( "cell", "cell_field16" ),
19, new XVar( "cell", "cell_field17" ),
20, new XVar( "cell", "cell_field18" ),
21, new XVar( "cell", "cell_field19" ),
22, new XVar( "cell", "cell_field20" ),
23, new XVar( "cell", "cell_field21" ),
24, new XVar( "cell", "cell_field22" ),
25, new XVar( "cell", "cell_field23" ),
26, new XVar( "cell", "cell_field24" ) ) ),
2, new XVar( "section", "foot",
"cells", new XVar( 0, new XVar( "cell", "footcell_icons" ),
1, new XVar( "cell", "footcell_checkbox" ),
2, new XVar( "cell", "footcell_field" ),
3, new XVar( "cell", "footcell_field1" ),
4, new XVar( "cell", "footcell_field2" ),
5, new XVar( "cell", "footcell_field3" ),
6, new XVar( "cell", "footcell_field4" ),
7, new XVar( "cell", "footcell_field5" ),
8, new XVar( "cell", "footcell_field6" ),
9, new XVar( "cell", "footcell_field7" ),
10, new XVar( "cell", "footcell_field8" ),
11, new XVar( "cell", "footcell_field9" ),
12, new XVar( "cell", "footcell_field10" ),
13, new XVar( "cell", "footcell_field11" ),
14, new XVar( "cell", "footcell_field12" ),
15, new XVar( "cell", "footcell_field13" ),
16, new XVar( "cell", "footcell_field14" ),
17, new XVar( "cell", "footcell_field15" ),
18, new XVar( "cell", "footcell_field16" ),
19, new XVar( "cell", "footcell_field17" ),
20, new XVar( "cell", "footcell_field18" ),
21, new XVar( "cell", "footcell_field19" ),
22, new XVar( "cell", "footcell_field20" ),
23, new XVar( "cell", "footcell_field21" ),
24, new XVar( "cell", "footcell_field22" ),
25, new XVar( "cell", "footcell_field23" ),
26, new XVar( "cell", "footcell_field24" ) ) ) ),
"cells", new XVar( "headcell_field", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field25" ),
"field", "ID",
"columnName", "field" ),
"cell_field", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field" ),
"field", "ID",
"columnName", "field" ),
"footcell_field", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field1", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field26" ),
"field", "HdrID",
"columnName", "field" ),
"cell_field1", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field1" ),
"field", "HdrID",
"columnName", "field" ),
"footcell_field1", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field2", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field27" ),
"field", "LOC_UNIT_STA_B",
"columnName", "field" ),
"cell_field2", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field2" ),
"field", "LOC_UNIT_STA_B",
"columnName", "field" ),
"footcell_field2", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field3", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field28" ),
"field", "LOC_STREET_STA_B",
"columnName", "field" ),
"cell_field3", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field3" ),
"field", "LOC_STREET_STA_B",
"columnName", "field" ),
"footcell_field3", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field4", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field29" ),
"field", "LOC_BRGY_STA_B",
"columnName", "field" ),
"cell_field4", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field4" ),
"field", "LOC_BRGY_STA_B",
"columnName", "field" ),
"footcell_field4", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field5", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field30" ),
"field", "CITY/MUNICIPALITY_STA_B",
"columnName", "field" ),
"cell_field5", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field5" ),
"field", "CITY/MUNICIPALITY_STA_B",
"columnName", "field" ),
"footcell_field5", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field6", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field31" ),
"field", "PROVINCE_STA_B",
"columnName", "field" ),
"cell_field6", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field6" ),
"field", "PROVINCE_STA_B",
"columnName", "field" ),
"footcell_field6", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field7", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field32" ),
"field", "ZIPCODE_STA_B",
"columnName", "field" ),
"cell_field7", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field7" ),
"field", "ZIPCODE_STA_B",
"columnName", "field" ),
"footcell_field7", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field8", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field33" ),
"field", "eDegB",
"columnName", "field" ),
"cell_field8", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field8" ),
"field", "eDegB",
"columnName", "field" ),
"footcell_field8", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field9", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field34" ),
"field", "eMinB",
"columnName", "field" ),
"cell_field9", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field9" ),
"field", "eMinB",
"columnName", "field" ),
"footcell_field9", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field10", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field35" ),
"field", "eSecB",
"columnName", "field" ),
"cell_field10", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field10" ),
"field", "eSecB",
"columnName", "field" ),
"footcell_field10", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field11", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field36" ),
"field", "nDegB",
"columnName", "field" ),
"cell_field11", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field11" ),
"field", "nDegB",
"columnName", "field" ),
"footcell_field11", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field12", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field37" ),
"field", "nMinB",
"columnName", "field" ),
"cell_field12", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field12" ),
"field", "nMinB",
"columnName", "field" ),
"footcell_field12", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field13", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field38" ),
"field", "nSecB",
"columnName", "field" ),
"cell_field13", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field13" ),
"field", "nSecB",
"columnName", "field" ),
"footcell_field13", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field14", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field39" ),
"field", "elevationB",
"columnName", "field" ),
"cell_field14", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field14" ),
"field", "elevationB",
"columnName", "field" ),
"footcell_field14", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field15", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field40" ),
"field", "aMakeTypeModelB",
"columnName", "field" ),
"cell_field15", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field15" ),
"field", "aMakeTypeModelB",
"columnName", "field" ),
"footcell_field15", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field16", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field41" ),
"field", "gainB",
"columnName", "field" ),
"cell_field16", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field16" ),
"field", "gainB",
"columnName", "field" ),
"footcell_field16", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field17", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field42" ),
"field", "diameterB",
"columnName", "field" ),
"cell_field17", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field17" ),
"field", "diameterB",
"columnName", "field" ),
"footcell_field17", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field18", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field43" ),
"field", "beamwidthB",
"columnName", "field" ),
"cell_field18", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field18" ),
"field", "beamwidthB",
"columnName", "field" ),
"footcell_field18", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field19", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field44" ),
"field", "polarizationB",
"columnName", "field" ),
"cell_field19", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field19" ),
"field", "polarizationB",
"columnName", "field" ),
"footcell_field19", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field20", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field45" ),
"field", "azimuthB",
"columnName", "field" ),
"cell_field20", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field20" ),
"field", "azimuthB",
"columnName", "field" ),
"footcell_field20", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field21", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field46" ),
"field", "elevAngleB",
"columnName", "field" ),
"cell_field21", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field21" ),
"field", "elevAngleB",
"columnName", "field" ),
"footcell_field21", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field22", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field47" ),
"field", "heightAGLB",
"columnName", "field" ),
"cell_field22", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field22" ),
"field", "heightAGLB",
"columnName", "field" ),
"footcell_field22", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field23", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field48" ),
"field", "feederLengthB",
"columnName", "field" ),
"cell_field23", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field23" ),
"field", "feederLengthB",
"columnName", "field" ),
"footcell_field23", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_field24", new XVar( "model", "headcell_field",
"items", new XVar( 0, "simple_grid_field49" ),
"field", "callSignB",
"columnName", "field" ),
"cell_field24", new XVar( "model", "cell_field",
"items", new XVar( 0, "simple_grid_field24" ),
"field", "callSignB",
"columnName", "field" ),
"footcell_field24", new XVar( "model", "footcell_field",
"items", XVar.Array() ),
"headcell_checkbox", new XVar( "model", "headcell_checkbox",
"items", new XVar( 0, "grid_checkbox_head" ) ),
"cell_checkbox", new XVar( "model", "cell_checkbox",
"items", new XVar( 0, "grid_checkbox" ) ),
"footcell_checkbox", new XVar( "model", "footcell_checkbox",
"items", XVar.Array() ),
"headcell_icons", new XVar( "model", "headcell_icons",
"items", XVar.Array() ),
"cell_icons", new XVar( "model", "cell_icons",
"items", new XVar( 0, "grid_edit",
1, "grid_inline_cancel",
2, "grid_view" ) ),
"footcell_icons", new XVar( "model", "footcell_icons",
"items", XVar.Array() ) ),
"deferredItems", XVar.Array(),
"recsPerRow", 1 ) ),
"items", new XVar( "page_size", new XVar( "type", "page_size" ),
"details_found", new XVar( "type", "details_found" ),
"breadcrumb", new XVar( "type", "breadcrumb" ),
"logo", new XVar( "type", "logo" ),
"menu", new XVar( "type", "menu" ),
"simple_search", new XVar( "type", "simple_search" ),
"pagination", new XVar( "type", "pagination" ),
"search_panel", new XVar( "type", "search_panel",
"items", new XVar( 0, "search_panel_field",
1, "search_panel_field24",
2, "search_panel_field23",
3, "search_panel_field22",
4, "search_panel_field21",
5, "search_panel_field20",
6, "search_panel_field19",
7, "search_panel_field18",
8, "search_panel_field17",
9, "search_panel_field16",
10, "search_panel_field15",
11, "search_panel_field14",
12, "search_panel_field13",
13, "search_panel_field12",
14, "search_panel_field11",
15, "search_panel_field10",
16, "search_panel_field9",
17, "search_panel_field8",
18, "search_panel_field7",
19, "search_panel_field6",
20, "search_panel_field5",
21, "search_panel_field4",
22, "search_panel_field3",
23, "search_panel_field2",
24, "search_panel_field1" ) ),
"list_options", new XVar( "type", "list_options",
"items", new XVar( 0, "export_selected",
1, "delete_selected",
2, "-3",
3, "advsearch_link",
4, "show_search_panel",
5, "hide_search_panel",
6, "-1",
7, "export",
8, "-2",
9, "import" ) ),
"show_search_panel", new XVar( "type", "show_search_panel" ),
"hide_search_panel", new XVar( "type", "hide_search_panel" ),
"search_panel_field", new XVar( "field", "CITY/MUNICIPALITY_STA_B",
"type", "search_panel_field",
"required", false ),
"search_panel_field1", new XVar( "field", "HdrID",
"type", "search_panel_field",
"required", false ),
"search_panel_field2", new XVar( "field", "ID",
"type", "search_panel_field",
"required", false ),
"search_panel_field3", new XVar( "field", "LOC_BRGY_STA_B",
"type", "search_panel_field",
"required", false ),
"search_panel_field4", new XVar( "field", "LOC_STREET_STA_B",
"type", "search_panel_field",
"required", false ),
"search_panel_field5", new XVar( "field", "LOC_UNIT_STA_B",
"type", "search_panel_field",
"required", false ),
"search_panel_field6", new XVar( "field", "PROVINCE_STA_B",
"type", "search_panel_field",
"required", false ),
"search_panel_field7", new XVar( "field", "ZIPCODE_STA_B",
"type", "search_panel_field",
"required", false ),
"search_panel_field8", new XVar( "field", "aMakeTypeModelB",
"type", "search_panel_field",
"required", false ),
"search_panel_field9", new XVar( "field", "azimuthB",
"type", "search_panel_field",
"required", false ),
"search_panel_field10", new XVar( "field", "beamwidthB",
"type", "search_panel_field",
"required", false ),
"search_panel_field11", new XVar( "field", "callSignB",
"type", "search_panel_field",
"required", false ),
"search_panel_field12", new XVar( "field", "diameterB",
"type", "search_panel_field",
"required", false ),
"search_panel_field13", new XVar( "field", "eDegB",
"type", "search_panel_field",
"required", false ),
"search_panel_field14", new XVar( "field", "eMinB",
"type", "search_panel_field",
"required", false ),
"search_panel_field15", new XVar( "field", "eSecB",
"type", "search_panel_field",
"required", false ),
"search_panel_field16", new XVar( "field", "elevAngleB",
"type", "search_panel_field",
"required", false ),
"search_panel_field17", new XVar( "field", "elevationB",
"type", "search_panel_field",
"required", false ),
"search_panel_field18", new XVar( "field", "feederLengthB",
"type", "search_panel_field",
"required", false ),
"search_panel_field19", new XVar( "field", "gainB",
"type", "search_panel_field",
"required", false ),
"search_panel_field20", new XVar( "field", "heightAGLB",
"type", "search_panel_field",
"required", false ),
"search_panel_field21", new XVar( "field", "nDegB",
"type", "search_panel_field",
"required", false ),
"search_panel_field22", new XVar( "field", "nMinB",
"type", "search_panel_field",
"required", false ),
"search_panel_field23", new XVar( "field", "nSecB",
"type", "search_panel_field",
"required", false ),
"search_panel_field24", new XVar( "field", "polarizationB",
"type", "search_panel_field",
"required", false ),
"username_button", new XVar( "type", "username_button",
"items", new XVar( 0, "userinfo_link",
1, "logout_link",
2, "adminarea_link" ) ),
"loginform_login", new XVar( "type", "loginform_login",
"popup", false ),
"userinfo_link", new XVar( "type", "userinfo_link" ),
"logout_link", new XVar( "type", "logout_link" ),
"adminarea_link", new XVar( "type", "adminarea_link" ),
"expand_menu_button", new XVar( "type", "expand_menu_button" ),
"collapse_button", new XVar( "type", "collapse_button" ),
"add", new XVar( "type", "add" ),
"print_panel", new XVar( "type", "print_panel",
"items", new XVar( 0, "print_scope",
1, "print_records",
2, "print_button" ) ),
"print_scope", new XVar( "type", "print_scope" ),
"print_button", new XVar( "type", "print_button" ),
"print_records", new XVar( "type", "print_records" ),
"export", new XVar( "type", "export" ),
"-", new XVar( "type", "-" ),
"export_selected", new XVar( "type", "export_selected" ),
"-1", new XVar( "type", "-" ),
"import", new XVar( "type", "import" ),
"-2", new XVar( "type", "-" ),
"delete", new XVar( "type", "delete" ),
"delete_selected", new XVar( "type", "delete_selected" ),
"advsearch_link", new XVar( "type", "advsearch_link" ),
"-3", new XVar( "type", "-" ),
"master_info", new XVar( "type", "master_info",
"tables", new XVar( "dbo.rspdHeader", "true" ) ),
"simple_grid_field", new XVar( "field", "ID",
"type", "grid_field",
"inlineAdd", false,
"inlineEdit", false ),
"simple_grid_field25", new XVar( "type", "grid_field_label",
"field", "ID" ),
"simple_grid_field1", new XVar( "field", "HdrID",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field26", new XVar( "type", "grid_field_label",
"field", "HdrID" ),
"simple_grid_field2", new XVar( "field", "LOC_UNIT_STA_B",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field27", new XVar( "type", "grid_field_label",
"field", "LOC_UNIT_STA_B" ),
"simple_grid_field3", new XVar( "field", "LOC_STREET_STA_B",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field28", new XVar( "type", "grid_field_label",
"field", "LOC_STREET_STA_B" ),
"simple_grid_field4", new XVar( "field", "LOC_BRGY_STA_B",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field29", new XVar( "type", "grid_field_label",
"field", "LOC_BRGY_STA_B" ),
"simple_grid_field5", new XVar( "field", "CITY/MUNICIPALITY_STA_B",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field30", new XVar( "type", "grid_field_label",
"field", "CITY/MUNICIPALITY_STA_B" ),
"simple_grid_field6", new XVar( "field", "PROVINCE_STA_B",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field31", new XVar( "type", "grid_field_label",
"field", "PROVINCE_STA_B" ),
"simple_grid_field7", new XVar( "field", "ZIPCODE_STA_B",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field32", new XVar( "type", "grid_field_label",
"field", "ZIPCODE_STA_B" ),
"simple_grid_field8", new XVar( "field", "eDegB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field33", new XVar( "type", "grid_field_label",
"field", "eDegB" ),
"simple_grid_field9", new XVar( "field", "eMinB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field34", new XVar( "type", "grid_field_label",
"field", "eMinB" ),
"simple_grid_field10", new XVar( "field", "eSecB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field35", new XVar( "type", "grid_field_label",
"field", "eSecB" ),
"simple_grid_field11", new XVar( "field", "nDegB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field36", new XVar( "type", "grid_field_label",
"field", "nDegB" ),
"simple_grid_field12", new XVar( "field", "nMinB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field37", new XVar( "type", "grid_field_label",
"field", "nMinB" ),
"simple_grid_field13", new XVar( "field", "nSecB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field38", new XVar( "type", "grid_field_label",
"field", "nSecB" ),
"simple_grid_field14", new XVar( "field", "elevationB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field39", new XVar( "type", "grid_field_label",
"field", "elevationB" ),
"simple_grid_field15", new XVar( "field", "aMakeTypeModelB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field40", new XVar( "type", "grid_field_label",
"field", "aMakeTypeModelB" ),
"simple_grid_field16", new XVar( "field", "gainB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field41", new XVar( "type", "grid_field_label",
"field", "gainB" ),
"simple_grid_field17", new XVar( "field", "diameterB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field42", new XVar( "type", "grid_field_label",
"field", "diameterB" ),
"simple_grid_field18", new XVar( "field", "beamwidthB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field43", new XVar( "type", "grid_field_label",
"field", "beamwidthB" ),
"simple_grid_field19", new XVar( "field", "polarizationB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field44", new XVar( "type", "grid_field_label",
"field", "polarizationB" ),
"simple_grid_field20", new XVar( "field", "azimuthB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field45", new XVar( "type", "grid_field_label",
"field", "azimuthB" ),
"simple_grid_field21", new XVar( "field", "elevAngleB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field46", new XVar( "type", "grid_field_label",
"field", "elevAngleB" ),
"simple_grid_field22", new XVar( "field", "heightAGLB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field47", new XVar( "type", "grid_field_label",
"field", "heightAGLB" ),
"simple_grid_field23", new XVar( "field", "feederLengthB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field48", new XVar( "type", "grid_field_label",
"field", "feederLengthB" ),
"simple_grid_field24", new XVar( "field", "callSignB",
"type", "grid_field",
"inlineAdd", true,
"inlineEdit", true ),
"simple_grid_field49", new XVar( "type", "grid_field_label",
"field", "callSignB" ),
"grid_checkbox", new XVar( "type", "grid_checkbox" ),
"grid_checkbox_head", new XVar( "type", "grid_checkbox_head" ),
"grid_edit", new XVar( "type", "grid_edit" ),
"grid_view", new XVar( "type", "grid_view" ),
"expand_button", new XVar( "type", "expand_button" ),
"inline_add", new XVar( "type", "inline_add",
"detailsOnly", true ),
"grid_inline_cancel", new XVar( "type", "grid_inline_cancel" ) ),
"dbProps", new XVar(  ),
"version", 13,
"imageItem", new XVar( "type", "page_image" ),
"imageBgColor", "#f2f2f2",
"controlsBgColor", "white",
"imagePosition", "right",
"listTotals", 1 );
				}
			}
		}