using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_admin_users
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["admin_users"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".ShortName"] = "admin_users";
			tdataArray["admin_users"][".OwnerID"] = "";
			tdataArray["admin_users"][".OriginalTable"] = "dbo.spectrum_beta_users";
			tdataArray["admin_users"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}"));
			tdataArray["admin_users"][".originalPagesByType"] = tdataArray["admin_users"][".pagesByType"];
			tdataArray["admin_users"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}")));
			tdataArray["admin_users"][".originalPages"] = tdataArray["admin_users"][".pages"];
			tdataArray["admin_users"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"add\":\"add\",\"edit\":\"edit\",\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\",\"view\":\"view\"}"));
			tdataArray["admin_users"][".originalDefaultPages"] = tdataArray["admin_users"][".defaultPages"];
			fieldLabelsArray["admin_users"] = SettingsMap.GetArray();
			fieldToolTipsArray["admin_users"] = SettingsMap.GetArray();
			pageTitlesArray["admin_users"] = SettingsMap.GetArray();
			placeHoldersArray["admin_users"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["admin_users"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["admin_users"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["admin_users"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["admin_users"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["admin_users"]["English"]["ID"] = "ID";
				fieldToolTipsArray["admin_users"]["English"]["ID"] = "";
				placeHoldersArray["admin_users"]["English"]["ID"] = "";
				fieldLabelsArray["admin_users"]["English"]["username"] = "Username";
				fieldToolTipsArray["admin_users"]["English"]["username"] = "";
				placeHoldersArray["admin_users"]["English"]["username"] = "";
				fieldLabelsArray["admin_users"]["English"]["password"] = "Password";
				fieldToolTipsArray["admin_users"]["English"]["password"] = "";
				placeHoldersArray["admin_users"]["English"]["password"] = "";
				fieldLabelsArray["admin_users"]["English"]["email"] = "Email";
				fieldToolTipsArray["admin_users"]["English"]["email"] = "";
				placeHoldersArray["admin_users"]["English"]["email"] = "";
				fieldLabelsArray["admin_users"]["English"]["fullname"] = "Name";
				fieldToolTipsArray["admin_users"]["English"]["fullname"] = "";
				placeHoldersArray["admin_users"]["English"]["fullname"] = "";
				fieldLabelsArray["admin_users"]["English"]["groupid"] = "Group Permission";
				fieldToolTipsArray["admin_users"]["English"]["groupid"] = "";
				placeHoldersArray["admin_users"]["English"]["groupid"] = "";
				fieldLabelsArray["admin_users"]["English"]["active"] = "Active";
				fieldToolTipsArray["admin_users"]["English"]["active"] = "";
				placeHoldersArray["admin_users"]["English"]["active"] = "";
				fieldLabelsArray["admin_users"]["English"]["ext_security_id"] = "Ext Security Id";
				fieldToolTipsArray["admin_users"]["English"]["ext_security_id"] = "";
				placeHoldersArray["admin_users"]["English"]["ext_security_id"] = "";
				fieldLabelsArray["admin_users"]["English"]["company"] = "Company";
				fieldToolTipsArray["admin_users"]["English"]["company"] = "";
				placeHoldersArray["admin_users"]["English"]["company"] = "";
				fieldLabelsArray["admin_users"]["English"]["position"] = "Position";
				fieldToolTipsArray["admin_users"]["English"]["position"] = "";
				placeHoldersArray["admin_users"]["English"]["position"] = "";
				fieldLabelsArray["admin_users"]["English"]["branch"] = "Office/Branch/Division";
				fieldToolTipsArray["admin_users"]["English"]["branch"] = "";
				placeHoldersArray["admin_users"]["English"]["branch"] = "";
				fieldLabelsArray["admin_users"]["English"]["groupPermission"] = "Group Permission";
				fieldToolTipsArray["admin_users"]["English"]["groupPermission"] = "";
				placeHoldersArray["admin_users"]["English"]["groupPermission"] = "";
				pageTitlesArray["admin_users"]["English"]["edit"] = "Admin Users, Edit [{%username}]";
				pageTitlesArray["admin_users"]["English"]["view"] = "Admin Users {%username}";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["admin_users"]["English"])))
				{
					tdataArray["admin_users"][".isUseToolTips"] = true;
				}
			}
			tdataArray["admin_users"][".NCSearch"] = true;
			tdataArray["admin_users"][".shortTableName"] = "admin_users";
			tdataArray["admin_users"][".nSecOptions"] = 0;
			tdataArray["admin_users"][".mainTableOwnerID"] = "";
			tdataArray["admin_users"][".entityType"] = 1;
			tdataArray["admin_users"][".connId"] = "RSPDDB_at_172_16_0_80";
			tdataArray["admin_users"][".strOriginalTableName"] = "dbo.spectrum_beta_users";
			tdataArray["admin_users"][".showAddInPopup"] = false;
			tdataArray["admin_users"][".showEditInPopup"] = false;
			tdataArray["admin_users"][".showViewInPopup"] = false;
			tdataArray["admin_users"][".listAjax"] = false;
			tdataArray["admin_users"][".audit"] = true;
			tdataArray["admin_users"][".locking"] = false;
			GlobalVars.pages = tdataArray["admin_users"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["admin_users"][".edit"] = true;
				tdataArray["admin_users"][".afterEditAction"] = 1;
				tdataArray["admin_users"][".closePopupAfterEdit"] = 1;
				tdataArray["admin_users"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["admin_users"][".add"] = true;
				tdataArray["admin_users"][".afterAddAction"] = 1;
				tdataArray["admin_users"][".closePopupAfterAdd"] = 1;
				tdataArray["admin_users"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["admin_users"][".list"] = true;
			}
			tdataArray["admin_users"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["admin_users"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["admin_users"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["admin_users"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["admin_users"][".printFriendly"] = true;
			}
			tdataArray["admin_users"][".showSimpleSearchOptions"] = true;
			tdataArray["admin_users"][".allowShowHideFields"] = true;
			tdataArray["admin_users"][".allowFieldsReordering"] = true;
			tdataArray["admin_users"][".isUseAjaxSuggest"] = true;


			tdataArray["admin_users"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["admin_users"][".buttonsAdded"] = false;
			tdataArray["admin_users"][".addPageEvents"] = false;
			tdataArray["admin_users"][".isUseTimeForSearch"] = false;
			tdataArray["admin_users"][".badgeColor"] = "008B8B";
			tdataArray["admin_users"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".googleLikeFields"].Add("ID");
			tdataArray["admin_users"][".googleLikeFields"].Add("username");
			tdataArray["admin_users"][".googleLikeFields"].Add("password");
			tdataArray["admin_users"][".googleLikeFields"].Add("email");
			tdataArray["admin_users"][".googleLikeFields"].Add("fullname");
			tdataArray["admin_users"][".googleLikeFields"].Add("groupid");
			tdataArray["admin_users"][".googleLikeFields"].Add("active");
			tdataArray["admin_users"][".googleLikeFields"].Add("ext_security_id");
			tdataArray["admin_users"][".googleLikeFields"].Add("company");
			tdataArray["admin_users"][".googleLikeFields"].Add("position");
			tdataArray["admin_users"][".googleLikeFields"].Add("branch");
			tdataArray["admin_users"][".googleLikeFields"].Add("groupPermission");
			tdataArray["admin_users"][".tableType"] = "list";
			tdataArray["admin_users"][".printerPageOrientation"] = 0;
			tdataArray["admin_users"][".nPrinterPageScale"] = 100;
			tdataArray["admin_users"][".nPrinterSplitRecords"] = 40;
			tdataArray["admin_users"][".geocodingEnabled"] = false;
			tdataArray["admin_users"][".pageSize"] = 20;
			tdataArray["admin_users"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["admin_users"][".strOrderBy"] = tstrOrderBy;
			tdataArray["admin_users"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["admin_users"][".sqlHead"] = "SELECT ID,  	username,  	password,  	email,  	fullname,  	groupid,  	active,  	ext_security_id,  	company,  	[position],  	branch,  	groupPermission";
			tdataArray["admin_users"][".sqlFrom"] = "FROM dbo.spectrum_beta_users";
			tdataArray["admin_users"][".sqlWhereExpr"] = "";
			tdataArray["admin_users"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["admin_users"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["admin_users"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["admin_users"][".highlightSearchResults"] = true;
			tableKeysArray["admin_users"] = SettingsMap.GetArray();
			tableKeysArray["admin_users"].Add("ID");
			tdataArray["admin_users"][".Keys"] = tableKeysArray["admin_users"];
			tdataArray["admin_users"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "ID";
			fdata["GoodName"] = "ID";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","ID");
			fdata["FieldType"] = 3;
			fdata["AutoInc"] = true;
			fdata["strField"] = "ID";
			fdata["sourceSingle"] = "ID";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ID";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["ID"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("ID");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "username";
			fdata["GoodName"] = "username";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","username");
			fdata["FieldType"] = 200;
			fdata["strField"] = "username";
			fdata["sourceSingle"] = "username";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "username";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Regular expression")));
			edata["validateAs"]["regExp"] = "^[^\\s]+(\\s+[^\\s]+)*$";
			edata["validateAs"]["customMessages"]["RegExp"] = new XVar("message", "Please remove whitespaces", "messageType", "Text");
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			edata["validateAs"]["basicValidate"].Add("DenyDuplicated");
			edata["validateAs"]["customMessages"]["DenyDuplicated"] = new XVar("message", "Username: %value% already exists", "messageType", "Text");
			edata["denyDuplicates"] = true;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["username"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("username");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "password";
			fdata["GoodName"] = "password";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","password");
			fdata["FieldType"] = 200;
			fdata["strField"] = "password";
			fdata["sourceSingle"] = "password";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "password";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Password");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["password"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("password");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "email";
			fdata["GoodName"] = "email";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","email");
			fdata["FieldType"] = 200;
			fdata["strField"] = "email";
			fdata["sourceSingle"] = "email";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "email";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Email")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			edata["validateAs"]["basicValidate"].Add("DenyDuplicated");
			edata["validateAs"]["customMessages"]["DenyDuplicated"] = new XVar("message", "Email: %value% already exists", "messageType", "Text");
			edata["denyDuplicates"] = true;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["email"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("email");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "fullname";
			fdata["GoodName"] = "fullname";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","fullname");
			fdata["FieldType"] = 200;
			fdata["strField"] = "fullname";
			fdata["sourceSingle"] = "fullname";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "fullname";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["fullname"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("fullname");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "groupid";
			fdata["GoodName"] = "groupid";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","groupid");
			fdata["FieldType"] = 200;
			fdata["strField"] = "groupid";
			fdata["sourceSingle"] = "groupid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "groupid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 2;
			edata["LookupTable"] = "dbo.spectrum_betauggroups";
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LinkField"] = "GroupID";
			edata["LinkFieldType"] = 3;
			edata["DisplayField"] = "Label";
			edata["LookupOrderBy"] = "";
			edata["SelectSize"] = 1;
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["groupid"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("groupid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "active";
			fdata["GoodName"] = "active";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","active");
			fdata["FieldType"] = 3;
			fdata["strField"] = "active";
			fdata["sourceSingle"] = "active";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "active";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Checkbox");
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Checkbox");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["active"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("active");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "ext_security_id";
			fdata["GoodName"] = "ext_security_id";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","ext_security_id");
			fdata["FieldType"] = 200;
			fdata["strField"] = "ext_security_id";
			fdata["sourceSingle"] = "ext_security_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ext_security_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["ext_security_id"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("ext_security_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "company";
			fdata["GoodName"] = "company";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","company");
			fdata["FieldType"] = 200;
			fdata["strField"] = "company";
			fdata["sourceSingle"] = "company";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "company";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 2;
			edata["LookupTable"] = "dbo.company";
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LinkField"] = "id";
			edata["LinkFieldType"] = 0;
			edata["DisplayField"] = "companyName";
			edata["LookupOrderBy"] = "";
			edata["SelectSize"] = 1;
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["company"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("company");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "position";
			fdata["GoodName"] = "position";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","position");
			fdata["FieldType"] = 200;
			fdata["strField"] = "position";
			fdata["sourceSingle"] = "position";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "[position]";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["position"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("position");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "branch";
			fdata["GoodName"] = "branch";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","branch");
			fdata["FieldType"] = 200;
			fdata["strField"] = "branch";
			fdata["sourceSingle"] = "branch";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "branch";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 2;
			edata["LookupTable"] = "dbo.branch";
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LinkField"] = "branchName";
			edata["LinkFieldType"] = 0;
			edata["DisplayField"] = "branchName";
			edata["LookupOrderBy"] = "";
			edata["SelectSize"] = 1;
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["branch"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("branch");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "groupPermission";
			fdata["GoodName"] = "groupPermission";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("admin_users","groupPermission");
			fdata["FieldType"] = 200;
			fdata["strField"] = "groupPermission";
			fdata["sourceSingle"] = "groupPermission";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "groupPermission";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 0;
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LookupValues"] = SettingsMap.GetArray();
			edata["LookupValues"].Add("Admin");
			edata["LookupValues"].Add("Delivery Unit");
			edata["SelectSize"] = 1;
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["admin_users"]["groupPermission"] = fdata;
			tdataArray["admin_users"][".searchableFields"].Add("groupPermission");
			GlobalVars.tables_data["admin_users"] = tdataArray["admin_users"];
			GlobalVars.field_labels["admin_users"] = fieldLabelsArray["admin_users"];
			GlobalVars.fieldToolTips["admin_users"] = fieldToolTipsArray["admin_users"];
			GlobalVars.placeHolders["admin_users"] = placeHoldersArray["admin_users"];
			GlobalVars.page_titles["admin_users"] = pageTitlesArray["admin_users"];
			CommonFunctions.changeTextControlsToDate(new XVar("admin_users"));
			GlobalVars.detailsTablesData["admin_users"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["admin_users"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "ID,  	username,  	password,  	email,  	fullname,  	groupid,  	active,  	ext_security_id,  	company,  	[position],  	branch,  	groupPermission";
protoArray["0"]["m_strFrom"] = "FROM dbo.spectrum_beta_users";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ID", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "admin_users"));

protoArray["6"]["m_sql"] = "ID";
protoArray["6"]["m_srcTableName"] = "admin_users";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "username", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "admin_users"));

protoArray["8"]["m_sql"] = "username";
protoArray["8"]["m_srcTableName"] = "admin_users";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "password", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "admin_users"));

protoArray["10"]["m_sql"] = "password";
protoArray["10"]["m_srcTableName"] = "admin_users";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "email", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "admin_users"));

protoArray["12"]["m_sql"] = "email";
protoArray["12"]["m_srcTableName"] = "admin_users";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "fullname", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "admin_users"));

protoArray["14"]["m_sql"] = "fullname";
protoArray["14"]["m_srcTableName"] = "admin_users";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "groupid", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "admin_users"));

protoArray["16"]["m_sql"] = "groupid";
protoArray["16"]["m_srcTableName"] = "admin_users";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "active", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "admin_users"));

protoArray["18"]["m_sql"] = "active";
protoArray["18"]["m_srcTableName"] = "admin_users";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ext_security_id", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "admin_users"));

protoArray["20"]["m_sql"] = "ext_security_id";
protoArray["20"]["m_srcTableName"] = "admin_users";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "company", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "admin_users"));

protoArray["22"]["m_sql"] = "company";
protoArray["22"]["m_srcTableName"] = "admin_users";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "position", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "admin_users"));

protoArray["24"]["m_sql"] = "[position]";
protoArray["24"]["m_srcTableName"] = "admin_users";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "branch", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "admin_users"));

protoArray["26"]["m_sql"] = "branch";
protoArray["26"]["m_srcTableName"] = "admin_users";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "groupPermission", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "admin_users"));

protoArray["28"]["m_sql"] = "groupPermission";
protoArray["28"]["m_srcTableName"] = "admin_users";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["30"] = SettingsMap.GetArray();
protoArray["30"]["m_link"] = "SQLL_MAIN";
protoArray["31"] = SettingsMap.GetArray();
protoArray["31"]["m_strName"] = "dbo.spectrum_beta_users";
protoArray["31"]["m_srcTableName"] = "admin_users";
protoArray["31"]["m_columns"] = SettingsMap.GetArray();
protoArray["31"]["m_columns"].Add("ID");
protoArray["31"]["m_columns"].Add("username");
protoArray["31"]["m_columns"].Add("password");
protoArray["31"]["m_columns"].Add("email");
protoArray["31"]["m_columns"].Add("fullname");
protoArray["31"]["m_columns"].Add("groupid");
protoArray["31"]["m_columns"].Add("active");
protoArray["31"]["m_columns"].Add("ext_security_id");
protoArray["31"]["m_columns"].Add("company");
protoArray["31"]["m_columns"].Add("position");
protoArray["31"]["m_columns"].Add("branch");
protoArray["31"]["m_columns"].Add("groupPermission");
obj = new SQLTable(protoArray["31"]);

protoArray["30"]["m_table"] = obj;
protoArray["30"]["m_sql"] = "dbo.spectrum_beta_users";
protoArray["30"]["m_alias"] = "";
protoArray["30"]["m_srcTableName"] = "admin_users";
protoArray["32"] = SettingsMap.GetArray();
protoArray["32"]["m_sql"] = "";
protoArray["32"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["32"]["m_column"] = obj;
protoArray["32"]["m_contained"] = SettingsMap.GetArray();
protoArray["32"]["m_strCase"] = "";
protoArray["32"]["m_havingmode"] = false;
protoArray["32"]["m_inBrackets"] = false;
protoArray["32"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["32"]);

protoArray["30"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["30"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "admin_users";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["admin_users"] = obj;

				
		
			tdataArray["admin_users"][".sqlquery"] = queryData_Array["admin_users"];
			tdataArray["admin_users"][".hasEvents"] = true;
		}
	}

}
