using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_delivery_unit
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["delivery_unit"] = SettingsMap.GetArray();
			tdataArray["delivery_unit"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["delivery_unit"][".ShortName"] = "delivery_unit";
			tdataArray["delivery_unit"][".OwnerID"] = "";
			tdataArray["delivery_unit"][".OriginalTable"] = "dbo.delivery_Unit";
			tdataArray["delivery_unit"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}"));
			tdataArray["delivery_unit"][".originalPagesByType"] = tdataArray["delivery_unit"][".pagesByType"];
			tdataArray["delivery_unit"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}")));
			tdataArray["delivery_unit"][".originalPages"] = tdataArray["delivery_unit"][".pages"];
			tdataArray["delivery_unit"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"add\":\"add\",\"edit\":\"edit\",\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\",\"view\":\"view\"}"));
			tdataArray["delivery_unit"][".originalDefaultPages"] = tdataArray["delivery_unit"][".defaultPages"];
			fieldLabelsArray["delivery_unit"] = SettingsMap.GetArray();
			fieldToolTipsArray["delivery_unit"] = SettingsMap.GetArray();
			pageTitlesArray["delivery_unit"] = SettingsMap.GetArray();
			placeHoldersArray["delivery_unit"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["delivery_unit"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["delivery_unit"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["delivery_unit"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["delivery_unit"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["delivery_unit"]["English"]["id"] = "Id";
				fieldToolTipsArray["delivery_unit"]["English"]["id"] = "";
				placeHoldersArray["delivery_unit"]["English"]["id"] = "";
				fieldLabelsArray["delivery_unit"]["English"]["first_name"] = "First Name";
				fieldToolTipsArray["delivery_unit"]["English"]["first_name"] = "";
				placeHoldersArray["delivery_unit"]["English"]["first_name"] = "";
				fieldLabelsArray["delivery_unit"]["English"]["last_name"] = "Last Name";
				fieldToolTipsArray["delivery_unit"]["English"]["last_name"] = "";
				placeHoldersArray["delivery_unit"]["English"]["last_name"] = "";
				fieldLabelsArray["delivery_unit"]["English"]["email"] = "Email";
				fieldToolTipsArray["delivery_unit"]["English"]["email"] = "";
				placeHoldersArray["delivery_unit"]["English"]["email"] = "";
				fieldLabelsArray["delivery_unit"]["English"]["userName"] = "User Name";
				fieldToolTipsArray["delivery_unit"]["English"]["userName"] = "";
				placeHoldersArray["delivery_unit"]["English"]["userName"] = "";
				fieldLabelsArray["delivery_unit"]["English"]["password"] = "Password";
				fieldToolTipsArray["delivery_unit"]["English"]["password"] = "";
				placeHoldersArray["delivery_unit"]["English"]["password"] = "";
				fieldLabelsArray["delivery_unit"]["English"]["address"] = "Address";
				fieldToolTipsArray["delivery_unit"]["English"]["address"] = "";
				placeHoldersArray["delivery_unit"]["English"]["address"] = "";
				fieldLabelsArray["delivery_unit"]["English"]["dateCreated"] = "Date Created";
				fieldToolTipsArray["delivery_unit"]["English"]["dateCreated"] = "";
				placeHoldersArray["delivery_unit"]["English"]["dateCreated"] = "";
				fieldLabelsArray["delivery_unit"]["English"]["createdBy"] = "Created By";
				fieldToolTipsArray["delivery_unit"]["English"]["createdBy"] = "";
				placeHoldersArray["delivery_unit"]["English"]["createdBy"] = "";
				fieldLabelsArray["delivery_unit"]["English"]["Name"] = "Name";
				fieldToolTipsArray["delivery_unit"]["English"]["Name"] = "";
				placeHoldersArray["delivery_unit"]["English"]["Name"] = "";
				fieldLabelsArray["delivery_unit"]["English"]["office"] = "Regional Office/Branch";
				fieldToolTipsArray["delivery_unit"]["English"]["office"] = "";
				placeHoldersArray["delivery_unit"]["English"]["office"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["delivery_unit"]["English"])))
				{
					tdataArray["delivery_unit"][".isUseToolTips"] = true;
				}
			}
			tdataArray["delivery_unit"][".NCSearch"] = true;
			tdataArray["delivery_unit"][".shortTableName"] = "delivery_unit";
			tdataArray["delivery_unit"][".nSecOptions"] = 0;
			tdataArray["delivery_unit"][".mainTableOwnerID"] = "";
			tdataArray["delivery_unit"][".entityType"] = 0;
			tdataArray["delivery_unit"][".connId"] = "RSPDDB_at_172_16_0_80";
			tdataArray["delivery_unit"][".strOriginalTableName"] = "dbo.delivery_Unit";
			tdataArray["delivery_unit"][".showAddInPopup"] = false;
			tdataArray["delivery_unit"][".showEditInPopup"] = false;
			tdataArray["delivery_unit"][".showViewInPopup"] = false;
			tdataArray["delivery_unit"][".listAjax"] = false;
			tdataArray["delivery_unit"][".audit"] = true;
			tdataArray["delivery_unit"][".locking"] = false;
			GlobalVars.pages = tdataArray["delivery_unit"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["delivery_unit"][".edit"] = true;
				tdataArray["delivery_unit"][".afterEditAction"] = 1;
				tdataArray["delivery_unit"][".closePopupAfterEdit"] = 1;
				tdataArray["delivery_unit"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["delivery_unit"][".add"] = true;
				tdataArray["delivery_unit"][".afterAddAction"] = 1;
				tdataArray["delivery_unit"][".closePopupAfterAdd"] = 1;
				tdataArray["delivery_unit"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["delivery_unit"][".list"] = true;
			}
			tdataArray["delivery_unit"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["delivery_unit"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["delivery_unit"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["delivery_unit"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["delivery_unit"][".printFriendly"] = true;
			}
			tdataArray["delivery_unit"][".showSimpleSearchOptions"] = true;
			tdataArray["delivery_unit"][".allowShowHideFields"] = true;
			tdataArray["delivery_unit"][".allowFieldsReordering"] = true;
			tdataArray["delivery_unit"][".isUseAjaxSuggest"] = true;


			tdataArray["delivery_unit"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["delivery_unit"][".buttonsAdded"] = false;
			tdataArray["delivery_unit"][".addPageEvents"] = false;
			tdataArray["delivery_unit"][".isUseTimeForSearch"] = false;
			tdataArray["delivery_unit"][".badgeColor"] = "5F9EA0";
			tdataArray["delivery_unit"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["delivery_unit"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["delivery_unit"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["delivery_unit"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["delivery_unit"][".googleLikeFields"].Add("id");
			tdataArray["delivery_unit"][".googleLikeFields"].Add("first_name");
			tdataArray["delivery_unit"][".googleLikeFields"].Add("last_name");
			tdataArray["delivery_unit"][".googleLikeFields"].Add("email");
			tdataArray["delivery_unit"][".googleLikeFields"].Add("userName");
			tdataArray["delivery_unit"][".googleLikeFields"].Add("password");
			tdataArray["delivery_unit"][".googleLikeFields"].Add("address");
			tdataArray["delivery_unit"][".googleLikeFields"].Add("dateCreated");
			tdataArray["delivery_unit"][".googleLikeFields"].Add("createdBy");
			tdataArray["delivery_unit"][".googleLikeFields"].Add("Name");
			tdataArray["delivery_unit"][".googleLikeFields"].Add("office");
			tdataArray["delivery_unit"][".tableType"] = "list";
			tdataArray["delivery_unit"][".printerPageOrientation"] = 0;
			tdataArray["delivery_unit"][".nPrinterPageScale"] = 100;
			tdataArray["delivery_unit"][".nPrinterSplitRecords"] = 40;
			tdataArray["delivery_unit"][".geocodingEnabled"] = false;
			tdataArray["delivery_unit"][".pageSize"] = 20;
			tdataArray["delivery_unit"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["delivery_unit"][".strOrderBy"] = tstrOrderBy;
			tdataArray["delivery_unit"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["delivery_unit"][".sqlHead"] = "SELECT id,  	first_name,  	last_name,  	email,  	userName,  	password,  	address,  	dateCreated,  	createdBy,  	Name,  	office";
			tdataArray["delivery_unit"][".sqlFrom"] = "FROM dbo.delivery_Unit";
			tdataArray["delivery_unit"][".sqlWhereExpr"] = "";
			tdataArray["delivery_unit"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["delivery_unit"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["delivery_unit"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["delivery_unit"][".highlightSearchResults"] = true;
			tableKeysArray["delivery_unit"] = SettingsMap.GetArray();
			tableKeysArray["delivery_unit"].Add("id");
			tdataArray["delivery_unit"][".Keys"] = tableKeysArray["delivery_unit"];
			tdataArray["delivery_unit"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "id";
			fdata["GoodName"] = "id";
			fdata["ownerTable"] = "dbo.delivery_Unit";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_delivery_Unit","id");
			fdata["FieldType"] = 3;
			fdata["AutoInc"] = true;
			fdata["strField"] = "id";
			fdata["sourceSingle"] = "id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["delivery_unit"]["id"] = fdata;
			tdataArray["delivery_unit"][".searchableFields"].Add("id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "first_name";
			fdata["GoodName"] = "first_name";
			fdata["ownerTable"] = "dbo.delivery_Unit";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_delivery_Unit","first_name");
			fdata["FieldType"] = 200;
			fdata["strField"] = "first_name";
			fdata["sourceSingle"] = "first_name";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "first_name";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["delivery_unit"]["first_name"] = fdata;
			tdataArray["delivery_unit"][".searchableFields"].Add("first_name");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "last_name";
			fdata["GoodName"] = "last_name";
			fdata["ownerTable"] = "dbo.delivery_Unit";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_delivery_Unit","last_name");
			fdata["FieldType"] = 200;
			fdata["strField"] = "last_name";
			fdata["sourceSingle"] = "last_name";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "last_name";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["delivery_unit"]["last_name"] = fdata;
			tdataArray["delivery_unit"][".searchableFields"].Add("last_name");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "email";
			fdata["GoodName"] = "email";
			fdata["ownerTable"] = "dbo.delivery_Unit";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_delivery_Unit","email");
			fdata["FieldType"] = 200;
			fdata["strField"] = "email";
			fdata["sourceSingle"] = "email";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "email";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "email";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Email")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["delivery_unit"]["email"] = fdata;
			tdataArray["delivery_unit"][".searchableFields"].Add("email");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "userName";
			fdata["GoodName"] = "userName";
			fdata["ownerTable"] = "dbo.delivery_Unit";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_delivery_Unit","userName");
			fdata["FieldType"] = 200;
			fdata["strField"] = "userName";
			fdata["sourceSingle"] = "userName";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "userName";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Regular expression")));
			edata["validateAs"]["regExp"] = "^[^\\s]+(\\s+[^\\s]+)*$";
			edata["validateAs"]["customMessages"]["RegExp"] = new XVar("message", "Please Remove Whitespace", "messageType", "Text");
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["delivery_unit"]["userName"] = fdata;
			tdataArray["delivery_unit"][".searchableFields"].Add("userName");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "password";
			fdata["GoodName"] = "password";
			fdata["ownerTable"] = "dbo.delivery_Unit";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_delivery_Unit","password");
			fdata["FieldType"] = 200;
			fdata["strField"] = "password";
			fdata["sourceSingle"] = "password";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "password";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Password");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["delivery_unit"]["password"] = fdata;
			tdataArray["delivery_unit"][".searchableFields"].Add("password");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "address";
			fdata["GoodName"] = "address";
			fdata["ownerTable"] = "dbo.delivery_Unit";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_delivery_Unit","address");
			fdata["FieldType"] = 201;
			fdata["strField"] = "address";
			fdata["sourceSingle"] = "address";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "address";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text area");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 0;
			edata["nRows"] = 100;
			edata["nCols"] = 200;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["CreateThumbnail"] = true;
			edata["StrThumbnail"] = "th";
			edata["ThumbnailSize"] = 600;
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["delivery_unit"]["address"] = fdata;
			tdataArray["delivery_unit"][".searchableFields"].Add("address");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "dateCreated";
			fdata["GoodName"] = "dateCreated";
			fdata["ownerTable"] = "dbo.delivery_Unit";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_delivery_Unit","dateCreated");
			fdata["FieldType"] = 135;
			fdata["strField"] = "dateCreated";
			fdata["sourceSingle"] = "dateCreated";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "dateCreated";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Short Date");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Date");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["DateEditType"] = 13;
			edata["InitialYearFactor"] = 100;
			edata["LastYearFactor"] = 10;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Equals", 1, "More than", 2, "Less than", 3, "Between", 4, Constants.EMPTY_SEARCH, 5, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["delivery_unit"]["dateCreated"] = fdata;
			tdataArray["delivery_unit"][".searchableFields"].Add("dateCreated");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "createdBy";
			fdata["GoodName"] = "createdBy";
			fdata["ownerTable"] = "dbo.delivery_Unit";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_delivery_Unit","createdBy");
			fdata["FieldType"] = 200;
			fdata["strField"] = "createdBy";
			fdata["sourceSingle"] = "createdBy";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "createdBy";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["delivery_unit"]["createdBy"] = fdata;
			tdataArray["delivery_unit"][".searchableFields"].Add("createdBy");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "Name";
			fdata["GoodName"] = "Name";
			fdata["ownerTable"] = "dbo.delivery_Unit";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_delivery_Unit","Name");
			fdata["FieldType"] = 200;
			fdata["strField"] = "Name";
			fdata["sourceSingle"] = "Name";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "Name";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["delivery_unit"]["Name"] = fdata;
			tdataArray["delivery_unit"][".searchableFields"].Add("Name");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "office";
			fdata["GoodName"] = "office";
			fdata["ownerTable"] = "dbo.delivery_Unit";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_delivery_Unit","office");
			fdata["FieldType"] = 3;
			fdata["strField"] = "office";
			fdata["sourceSingle"] = "office";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "office";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["delivery_unit"]["office"] = fdata;
			tdataArray["delivery_unit"][".searchableFields"].Add("office");
			GlobalVars.tables_data["dbo.delivery_Unit"] = tdataArray["delivery_unit"];
			GlobalVars.field_labels["dbo_delivery_Unit"] = fieldLabelsArray["delivery_unit"];
			GlobalVars.fieldToolTips["dbo_delivery_Unit"] = fieldToolTipsArray["delivery_unit"];
			GlobalVars.placeHolders["dbo_delivery_Unit"] = placeHoldersArray["delivery_unit"];
			GlobalVars.page_titles["dbo_delivery_Unit"] = pageTitlesArray["delivery_unit"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.delivery_Unit"));
			GlobalVars.detailsTablesData["dbo.delivery_Unit"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.delivery_Unit"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "id,  	first_name,  	last_name,  	email,  	userName,  	password,  	address,  	dateCreated,  	createdBy,  	Name,  	office";
protoArray["0"]["m_strFrom"] = "FROM dbo.delivery_Unit";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "id", "m_strTable", "dbo.delivery_Unit", "m_srcTableName", "dbo.delivery_Unit"));

protoArray["6"]["m_sql"] = "id";
protoArray["6"]["m_srcTableName"] = "dbo.delivery_Unit";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "first_name", "m_strTable", "dbo.delivery_Unit", "m_srcTableName", "dbo.delivery_Unit"));

protoArray["8"]["m_sql"] = "first_name";
protoArray["8"]["m_srcTableName"] = "dbo.delivery_Unit";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "last_name", "m_strTable", "dbo.delivery_Unit", "m_srcTableName", "dbo.delivery_Unit"));

protoArray["10"]["m_sql"] = "last_name";
protoArray["10"]["m_srcTableName"] = "dbo.delivery_Unit";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "email", "m_strTable", "dbo.delivery_Unit", "m_srcTableName", "dbo.delivery_Unit"));

protoArray["12"]["m_sql"] = "email";
protoArray["12"]["m_srcTableName"] = "dbo.delivery_Unit";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "userName", "m_strTable", "dbo.delivery_Unit", "m_srcTableName", "dbo.delivery_Unit"));

protoArray["14"]["m_sql"] = "userName";
protoArray["14"]["m_srcTableName"] = "dbo.delivery_Unit";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "password", "m_strTable", "dbo.delivery_Unit", "m_srcTableName", "dbo.delivery_Unit"));

protoArray["16"]["m_sql"] = "password";
protoArray["16"]["m_srcTableName"] = "dbo.delivery_Unit";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "address", "m_strTable", "dbo.delivery_Unit", "m_srcTableName", "dbo.delivery_Unit"));

protoArray["18"]["m_sql"] = "address";
protoArray["18"]["m_srcTableName"] = "dbo.delivery_Unit";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "dateCreated", "m_strTable", "dbo.delivery_Unit", "m_srcTableName", "dbo.delivery_Unit"));

protoArray["20"]["m_sql"] = "dateCreated";
protoArray["20"]["m_srcTableName"] = "dbo.delivery_Unit";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "createdBy", "m_strTable", "dbo.delivery_Unit", "m_srcTableName", "dbo.delivery_Unit"));

protoArray["22"]["m_sql"] = "createdBy";
protoArray["22"]["m_srcTableName"] = "dbo.delivery_Unit";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "Name", "m_strTable", "dbo.delivery_Unit", "m_srcTableName", "dbo.delivery_Unit"));

protoArray["24"]["m_sql"] = "Name";
protoArray["24"]["m_srcTableName"] = "dbo.delivery_Unit";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "office", "m_strTable", "dbo.delivery_Unit", "m_srcTableName", "dbo.delivery_Unit"));

protoArray["26"]["m_sql"] = "office";
protoArray["26"]["m_srcTableName"] = "dbo.delivery_Unit";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["28"] = SettingsMap.GetArray();
protoArray["28"]["m_link"] = "SQLL_MAIN";
protoArray["29"] = SettingsMap.GetArray();
protoArray["29"]["m_strName"] = "dbo.delivery_Unit";
protoArray["29"]["m_srcTableName"] = "dbo.delivery_Unit";
protoArray["29"]["m_columns"] = SettingsMap.GetArray();
protoArray["29"]["m_columns"].Add("id");
protoArray["29"]["m_columns"].Add("first_name");
protoArray["29"]["m_columns"].Add("last_name");
protoArray["29"]["m_columns"].Add("email");
protoArray["29"]["m_columns"].Add("userName");
protoArray["29"]["m_columns"].Add("password");
protoArray["29"]["m_columns"].Add("address");
protoArray["29"]["m_columns"].Add("dateCreated");
protoArray["29"]["m_columns"].Add("createdBy");
protoArray["29"]["m_columns"].Add("Name");
protoArray["29"]["m_columns"].Add("office");
obj = new SQLTable(protoArray["29"]);

protoArray["28"]["m_table"] = obj;
protoArray["28"]["m_sql"] = "dbo.delivery_Unit";
protoArray["28"]["m_alias"] = "";
protoArray["28"]["m_srcTableName"] = "dbo.delivery_Unit";
protoArray["30"] = SettingsMap.GetArray();
protoArray["30"]["m_sql"] = "";
protoArray["30"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["30"]["m_column"] = obj;
protoArray["30"]["m_contained"] = SettingsMap.GetArray();
protoArray["30"]["m_strCase"] = "";
protoArray["30"]["m_havingmode"] = false;
protoArray["30"]["m_inBrackets"] = false;
protoArray["30"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["30"]);

protoArray["28"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["28"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.delivery_Unit";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["delivery_unit"] = obj;

				
		
			tdataArray["delivery_unit"][".sqlquery"] = queryData_Array["delivery_unit"];
			tdataArray["delivery_unit"][".hasEvents"] = true;
		}
	}

}
