using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public partial class CommonFunctions
	{
		public static XVar GetMenuNodesmain()
		{
			dynamic menuNode = XVar.Array(), menuNodes = XVar.Array();
			menuNodes = XVar.Clone(XVar.Array());
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("4", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("Dashboard", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("Dashboard")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("glyphicon-dashboard", "icon");
			menuNode.InitAndSetArrayItem("2", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Dashboard", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("5", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.rspdHeader", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("glyphicon-list-alt", "icon");
			menuNode.InitAndSetArrayItem("2", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("RSPD Form", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("6", "id");
			menuNode.InitAndSetArrayItem("Setup", "name");
			menuNode.InitAndSetArrayItem("", "href");
			menuNode.InitAndSetArrayItem("Group", "type");
			menuNode.InitAndSetArrayItem("", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("None", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("fa-gears", "icon");
			menuNode.InitAndSetArrayItem("3", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Setup", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("3", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.company", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("6", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("glyphicon-earphone", "icon");
			menuNode.InitAndSetArrayItem("2", "iconType");
			menuNode.InitAndSetArrayItem("2", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Company", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("19", "id");
			menuNode.InitAndSetArrayItem("Audit Trail", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.spectrum_beta_audit", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("6", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Audit Trail", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("32", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.branch", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("6", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Branch", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("33", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("users", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("6", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("Search")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Users", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("34", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.classStation", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("6", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Class Station", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("16", "id");
			menuNode.InitAndSetArrayItem("Location", "name");
			menuNode.InitAndSetArrayItem("", "href");
			menuNode.InitAndSetArrayItem("Group", "type");
			menuNode.InitAndSetArrayItem("", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("6", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("None", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Location", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("41", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.region", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("16", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Region", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("11", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.province", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("16", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("glyphicon-leaf", "icon");
			menuNode.InitAndSetArrayItem("2", "iconType");
			menuNode.InitAndSetArrayItem("2", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Province", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("10", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.city", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("16", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("glyphicon-leaf", "icon");
			menuNode.InitAndSetArrayItem("2", "iconType");
			menuNode.InitAndSetArrayItem("2", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("City", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("8", "id");
			menuNode.InitAndSetArrayItem("Barangay", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.baranggay", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("16", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("glyphicon-shopping-cart", "icon");
			menuNode.InitAndSetArrayItem("2", "iconType");
			menuNode.InitAndSetArrayItem("2", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Barangay", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("17", "id");
			menuNode.InitAndSetArrayItem("Stage Setup", "name");
			menuNode.InitAndSetArrayItem("", "href");
			menuNode.InitAndSetArrayItem("Group", "type");
			menuNode.InitAndSetArrayItem("", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("6", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("None", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Stage Setup", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("14", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.stage", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("17", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Stage", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("15", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.stageStatus", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("17", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Stage Status", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("18", "id");
			menuNode.InitAndSetArrayItem("Report", "name");
			menuNode.InitAndSetArrayItem("", "href");
			menuNode.InitAndSetArrayItem("Group", "type");
			menuNode.InitAndSetArrayItem("", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("None", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("fa-newspaper-o", "icon");
			menuNode.InitAndSetArrayItem("3", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Report", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("12", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("FAS Report", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("18", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("Report")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("glyphicon-earphone", "icon");
			menuNode.InitAndSetArrayItem("2", "iconType");
			menuNode.InitAndSetArrayItem("2", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("FAS Report", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("28", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("{04AFFBE6-86C0-47b0-ADD3-BA7FA19CA6FC}", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("WebReports")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Web Reports", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("35", "id");
			menuNode.InitAndSetArrayItem("Pre-Assessment Stage", "name");
			menuNode.InitAndSetArrayItem("", "href");
			menuNode.InitAndSetArrayItem("Group", "type");
			menuNode.InitAndSetArrayItem("", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("None", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Pre-Assessment Stage", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("38", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("applicationEndorsed", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("35", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Application Endorsed", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("30", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.applicationsRecieved", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("35", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Applications Recieved", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("39", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("applicationUnderAssessment", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("35", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Application Under Assessment", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("40", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("applicationUnderTechnicalEvaluation", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("35", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Application Under Technical Evaluation", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("36", "id");
			menuNode.InitAndSetArrayItem("Processing Stage", "name");
			menuNode.InitAndSetArrayItem("", "href");
			menuNode.InitAndSetArrayItem("Group", "type");
			menuNode.InitAndSetArrayItem("", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("None", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Processing Stage", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("37", "id");
			menuNode.InitAndSetArrayItem("Releasing Stage", "name");
			menuNode.InitAndSetArrayItem("", "href");
			menuNode.InitAndSetArrayItem("Group", "type");
			menuNode.InitAndSetArrayItem("", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("None", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Releasing Stage", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("31", "id");
			menuNode.InitAndSetArrayItem("Approvals", "name");
			menuNode.InitAndSetArrayItem("", "href");
			menuNode.InitAndSetArrayItem("Group", "type");
			menuNode.InitAndSetArrayItem("", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("0", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("None", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Approvals", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			menuNode = XVar.Clone(XVar.Array());
			menuNode.InitAndSetArrayItem("29", "id");
			menuNode.InitAndSetArrayItem("", "name");
			menuNode.InitAndSetArrayItem("mypage.htm", "href");
			menuNode.InitAndSetArrayItem("Leaf", "type");
			menuNode.InitAndSetArrayItem("dbo.rspd_application_received", "table");
			menuNode.InitAndSetArrayItem("", "style");
			menuNode.InitAndSetArrayItem("", "params");
			menuNode.InitAndSetArrayItem("31", "parent");
			menuNode.InitAndSetArrayItem("Text", "nameType");
			menuNode.InitAndSetArrayItem("Internal", "linkType");
			menuNode.InitAndSetArrayItem(MVCFunctions.strtolower(new XVar("List")), "pageType");
			menuNode.InitAndSetArrayItem("", "pageId");
			menuNode.InitAndSetArrayItem("None", "openType");
			menuNode.InitAndSetArrayItem("", "icon");
			menuNode.InitAndSetArrayItem("0", "iconType");
			menuNode.InitAndSetArrayItem("1", "iconShow");
			menuNode.InitAndSetArrayItem("", "color");
			menuNode.InitAndSetArrayItem("Rspd Application Received", "title");
			menuNodes.InitAndSetArrayItem(menuNode, null);
			GlobalVars.menuNodesCache.InitAndSetArrayItem(menuNodes, "main");
			return null;
		}
	}
}
