using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_radioequipment
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["radioequipment"] = SettingsMap.GetArray();
			tdataArray["radioequipment"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["radioequipment"][".ShortName"] = "radioequipment";
			tdataArray["radioequipment"][".OwnerID"] = "";
			tdataArray["radioequipment"][".OriginalTable"] = "dbo.radioEquipment";
			tdataArray["radioequipment"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\",\"list1\"],\"masterlist\":[\"masterlist\"],\"masterprint\":[\"masterprint\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}"));
			tdataArray["radioequipment"][".originalPagesByType"] = tdataArray["radioequipment"][".pagesByType"];
			tdataArray["radioequipment"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\",\"list1\"],\"masterlist\":[\"masterlist\"],\"masterprint\":[\"masterprint\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}")));
			tdataArray["radioequipment"][".originalPages"] = tdataArray["radioequipment"][".pages"];
			tdataArray["radioequipment"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"add\":\"add\",\"edit\":\"edit\",\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"masterlist\":\"masterlist\",\"masterprint\":\"masterprint\",\"print\":\"print\",\"search\":\"search\",\"view\":\"view\"}"));
			tdataArray["radioequipment"][".originalDefaultPages"] = tdataArray["radioequipment"][".defaultPages"];
			fieldLabelsArray["radioequipment"] = SettingsMap.GetArray();
			fieldToolTipsArray["radioequipment"] = SettingsMap.GetArray();
			pageTitlesArray["radioequipment"] = SettingsMap.GetArray();
			placeHoldersArray["radioequipment"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["radioequipment"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["radioequipment"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["radioequipment"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["radioequipment"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["radioequipment"]["English"]["id"] = "Id";
				fieldToolTipsArray["radioequipment"]["English"]["id"] = "";
				placeHoldersArray["radioequipment"]["English"]["id"] = "";
				fieldLabelsArray["radioequipment"]["English"]["makeModelA"] = "Make/Model:";
				fieldToolTipsArray["radioequipment"]["English"]["makeModelA"] = "";
				placeHoldersArray["radioequipment"]["English"]["makeModelA"] = "";
				fieldLabelsArray["radioequipment"]["English"]["capacityA"] = "Capacity:";
				fieldToolTipsArray["radioequipment"]["English"]["capacityA"] = "";
				placeHoldersArray["radioequipment"]["English"]["capacityA"] = "";
				fieldLabelsArray["radioequipment"]["English"]["powerA"] = "Output Power:";
				fieldToolTipsArray["radioequipment"]["English"]["powerA"] = "";
				placeHoldersArray["radioequipment"]["English"]["powerA"] = "";
				fieldLabelsArray["radioequipment"]["English"]["modA"] = "Modulation:";
				fieldToolTipsArray["radioequipment"]["English"]["modA"] = "";
				placeHoldersArray["radioequipment"]["English"]["modA"] = "";
				fieldLabelsArray["radioequipment"]["English"]["BWEA"] = "Bandwidth & Emmission:";
				fieldToolTipsArray["radioequipment"]["English"]["BWEA"] = "";
				placeHoldersArray["radioequipment"]["English"]["BWEA"] = "";
				fieldLabelsArray["radioequipment"]["English"]["serialNoA"] = "Serial No:";
				fieldToolTipsArray["radioequipment"]["English"]["serialNoA"] = "";
				placeHoldersArray["radioequipment"]["English"]["serialNoA"] = "";
				fieldLabelsArray["radioequipment"]["English"]["makeModelB"] = "Make Model:";
				fieldToolTipsArray["radioequipment"]["English"]["makeModelB"] = "";
				placeHoldersArray["radioequipment"]["English"]["makeModelB"] = "";
				fieldLabelsArray["radioequipment"]["English"]["capacityB"] = "Capacity:";
				fieldToolTipsArray["radioequipment"]["English"]["capacityB"] = "";
				placeHoldersArray["radioequipment"]["English"]["capacityB"] = "";
				fieldLabelsArray["radioequipment"]["English"]["powerB"] = "Output Power:";
				fieldToolTipsArray["radioequipment"]["English"]["powerB"] = "";
				placeHoldersArray["radioequipment"]["English"]["powerB"] = "";
				fieldLabelsArray["radioequipment"]["English"]["modB"] = "Modulation:";
				fieldToolTipsArray["radioequipment"]["English"]["modB"] = "";
				placeHoldersArray["radioequipment"]["English"]["modB"] = "";
				fieldLabelsArray["radioequipment"]["English"]["BWEB"] = "Bandwidth & Emmission:";
				fieldToolTipsArray["radioequipment"]["English"]["BWEB"] = "";
				placeHoldersArray["radioequipment"]["English"]["BWEB"] = "";
				fieldLabelsArray["radioequipment"]["English"]["serialNoB"] = "Serial No:";
				fieldToolTipsArray["radioequipment"]["English"]["serialNoB"] = "";
				placeHoldersArray["radioequipment"]["English"]["serialNoB"] = "";
				fieldLabelsArray["radioequipment"]["English"]["rspdID"] = "Rspd ID";
				fieldToolTipsArray["radioequipment"]["English"]["rspdID"] = "";
				placeHoldersArray["radioequipment"]["English"]["rspdID"] = "";
				fieldLabelsArray["radioequipment"]["English"]["txA"] = "Tx:";
				fieldToolTipsArray["radioequipment"]["English"]["txA"] = "";
				placeHoldersArray["radioequipment"]["English"]["txA"] = "";
				fieldLabelsArray["radioequipment"]["English"]["txB"] = "Tx:";
				fieldToolTipsArray["radioequipment"]["English"]["txB"] = "";
				placeHoldersArray["radioequipment"]["English"]["txB"] = "";
				fieldLabelsArray["radioequipment"]["English"]["rxA"] = "Rx:";
				fieldToolTipsArray["radioequipment"]["English"]["rxA"] = "";
				placeHoldersArray["radioequipment"]["English"]["rxA"] = "";
				fieldLabelsArray["radioequipment"]["English"]["rxB"] = "Rx:";
				fieldToolTipsArray["radioequipment"]["English"]["rxB"] = "";
				placeHoldersArray["radioequipment"]["English"]["rxB"] = "";
				fieldLabelsArray["radioequipment"]["English"]["frequencyRange"] = "Frequency Range";
				fieldToolTipsArray["radioequipment"]["English"]["frequencyRange"] = "";
				placeHoldersArray["radioequipment"]["English"]["frequencyRange"] = "";
				fieldLabelsArray["radioequipment"]["English"]["frequencyRangeB"] = "Frequency Range B";
				fieldToolTipsArray["radioequipment"]["English"]["frequencyRangeB"] = "";
				placeHoldersArray["radioequipment"]["English"]["frequencyRangeB"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["radioequipment"]["English"])))
				{
					tdataArray["radioequipment"][".isUseToolTips"] = true;
				}
			}
			tdataArray["radioequipment"][".NCSearch"] = true;
			tdataArray["radioequipment"][".shortTableName"] = "radioequipment";
			tdataArray["radioequipment"][".nSecOptions"] = 0;
			tdataArray["radioequipment"][".mainTableOwnerID"] = "";
			tdataArray["radioequipment"][".entityType"] = 0;
			tdataArray["radioequipment"][".connId"] = "RSPDDB_at_172_16_0_80";
			tdataArray["radioequipment"][".strOriginalTableName"] = "dbo.radioEquipment";
			tdataArray["radioequipment"][".showAddInPopup"] = false;
			tdataArray["radioequipment"][".showEditInPopup"] = false;
			tdataArray["radioequipment"][".showViewInPopup"] = false;
			tdataArray["radioequipment"][".listAjax"] = false;
			tdataArray["radioequipment"][".audit"] = true;
			tdataArray["radioequipment"][".locking"] = false;
			GlobalVars.pages = tdataArray["radioequipment"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["radioequipment"][".edit"] = true;
				tdataArray["radioequipment"][".afterEditAction"] = 1;
				tdataArray["radioequipment"][".closePopupAfterEdit"] = 1;
				tdataArray["radioequipment"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["radioequipment"][".add"] = true;
				tdataArray["radioequipment"][".afterAddAction"] = 1;
				tdataArray["radioequipment"][".closePopupAfterAdd"] = 1;
				tdataArray["radioequipment"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["radioequipment"][".list"] = true;
			}
			tdataArray["radioequipment"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["radioequipment"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["radioequipment"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["radioequipment"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["radioequipment"][".printFriendly"] = true;
			}
			tdataArray["radioequipment"][".showSimpleSearchOptions"] = true;
			tdataArray["radioequipment"][".allowShowHideFields"] = true;
			tdataArray["radioequipment"][".allowFieldsReordering"] = true;
			tdataArray["radioequipment"][".isUseAjaxSuggest"] = true;


			tdataArray["radioequipment"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["radioequipment"][".buttonsAdded"] = false;
			tdataArray["radioequipment"][".addPageEvents"] = true;
			tdataArray["radioequipment"][".isUseTimeForSearch"] = false;
			tdataArray["radioequipment"][".badgeColor"] = "daa520";
			tdataArray["radioequipment"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["radioequipment"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["radioequipment"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["radioequipment"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["radioequipment"][".googleLikeFields"].Add("id");
			tdataArray["radioequipment"][".googleLikeFields"].Add("makeModelA");
			tdataArray["radioequipment"][".googleLikeFields"].Add("capacityA");
			tdataArray["radioequipment"][".googleLikeFields"].Add("powerA");
			tdataArray["radioequipment"][".googleLikeFields"].Add("modA");
			tdataArray["radioequipment"][".googleLikeFields"].Add("BWEA");
			tdataArray["radioequipment"][".googleLikeFields"].Add("serialNoA");
			tdataArray["radioequipment"][".googleLikeFields"].Add("makeModelB");
			tdataArray["radioequipment"][".googleLikeFields"].Add("capacityB");
			tdataArray["radioequipment"][".googleLikeFields"].Add("powerB");
			tdataArray["radioequipment"][".googleLikeFields"].Add("modB");
			tdataArray["radioequipment"][".googleLikeFields"].Add("BWEB");
			tdataArray["radioequipment"][".googleLikeFields"].Add("serialNoB");
			tdataArray["radioequipment"][".googleLikeFields"].Add("rspdID");
			tdataArray["radioequipment"][".googleLikeFields"].Add("txA");
			tdataArray["radioequipment"][".googleLikeFields"].Add("txB");
			tdataArray["radioequipment"][".googleLikeFields"].Add("rxA");
			tdataArray["radioequipment"][".googleLikeFields"].Add("rxB");
			tdataArray["radioequipment"][".googleLikeFields"].Add("frequencyRange");
			tdataArray["radioequipment"][".googleLikeFields"].Add("frequencyRangeB");
			tdataArray["radioequipment"][".tableType"] = "list";
			tdataArray["radioequipment"][".printerPageOrientation"] = 0;
			tdataArray["radioequipment"][".nPrinterPageScale"] = 100;
			tdataArray["radioequipment"][".nPrinterSplitRecords"] = 40;
			tdataArray["radioequipment"][".geocodingEnabled"] = false;
			tdataArray["radioequipment"][".pageSize"] = 20;
			tdataArray["radioequipment"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["radioequipment"][".strOrderBy"] = tstrOrderBy;
			tdataArray["radioequipment"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["radioequipment"][".sqlHead"] = "SELECT id,  	makeModelA,  	capacityA,  	powerA,  	modA,  	BWEA,  	serialNoA,  	makeModelB,  	capacityB,  	powerB,  	modB,  	BWEB,  	serialNoB,  	rspdID,  	txA,  	txB,  	rxA,  	rxB,  	frequencyRange,  	frequencyRangeB";
			tdataArray["radioequipment"][".sqlFrom"] = "FROM dbo.radioEquipment";
			tdataArray["radioequipment"][".sqlWhereExpr"] = "";
			tdataArray["radioequipment"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["radioequipment"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["radioequipment"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["radioequipment"][".highlightSearchResults"] = true;
			tableKeysArray["radioequipment"] = SettingsMap.GetArray();
			tableKeysArray["radioequipment"].Add("id");
			tdataArray["radioequipment"][".Keys"] = tableKeysArray["radioequipment"];
			tdataArray["radioequipment"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "id";
			fdata["GoodName"] = "id";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","id");
			fdata["FieldType"] = 3;
			fdata["AutoInc"] = true;
			fdata["strField"] = "id";
			fdata["sourceSingle"] = "id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["id"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "makeModelA";
			fdata["GoodName"] = "makeModelA";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","makeModelA");
			fdata["FieldType"] = 200;
			fdata["strField"] = "makeModelA";
			fdata["sourceSingle"] = "makeModelA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "makeModelA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["makeModelA"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("makeModelA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "capacityA";
			fdata["GoodName"] = "capacityA";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","capacityA");
			fdata["FieldType"] = 200;
			fdata["strField"] = "capacityA";
			fdata["sourceSingle"] = "capacityA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "capacityA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["capacityA"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("capacityA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "powerA";
			fdata["GoodName"] = "powerA";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","powerA");
			fdata["FieldType"] = 200;
			fdata["strField"] = "powerA";
			fdata["sourceSingle"] = "powerA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "powerA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 0;
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LookupValues"] = SettingsMap.GetArray();
			edata["LookupValues"].Add("dBm");
			edata["LookupValues"].Add("Watts");
			edata["SelectSize"] = 1;
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["powerA"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("powerA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "modA";
			fdata["GoodName"] = "modA";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","modA");
			fdata["FieldType"] = 200;
			fdata["strField"] = "modA";
			fdata["sourceSingle"] = "modA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "modA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["modA"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("modA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "BWEA";
			fdata["GoodName"] = "BWEA";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","BWEA");
			fdata["FieldType"] = 200;
			fdata["strField"] = "BWEA";
			fdata["sourceSingle"] = "BWEA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "BWEA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["BWEA"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("BWEA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "serialNoA";
			fdata["GoodName"] = "serialNoA";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","serialNoA");
			fdata["FieldType"] = 200;
			fdata["strField"] = "serialNoA";
			fdata["sourceSingle"] = "serialNoA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "serialNoA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["serialNoA"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("serialNoA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "makeModelB";
			fdata["GoodName"] = "makeModelB";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","makeModelB");
			fdata["FieldType"] = 200;
			fdata["strField"] = "makeModelB";
			fdata["sourceSingle"] = "makeModelB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "makeModelB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["makeModelB"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("makeModelB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "capacityB";
			fdata["GoodName"] = "capacityB";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","capacityB");
			fdata["FieldType"] = 200;
			fdata["strField"] = "capacityB";
			fdata["sourceSingle"] = "capacityB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "capacityB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["capacityB"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("capacityB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "powerB";
			fdata["GoodName"] = "powerB";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","powerB");
			fdata["FieldType"] = 200;
			fdata["strField"] = "powerB";
			fdata["sourceSingle"] = "powerB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "powerB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Equals";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["powerB"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("powerB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "modB";
			fdata["GoodName"] = "modB";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","modB");
			fdata["FieldType"] = 200;
			fdata["strField"] = "modB";
			fdata["sourceSingle"] = "modB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "modB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["modB"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("modB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "BWEB";
			fdata["GoodName"] = "BWEB";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","BWEB");
			fdata["FieldType"] = 200;
			fdata["strField"] = "BWEB";
			fdata["sourceSingle"] = "BWEB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "BWEB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["BWEB"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("BWEB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "serialNoB";
			fdata["GoodName"] = "serialNoB";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","serialNoB");
			fdata["FieldType"] = 200;
			fdata["strField"] = "serialNoB";
			fdata["sourceSingle"] = "serialNoB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "serialNoB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["serialNoB"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("serialNoB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 14;
			fdata["strName"] = "rspdID";
			fdata["GoodName"] = "rspdID";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","rspdID");
			fdata["FieldType"] = 3;
			fdata["strField"] = "rspdID";
			fdata["sourceSingle"] = "rspdID";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "rspdID";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["rspdID"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("rspdID");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 15;
			fdata["strName"] = "txA";
			fdata["GoodName"] = "txA";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","txA");
			fdata["FieldType"] = 14;
			fdata["strField"] = "txA";
			fdata["sourceSingle"] = "txA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "txA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["txA"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("txA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 16;
			fdata["strName"] = "txB";
			fdata["GoodName"] = "txB";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","txB");
			fdata["FieldType"] = 14;
			fdata["strField"] = "txB";
			fdata["sourceSingle"] = "txB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "txB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["txB"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("txB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 17;
			fdata["strName"] = "rxA";
			fdata["GoodName"] = "rxA";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","rxA");
			fdata["FieldType"] = 14;
			fdata["strField"] = "rxA";
			fdata["sourceSingle"] = "rxA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "rxA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["rxA"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("rxA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 18;
			fdata["strName"] = "rxB";
			fdata["GoodName"] = "rxB";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","rxB");
			fdata["FieldType"] = 14;
			fdata["strField"] = "rxB";
			fdata["sourceSingle"] = "rxB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "rxB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["rxB"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("rxB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 19;
			fdata["strName"] = "frequencyRange";
			fdata["GoodName"] = "frequencyRange";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","frequencyRange");
			fdata["FieldType"] = 200;
			fdata["strField"] = "frequencyRange";
			fdata["sourceSingle"] = "frequencyRange";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "frequencyRange";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["frequencyRange"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("frequencyRange");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 20;
			fdata["strName"] = "frequencyRangeB";
			fdata["GoodName"] = "frequencyRangeB";
			fdata["ownerTable"] = "dbo.radioEquipment";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_radioEquipment","frequencyRangeB");
			fdata["FieldType"] = 200;
			fdata["strField"] = "frequencyRangeB";
			fdata["sourceSingle"] = "frequencyRangeB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "frequencyRangeB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["radioequipment"]["frequencyRangeB"] = fdata;
			tdataArray["radioequipment"][".searchableFields"].Add("frequencyRangeB");
			GlobalVars.tables_data["dbo.radioEquipment"] = tdataArray["radioequipment"];
			GlobalVars.field_labels["dbo_radioEquipment"] = fieldLabelsArray["radioequipment"];
			GlobalVars.fieldToolTips["dbo_radioEquipment"] = fieldToolTipsArray["radioequipment"];
			GlobalVars.placeHolders["dbo_radioEquipment"] = placeHoldersArray["radioequipment"];
			GlobalVars.page_titles["dbo_radioEquipment"] = pageTitlesArray["radioequipment"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.radioEquipment"));
			GlobalVars.detailsTablesData["dbo.radioEquipment"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.radioEquipment"] = SettingsMap.GetArray();


			strOriginalDetailsTable = "dbo.rspdHeader";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "dbo.rspdHeader";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "dbo_rspdheader";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo.radioEquipment"][0] = masterParams;
			GlobalVars.masterTablesData["dbo.radioEquipment"][0]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.radioEquipment"][0]["masterKeys"].Add("ID");
			GlobalVars.masterTablesData["dbo.radioEquipment"][0]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.radioEquipment"][0]["detailKeys"].Add("rspdID");

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "id,  	makeModelA,  	capacityA,  	powerA,  	modA,  	BWEA,  	serialNoA,  	makeModelB,  	capacityB,  	powerB,  	modB,  	BWEB,  	serialNoB,  	rspdID,  	txA,  	txB,  	rxA,  	rxB,  	frequencyRange,  	frequencyRangeB";
protoArray["0"]["m_strFrom"] = "FROM dbo.radioEquipment";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "id", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["6"]["m_sql"] = "id";
protoArray["6"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "makeModelA", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["8"]["m_sql"] = "makeModelA";
protoArray["8"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "capacityA", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["10"]["m_sql"] = "capacityA";
protoArray["10"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "powerA", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["12"]["m_sql"] = "powerA";
protoArray["12"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "modA", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["14"]["m_sql"] = "modA";
protoArray["14"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "BWEA", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["16"]["m_sql"] = "BWEA";
protoArray["16"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "serialNoA", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["18"]["m_sql"] = "serialNoA";
protoArray["18"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "makeModelB", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["20"]["m_sql"] = "makeModelB";
protoArray["20"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "capacityB", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["22"]["m_sql"] = "capacityB";
protoArray["22"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "powerB", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["24"]["m_sql"] = "powerB";
protoArray["24"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "modB", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["26"]["m_sql"] = "modB";
protoArray["26"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "BWEB", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["28"]["m_sql"] = "BWEB";
protoArray["28"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "serialNoB", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["30"]["m_sql"] = "serialNoB";
protoArray["30"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["32"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "rspdID", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["32"]["m_sql"] = "rspdID";
protoArray["32"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["32"]["m_expr"] = obj;
protoArray["32"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["32"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["34"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "txA", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["34"]["m_sql"] = "txA";
protoArray["34"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["34"]["m_expr"] = obj;
protoArray["34"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["34"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["36"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "txB", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["36"]["m_sql"] = "txB";
protoArray["36"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["36"]["m_expr"] = obj;
protoArray["36"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["36"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["38"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "rxA", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["38"]["m_sql"] = "rxA";
protoArray["38"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["38"]["m_expr"] = obj;
protoArray["38"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["38"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["40"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "rxB", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["40"]["m_sql"] = "rxB";
protoArray["40"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["40"]["m_expr"] = obj;
protoArray["40"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["40"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["42"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "frequencyRange", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["42"]["m_sql"] = "frequencyRange";
protoArray["42"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["42"]["m_expr"] = obj;
protoArray["42"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["42"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["44"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "frequencyRangeB", "m_strTable", "dbo.radioEquipment", "m_srcTableName", "dbo.radioEquipment"));

protoArray["44"]["m_sql"] = "frequencyRangeB";
protoArray["44"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["44"]["m_expr"] = obj;
protoArray["44"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["44"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["46"] = SettingsMap.GetArray();
protoArray["46"]["m_link"] = "SQLL_MAIN";
protoArray["47"] = SettingsMap.GetArray();
protoArray["47"]["m_strName"] = "dbo.radioEquipment";
protoArray["47"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["47"]["m_columns"] = SettingsMap.GetArray();
protoArray["47"]["m_columns"].Add("id");
protoArray["47"]["m_columns"].Add("makeModelA");
protoArray["47"]["m_columns"].Add("capacityA");
protoArray["47"]["m_columns"].Add("powerA");
protoArray["47"]["m_columns"].Add("modA");
protoArray["47"]["m_columns"].Add("BWEA");
protoArray["47"]["m_columns"].Add("serialNoA");
protoArray["47"]["m_columns"].Add("makeModelB");
protoArray["47"]["m_columns"].Add("capacityB");
protoArray["47"]["m_columns"].Add("powerB");
protoArray["47"]["m_columns"].Add("modB");
protoArray["47"]["m_columns"].Add("BWEB");
protoArray["47"]["m_columns"].Add("serialNoB");
protoArray["47"]["m_columns"].Add("rspdID");
protoArray["47"]["m_columns"].Add("txA");
protoArray["47"]["m_columns"].Add("txB");
protoArray["47"]["m_columns"].Add("rxA");
protoArray["47"]["m_columns"].Add("rxB");
protoArray["47"]["m_columns"].Add("frequencyRange");
protoArray["47"]["m_columns"].Add("frequencyRangeB");
obj = new SQLTable(protoArray["47"]);

protoArray["46"]["m_table"] = obj;
protoArray["46"]["m_sql"] = "dbo.radioEquipment";
protoArray["46"]["m_alias"] = "";
protoArray["46"]["m_srcTableName"] = "dbo.radioEquipment";
protoArray["48"] = SettingsMap.GetArray();
protoArray["48"]["m_sql"] = "";
protoArray["48"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["48"]["m_column"] = obj;
protoArray["48"]["m_contained"] = SettingsMap.GetArray();
protoArray["48"]["m_strCase"] = "";
protoArray["48"]["m_havingmode"] = false;
protoArray["48"]["m_inBrackets"] = false;
protoArray["48"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["48"]);

protoArray["46"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["46"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.radioEquipment";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["radioequipment"] = obj;

				
		
			tdataArray["radioequipment"][".sqlquery"] = queryData_Array["radioequipment"];
			tdataArray["radioequipment"][".hasEvents"] = true;
		}
	}

}
