using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_rspdlineb
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["rspdlineb"] = SettingsMap.GetArray();
			tdataArray["rspdlineb"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["rspdlineb"][".ShortName"] = "rspdlineb";
			tdataArray["rspdlineb"][".OwnerID"] = "";
			tdataArray["rspdlineb"][".OriginalTable"] = "dbo.rspdLineB";
			tdataArray["rspdlineb"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}"));
			tdataArray["rspdlineb"][".originalPagesByType"] = tdataArray["rspdlineb"][".pagesByType"];
			tdataArray["rspdlineb"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}")));
			tdataArray["rspdlineb"][".originalPages"] = tdataArray["rspdlineb"][".pages"];
			tdataArray["rspdlineb"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"add\":\"add\",\"edit\":\"edit\",\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\",\"view\":\"view\"}"));
			tdataArray["rspdlineb"][".originalDefaultPages"] = tdataArray["rspdlineb"][".defaultPages"];
			fieldLabelsArray["rspdlineb"] = SettingsMap.GetArray();
			fieldToolTipsArray["rspdlineb"] = SettingsMap.GetArray();
			pageTitlesArray["rspdlineb"] = SettingsMap.GetArray();
			placeHoldersArray["rspdlineb"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["rspdlineb"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["rspdlineb"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["rspdlineb"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["rspdlineb"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["rspdlineb"]["English"]["ID"] = "ID";
				fieldToolTipsArray["rspdlineb"]["English"]["ID"] = "";
				placeHoldersArray["rspdlineb"]["English"]["ID"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["HdrID"] = "Hdr ID";
				fieldToolTipsArray["rspdlineb"]["English"]["HdrID"] = "";
				placeHoldersArray["rspdlineb"]["English"]["HdrID"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["LOC_UNIT_STA_B"] = "LOC UNIT STA B";
				fieldToolTipsArray["rspdlineb"]["English"]["LOC_UNIT_STA_B"] = "";
				placeHoldersArray["rspdlineb"]["English"]["LOC_UNIT_STA_B"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["LOC_STREET_STA_B"] = "LOC STREET STA B";
				fieldToolTipsArray["rspdlineb"]["English"]["LOC_STREET_STA_B"] = "";
				placeHoldersArray["rspdlineb"]["English"]["LOC_STREET_STA_B"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["LOC_BRGY_STA_B"] = "LOC BRGY STA B";
				fieldToolTipsArray["rspdlineb"]["English"]["LOC_BRGY_STA_B"] = "";
				placeHoldersArray["rspdlineb"]["English"]["LOC_BRGY_STA_B"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["CITY_MUNICIPALITY_STA_B"] = "CITY/MUNICIPALITY STA B";
				fieldToolTipsArray["rspdlineb"]["English"]["CITY_MUNICIPALITY_STA_B"] = "";
				placeHoldersArray["rspdlineb"]["English"]["CITY_MUNICIPALITY_STA_B"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["PROVINCE_STA_B"] = "PROVINCE STA B";
				fieldToolTipsArray["rspdlineb"]["English"]["PROVINCE_STA_B"] = "";
				placeHoldersArray["rspdlineb"]["English"]["PROVINCE_STA_B"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["ZIPCODE_STA_B"] = "ZIPCODE STA B";
				fieldToolTipsArray["rspdlineb"]["English"]["ZIPCODE_STA_B"] = "";
				placeHoldersArray["rspdlineb"]["English"]["ZIPCODE_STA_B"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["eDegB"] = "E Deg B";
				fieldToolTipsArray["rspdlineb"]["English"]["eDegB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["eDegB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["eMinB"] = "E Min B";
				fieldToolTipsArray["rspdlineb"]["English"]["eMinB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["eMinB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["eSecB"] = "E Sec B";
				fieldToolTipsArray["rspdlineb"]["English"]["eSecB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["eSecB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["nDegB"] = "N Deg B";
				fieldToolTipsArray["rspdlineb"]["English"]["nDegB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["nDegB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["nMinB"] = "N Min B";
				fieldToolTipsArray["rspdlineb"]["English"]["nMinB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["nMinB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["nSecB"] = "N Sec B";
				fieldToolTipsArray["rspdlineb"]["English"]["nSecB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["nSecB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["elevationB"] = "Elevation B";
				fieldToolTipsArray["rspdlineb"]["English"]["elevationB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["elevationB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["aMakeTypeModelB"] = "A Make Type Model B";
				fieldToolTipsArray["rspdlineb"]["English"]["aMakeTypeModelB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["aMakeTypeModelB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["gainB"] = "Gain B";
				fieldToolTipsArray["rspdlineb"]["English"]["gainB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["gainB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["diameterB"] = "Diameter B";
				fieldToolTipsArray["rspdlineb"]["English"]["diameterB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["diameterB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["beamwidthB"] = "Beamwidth B";
				fieldToolTipsArray["rspdlineb"]["English"]["beamwidthB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["beamwidthB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["polarizationB"] = "Polarization B";
				fieldToolTipsArray["rspdlineb"]["English"]["polarizationB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["polarizationB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["azimuthB"] = "Azimuth B";
				fieldToolTipsArray["rspdlineb"]["English"]["azimuthB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["azimuthB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["elevAngleB"] = "Elev Angle B";
				fieldToolTipsArray["rspdlineb"]["English"]["elevAngleB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["elevAngleB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["heightAGLB"] = "Height AGLB";
				fieldToolTipsArray["rspdlineb"]["English"]["heightAGLB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["heightAGLB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["feederLengthB"] = "Feeder Length B";
				fieldToolTipsArray["rspdlineb"]["English"]["feederLengthB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["feederLengthB"] = "";
				fieldLabelsArray["rspdlineb"]["English"]["callSignB"] = "Call Sign B";
				fieldToolTipsArray["rspdlineb"]["English"]["callSignB"] = "";
				placeHoldersArray["rspdlineb"]["English"]["callSignB"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["rspdlineb"]["English"])))
				{
					tdataArray["rspdlineb"][".isUseToolTips"] = true;
				}
			}
			tdataArray["rspdlineb"][".NCSearch"] = true;
			tdataArray["rspdlineb"][".shortTableName"] = "rspdlineb";
			tdataArray["rspdlineb"][".nSecOptions"] = 0;
			tdataArray["rspdlineb"][".mainTableOwnerID"] = "";
			tdataArray["rspdlineb"][".entityType"] = 0;
			tdataArray["rspdlineb"][".connId"] = "RSPDDB_at_172_16_0_80";
			tdataArray["rspdlineb"][".strOriginalTableName"] = "dbo.rspdLineB";
			tdataArray["rspdlineb"][".showAddInPopup"] = false;
			tdataArray["rspdlineb"][".showEditInPopup"] = false;
			tdataArray["rspdlineb"][".showViewInPopup"] = false;
			tdataArray["rspdlineb"][".listAjax"] = false;
			tdataArray["rspdlineb"][".audit"] = false;
			tdataArray["rspdlineb"][".locking"] = false;
			GlobalVars.pages = tdataArray["rspdlineb"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["rspdlineb"][".edit"] = true;
				tdataArray["rspdlineb"][".afterEditAction"] = 1;
				tdataArray["rspdlineb"][".closePopupAfterEdit"] = 1;
				tdataArray["rspdlineb"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["rspdlineb"][".add"] = true;
				tdataArray["rspdlineb"][".afterAddAction"] = 1;
				tdataArray["rspdlineb"][".closePopupAfterAdd"] = 1;
				tdataArray["rspdlineb"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["rspdlineb"][".list"] = true;
			}
			tdataArray["rspdlineb"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["rspdlineb"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["rspdlineb"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["rspdlineb"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["rspdlineb"][".printFriendly"] = true;
			}
			tdataArray["rspdlineb"][".showSimpleSearchOptions"] = true;
			tdataArray["rspdlineb"][".allowShowHideFields"] = true;
			tdataArray["rspdlineb"][".allowFieldsReordering"] = true;
			tdataArray["rspdlineb"][".isUseAjaxSuggest"] = true;


			tdataArray["rspdlineb"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["rspdlineb"][".buttonsAdded"] = false;
			tdataArray["rspdlineb"][".addPageEvents"] = false;
			tdataArray["rspdlineb"][".isUseTimeForSearch"] = false;
			tdataArray["rspdlineb"][".badgeColor"] = "7B68EE";
			tdataArray["rspdlineb"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["rspdlineb"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["rspdlineb"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["rspdlineb"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["rspdlineb"][".googleLikeFields"].Add("ID");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("HdrID");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("LOC_UNIT_STA_B");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("LOC_STREET_STA_B");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("LOC_BRGY_STA_B");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("CITY/MUNICIPALITY_STA_B");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("PROVINCE_STA_B");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("ZIPCODE_STA_B");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("eDegB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("eMinB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("eSecB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("nDegB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("nMinB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("nSecB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("elevationB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("aMakeTypeModelB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("gainB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("diameterB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("beamwidthB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("polarizationB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("azimuthB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("elevAngleB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("heightAGLB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("feederLengthB");
			tdataArray["rspdlineb"][".googleLikeFields"].Add("callSignB");
			tdataArray["rspdlineb"][".tableType"] = "list";
			tdataArray["rspdlineb"][".printerPageOrientation"] = 0;
			tdataArray["rspdlineb"][".nPrinterPageScale"] = 100;
			tdataArray["rspdlineb"][".nPrinterSplitRecords"] = 40;
			tdataArray["rspdlineb"][".geocodingEnabled"] = false;
			tdataArray["rspdlineb"][".pageSize"] = 20;
			tdataArray["rspdlineb"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["rspdlineb"][".strOrderBy"] = tstrOrderBy;
			tdataArray["rspdlineb"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["rspdlineb"][".sqlHead"] = "SELECT ID,  	HdrID,  	LOC_UNIT_STA_B,  	LOC_STREET_STA_B,  	LOC_BRGY_STA_B,  	[CITY/MUNICIPALITY_STA_B],  	PROVINCE_STA_B,  	ZIPCODE_STA_B,  	eDegB,  	eMinB,  	eSecB,  	nDegB,  	nMinB,  	nSecB,  	elevationB,  	aMakeTypeModelB,  	gainB,  	diameterB,  	beamwidthB,  	polarizationB,  	azimuthB,  	elevAngleB,  	heightAGLB,  	feederLengthB,  	callSignB";
			tdataArray["rspdlineb"][".sqlFrom"] = "FROM dbo.rspdLineB";
			tdataArray["rspdlineb"][".sqlWhereExpr"] = "";
			tdataArray["rspdlineb"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["rspdlineb"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["rspdlineb"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["rspdlineb"][".highlightSearchResults"] = true;
			tableKeysArray["rspdlineb"] = SettingsMap.GetArray();
			tableKeysArray["rspdlineb"].Add("ID");
			tdataArray["rspdlineb"][".Keys"] = tableKeysArray["rspdlineb"];
			tdataArray["rspdlineb"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "ID";
			fdata["GoodName"] = "ID";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","ID");
			fdata["FieldType"] = 3;
			fdata["AutoInc"] = true;
			fdata["strField"] = "ID";
			fdata["sourceSingle"] = "ID";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ID";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["ID"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("ID");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "HdrID";
			fdata["GoodName"] = "HdrID";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","HdrID");
			fdata["FieldType"] = 3;
			fdata["strField"] = "HdrID";
			fdata["sourceSingle"] = "HdrID";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "HdrID";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Lookup wizard");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["LookupType"] = 2;
			edata["LookupTable"] = "dbo.rspdHeader";
			edata["autoCompleteFieldsOnEdit"] = 0;
			edata["autoCompleteFields"] = SettingsMap.GetArray();
			edata["LCType"] = 0;
			edata["LinkField"] = "ID";
			edata["LinkFieldType"] = 3;
			edata["DisplayField"] = "referenceID";
			edata["LookupOrderBy"] = "";
			edata["SelectSize"] = 1;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["HdrID"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("HdrID");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "LOC_UNIT_STA_B";
			fdata["GoodName"] = "LOC_UNIT_STA_B";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","LOC_UNIT_STA_B");
			fdata["FieldType"] = 200;
			fdata["strField"] = "LOC_UNIT_STA_B";
			fdata["sourceSingle"] = "LOC_UNIT_STA_B";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "LOC_UNIT_STA_B";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["LOC_UNIT_STA_B"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("LOC_UNIT_STA_B");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "LOC_STREET_STA_B";
			fdata["GoodName"] = "LOC_STREET_STA_B";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","LOC_STREET_STA_B");
			fdata["FieldType"] = 200;
			fdata["strField"] = "LOC_STREET_STA_B";
			fdata["sourceSingle"] = "LOC_STREET_STA_B";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "LOC_STREET_STA_B";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["LOC_STREET_STA_B"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("LOC_STREET_STA_B");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "LOC_BRGY_STA_B";
			fdata["GoodName"] = "LOC_BRGY_STA_B";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","LOC_BRGY_STA_B");
			fdata["FieldType"] = 200;
			fdata["strField"] = "LOC_BRGY_STA_B";
			fdata["sourceSingle"] = "LOC_BRGY_STA_B";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "LOC_BRGY_STA_B";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["LOC_BRGY_STA_B"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("LOC_BRGY_STA_B");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "CITY/MUNICIPALITY_STA_B";
			fdata["GoodName"] = "CITY_MUNICIPALITY_STA_B";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","CITY_MUNICIPALITY_STA_B");
			fdata["FieldType"] = 200;
			fdata["strField"] = "CITY/MUNICIPALITY_STA_B";
			fdata["sourceSingle"] = "CITY/MUNICIPALITY_STA_B";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "[CITY/MUNICIPALITY_STA_B]";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["CITY/MUNICIPALITY_STA_B"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("CITY/MUNICIPALITY_STA_B");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "PROVINCE_STA_B";
			fdata["GoodName"] = "PROVINCE_STA_B";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","PROVINCE_STA_B");
			fdata["FieldType"] = 200;
			fdata["strField"] = "PROVINCE_STA_B";
			fdata["sourceSingle"] = "PROVINCE_STA_B";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "PROVINCE_STA_B";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["PROVINCE_STA_B"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("PROVINCE_STA_B");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "ZIPCODE_STA_B";
			fdata["GoodName"] = "ZIPCODE_STA_B";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","ZIPCODE_STA_B");
			fdata["FieldType"] = 200;
			fdata["strField"] = "ZIPCODE_STA_B";
			fdata["sourceSingle"] = "ZIPCODE_STA_B";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ZIPCODE_STA_B";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["ZIPCODE_STA_B"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("ZIPCODE_STA_B");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "eDegB";
			fdata["GoodName"] = "eDegB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","eDegB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "eDegB";
			fdata["sourceSingle"] = "eDegB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "eDegB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["eDegB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("eDegB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "eMinB";
			fdata["GoodName"] = "eMinB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","eMinB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "eMinB";
			fdata["sourceSingle"] = "eMinB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "eMinB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["eMinB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("eMinB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "eSecB";
			fdata["GoodName"] = "eSecB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","eSecB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "eSecB";
			fdata["sourceSingle"] = "eSecB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "eSecB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["eSecB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("eSecB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "nDegB";
			fdata["GoodName"] = "nDegB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","nDegB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "nDegB";
			fdata["sourceSingle"] = "nDegB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "nDegB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["nDegB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("nDegB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "nMinB";
			fdata["GoodName"] = "nMinB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","nMinB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "nMinB";
			fdata["sourceSingle"] = "nMinB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "nMinB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["nMinB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("nMinB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 14;
			fdata["strName"] = "nSecB";
			fdata["GoodName"] = "nSecB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","nSecB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "nSecB";
			fdata["sourceSingle"] = "nSecB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "nSecB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["nSecB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("nSecB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 15;
			fdata["strName"] = "elevationB";
			fdata["GoodName"] = "elevationB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","elevationB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "elevationB";
			fdata["sourceSingle"] = "elevationB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "elevationB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 6;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["elevationB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("elevationB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 16;
			fdata["strName"] = "aMakeTypeModelB";
			fdata["GoodName"] = "aMakeTypeModelB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","aMakeTypeModelB");
			fdata["FieldType"] = 200;
			fdata["strField"] = "aMakeTypeModelB";
			fdata["sourceSingle"] = "aMakeTypeModelB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "aMakeTypeModelB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=250");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["aMakeTypeModelB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("aMakeTypeModelB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 17;
			fdata["strName"] = "gainB";
			fdata["GoodName"] = "gainB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","gainB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "gainB";
			fdata["sourceSingle"] = "gainB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "gainB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["gainB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("gainB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 18;
			fdata["strName"] = "diameterB";
			fdata["GoodName"] = "diameterB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","diameterB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "diameterB";
			fdata["sourceSingle"] = "diameterB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "diameterB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["diameterB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("diameterB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 19;
			fdata["strName"] = "beamwidthB";
			fdata["GoodName"] = "beamwidthB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","beamwidthB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "beamwidthB";
			fdata["sourceSingle"] = "beamwidthB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "beamwidthB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["beamwidthB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("beamwidthB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 20;
			fdata["strName"] = "polarizationB";
			fdata["GoodName"] = "polarizationB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","polarizationB");
			fdata["FieldType"] = 200;
			fdata["strField"] = "polarizationB";
			fdata["sourceSingle"] = "polarizationB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "polarizationB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=150");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["polarizationB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("polarizationB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 21;
			fdata["strName"] = "azimuthB";
			fdata["GoodName"] = "azimuthB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","azimuthB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "azimuthB";
			fdata["sourceSingle"] = "azimuthB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "azimuthB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["azimuthB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("azimuthB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 22;
			fdata["strName"] = "elevAngleB";
			fdata["GoodName"] = "elevAngleB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","elevAngleB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "elevAngleB";
			fdata["sourceSingle"] = "elevAngleB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "elevAngleB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["elevAngleB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("elevAngleB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 23;
			fdata["strName"] = "heightAGLB";
			fdata["GoodName"] = "heightAGLB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","heightAGLB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "heightAGLB";
			fdata["sourceSingle"] = "heightAGLB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "heightAGLB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["heightAGLB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("heightAGLB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 24;
			fdata["strName"] = "feederLengthB";
			fdata["GoodName"] = "feederLengthB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","feederLengthB");
			fdata["FieldType"] = 131;
			fdata["strField"] = "feederLengthB";
			fdata["sourceSingle"] = "feederLengthB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "feederLengthB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["feederLengthB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("feederLengthB");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 25;
			fdata["strName"] = "callSignB";
			fdata["GoodName"] = "callSignB";
			fdata["ownerTable"] = "dbo.rspdLineB";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineB","callSignB");
			fdata["FieldType"] = 200;
			fdata["strField"] = "callSignB";
			fdata["sourceSingle"] = "callSignB";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "callSignB";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlineb"]["callSignB"] = fdata;
			tdataArray["rspdlineb"][".searchableFields"].Add("callSignB");
			GlobalVars.tables_data["dbo.rspdLineB"] = tdataArray["rspdlineb"];
			GlobalVars.field_labels["dbo_rspdLineB"] = fieldLabelsArray["rspdlineb"];
			GlobalVars.fieldToolTips["dbo_rspdLineB"] = fieldToolTipsArray["rspdlineb"];
			GlobalVars.placeHolders["dbo_rspdLineB"] = placeHoldersArray["rspdlineb"];
			GlobalVars.page_titles["dbo_rspdLineB"] = pageTitlesArray["rspdlineb"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.rspdLineB"));
			GlobalVars.detailsTablesData["dbo.rspdLineB"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.rspdLineB"] = SettingsMap.GetArray();


			strOriginalDetailsTable = "dbo.rspdHeader";
			masterParams = SettingsMap.GetArray();
			masterParams["mDataSourceTable"] = "dbo.rspdHeader";
			masterParams["mOriginalTable"] = strOriginalDetailsTable;
			masterParams["mShortTable"] = "dbo_rspdheader";
			masterParams["masterKeys"] = SettingsMap.GetArray();
			masterParams["detailKeys"] = SettingsMap.GetArray();
			masterParams["type"] = Constants.PAGE_LIST;
			GlobalVars.masterTablesData["dbo.rspdLineB"][0] = masterParams;
			GlobalVars.masterTablesData["dbo.rspdLineB"][0]["masterKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.rspdLineB"][0]["masterKeys"].Add("ID");
			GlobalVars.masterTablesData["dbo.rspdLineB"][0]["detailKeys"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.rspdLineB"][0]["detailKeys"].Add("HdrID");

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "ID,  	HdrID,  	LOC_UNIT_STA_B,  	LOC_STREET_STA_B,  	LOC_BRGY_STA_B,  	[CITY/MUNICIPALITY_STA_B],  	PROVINCE_STA_B,  	ZIPCODE_STA_B,  	eDegB,  	eMinB,  	eSecB,  	nDegB,  	nMinB,  	nSecB,  	elevationB,  	aMakeTypeModelB,  	gainB,  	diameterB,  	beamwidthB,  	polarizationB,  	azimuthB,  	elevAngleB,  	heightAGLB,  	feederLengthB,  	callSignB";
protoArray["0"]["m_strFrom"] = "FROM dbo.rspdLineB";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ID", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["6"]["m_sql"] = "ID";
protoArray["6"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "HdrID", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["8"]["m_sql"] = "HdrID";
protoArray["8"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "LOC_UNIT_STA_B", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["10"]["m_sql"] = "LOC_UNIT_STA_B";
protoArray["10"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "LOC_STREET_STA_B", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["12"]["m_sql"] = "LOC_STREET_STA_B";
protoArray["12"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "LOC_BRGY_STA_B", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["14"]["m_sql"] = "LOC_BRGY_STA_B";
protoArray["14"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "CITY/MUNICIPALITY_STA_B", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["16"]["m_sql"] = "[CITY/MUNICIPALITY_STA_B]";
protoArray["16"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "PROVINCE_STA_B", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["18"]["m_sql"] = "PROVINCE_STA_B";
protoArray["18"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ZIPCODE_STA_B", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["20"]["m_sql"] = "ZIPCODE_STA_B";
protoArray["20"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "eDegB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["22"]["m_sql"] = "eDegB";
protoArray["22"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "eMinB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["24"]["m_sql"] = "eMinB";
protoArray["24"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "eSecB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["26"]["m_sql"] = "eSecB";
protoArray["26"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "nDegB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["28"]["m_sql"] = "nDegB";
protoArray["28"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "nMinB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["30"]["m_sql"] = "nMinB";
protoArray["30"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["32"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "nSecB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["32"]["m_sql"] = "nSecB";
protoArray["32"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["32"]["m_expr"] = obj;
protoArray["32"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["32"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["34"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "elevationB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["34"]["m_sql"] = "elevationB";
protoArray["34"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["34"]["m_expr"] = obj;
protoArray["34"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["34"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["36"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "aMakeTypeModelB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["36"]["m_sql"] = "aMakeTypeModelB";
protoArray["36"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["36"]["m_expr"] = obj;
protoArray["36"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["36"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["38"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "gainB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["38"]["m_sql"] = "gainB";
protoArray["38"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["38"]["m_expr"] = obj;
protoArray["38"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["38"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["40"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "diameterB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["40"]["m_sql"] = "diameterB";
protoArray["40"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["40"]["m_expr"] = obj;
protoArray["40"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["40"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["42"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "beamwidthB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["42"]["m_sql"] = "beamwidthB";
protoArray["42"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["42"]["m_expr"] = obj;
protoArray["42"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["42"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["44"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "polarizationB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["44"]["m_sql"] = "polarizationB";
protoArray["44"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["44"]["m_expr"] = obj;
protoArray["44"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["44"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["46"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "azimuthB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["46"]["m_sql"] = "azimuthB";
protoArray["46"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["46"]["m_expr"] = obj;
protoArray["46"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["46"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["48"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "elevAngleB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["48"]["m_sql"] = "elevAngleB";
protoArray["48"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["48"]["m_expr"] = obj;
protoArray["48"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["48"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["50"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "heightAGLB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["50"]["m_sql"] = "heightAGLB";
protoArray["50"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["50"]["m_expr"] = obj;
protoArray["50"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["50"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["52"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "feederLengthB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["52"]["m_sql"] = "feederLengthB";
protoArray["52"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["52"]["m_expr"] = obj;
protoArray["52"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["52"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["54"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "callSignB", "m_strTable", "dbo.rspdLineB", "m_srcTableName", "dbo.rspdLineB"));

protoArray["54"]["m_sql"] = "callSignB";
protoArray["54"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["54"]["m_expr"] = obj;
protoArray["54"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["54"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["56"] = SettingsMap.GetArray();
protoArray["56"]["m_link"] = "SQLL_MAIN";
protoArray["57"] = SettingsMap.GetArray();
protoArray["57"]["m_strName"] = "dbo.rspdLineB";
protoArray["57"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["57"]["m_columns"] = SettingsMap.GetArray();
protoArray["57"]["m_columns"].Add("ID");
protoArray["57"]["m_columns"].Add("HdrID");
protoArray["57"]["m_columns"].Add("LOC_UNIT_STA_B");
protoArray["57"]["m_columns"].Add("LOC_STREET_STA_B");
protoArray["57"]["m_columns"].Add("LOC_BRGY_STA_B");
protoArray["57"]["m_columns"].Add("CITY/MUNICIPALITY_STA_B");
protoArray["57"]["m_columns"].Add("PROVINCE_STA_B");
protoArray["57"]["m_columns"].Add("ZIPCODE_STA_B");
protoArray["57"]["m_columns"].Add("eDegB");
protoArray["57"]["m_columns"].Add("eMinB");
protoArray["57"]["m_columns"].Add("eSecB");
protoArray["57"]["m_columns"].Add("nDegB");
protoArray["57"]["m_columns"].Add("nMinB");
protoArray["57"]["m_columns"].Add("nSecB");
protoArray["57"]["m_columns"].Add("elevationB");
protoArray["57"]["m_columns"].Add("aMakeTypeModelB");
protoArray["57"]["m_columns"].Add("gainB");
protoArray["57"]["m_columns"].Add("diameterB");
protoArray["57"]["m_columns"].Add("beamwidthB");
protoArray["57"]["m_columns"].Add("polarizationB");
protoArray["57"]["m_columns"].Add("azimuthB");
protoArray["57"]["m_columns"].Add("elevAngleB");
protoArray["57"]["m_columns"].Add("heightAGLB");
protoArray["57"]["m_columns"].Add("feederLengthB");
protoArray["57"]["m_columns"].Add("callSignB");
obj = new SQLTable(protoArray["57"]);

protoArray["56"]["m_table"] = obj;
protoArray["56"]["m_sql"] = "dbo.rspdLineB";
protoArray["56"]["m_alias"] = "";
protoArray["56"]["m_srcTableName"] = "dbo.rspdLineB";
protoArray["58"] = SettingsMap.GetArray();
protoArray["58"]["m_sql"] = "";
protoArray["58"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["58"]["m_column"] = obj;
protoArray["58"]["m_contained"] = SettingsMap.GetArray();
protoArray["58"]["m_strCase"] = "";
protoArray["58"]["m_havingmode"] = false;
protoArray["58"]["m_inBrackets"] = false;
protoArray["58"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["58"]);

protoArray["56"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["56"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.rspdLineB";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["rspdlineb"] = obj;

				
		
			tdataArray["rspdlineb"][".sqlquery"] = queryData_Array["rspdlineb"];
			tdataArray["rspdlineb"][".hasEvents"] = false;
		}
	}

}
