using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_rspdlinea
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["rspdlinea"] = SettingsMap.GetArray();
			tdataArray["rspdlinea"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["rspdlinea"][".ShortName"] = "rspdlinea";
			tdataArray["rspdlinea"][".OwnerID"] = "";
			tdataArray["rspdlinea"][".OriginalTable"] = "dbo.rspdLineA";
			tdataArray["rspdlinea"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}"));
			tdataArray["rspdlinea"][".originalPagesByType"] = tdataArray["rspdlinea"][".pagesByType"];
			tdataArray["rspdlinea"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"add\":[\"add\"],\"edit\":[\"edit\"],\"export\":[\"export\"],\"import\":[\"import\"],\"list\":[\"list\"],\"print\":[\"print\"],\"search\":[\"search\"],\"view\":[\"view\"]}")));
			tdataArray["rspdlinea"][".originalPages"] = tdataArray["rspdlinea"][".pages"];
			tdataArray["rspdlinea"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"add\":\"add\",\"edit\":\"edit\",\"export\":\"export\",\"import\":\"import\",\"list\":\"list\",\"print\":\"print\",\"search\":\"search\",\"view\":\"view\"}"));
			tdataArray["rspdlinea"][".originalDefaultPages"] = tdataArray["rspdlinea"][".defaultPages"];
			fieldLabelsArray["rspdlinea"] = SettingsMap.GetArray();
			fieldToolTipsArray["rspdlinea"] = SettingsMap.GetArray();
			pageTitlesArray["rspdlinea"] = SettingsMap.GetArray();
			placeHoldersArray["rspdlinea"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["rspdlinea"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["rspdlinea"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["rspdlinea"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["rspdlinea"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["rspdlinea"]["English"]["ID"] = "ID";
				fieldToolTipsArray["rspdlinea"]["English"]["ID"] = "";
				placeHoldersArray["rspdlinea"]["English"]["ID"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["HdrID"] = "Hdr ID";
				fieldToolTipsArray["rspdlinea"]["English"]["HdrID"] = "";
				placeHoldersArray["rspdlinea"]["English"]["HdrID"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["LOC_UNIT_STA_A"] = "LOC UNIT STA A";
				fieldToolTipsArray["rspdlinea"]["English"]["LOC_UNIT_STA_A"] = "";
				placeHoldersArray["rspdlinea"]["English"]["LOC_UNIT_STA_A"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["LOC_STREET_STA_A"] = "LOC STREET STA A";
				fieldToolTipsArray["rspdlinea"]["English"]["LOC_STREET_STA_A"] = "";
				placeHoldersArray["rspdlinea"]["English"]["LOC_STREET_STA_A"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["LOC_BRGY_STA_A"] = "LOC BRGY STA A";
				fieldToolTipsArray["rspdlinea"]["English"]["LOC_BRGY_STA_A"] = "";
				placeHoldersArray["rspdlinea"]["English"]["LOC_BRGY_STA_A"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["CITY_MUNICIPALITY_STA_A"] = "CITY/MUNICIPALITY STA A";
				fieldToolTipsArray["rspdlinea"]["English"]["CITY_MUNICIPALITY_STA_A"] = "";
				placeHoldersArray["rspdlinea"]["English"]["CITY_MUNICIPALITY_STA_A"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["PROVINCE_STA_A"] = "PROVINCE STA A";
				fieldToolTipsArray["rspdlinea"]["English"]["PROVINCE_STA_A"] = "";
				placeHoldersArray["rspdlinea"]["English"]["PROVINCE_STA_A"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["ZIPCODE_STA_A"] = "ZIPCODE STA A";
				fieldToolTipsArray["rspdlinea"]["English"]["ZIPCODE_STA_A"] = "";
				placeHoldersArray["rspdlinea"]["English"]["ZIPCODE_STA_A"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["eDegA"] = "E Deg A";
				fieldToolTipsArray["rspdlinea"]["English"]["eDegA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["eDegA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["eMinA"] = "E Min A";
				fieldToolTipsArray["rspdlinea"]["English"]["eMinA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["eMinA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["eSecA"] = "E Sec A";
				fieldToolTipsArray["rspdlinea"]["English"]["eSecA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["eSecA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["nDegA"] = "N Deg A";
				fieldToolTipsArray["rspdlinea"]["English"]["nDegA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["nDegA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["nMinA"] = "N Min A";
				fieldToolTipsArray["rspdlinea"]["English"]["nMinA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["nMinA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["nSecA"] = "N Sec A";
				fieldToolTipsArray["rspdlinea"]["English"]["nSecA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["nSecA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["elevationA"] = "Elevation A";
				fieldToolTipsArray["rspdlinea"]["English"]["elevationA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["elevationA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["aMakeTypeModelA"] = "A Make Type Model A";
				fieldToolTipsArray["rspdlinea"]["English"]["aMakeTypeModelA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["aMakeTypeModelA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["gainA"] = "Gain A";
				fieldToolTipsArray["rspdlinea"]["English"]["gainA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["gainA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["diameterA"] = "Diameter A";
				fieldToolTipsArray["rspdlinea"]["English"]["diameterA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["diameterA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["beamwidthA"] = "Beamwidth A";
				fieldToolTipsArray["rspdlinea"]["English"]["beamwidthA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["beamwidthA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["polarizationA"] = "Polarization A";
				fieldToolTipsArray["rspdlinea"]["English"]["polarizationA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["polarizationA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["azimuthA"] = "Azimuth A";
				fieldToolTipsArray["rspdlinea"]["English"]["azimuthA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["azimuthA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["elevAngleA"] = "Elev Angle A";
				fieldToolTipsArray["rspdlinea"]["English"]["elevAngleA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["elevAngleA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["heightAGLA"] = "Height AGLA";
				fieldToolTipsArray["rspdlinea"]["English"]["heightAGLA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["heightAGLA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["feederLengthA"] = "Feeder Length A";
				fieldToolTipsArray["rspdlinea"]["English"]["feederLengthA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["feederLengthA"] = "";
				fieldLabelsArray["rspdlinea"]["English"]["callSignA"] = "Call Sign A";
				fieldToolTipsArray["rspdlinea"]["English"]["callSignA"] = "";
				placeHoldersArray["rspdlinea"]["English"]["callSignA"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["rspdlinea"]["English"])))
				{
					tdataArray["rspdlinea"][".isUseToolTips"] = true;
				}
			}
			tdataArray["rspdlinea"][".NCSearch"] = true;
			tdataArray["rspdlinea"][".shortTableName"] = "rspdlinea";
			tdataArray["rspdlinea"][".nSecOptions"] = 0;
			tdataArray["rspdlinea"][".mainTableOwnerID"] = "";
			tdataArray["rspdlinea"][".entityType"] = 0;
			tdataArray["rspdlinea"][".connId"] = "RSPDDB_at_172_16_0_80";
			tdataArray["rspdlinea"][".strOriginalTableName"] = "dbo.rspdLineA";
			tdataArray["rspdlinea"][".showAddInPopup"] = false;
			tdataArray["rspdlinea"][".showEditInPopup"] = false;
			tdataArray["rspdlinea"][".showViewInPopup"] = false;
			tdataArray["rspdlinea"][".listAjax"] = false;
			tdataArray["rspdlinea"][".audit"] = false;
			tdataArray["rspdlinea"][".locking"] = false;
			GlobalVars.pages = tdataArray["rspdlinea"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["rspdlinea"][".edit"] = true;
				tdataArray["rspdlinea"][".afterEditAction"] = 1;
				tdataArray["rspdlinea"][".closePopupAfterEdit"] = 1;
				tdataArray["rspdlinea"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["rspdlinea"][".add"] = true;
				tdataArray["rspdlinea"][".afterAddAction"] = 1;
				tdataArray["rspdlinea"][".closePopupAfterAdd"] = 1;
				tdataArray["rspdlinea"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["rspdlinea"][".list"] = true;
			}
			tdataArray["rspdlinea"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["rspdlinea"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["rspdlinea"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["rspdlinea"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["rspdlinea"][".printFriendly"] = true;
			}
			tdataArray["rspdlinea"][".showSimpleSearchOptions"] = true;
			tdataArray["rspdlinea"][".allowShowHideFields"] = true;
			tdataArray["rspdlinea"][".allowFieldsReordering"] = true;
			tdataArray["rspdlinea"][".isUseAjaxSuggest"] = true;


			tdataArray["rspdlinea"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["rspdlinea"][".buttonsAdded"] = false;
			tdataArray["rspdlinea"][".addPageEvents"] = false;
			tdataArray["rspdlinea"][".isUseTimeForSearch"] = false;
			tdataArray["rspdlinea"][".badgeColor"] = "CD5C5C";
			tdataArray["rspdlinea"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["rspdlinea"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["rspdlinea"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["rspdlinea"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["rspdlinea"][".googleLikeFields"].Add("ID");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("HdrID");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("LOC_UNIT_STA_A");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("LOC_STREET_STA_A");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("LOC_BRGY_STA_A");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("CITY/MUNICIPALITY_STA_A");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("PROVINCE_STA_A");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("ZIPCODE_STA_A");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("eDegA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("eMinA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("eSecA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("nDegA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("nMinA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("nSecA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("elevationA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("aMakeTypeModelA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("gainA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("diameterA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("beamwidthA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("polarizationA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("azimuthA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("elevAngleA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("heightAGLA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("feederLengthA");
			tdataArray["rspdlinea"][".googleLikeFields"].Add("callSignA");
			tdataArray["rspdlinea"][".tableType"] = "list";
			tdataArray["rspdlinea"][".printerPageOrientation"] = 0;
			tdataArray["rspdlinea"][".nPrinterPageScale"] = 100;
			tdataArray["rspdlinea"][".nPrinterSplitRecords"] = 40;
			tdataArray["rspdlinea"][".geocodingEnabled"] = false;
			tdataArray["rspdlinea"][".pageSize"] = 20;
			tdataArray["rspdlinea"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["rspdlinea"][".strOrderBy"] = tstrOrderBy;
			tdataArray["rspdlinea"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["rspdlinea"][".sqlHead"] = "SELECT ID,  	HdrID,  	LOC_UNIT_STA_A,  	LOC_STREET_STA_A,  	LOC_BRGY_STA_A,  	[CITY/MUNICIPALITY_STA_A],  	PROVINCE_STA_A,  	ZIPCODE_STA_A,  	eDegA,  	eMinA,  	eSecA,  	nDegA,  	nMinA,  	nSecA,  	elevationA,  	aMakeTypeModelA,  	gainA,  	diameterA,  	beamwidthA,  	polarizationA,  	azimuthA,  	elevAngleA,  	heightAGLA,  	feederLengthA,  	callSignA";
			tdataArray["rspdlinea"][".sqlFrom"] = "FROM dbo.rspdLineA";
			tdataArray["rspdlinea"][".sqlWhereExpr"] = "";
			tdataArray["rspdlinea"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["rspdlinea"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["rspdlinea"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["rspdlinea"][".highlightSearchResults"] = true;
			tableKeysArray["rspdlinea"] = SettingsMap.GetArray();
			tableKeysArray["rspdlinea"].Add("ID");
			tdataArray["rspdlinea"][".Keys"] = tableKeysArray["rspdlinea"];
			tdataArray["rspdlinea"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "ID";
			fdata["GoodName"] = "ID";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","ID");
			fdata["FieldType"] = 3;
			fdata["AutoInc"] = true;
			fdata["strField"] = "ID";
			fdata["sourceSingle"] = "ID";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ID";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["ID"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("ID");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "HdrID";
			fdata["GoodName"] = "HdrID";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","HdrID");
			fdata["FieldType"] = 3;
			fdata["strField"] = "HdrID";
			fdata["sourceSingle"] = "HdrID";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "HdrID";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["HdrID"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("HdrID");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "LOC_UNIT_STA_A";
			fdata["GoodName"] = "LOC_UNIT_STA_A";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","LOC_UNIT_STA_A");
			fdata["FieldType"] = 200;
			fdata["strField"] = "LOC_UNIT_STA_A";
			fdata["sourceSingle"] = "LOC_UNIT_STA_A";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "LOC_UNIT_STA_A";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["LOC_UNIT_STA_A"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("LOC_UNIT_STA_A");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "LOC_STREET_STA_A";
			fdata["GoodName"] = "LOC_STREET_STA_A";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","LOC_STREET_STA_A");
			fdata["FieldType"] = 200;
			fdata["strField"] = "LOC_STREET_STA_A";
			fdata["sourceSingle"] = "LOC_STREET_STA_A";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "LOC_STREET_STA_A";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["LOC_STREET_STA_A"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("LOC_STREET_STA_A");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "LOC_BRGY_STA_A";
			fdata["GoodName"] = "LOC_BRGY_STA_A";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","LOC_BRGY_STA_A");
			fdata["FieldType"] = 200;
			fdata["strField"] = "LOC_BRGY_STA_A";
			fdata["sourceSingle"] = "LOC_BRGY_STA_A";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "LOC_BRGY_STA_A";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["LOC_BRGY_STA_A"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("LOC_BRGY_STA_A");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "CITY/MUNICIPALITY_STA_A";
			fdata["GoodName"] = "CITY_MUNICIPALITY_STA_A";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","CITY_MUNICIPALITY_STA_A");
			fdata["FieldType"] = 200;
			fdata["strField"] = "CITY/MUNICIPALITY_STA_A";
			fdata["sourceSingle"] = "CITY/MUNICIPALITY_STA_A";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "[CITY/MUNICIPALITY_STA_A]";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["CITY/MUNICIPALITY_STA_A"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("CITY/MUNICIPALITY_STA_A");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "PROVINCE_STA_A";
			fdata["GoodName"] = "PROVINCE_STA_A";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","PROVINCE_STA_A");
			fdata["FieldType"] = 200;
			fdata["strField"] = "PROVINCE_STA_A";
			fdata["sourceSingle"] = "PROVINCE_STA_A";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "PROVINCE_STA_A";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["PROVINCE_STA_A"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("PROVINCE_STA_A");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "ZIPCODE_STA_A";
			fdata["GoodName"] = "ZIPCODE_STA_A";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","ZIPCODE_STA_A");
			fdata["FieldType"] = 200;
			fdata["strField"] = "ZIPCODE_STA_A";
			fdata["sourceSingle"] = "ZIPCODE_STA_A";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ZIPCODE_STA_A";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["ZIPCODE_STA_A"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("ZIPCODE_STA_A");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "eDegA";
			fdata["GoodName"] = "eDegA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","eDegA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "eDegA";
			fdata["sourceSingle"] = "eDegA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "eDegA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["eDegA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("eDegA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "eMinA";
			fdata["GoodName"] = "eMinA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","eMinA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "eMinA";
			fdata["sourceSingle"] = "eMinA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "eMinA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["eMinA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("eMinA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "eSecA";
			fdata["GoodName"] = "eSecA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","eSecA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "eSecA";
			fdata["sourceSingle"] = "eSecA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "eSecA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["eSecA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("eSecA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "nDegA";
			fdata["GoodName"] = "nDegA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","nDegA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "nDegA";
			fdata["sourceSingle"] = "nDegA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "nDegA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["nDegA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("nDegA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 13;
			fdata["strName"] = "nMinA";
			fdata["GoodName"] = "nMinA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","nMinA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "nMinA";
			fdata["sourceSingle"] = "nMinA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "nMinA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["nMinA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("nMinA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 14;
			fdata["strName"] = "nSecA";
			fdata["GoodName"] = "nSecA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","nSecA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "nSecA";
			fdata["sourceSingle"] = "nSecA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "nSecA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["nSecA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("nSecA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 15;
			fdata["strName"] = "elevationA";
			fdata["GoodName"] = "elevationA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","elevationA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "elevationA";
			fdata["sourceSingle"] = "elevationA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "elevationA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 6;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["elevationA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("elevationA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 16;
			fdata["strName"] = "aMakeTypeModelA";
			fdata["GoodName"] = "aMakeTypeModelA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","aMakeTypeModelA");
			fdata["FieldType"] = 200;
			fdata["strField"] = "aMakeTypeModelA";
			fdata["sourceSingle"] = "aMakeTypeModelA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "aMakeTypeModelA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=250");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["aMakeTypeModelA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("aMakeTypeModelA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 17;
			fdata["strName"] = "gainA";
			fdata["GoodName"] = "gainA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","gainA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "gainA";
			fdata["sourceSingle"] = "gainA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "gainA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["gainA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("gainA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 18;
			fdata["strName"] = "diameterA";
			fdata["GoodName"] = "diameterA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","diameterA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "diameterA";
			fdata["sourceSingle"] = "diameterA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "diameterA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["diameterA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("diameterA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 19;
			fdata["strName"] = "beamwidthA";
			fdata["GoodName"] = "beamwidthA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","beamwidthA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "beamwidthA";
			fdata["sourceSingle"] = "beamwidthA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "beamwidthA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["beamwidthA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("beamwidthA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 20;
			fdata["strName"] = "polarizationA";
			fdata["GoodName"] = "polarizationA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","polarizationA");
			fdata["FieldType"] = 200;
			fdata["strField"] = "polarizationA";
			fdata["sourceSingle"] = "polarizationA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "polarizationA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=150");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["polarizationA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("polarizationA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 21;
			fdata["strName"] = "azimuthA";
			fdata["GoodName"] = "azimuthA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","azimuthA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "azimuthA";
			fdata["sourceSingle"] = "azimuthA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "azimuthA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["azimuthA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("azimuthA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 22;
			fdata["strName"] = "elevAngleA";
			fdata["GoodName"] = "elevAngleA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","elevAngleA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "elevAngleA";
			fdata["sourceSingle"] = "elevAngleA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "elevAngleA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["elevAngleA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("elevAngleA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 23;
			fdata["strName"] = "heightAGLA";
			fdata["GoodName"] = "heightAGLA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","heightAGLA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "heightAGLA";
			fdata["sourceSingle"] = "heightAGLA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "heightAGLA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["heightAGLA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("heightAGLA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 24;
			fdata["strName"] = "feederLengthA";
			fdata["GoodName"] = "feederLengthA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","feederLengthA");
			fdata["FieldType"] = 131;
			fdata["strField"] = "feederLengthA";
			fdata["sourceSingle"] = "feederLengthA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "feederLengthA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "Number");
			vdata["DecimalDigits"] = 2;
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["feederLengthA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("feederLengthA");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 25;
			fdata["strName"] = "callSignA";
			fdata["GoodName"] = "callSignA";
			fdata["ownerTable"] = "dbo.rspdLineA";
			fdata["Label"] = CommonFunctions.GetFieldLabel("dbo_rspdLineA","callSignA");
			fdata["FieldType"] = 200;
			fdata["strField"] = "callSignA";
			fdata["sourceSingle"] = "callSignA";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "callSignA";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["rspdlinea"]["callSignA"] = fdata;
			tdataArray["rspdlinea"][".searchableFields"].Add("callSignA");
			GlobalVars.tables_data["dbo.rspdLineA"] = tdataArray["rspdlinea"];
			GlobalVars.field_labels["dbo_rspdLineA"] = fieldLabelsArray["rspdlinea"];
			GlobalVars.fieldToolTips["dbo_rspdLineA"] = fieldToolTipsArray["rspdlinea"];
			GlobalVars.placeHolders["dbo_rspdLineA"] = placeHoldersArray["rspdlinea"];
			GlobalVars.page_titles["dbo_rspdLineA"] = pageTitlesArray["rspdlinea"];
			CommonFunctions.changeTextControlsToDate(new XVar("dbo.rspdLineA"));
			GlobalVars.detailsTablesData["dbo.rspdLineA"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["dbo.rspdLineA"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "ID,  	HdrID,  	LOC_UNIT_STA_A,  	LOC_STREET_STA_A,  	LOC_BRGY_STA_A,  	[CITY/MUNICIPALITY_STA_A],  	PROVINCE_STA_A,  	ZIPCODE_STA_A,  	eDegA,  	eMinA,  	eSecA,  	nDegA,  	nMinA,  	nSecA,  	elevationA,  	aMakeTypeModelA,  	gainA,  	diameterA,  	beamwidthA,  	polarizationA,  	azimuthA,  	elevAngleA,  	heightAGLA,  	feederLengthA,  	callSignA";
protoArray["0"]["m_strFrom"] = "FROM dbo.rspdLineA";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ID", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["6"]["m_sql"] = "ID";
protoArray["6"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "HdrID", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["8"]["m_sql"] = "HdrID";
protoArray["8"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "LOC_UNIT_STA_A", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["10"]["m_sql"] = "LOC_UNIT_STA_A";
protoArray["10"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "LOC_STREET_STA_A", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["12"]["m_sql"] = "LOC_STREET_STA_A";
protoArray["12"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "LOC_BRGY_STA_A", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["14"]["m_sql"] = "LOC_BRGY_STA_A";
protoArray["14"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "CITY/MUNICIPALITY_STA_A", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["16"]["m_sql"] = "[CITY/MUNICIPALITY_STA_A]";
protoArray["16"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "PROVINCE_STA_A", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["18"]["m_sql"] = "PROVINCE_STA_A";
protoArray["18"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ZIPCODE_STA_A", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["20"]["m_sql"] = "ZIPCODE_STA_A";
protoArray["20"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "eDegA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["22"]["m_sql"] = "eDegA";
protoArray["22"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "eMinA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["24"]["m_sql"] = "eMinA";
protoArray["24"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "eSecA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["26"]["m_sql"] = "eSecA";
protoArray["26"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "nDegA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["28"]["m_sql"] = "nDegA";
protoArray["28"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["30"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "nMinA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["30"]["m_sql"] = "nMinA";
protoArray["30"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["30"]["m_expr"] = obj;
protoArray["30"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["30"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["32"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "nSecA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["32"]["m_sql"] = "nSecA";
protoArray["32"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["32"]["m_expr"] = obj;
protoArray["32"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["32"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["34"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "elevationA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["34"]["m_sql"] = "elevationA";
protoArray["34"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["34"]["m_expr"] = obj;
protoArray["34"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["34"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["36"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "aMakeTypeModelA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["36"]["m_sql"] = "aMakeTypeModelA";
protoArray["36"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["36"]["m_expr"] = obj;
protoArray["36"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["36"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["38"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "gainA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["38"]["m_sql"] = "gainA";
protoArray["38"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["38"]["m_expr"] = obj;
protoArray["38"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["38"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["40"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "diameterA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["40"]["m_sql"] = "diameterA";
protoArray["40"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["40"]["m_expr"] = obj;
protoArray["40"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["40"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["42"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "beamwidthA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["42"]["m_sql"] = "beamwidthA";
protoArray["42"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["42"]["m_expr"] = obj;
protoArray["42"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["42"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["44"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "polarizationA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["44"]["m_sql"] = "polarizationA";
protoArray["44"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["44"]["m_expr"] = obj;
protoArray["44"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["44"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["46"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "azimuthA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["46"]["m_sql"] = "azimuthA";
protoArray["46"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["46"]["m_expr"] = obj;
protoArray["46"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["46"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["48"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "elevAngleA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["48"]["m_sql"] = "elevAngleA";
protoArray["48"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["48"]["m_expr"] = obj;
protoArray["48"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["48"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["50"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "heightAGLA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["50"]["m_sql"] = "heightAGLA";
protoArray["50"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["50"]["m_expr"] = obj;
protoArray["50"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["50"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["52"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "feederLengthA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["52"]["m_sql"] = "feederLengthA";
protoArray["52"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["52"]["m_expr"] = obj;
protoArray["52"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["52"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["54"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "callSignA", "m_strTable", "dbo.rspdLineA", "m_srcTableName", "dbo.rspdLineA"));

protoArray["54"]["m_sql"] = "callSignA";
protoArray["54"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["54"]["m_expr"] = obj;
protoArray["54"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["54"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["56"] = SettingsMap.GetArray();
protoArray["56"]["m_link"] = "SQLL_MAIN";
protoArray["57"] = SettingsMap.GetArray();
protoArray["57"]["m_strName"] = "dbo.rspdLineA";
protoArray["57"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["57"]["m_columns"] = SettingsMap.GetArray();
protoArray["57"]["m_columns"].Add("ID");
protoArray["57"]["m_columns"].Add("HdrID");
protoArray["57"]["m_columns"].Add("LOC_UNIT_STA_A");
protoArray["57"]["m_columns"].Add("LOC_STREET_STA_A");
protoArray["57"]["m_columns"].Add("LOC_BRGY_STA_A");
protoArray["57"]["m_columns"].Add("CITY/MUNICIPALITY_STA_A");
protoArray["57"]["m_columns"].Add("PROVINCE_STA_A");
protoArray["57"]["m_columns"].Add("ZIPCODE_STA_A");
protoArray["57"]["m_columns"].Add("eDegA");
protoArray["57"]["m_columns"].Add("eMinA");
protoArray["57"]["m_columns"].Add("eSecA");
protoArray["57"]["m_columns"].Add("nDegA");
protoArray["57"]["m_columns"].Add("nMinA");
protoArray["57"]["m_columns"].Add("nSecA");
protoArray["57"]["m_columns"].Add("elevationA");
protoArray["57"]["m_columns"].Add("aMakeTypeModelA");
protoArray["57"]["m_columns"].Add("gainA");
protoArray["57"]["m_columns"].Add("diameterA");
protoArray["57"]["m_columns"].Add("beamwidthA");
protoArray["57"]["m_columns"].Add("polarizationA");
protoArray["57"]["m_columns"].Add("azimuthA");
protoArray["57"]["m_columns"].Add("elevAngleA");
protoArray["57"]["m_columns"].Add("heightAGLA");
protoArray["57"]["m_columns"].Add("feederLengthA");
protoArray["57"]["m_columns"].Add("callSignA");
obj = new SQLTable(protoArray["57"]);

protoArray["56"]["m_table"] = obj;
protoArray["56"]["m_sql"] = "dbo.rspdLineA";
protoArray["56"]["m_alias"] = "";
protoArray["56"]["m_srcTableName"] = "dbo.rspdLineA";
protoArray["58"] = SettingsMap.GetArray();
protoArray["58"]["m_sql"] = "";
protoArray["58"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["58"]["m_column"] = obj;
protoArray["58"]["m_contained"] = SettingsMap.GetArray();
protoArray["58"]["m_strCase"] = "";
protoArray["58"]["m_havingmode"] = false;
protoArray["58"]["m_inBrackets"] = false;
protoArray["58"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["58"]);

protoArray["56"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["56"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "dbo.rspdLineA";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["rspdlinea"] = obj;

				
		
			tdataArray["rspdlinea"][".sqlquery"] = queryData_Array["rspdlinea"];
			tdataArray["rspdlinea"][".hasEvents"] = false;
		}
	}

}
