using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Reflection;
using runnerDotNet;
namespace runnerDotNet
{
	public static partial class Settings_users
	{
		static public void Apply()
		{
			SettingsMap arrGPP = SettingsMap.GetArray(), arrGridTabs = SettingsMap.GetArray(), arrRPP = SettingsMap.GetArray(), dIndex = null, detailsParam = SettingsMap.GetArray(), edata = SettingsMap.GetArray(), eventsData = SettingsMap.GetArray(), fdata = SettingsMap.GetArray(), fieldLabelsArray = new XVar(), fieldToolTipsArray = new XVar(), hours = null, intervalData = SettingsMap.GetArray(), masterParams = SettingsMap.GetArray(), pageTitlesArray = new XVar(), placeHoldersArray = new XVar(), query = null, queryData_Array = new XVar(), strOriginalDetailsTable = null, table = null, tableKeysArray = new XVar(), tdataArray = new XVar(), tstrOrderBy = null, vdata = SettingsMap.GetArray();
			tdataArray["users"] = SettingsMap.GetArray();
			tdataArray["users"][".searchableFields"] = SettingsMap.GetArray();
			tdataArray["users"][".ShortName"] = "users";
			tdataArray["users"][".OwnerID"] = "";
			tdataArray["users"][".OriginalTable"] = "dbo.spectrum_beta_users";
			tdataArray["users"][".pagesByType"] = MVCFunctions.my_json_decode(new XVar("{\"search\":[\"search\"]}"));
			tdataArray["users"][".originalPagesByType"] = tdataArray["users"][".pagesByType"];
			tdataArray["users"][".pages"] = CommonFunctions.types2pages(MVCFunctions.my_json_decode(new XVar("{\"search\":[\"search\"]}")));
			tdataArray["users"][".originalPages"] = tdataArray["users"][".pages"];
			tdataArray["users"][".defaultPages"] = MVCFunctions.my_json_decode(new XVar("{\"search\":\"search\"}"));
			tdataArray["users"][".originalDefaultPages"] = tdataArray["users"][".defaultPages"];
			fieldLabelsArray["users"] = SettingsMap.GetArray();
			fieldToolTipsArray["users"] = SettingsMap.GetArray();
			pageTitlesArray["users"] = SettingsMap.GetArray();
			placeHoldersArray["users"] = SettingsMap.GetArray();
			if(CommonFunctions.mlang_getcurrentlang() == "English")
			{
				fieldLabelsArray["users"]["English"] = SettingsMap.GetArray();
				fieldToolTipsArray["users"]["English"] = SettingsMap.GetArray();
				placeHoldersArray["users"]["English"] = SettingsMap.GetArray();
				pageTitlesArray["users"]["English"] = SettingsMap.GetArray();
				fieldLabelsArray["users"]["English"]["ID"] = "ID";
				fieldToolTipsArray["users"]["English"]["ID"] = "";
				placeHoldersArray["users"]["English"]["ID"] = "";
				fieldLabelsArray["users"]["English"]["username"] = "Username";
				fieldToolTipsArray["users"]["English"]["username"] = "";
				placeHoldersArray["users"]["English"]["username"] = "";
				fieldLabelsArray["users"]["English"]["password"] = "Password";
				fieldToolTipsArray["users"]["English"]["password"] = "";
				placeHoldersArray["users"]["English"]["password"] = "";
				fieldLabelsArray["users"]["English"]["email"] = "Email";
				fieldToolTipsArray["users"]["English"]["email"] = "";
				placeHoldersArray["users"]["English"]["email"] = "";
				fieldLabelsArray["users"]["English"]["fullname"] = "Fullname";
				fieldToolTipsArray["users"]["English"]["fullname"] = "";
				placeHoldersArray["users"]["English"]["fullname"] = "";
				fieldLabelsArray["users"]["English"]["groupid"] = "Groupid";
				fieldToolTipsArray["users"]["English"]["groupid"] = "";
				placeHoldersArray["users"]["English"]["groupid"] = "";
				fieldLabelsArray["users"]["English"]["active"] = "Active";
				fieldToolTipsArray["users"]["English"]["active"] = "";
				placeHoldersArray["users"]["English"]["active"] = "";
				fieldLabelsArray["users"]["English"]["ext_security_id"] = "Ext Security Id";
				fieldToolTipsArray["users"]["English"]["ext_security_id"] = "";
				placeHoldersArray["users"]["English"]["ext_security_id"] = "";
				fieldLabelsArray["users"]["English"]["company"] = "Company";
				fieldToolTipsArray["users"]["English"]["company"] = "";
				placeHoldersArray["users"]["English"]["company"] = "";
				fieldLabelsArray["users"]["English"]["position"] = "Position";
				fieldToolTipsArray["users"]["English"]["position"] = "";
				placeHoldersArray["users"]["English"]["position"] = "";
				fieldLabelsArray["users"]["English"]["branch"] = "Branch";
				fieldToolTipsArray["users"]["English"]["branch"] = "";
				placeHoldersArray["users"]["English"]["branch"] = "";
				fieldLabelsArray["users"]["English"]["groupPermission"] = "Group Permission";
				fieldToolTipsArray["users"]["English"]["groupPermission"] = "";
				placeHoldersArray["users"]["English"]["groupPermission"] = "";
				if(XVar.Pack(MVCFunctions.count(fieldToolTipsArray["users"]["English"])))
				{
					tdataArray["users"][".isUseToolTips"] = true;
				}
			}
			tdataArray["users"][".NCSearch"] = true;
			tdataArray["users"][".shortTableName"] = "users";
			tdataArray["users"][".nSecOptions"] = 0;
			tdataArray["users"][".mainTableOwnerID"] = "";
			tdataArray["users"][".entityType"] = 1;
			tdataArray["users"][".connId"] = "RSPDDB_at_172_16_0_80";
			tdataArray["users"][".strOriginalTableName"] = "dbo.spectrum_beta_users";
			tdataArray["users"][".showAddInPopup"] = false;
			tdataArray["users"][".showEditInPopup"] = false;
			tdataArray["users"][".showViewInPopup"] = false;
			tdataArray["users"][".listAjax"] = false;
			tdataArray["users"][".audit"] = true;
			tdataArray["users"][".locking"] = false;
			GlobalVars.pages = tdataArray["users"][".defaultPages"];
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EDIT]))
			{
				tdataArray["users"][".edit"] = true;
				tdataArray["users"][".afterEditAction"] = 1;
				tdataArray["users"][".closePopupAfterEdit"] = 1;
				tdataArray["users"][".afterEditActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_ADD]))
			{
				tdataArray["users"][".add"] = true;
				tdataArray["users"][".afterAddAction"] = 1;
				tdataArray["users"][".closePopupAfterAdd"] = 1;
				tdataArray["users"][".afterAddActionDetTable"] = "";
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_LIST]))
			{
				tdataArray["users"][".list"] = true;
			}
			tdataArray["users"][".strSortControlSettingsJSON"] = "";
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_VIEW]))
			{
				tdataArray["users"][".view"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_IMPORT]))
			{
				tdataArray["users"][".import"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_EXPORT]))
			{
				tdataArray["users"][".exportTo"] = true;
			}
			if(XVar.Pack(GlobalVars.pages[Constants.PAGE_PRINT]))
			{
				tdataArray["users"][".printFriendly"] = true;
			}
			tdataArray["users"][".showSimpleSearchOptions"] = true;
			tdataArray["users"][".allowShowHideFields"] = true;
			tdataArray["users"][".allowFieldsReordering"] = true;
			tdataArray["users"][".isUseAjaxSuggest"] = true;


			tdataArray["users"][".ajaxCodeSnippetAdded"] = false;
			tdataArray["users"][".buttonsAdded"] = false;
			tdataArray["users"][".addPageEvents"] = false;
			tdataArray["users"][".isUseTimeForSearch"] = false;
			tdataArray["users"][".badgeColor"] = "D2691E";
			tdataArray["users"][".allSearchFields"] = SettingsMap.GetArray();
			tdataArray["users"][".filterFields"] = SettingsMap.GetArray();
			tdataArray["users"][".requiredSearchFields"] = SettingsMap.GetArray();
			tdataArray["users"][".googleLikeFields"] = SettingsMap.GetArray();
			tdataArray["users"][".googleLikeFields"].Add("ID");
			tdataArray["users"][".googleLikeFields"].Add("username");
			tdataArray["users"][".googleLikeFields"].Add("password");
			tdataArray["users"][".googleLikeFields"].Add("email");
			tdataArray["users"][".googleLikeFields"].Add("fullname");
			tdataArray["users"][".googleLikeFields"].Add("groupid");
			tdataArray["users"][".googleLikeFields"].Add("active");
			tdataArray["users"][".googleLikeFields"].Add("ext_security_id");
			tdataArray["users"][".googleLikeFields"].Add("company");
			tdataArray["users"][".googleLikeFields"].Add("position");
			tdataArray["users"][".googleLikeFields"].Add("branch");
			tdataArray["users"][".googleLikeFields"].Add("groupPermission");
			tdataArray["users"][".tableType"] = "list";
			tdataArray["users"][".printerPageOrientation"] = 0;
			tdataArray["users"][".nPrinterPageScale"] = 100;
			tdataArray["users"][".nPrinterSplitRecords"] = 40;
			tdataArray["users"][".geocodingEnabled"] = false;
			tdataArray["users"][".pageSize"] = 20;
			tdataArray["users"][".warnLeavingPages"] = true;
			tstrOrderBy = "";
			tdataArray["users"][".strOrderBy"] = tstrOrderBy;
			tdataArray["users"][".orderindexes"] = SettingsMap.GetArray();
			tdataArray["users"][".sqlHead"] = "SELECT ID,  	username,  	password,  	email,  	fullname,  	groupid,  	active,  	ext_security_id,  	company,  	[position],  	branch,  	groupPermission";
			tdataArray["users"][".sqlFrom"] = "FROM dbo.spectrum_beta_users";
			tdataArray["users"][".sqlWhereExpr"] = "";
			tdataArray["users"][".sqlTail"] = "";
			arrRPP = SettingsMap.GetArray();
			arrRPP.Add(10);
			arrRPP.Add(20);
			arrRPP.Add(30);
			arrRPP.Add(50);
			arrRPP.Add(100);
			arrRPP.Add(500);
			arrRPP.Add(-1);
			tdataArray["users"][".arrRecsPerPage"] = arrRPP;
			arrGPP = SettingsMap.GetArray();
			arrGPP.Add(1);
			arrGPP.Add(3);
			arrGPP.Add(5);
			arrGPP.Add(10);
			arrGPP.Add(50);
			arrGPP.Add(100);
			arrGPP.Add(-1);
			tdataArray["users"][".arrGroupsPerPage"] = arrGPP;
			tdataArray["users"][".highlightSearchResults"] = true;
			tableKeysArray["users"] = SettingsMap.GetArray();
			tableKeysArray["users"].Add("ID");
			tdataArray["users"][".Keys"] = tableKeysArray["users"];
			tdataArray["users"][".hideMobileList"] = SettingsMap.GetArray();
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 1;
			fdata["strName"] = "ID";
			fdata["GoodName"] = "ID";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("users","ID");
			fdata["FieldType"] = 3;
			fdata["AutoInc"] = true;
			fdata["strField"] = "ID";
			fdata["sourceSingle"] = "ID";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ID";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["IsRequired"] = true;
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			edata["validateAs"]["basicValidate"].Add("IsRequired");
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["users"]["ID"] = fdata;
			tdataArray["users"][".searchableFields"].Add("ID");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 2;
			fdata["strName"] = "username";
			fdata["GoodName"] = "username";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("users","username");
			fdata["FieldType"] = 200;
			fdata["strField"] = "username";
			fdata["sourceSingle"] = "username";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "username";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["users"]["username"] = fdata;
			tdataArray["users"][".searchableFields"].Add("username");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 3;
			fdata["strName"] = "password";
			fdata["GoodName"] = "password";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("users","password");
			fdata["FieldType"] = 200;
			fdata["strField"] = "password";
			fdata["sourceSingle"] = "password";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "password";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Password");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["users"]["password"] = fdata;
			tdataArray["users"][".searchableFields"].Add("password");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 4;
			fdata["strName"] = "email";
			fdata["GoodName"] = "email";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("users","email");
			fdata["FieldType"] = 200;
			fdata["strField"] = "email";
			fdata["sourceSingle"] = "email";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "email";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["users"]["email"] = fdata;
			tdataArray["users"][".searchableFields"].Add("email");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 5;
			fdata["strName"] = "fullname";
			fdata["GoodName"] = "fullname";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("users","fullname");
			fdata["FieldType"] = 200;
			fdata["strField"] = "fullname";
			fdata["sourceSingle"] = "fullname";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "fullname";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["users"]["fullname"] = fdata;
			tdataArray["users"][".searchableFields"].Add("fullname");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 6;
			fdata["strName"] = "groupid";
			fdata["GoodName"] = "groupid";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("users","groupid");
			fdata["FieldType"] = 200;
			fdata["strField"] = "groupid";
			fdata["sourceSingle"] = "groupid";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "groupid";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=255");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["users"]["groupid"] = fdata;
			tdataArray["users"][".searchableFields"].Add("groupid");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 7;
			fdata["strName"] = "active";
			fdata["GoodName"] = "active";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("users","active");
			fdata["FieldType"] = 3;
			fdata["strField"] = "active";
			fdata["sourceSingle"] = "active";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "active";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["users"]["active"] = fdata;
			tdataArray["users"][".searchableFields"].Add("active");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 8;
			fdata["strName"] = "ext_security_id";
			fdata["GoodName"] = "ext_security_id";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("users","ext_security_id");
			fdata["FieldType"] = 200;
			fdata["strField"] = "ext_security_id";
			fdata["sourceSingle"] = "ext_security_id";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "ext_security_id";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["users"]["ext_security_id"] = fdata;
			tdataArray["users"][".searchableFields"].Add("ext_security_id");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 9;
			fdata["strName"] = "company";
			fdata["GoodName"] = "company";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("users","company");
			fdata["FieldType"] = 200;
			fdata["strField"] = "company";
			fdata["sourceSingle"] = "company";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "company";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=100");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["users"]["company"] = fdata;
			tdataArray["users"][".searchableFields"].Add("company");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 10;
			fdata["strName"] = "position";
			fdata["GoodName"] = "position";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("users","position");
			fdata["FieldType"] = 200;
			fdata["strField"] = "position";
			fdata["sourceSingle"] = "position";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "[position]";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["users"]["position"] = fdata;
			tdataArray["users"][".searchableFields"].Add("position");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 11;
			fdata["strName"] = "branch";
			fdata["GoodName"] = "branch";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("users","branch");
			fdata["FieldType"] = 200;
			fdata["strField"] = "branch";
			fdata["sourceSingle"] = "branch";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "branch";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"].Add(CommonFunctions.getJsValidatorName(new XVar("Number")));
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["users"]["branch"] = fdata;
			tdataArray["users"][".searchableFields"].Add("branch");
			fdata = SettingsMap.GetArray();
			fdata["Index"] = 12;
			fdata["strName"] = "groupPermission";
			fdata["GoodName"] = "groupPermission";
			fdata["ownerTable"] = "dbo.spectrum_beta_users";
			fdata["Label"] = CommonFunctions.GetFieldLabel("users","groupPermission");
			fdata["FieldType"] = 200;
			fdata["strField"] = "groupPermission";
			fdata["sourceSingle"] = "groupPermission";
			fdata["isSQLExpression"] = true;
			fdata["FullName"] = "groupPermission";
			fdata["UploadFolder"] = "files";
			fdata["ViewFormats"] = SettingsMap.GetArray();
			vdata = new XVar("ViewFormat", "");
			vdata["NeedEncode"] = true;
			vdata["truncateText"] = true;
			vdata["NumberOfChars"] = 80;
			fdata["ViewFormats"]["view"] = vdata;
			fdata["EditFormats"] = SettingsMap.GetArray();
			edata = new XVar("EditFormat", "Text field");
			edata["weekdayMessage"] = new XVar("message", "", "messageType", "Text");
			edata["weekdays"] = "[]";
			edata["acceptFileTypesHtml"] = "";
			edata["maxNumberOfFiles"] = 1;
			edata["HTML5InuptType"] = "text";
			edata["EditParams"] = "";
			edata["EditParams"] = MVCFunctions.Concat(edata["EditParams"], " maxlength=50");
			edata["controlWidth"] = 200;
			edata["validateAs"] = SettingsMap.GetArray();
			edata["validateAs"]["basicValidate"] = SettingsMap.GetArray();
			edata["validateAs"]["customMessages"] = SettingsMap.GetArray();
			fdata["EditFormats"]["edit"] = edata;
			fdata["isSeparate"] = false;
			fdata["defaultSearchOption"] = "Contains";
			fdata["searchOptionsList"] = new XVar(0, "Contains", 1, "Equals", 2, "Starts with", 3, "More than", 4, "Less than", 5, "Between", 6, "Empty", 7, Constants.NOT_EMPTY);
			fdata["filterTotals"] = 0;
			fdata["filterMultiSelect"] = 0;
			fdata["filterFormat"] = "Values list";
			fdata["showCollapsed"] = false;
			fdata["sortValueType"] = 0;
			fdata["numberOfVisibleItems"] = 10;
			fdata["filterBy"] = 0;
			tdataArray["users"]["groupPermission"] = fdata;
			tdataArray["users"][".searchableFields"].Add("groupPermission");
			GlobalVars.tables_data["users"] = tdataArray["users"];
			GlobalVars.field_labels["users"] = fieldLabelsArray["users"];
			GlobalVars.fieldToolTips["users"] = fieldToolTipsArray["users"];
			GlobalVars.placeHolders["users"] = placeHoldersArray["users"];
			GlobalVars.page_titles["users"] = pageTitlesArray["users"];
			CommonFunctions.changeTextControlsToDate(new XVar("users"));
			GlobalVars.detailsTablesData["users"] = SettingsMap.GetArray();
			GlobalVars.masterTablesData["users"] = SettingsMap.GetArray();

SQLEntity obj = null;
var protoArray = SettingsMap.GetArray();
protoArray["0"] = SettingsMap.GetArray();
protoArray["0"]["m_strHead"] = "SELECT";
protoArray["0"]["m_strFieldList"] = "ID,  	username,  	password,  	email,  	fullname,  	groupid,  	active,  	ext_security_id,  	company,  	[position],  	branch,  	groupPermission";
protoArray["0"]["m_strFrom"] = "FROM dbo.spectrum_beta_users";
protoArray["0"]["m_strWhere"] = "";
protoArray["0"]["m_strOrderBy"] = "";
	
		
protoArray["0"]["cipherer"] = null;
protoArray["2"] = SettingsMap.GetArray();
protoArray["2"]["m_sql"] = "";
protoArray["2"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["2"]["m_column"] = obj;
protoArray["2"]["m_contained"] = SettingsMap.GetArray();
protoArray["2"]["m_strCase"] = "";
protoArray["2"]["m_havingmode"] = false;
protoArray["2"]["m_inBrackets"] = false;
protoArray["2"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["2"]);

protoArray["0"]["m_where"] = obj;
protoArray["4"] = SettingsMap.GetArray();
protoArray["4"]["m_sql"] = "";
protoArray["4"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["4"]["m_column"] = obj;
protoArray["4"]["m_contained"] = SettingsMap.GetArray();
protoArray["4"]["m_strCase"] = "";
protoArray["4"]["m_havingmode"] = false;
protoArray["4"]["m_inBrackets"] = false;
protoArray["4"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["4"]);

protoArray["0"]["m_having"] = obj;
protoArray["0"]["m_fieldlist"] = SettingsMap.GetArray();
protoArray["6"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ID", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "users"));

protoArray["6"]["m_sql"] = "ID";
protoArray["6"]["m_srcTableName"] = "users";
protoArray["6"]["m_expr"] = obj;
protoArray["6"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["6"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["8"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "username", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "users"));

protoArray["8"]["m_sql"] = "username";
protoArray["8"]["m_srcTableName"] = "users";
protoArray["8"]["m_expr"] = obj;
protoArray["8"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["8"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["10"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "password", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "users"));

protoArray["10"]["m_sql"] = "password";
protoArray["10"]["m_srcTableName"] = "users";
protoArray["10"]["m_expr"] = obj;
protoArray["10"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["10"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["12"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "email", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "users"));

protoArray["12"]["m_sql"] = "email";
protoArray["12"]["m_srcTableName"] = "users";
protoArray["12"]["m_expr"] = obj;
protoArray["12"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["12"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["14"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "fullname", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "users"));

protoArray["14"]["m_sql"] = "fullname";
protoArray["14"]["m_srcTableName"] = "users";
protoArray["14"]["m_expr"] = obj;
protoArray["14"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["14"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["16"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "groupid", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "users"));

protoArray["16"]["m_sql"] = "groupid";
protoArray["16"]["m_srcTableName"] = "users";
protoArray["16"]["m_expr"] = obj;
protoArray["16"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["16"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["18"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "active", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "users"));

protoArray["18"]["m_sql"] = "active";
protoArray["18"]["m_srcTableName"] = "users";
protoArray["18"]["m_expr"] = obj;
protoArray["18"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["18"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["20"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "ext_security_id", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "users"));

protoArray["20"]["m_sql"] = "ext_security_id";
protoArray["20"]["m_srcTableName"] = "users";
protoArray["20"]["m_expr"] = obj;
protoArray["20"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["20"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["22"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "company", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "users"));

protoArray["22"]["m_sql"] = "company";
protoArray["22"]["m_srcTableName"] = "users";
protoArray["22"]["m_expr"] = obj;
protoArray["22"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["22"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["24"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "position", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "users"));

protoArray["24"]["m_sql"] = "[position]";
protoArray["24"]["m_srcTableName"] = "users";
protoArray["24"]["m_expr"] = obj;
protoArray["24"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["24"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["26"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "branch", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "users"));

protoArray["26"]["m_sql"] = "branch";
protoArray["26"]["m_srcTableName"] = "users";
protoArray["26"]["m_expr"] = obj;
protoArray["26"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["26"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["28"] = SettingsMap.GetArray();
obj = new SQLField(new XVar("m_strName", "groupPermission", "m_strTable", "dbo.spectrum_beta_users", "m_srcTableName", "users"));

protoArray["28"]["m_sql"] = "groupPermission";
protoArray["28"]["m_srcTableName"] = "users";
protoArray["28"]["m_expr"] = obj;
protoArray["28"]["m_alias"] = "";
obj = new SQLFieldListItem(protoArray["28"]);

protoArray["0"]["m_fieldlist"].Add(obj);
protoArray["0"]["m_fromlist"] = SettingsMap.GetArray();
protoArray["30"] = SettingsMap.GetArray();
protoArray["30"]["m_link"] = "SQLL_MAIN";
protoArray["31"] = SettingsMap.GetArray();
protoArray["31"]["m_strName"] = "dbo.spectrum_beta_users";
protoArray["31"]["m_srcTableName"] = "users";
protoArray["31"]["m_columns"] = SettingsMap.GetArray();
protoArray["31"]["m_columns"].Add("ID");
protoArray["31"]["m_columns"].Add("username");
protoArray["31"]["m_columns"].Add("password");
protoArray["31"]["m_columns"].Add("email");
protoArray["31"]["m_columns"].Add("fullname");
protoArray["31"]["m_columns"].Add("groupid");
protoArray["31"]["m_columns"].Add("active");
protoArray["31"]["m_columns"].Add("ext_security_id");
protoArray["31"]["m_columns"].Add("company");
protoArray["31"]["m_columns"].Add("position");
protoArray["31"]["m_columns"].Add("branch");
protoArray["31"]["m_columns"].Add("groupPermission");
obj = new SQLTable(protoArray["31"]);

protoArray["30"]["m_table"] = obj;
protoArray["30"]["m_sql"] = "dbo.spectrum_beta_users";
protoArray["30"]["m_alias"] = "";
protoArray["30"]["m_srcTableName"] = "users";
protoArray["32"] = SettingsMap.GetArray();
protoArray["32"]["m_sql"] = "";
protoArray["32"]["m_uniontype"] = "SQLL_UNKNOWN";
obj = new SQLNonParsed(new XVar("m_sql", ""));

protoArray["32"]["m_column"] = obj;
protoArray["32"]["m_contained"] = SettingsMap.GetArray();
protoArray["32"]["m_strCase"] = "";
protoArray["32"]["m_havingmode"] = false;
protoArray["32"]["m_inBrackets"] = false;
protoArray["32"]["m_useAlias"] = false;
obj = new SQLLogicalExpr(protoArray["32"]);

protoArray["30"]["m_joinon"] = obj;
obj = new SQLFromListItem(protoArray["30"]);

protoArray["0"]["m_fromlist"].Add(obj);
protoArray["0"]["m_groupby"] = SettingsMap.GetArray();
protoArray["0"]["m_orderby"] = SettingsMap.GetArray();
protoArray["0"]["m_srcTableName"] = "users";
obj = new SQLQuery(protoArray["0"]);

queryData_Array["users"] = obj;

				
		
			tdataArray["users"][".sqlquery"] = queryData_Array["users"];
			tdataArray["users"][".hasEvents"] = false;
		}
	}

}
